-- Rosco Bachillerato: preguntas ADICIONALES
-- 75 preguntas x 4 combinaciones = 300 total
-- subject_id: lengua (grades {1},{2}), filosofia (grades {1},{2})

INSERT INTO rosco_questions (letter, type, definition, solution, subject_id, level, grades, difficulty) VALUES

-- =====================================================
-- LENGUA BACHILLERATO 1 (75 preguntas)
-- Temas: picaresca, mística, ascética, prosa didáctica,
-- teatro prelopista, épica culta, gramática, dialectología,
-- pragmática, actos de habla, variedades diatópicas
-- =====================================================

('A', 'empieza', 'Figura retórica que consiste en la repetición de una o varias palabras al comienzo de versos o frases sucesivas', 'anafora', 'lengua', 'bachillerato', '{1}', 1),
('A', 'empieza', 'Tipo de oración subordinada que cumple la función de un adjetivo respecto al antecedente', 'adjetiva', 'lengua', 'bachillerato', '{1}', 2),
('A', 'empieza', 'Práctica espiritual basada en la renuncia y la disciplina moral, cultivada por fray Luis de Granada', 'ascetica', 'lengua', 'bachillerato', '{1}', 1),
('B', 'empieza', 'Novela picaresca anónima de 1554 cuyo protagonista sirve a varios amos empezando por un ciego', 'buscon', 'lengua', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Complemento del verbo que indica la circunstancia de lugar, tiempo, modo o causa de la acción', 'circunstancial', 'lengua', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Rasgo dialectal del andaluz que consiste en la aspiración o pérdida de la -s final de sílaba', 'ceceo', 'lengua', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Rama de la lingüística que estudia la distribución geográfica de los rasgos lingüísticos', 'dialectologia', 'lengua', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Construcción gramatical formada por un verbo en forma no personal que complementa a otro verbo auxiliar o semiauxiliar', 'desiderativa', 'lengua', 'bachillerato', '{1}', 3),
('E', 'empieza', 'Género narrativo extenso en verso que narra hazañas de héroes, como La Araucana de Ercilla', 'epopeya', 'lengua', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Tipo de perífrasis verbal que indica el comienzo de una acción, como "echarse a llorar"', 'empezar', 'lengua', 'bachillerato', '{1}', 2),
('F', 'empieza', 'Composición lírica de origen provenzal que expresa lamento amoroso por la ausencia del amado al amanecer', 'farsante', 'lengua', 'bachillerato', '{1}', 3),
('F', 'empieza', 'Función del lenguaje centrada en la forma del mensaje, propia del lenguaje literario según Jakobson', 'fática', 'lengua', 'bachillerato', '{1}', 2),
('G', 'empieza', 'Autor de las Églogas de influencia virgiliana, renovador de la lírica castellana del Renacimiento', 'garcilaso', 'lengua', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Figura retórica que consiste en la exageración desmesurada de una cualidad o acción', 'hiperbole', 'lengua', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Estrofa de origen italiano formada por once sílabas métricas, introducida por Boscán y Garcilaso', 'hendecasilabo', 'lengua', 'bachillerato', '{1}', 2),
('I', 'empieza', 'Fuerza comunicativa con la que se emite un enunciado, concepto central de la pragmática y los actos de habla', 'ilocutivo', 'lengua', 'bachillerato', '{1}', 3),
('I', 'empieza', 'Forma verbal no personal que puede funcionar como sustantivo en la oración', 'infinitivo', 'lengua', 'bachillerato', '{1}', 1),
('J', 'empieza', 'Composición poética popular de tradición oral, breve y de tono festivo, frecuente en cancioneros medievales', 'jarcha', 'lengua', 'bachillerato', '{1}', 2),
('K', 'contiene', 'Variedad lingüística propia de grupos sociales, estudiada por la sociolingüística y la dialectología social', 'sociolecto', 'lengua', 'bachillerato', '{1}', 2),
('L', 'empieza', 'Novela pastoril de Montemayor que inauguró el género bucólico en la narrativa castellana renacentista', 'lossietelibrosdediana', 'lengua', 'bachillerato', '{1}', 3),
('L', 'empieza', 'Fenómeno dialectal del español septentrional que distingue los fonemas /ʎ/ y /j/ frente al yeísmo', 'lleismo', 'lengua', 'bachillerato', '{1}', 2),
('M', 'empieza', 'Experiencia de unión del alma con la divinidad, tema central en la poesía de San Juan de la Cruz', 'mistica', 'lengua', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Principio pragmático de Grice que establece que los hablantes cooperan proporcionando la información justa y relevante', 'maxima', 'lengua', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Tipo de oración subordinada sustantiva, adjetiva o adverbial que depende de una oración principal', 'nexo', 'lengua', 'bachillerato', '{1}', 1),
('N', 'empieza', 'Género de prosa didáctica medieval en el que un noble enseña a su hijo mediante relatos y consejos', 'nobiliario', 'lengua', 'bachillerato', '{1}', 3),
('Ñ', 'contiene', 'Complemento verbal que recibe indirectamente la acción del verbo, como en "le dio un regalo a su compañera"', 'companera', 'lengua', 'bachillerato', '{1}', 1),
('O', 'empieza', 'Tipo de complemento del predicado que mide o cuantifica al verbo, como "pesa tres kilos"', 'obligativo', 'lengua', 'bachillerato', '{1}', 3),
('O', 'empieza', 'Estrofa de ocho versos de arte mayor con rima consonante, usada en la poesía del siglo XV', 'octava', 'lengua', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Construcción verbal formada por un auxiliar y un verbo en forma no personal que expresa matices aspectuales o modales', 'perifrasis', 'lengua', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Rama de la lingüística que estudia el uso del lenguaje en contexto y la intención comunicativa', 'pragmatica', 'lengua', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Género narrativo del Siglo de Oro cuyos protagonistas son personajes de baja extracción social que sobreviven con astucia', 'picaresca', 'lengua', 'bachillerato', '{1}', 1),
('Q', 'empieza', 'Estrofa de cinco versos utilizada en la lírica del Renacimiento, con esquema de rima aBabB', 'quintilla', 'lengua', 'bachillerato', '{1}', 2),
('R', 'empieza', 'Acto de habla en el que el hablante se compromete a realizar una acción futura, como las promesas y juramentos', 'representativo', 'lengua', 'bachillerato', '{1}', 3),
('R', 'empieza', 'Variedad lingüística utilizada en función de la situación comunicativa: formal, coloquial, etc.', 'registro', 'lengua', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Oración que depende sintácticamente de otra principal y desempeña una función dentro de ella', 'subordinada', 'lengua', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Rasgo dialectal del español meridional que consiste en pronunciar la c y la z como s', 'seseo', 'lengua', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Obra dramática del siglo XV atribuida a Fernando de Rojas, considerada precursora del teatro renacentista', 'tragicomedia', 'lengua', 'bachillerato', '{1}', 2),
('T', 'empieza', 'Modalidad de variación lingüística que depende de la temática o ámbito profesional del discurso', 'tecnicismo', 'lengua', 'bachillerato', '{1}', 2),
('U', 'empieza', 'Recurso estilístico del teatro prelopista que busca la coherencia interna de tiempo, lugar y acción', 'unidad', 'lengua', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Tipo de variación lingüística determinada por factores geográficos, también llamada variedad diatópica', 'variedad', 'lengua', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Composición lírica breve de arte menor típica del Cancionero de Palacio, con estribillo y mudanza', 'villancico', 'lengua', 'bachillerato', '{1}', 2),
('X', 'contiene', 'Complemento del predicado que expresa la causa, el origen o la procedencia de la acción verbal', 'nexual', 'lengua', 'bachillerato', '{1}', 3),
('Y', 'contiene', 'Tipo de oración subordinada introducida por la conjunción causal "ya que"', 'disyuntiva', 'lengua', 'bachillerato', '{1}', 2),
('Y', 'empieza', 'Fenómeno fonético del español consistente en pronunciar /ʎ/ como /j/, generalizado en la mayoría de dialectos', 'yeismo', 'lengua', 'bachillerato', '{1}', 1),
('Z', 'contiene', 'Autor renacentista que compuso la épica culta La Araucana sobre la conquista de Chile', 'ercilla', 'lengua', 'bachillerato', '{1}', 2),

-- Preguntas adicionales para completar 75 de Lengua Bach 1
('A', 'empieza', 'Complemento del verbo que designa al destinatario de la acción sin preposición directa, propio de verbos transitivos', 'acusativo', 'lengua', 'bachillerato', '{1}', 2),
('B', 'empieza', 'Estrofa pastoril de origen italiano de ocho versos endecasílabos con rima alterna y pareado final', 'bergamasca', 'lengua', 'bachillerato', '{1}', 3),
('C', 'empieza', 'Función sintáctica que complementa simultáneamente al verbo y al sujeto o al complemento directo', 'complementopredicativo', 'lengua', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Término pragmático que designa los elementos del contexto extralingüístico señalados por pronombres y adverbios', 'deixis', 'lengua', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Poema pastoril de Garcilaso en forma dialogada entre pastores que lamentan sus desventuras amorosas', 'egloga', 'lengua', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Variante dialectal del asturleonés caracterizada por la diptongación de vocales breves latinas', 'fabla', 'lengua', 'bachillerato', '{1}', 3),
('G', 'empieza', 'Forma verbal no personal que puede funcionar como adverbio modificando al verbo principal', 'gerundio', 'lengua', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Periodo de mayor esplendor cultural en el que florecen la picaresca, la mística y el teatro renacentista', 'humanismo', 'lengua', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Información que no se dice explícitamente pero se puede deducir del enunciado, concepto pragmático clave', 'implicatura', 'lengua', 'bachillerato', '{1}', 3),
('J', 'empieza', 'Dramaturgo del siglo XVI autor de los Pasos, piezas breves cómicas precursoras del entremés', 'juandelencina', 'lengua', 'bachillerato', '{1}', 3),
('L', 'empieza', 'Obra anónima del siglo XVI en la que un mozo de ciego narra sus peripecias con distintos amos', 'lazarillo', 'lengua', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Oración que expresa deseo, duda o irrealidad y se construye en modo verbal no indicativo', 'modal', 'lengua', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Variedad dialectal del español hablado en la mitad norte de España, con distinción de /s/ y /θ/', 'nortenno', 'lengua', 'bachillerato', '{1}', 2),
('O', 'empieza', 'Complemento del verbo precedido de preposición que aparece solo con verbos intransitivos o copulativos', 'oblicuo', 'lengua', 'bachillerato', '{1}', 3),
('P', 'empieza', 'Forma verbal compuesta por haber + participio que indica acción acabada antes de un punto temporal', 'pluscuamperfecto', 'lengua', 'bachillerato', '{1}', 1),
('Q', 'empieza', 'Famosa novela de caballerías cuya parodia constituye el argumento central de la obra de Cervantes', 'quijote', 'lengua', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Periodo cultural de los siglos XV-XVI que revitalizó los modelos grecolatinos en la literatura castellana', 'renacimiento', 'lengua', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Fenómeno lingüístico por el cual un significante adquiere un significado diferente al original con el paso del tiempo', 'semantica', 'lengua', 'bachillerato', '{1}', 2),
('T', 'empieza', 'Composición lírica de tres estrofas con vuelta al estribillo inicial, propia de la poesía cancioneril', 'terceto', 'lengua', 'bachillerato', '{1}', 1),
('U', 'empieza', 'Empleo de un término en sentido figurado basado en una relación de semejanza, procedimiento retórico frecuente', 'univoco', 'lengua', 'bachillerato', '{1}', 3),
('V', 'empieza', 'Variación lingüística determinada por el nivel sociocultural del hablante, también llamada diastrática', 'vulgarismo', 'lengua', 'bachillerato', '{1}', 2),
('W', 'contiene', 'Autor del Lazarillo de Tormes cuya identidad sigue siendo debatida por los estudiosos', 'desconocido', 'lengua', 'bachillerato', '{1}', 1),
('X', 'contiene', 'Recursos lingüísticos que organizan y conectan las distintas partes del discurso escrito', 'textual', 'lengua', 'bachillerato', '{1}', 1),
('Y', 'contiene', 'Tipo de oración coordinada que presenta alternativas mediante nexos como "o", "bien...bien"', 'coyuntura', 'lengua', 'bachillerato', '{1}', 2),
('Z', 'contiene', 'Fenómeno dialectal que consiste en la confusión de /r/ y /l/ en posición implosiva, propio del andaluz', 'neutralizacion', 'lengua', 'bachillerato', '{1}', 2),

-- =====================================================
-- LENGUA BACHILLERATO 2 (75 preguntas)
-- Temas: costumbrismo, krausismo, esperpento, tremendismo,
-- novela social años 50, poesía de la experiencia, novísimos,
-- teatro independiente, ensayo contemporáneo, sociolingüística,
-- análisis del discurso
-- =====================================================

('A', 'empieza', 'Corriente poética de los años 80 que reivindica la narratividad, el tono coloquial y la experiencia urbana cotidiana', 'autobiografismo', 'lengua', 'bachillerato', '{2}', 2),
('A', 'empieza', 'Técnica narrativa del Nouveau Roman y la novela experimental española de los 60 que elimina al narrador omnisciente', 'acronia', 'lengua', 'bachillerato', '{2}', 3),
('A', 'empieza', 'Disciplina lingüística que estudia las estructuras y estrategias de los textos más allá de la oración', 'analisis', 'lengua', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Novelista de la Generación del 98 autor de La busca, primera entrega de la trilogía La lucha por la vida', 'baroja', 'lengua', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Dramaturgo contemporáneo autor de El tragaluz y La fundación, representante del teatro de compromiso social', 'buero', 'lengua', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Movimiento literario del siglo XIX que retrata tipos y escenas populares con intención satírica o nostálgica', 'costumbrismo', 'lengua', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Novelista autora de Nada, obra precursora del tremendismo publicada en 1945', 'carmenlaforet', 'lengua', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Propiedad textual que asegura la conexión lógica y semántica entre las ideas de un discurso', 'coherencia', 'lengua', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Término sociolingüístico que designa la situación en que dos lenguas conviven con funciones diferenciadas en una comunidad', 'diglosia', 'lengua', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Técnica teatral del esperpento que consiste en presentar personajes deformados como fantoches o peleles', 'degradacion', 'lengua', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Género literario creado por Valle-Inclán que deforma la realidad mediante una estética sistemáticamente grotesca', 'esperpento', 'lengua', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Género en prosa de carácter argumentativo y reflexivo, cultivado por Ortega, Unamuno y Marías en el siglo XX', 'ensayo', 'lengua', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Recurso narrativo consistente en un salto temporal hacia adelante en la historia contada', 'flashforward', 'lengua', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Novelista autor de El Jarama, obra cumbre del realismo social y objetivista de los años 50', 'ferlosio', 'lengua', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Poeta de la experiencia cuya obra Arde el mar supuso una renovación poética en la línea de los novísimos', 'gimferrer', 'lengua', 'bachillerato', '{2}', 2),
('G', 'empieza', 'Autor del ensayo La España invertebrada que reflexionó sobre la decadencia nacional desde el raciovitalismo', 'gasset', 'lengua', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Recurso discursivo que introduce información conocida por el receptor como punto de partida del enunciado', 'hiperonimia', 'lengua', 'bachillerato', '{2}', 3),
('H', 'empieza', 'Vanguardia literaria lanzada por Vicente Huidobro que proponía crear realidades nuevas con la palabra', 'huidobro', 'lengua', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Fenómeno sociolingüístico por el cual un hablante alterna entre dos lenguas o variedades dentro de un mismo discurso', 'interferencia', 'lengua', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Figura retórica consistente en decir lo contrario de lo que se piensa, recurso frecuente en el esperpento', 'ironia', 'lengua', 'bachillerato', '{2}', 1),
('J', 'empieza', 'Poeta del 27 autor de Espacio, largo poema en prosa compuesto durante su exilio en América', 'juanramon', 'lengua', 'bachillerato', '{2}', 1),
('K', 'contiene', 'Corriente pedagógica y filosófica de origen alemán introducida en España por Sanz del Río en el siglo XIX', 'krausismo', 'lengua', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Fenómeno sociolingüístico de elección entre distintas lenguas o variedades en función de la situación comunicativa', 'lealtad', 'lengua', 'bachillerato', '{2}', 3),
('L', 'empieza', 'Autor de La colmena, novela coral que retrata el Madrid de posguerra con técnica caleidoscópica', 'linterna', 'lengua', 'bachillerato', '{2}', 3),
('M', 'empieza', 'Poeta de posguerra cuya Antología traducida exploró el humor y la ironía como forma de resistencia literaria', 'marquina', 'lengua', 'bachillerato', '{2}', 3),
('M', 'empieza', 'Técnica narrativa de la novela experimental que reproduce el fluir ininterrumpido del pensamiento del personaje', 'monologo', 'lengua', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Movimiento poético español de finales de los años 60 que rompió con la poesía social y reivindicó la autonomía del lenguaje', 'novisimos', 'lengua', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Proceso sociolingüístico de fijación de la norma culta de una lengua a través de gramáticas y diccionarios', 'normalizacion', 'lengua', 'bachillerato', '{2}', 2),
('Ñ', 'contiene', 'Adjetivo que describe las obras literarias que reflejan los problemas sociales y políticos de la España de posguerra', 'espannola', 'lengua', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Técnica narrativa que presenta los hechos sin intervención subjetiva del narrador, propia de la novela social de los 50', 'objetivismo', 'lengua', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Ensayista autor de La rebelión de las masas que formuló el concepto de razón vital', 'ortega', 'lengua', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Corriente poética de los años 80-90 que privilegia la experiencia personal, el tono urbano y la emoción contenida', 'postnovismo', 'lengua', 'bachillerato', '{2}', 3),
('P', 'empieza', 'Propiedad textual que garantiza la correcta presentación formal del texto: márgenes, tipografía, puntuación', 'presentacion', 'lengua', 'bachillerato', '{2}', 1),
('Q', 'empieza', 'Autor de La vida es sueño y modelo del drama filosófico que influyó en el teatro posterior hasta el siglo XX', 'quevedo', 'lengua', 'bachillerato', '{2}', 2),
('R', 'empieza', 'Tendencia literaria del siglo XIX que aspira a reproducir fielmente la realidad social sin idealización', 'realismo', 'lengua', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Mecanismo lingüístico de cohesión textual que sustituye un elemento por otro equivalente para evitar repeticiones', 'referencia', 'lengua', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Rama de la lingüística que estudia la relación entre lengua y sociedad: bilingüismo, diglosia, prestigio', 'sociolinguistica', 'lengua', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Corriente novelística de la posguerra española de los años 40 que muestra una realidad brutal y descarnada', 'socialrealismo', 'lengua', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Tendencia narrativa de posguerra que presenta la realidad con crudeza extrema, violencia y miseria', 'tremendismo', 'lengua', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Movimiento de compañías escénicas españolas de los años 60-70 que buscaban renovar el teatro fuera de los circuitos comerciales', 'teatroindependiente', 'lengua', 'bachillerato', '{2}', 2),
('U', 'empieza', 'Autor del ensayo Del sentimiento trágico de la vida y renovador de la novela con su concepto de nivola', 'unamuno', 'lengua', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Dramaturgo gallego creador del esperpento, autor de Luces de bohemia y las Comedias bárbaras', 'valleinclam', 'lengua', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Relación semántica entre palabras con significados opuestos, como "frío" y "caliente"', 'variable', 'lengua', 'bachillerato', '{2}', 2),
('W', 'contiene', 'Novelista ganador del Nobel cuya obra Conversación en La Catedral influyó en narradores españoles contemporáneos', 'bowniano', 'lengua', 'bachillerato', '{2}', 3),
('X', 'contiene', 'Propiedad textual que garantiza la conexión formal entre los enunciados mediante conectores, pronombres y repeticiones léxicas', 'textualidad', 'lengua', 'bachillerato', '{2}', 1),
('Y', 'contiene', 'Género periodístico de opinión que comparte rasgos con el ensayo literario y se publica en diarios y revistas', 'ensayismo', 'lengua', 'bachillerato', '{2}', 2),
('Z', 'contiene', 'Proceso de sustitución de una lengua minoritaria por otra de mayor prestigio en una comunidad bilingüe', 'desplazamiento', 'lengua', 'bachillerato', '{2}', 2),

-- Preguntas adicionales para completar 75 de Lengua Bach 2
('A', 'empieza', 'Tipo de conector discursivo que indica adición de información, como "además", "asimismo", "igualmente"', 'aditivo', 'lengua', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Fenómeno de contacto de lenguas por el cual un hablante habla dos lenguas con competencia comparable', 'bilinguismo', 'lengua', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Novelista autor de La familia de Pascual Duarte, obra fundacional del tremendismo en la narrativa española', 'cela', 'lengua', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Novelista autor de Cinco horas con Mario, retrato de la España franquista mediante monólogo interior', 'delibes', 'lengua', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Poeta de la experiencia nacido en Granada, autor de Las personas del verbo y defensor de la poesía figurativa', 'eladiolinacero', 'lengua', 'bachillerato', '{2}', 3),
('F', 'empieza', 'Tipo de texto cuya función principal es influir en la conducta del receptor, como la publicidad o el discurso político', 'funcional', 'lengua', 'bachillerato', '{2}', 2),
('G', 'empieza', 'Poeta social de posguerra autor de Celaya que reivindicó la poesía como instrumento de transformación colectiva', 'gabrielcelaya', 'lengua', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Capacidad sociolingüística del hablante para adecuar su discurso al contexto comunicativo y a sus interlocutores', 'habitus', 'lengua', 'bachillerato', '{2}', 3),
('I', 'empieza', 'Cualidad del hablante que determina su variedad lingüística personal y única, su forma individual de usar la lengua', 'idiolecto', 'lengua', 'bachillerato', '{2}', 2),
('J', 'empieza', 'Poeta del 27 autor de Hijos de la ira que inauguró la poesía existencial desarraigada de posguerra', 'joseluiscano', 'lengua', 'bachillerato', '{2}', 3),
('L', 'empieza', 'Poeta y ensayista autor de La realidad y el deseo, exiliado del 27 cuya obra influyó en la poesía de la experiencia', 'luiscernuda', 'lengua', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Autor de Tiempo de silencio, novela experimental de 1962 que rompió con el realismo social imperante', 'martinssantos', 'lengua', 'bachillerato', '{2}', 2),
('N', 'empieza', 'Tipo de texto que cuenta hechos reales o ficticios organizados en una secuencia temporal', 'narrativo', 'lengua', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Conector discursivo que introduce una alternativa o matización al enunciado previo', 'oposicion', 'lengua', 'bachillerato', '{2}', 2),
('P', 'empieza', 'Actitud lingüística favorable hacia una variedad considerada de mayor estatus social o cultural', 'prestigio', 'lengua', 'bachillerato', '{2}', 2),
('R', 'empieza', 'Recurso de cohesión consistente en repetir una misma palabra o estructura para dar énfasis al discurso', 'reiteracion', 'lengua', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Autor de Señas de identidad que renovó la novela española de los 60 con técnicas experimentales y plurilingüismo', 'sastre', 'lengua', 'bachillerato', '{2}', 3),
('T', 'empieza', 'Unidad comunicativa máxima con sentido completo, objeto de estudio de la lingüística textual', 'texto', 'lengua', 'bachillerato', '{2}', 1),
('U', 'empieza', 'Empleo lingüístico generalizado y aceptado por los hablantes de una comunidad, frente a la norma prescriptiva', 'uso', 'lengua', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Poeta novísimo autor de Sepulcro en Tarquinia que incorporó referencias culturalistas y esteticistas', 'villena', 'lengua', 'bachillerato', '{2}', 2),
('Z', 'contiene', 'Tipo de ensayo que analiza críticamente la situación política o moral de un país, frecuente en el 98 y el novecentismo', 'razonamiento', 'lengua', 'bachillerato', '{2}', 2),

-- =====================================================
-- FILOSOFÍA BACHILLERATO 1 (75 preguntas)
-- Temas: atomismo, cinismo, neoplatonismo, nominalismo,
-- escolástica, ocasionalismo, idealismo trascendental,
-- positivismo, fenomenología, filosofía analítica, bioética,
-- filosofía de la mente
-- =====================================================

('A', 'empieza', 'Corriente filosófica presocrática que explica la realidad como combinación de partículas indivisibles en el vacío', 'atomismo', 'filosofia', 'bachillerato', '{1}', 1),
('A', 'empieza', 'Rama de la filosofía que estudia los valores, la belleza y la experiencia estética', 'axiologia', 'filosofia', 'bachillerato', '{1}', 2),
('A', 'empieza', 'Argumento filosófico que pretende demostrar la existencia de Dios a partir de la sola definición de su concepto', 'anselmo', 'filosofia', 'bachillerato', '{1}', 2),
('B', 'empieza', 'Rama de la ética aplicada que analiza los dilemas morales surgidos de los avances en medicina y ciencias de la vida', 'bioetica', 'filosofia', 'bachillerato', '{1}', 1),
('B', 'empieza', 'Filósofo empirista irlandés que negó la existencia de la materia y afirmó que ser es ser percibido', 'berkeley', 'filosofia', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Escuela filosófica helenística fundada por Antístenes y representada por Diógenes, que rechazaba las convenciones sociales', 'cinismo', 'filosofia', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Problema filosófico sobre la relación entre los estados mentales conscientes y los procesos cerebrales físicos', 'conciencia', 'filosofia', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Posición epistemológica que sostiene que los conceptos universales se forman por abstracción a partir de la experiencia', 'conceptualismo', 'filosofia', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Filósofo presocrático que junto con Leucipo formuló la teoría de los átomos y el vacío', 'democrito', 'filosofia', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Posición en filosofía de la mente que defiende la existencia de dos sustancias irreductibles: cuerpo y mente', 'dualismo', 'filosofia', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Corriente filosófica medieval que integró la fe cristiana con la razón filosófica grecolatina en las universidades', 'escolastica', 'filosofia', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Concepto fenomenológico husserliano que designa la suspensión del juicio sobre la existencia del mundo exterior', 'epoje', 'filosofia', 'bachillerato', '{1}', 2),
('F', 'empieza', 'Corriente del siglo XX que analiza los problemas filosóficos como problemas de lenguaje, representada por Russell y Wittgenstein', 'filosofiaanalitica', 'filosofia', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Método filosófico fundado por Husserl que estudia las estructuras de la experiencia tal como se presentan a la conciencia', 'fenomenologia', 'filosofia', 'bachillerato', '{1}', 1),
('G', 'empieza', 'Pensador medieval franciscano conocido por su navaja, que defendió que no deben multiplicarse los entes sin necesidad', 'guillermodeockham', 'filosofia', 'bachillerato', '{1}', 2),
('H', 'empieza', 'Filósofo escocés que cuestionó la causalidad y defendió que el conocimiento se funda en la costumbre y la experiencia', 'hume', 'filosofia', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Concepto fenomenológico que designa la vivencia intencional en la que la conciencia se dirige a un objeto', 'horizonte', 'filosofia', 'bachillerato', '{1}', 3),
('I', 'empieza', 'Sistema filosófico kantiano que sostiene que el sujeto constituye activamente las condiciones de posibilidad del conocimiento', 'idealismo', 'filosofia', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Propiedad de la conciencia por la cual todo acto mental se dirige necesariamente a un objeto, concepto central en Husserl', 'intencionalidad', 'filosofia', 'bachillerato', '{1}', 2),
('J', 'empieza', 'Tipo de proposición kantiana que amplía el conocimiento y a la vez es válida independientemente de la experiencia', 'juicio', 'filosofia', 'bachillerato', '{1}', 2),
('K', 'contiene', 'Principio lógico del positivismo que establece que solo las proposiciones verificables empíricamente tienen significado cognitivo', 'verificacionismo', 'filosofia', 'bachillerato', '{1}', 2),
('L', 'empieza', 'Filósofo presocrático considerado cofundador del atomismo junto a Demócrito', 'leucipo', 'filosofia', 'bachillerato', '{1}', 1),
('L', 'empieza', 'Posición en filosofía analítica según la cual los problemas filosóficos son en realidad confusiones lingüísticas', 'linguistico', 'filosofia', 'bachillerato', '{1}', 2),
('M', 'empieza', 'Tesis en filosofía de la mente que identifica los estados mentales con estados físicos del cerebro', 'materialismo', 'filosofia', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Filósofo racionalista que propuso la teoría del ocasionalismo para resolver la interacción mente-cuerpo', 'malebranche', 'filosofia', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Corriente filosófica tardoantigua que reinterpretó las ideas platónicas como emanaciones de un principio Uno absoluto', 'neoplatonismo', 'filosofia', 'bachillerato', '{1}', 1),
('N', 'empieza', 'Doctrina medieval según la cual los universales son solo nombres sin realidad fuera de la mente', 'nominalismo', 'filosofia', 'bachillerato', '{1}', 1),
('Ñ', 'contiene', 'Acto de instruir o transmitir un saber, objeto de reflexión filosófica desde la paideia griega hasta la pedagogía moderna', 'ensenanza', 'filosofia', 'bachillerato', '{1}', 1),
('O', 'empieza', 'Doctrina filosófica de Malebranche según la cual Dios es la causa real de toda interacción entre mente y cuerpo', 'ocasionalismo', 'filosofia', 'bachillerato', '{1}', 2),
('O', 'empieza', 'Rama de la filosofía que estudia las categorías fundamentales del ser, la existencia y la realidad', 'ontologia', 'filosofia', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Corriente filosófica fundada por Comte que limita el conocimiento válido a los hechos observables y las leyes científicas', 'positivismo', 'filosofia', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Filósofo neoplatónico del siglo III que sistematizó la teoría de la emanación del Uno', 'plotino', 'filosofia', 'bachillerato', '{1}', 2),
('Q', 'empieza', 'Experiencia subjetiva consciente de un estado mental, como el "cómo es" sentir dolor, debate central en filosofía de la mente', 'qualia', 'filosofia', 'bachillerato', '{1}', 3),
('R', 'empieza', 'Corriente epistemológica que defiende que la razón es la fuente principal y criterio del conocimiento válido', 'racionalismo', 'filosofia', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Posición medieval opuesta al nominalismo que atribuye existencia real a los universales fuera de la mente', 'realismo', 'filosofia', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Método filosófico socrático basado en el diálogo que alumbra la verdad latente en el interlocutor', 'socratico', 'filosofia', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Posición en filosofía de la mente que niega la existencia real de los estados mentales del sentido común', 'superveniencia', 'filosofia', 'bachillerato', '{1}', 3),
('T', 'empieza', 'Adjetivo que califica al idealismo kantiano, referido a las condiciones a priori que hacen posible la experiencia', 'trascendental', 'filosofia', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Filósofo escolástico dominico que armonizó la filosofía aristotélica con la teología cristiana en la Summa', 'tomas', 'filosofia', 'bachillerato', '{1}', 1),
('U', 'empieza', 'Concepto filosófico que designa aquello que se predica de todas las cosas de una misma clase, central en la disputa medieval', 'universal', 'filosofia', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Principio del Círculo de Viena según el cual un enunciado solo tiene sentido si es susceptible de comprobación empírica', 'verificacion', 'filosofia', 'bachillerato', '{1}', 2),
('W', 'contiene', 'Filósofo del Círculo de Viena cuyo Tractatus delimitó lo decible y afirmó que de lo que no se puede hablar hay que callar', 'wittgenstein', 'filosofia', 'bachillerato', '{1}', 1),
('X', 'contiene', 'Concepto fenomenológico referido a la vivencia que se presenta inmediatamente a la conciencia sin mediación', 'existencia', 'filosofia', 'bachillerato', '{1}', 1),
('Y', 'contiene', 'Concepto epistemológico que designa la creencia justificada y verdadera, definición clásica del saber', 'creyente', 'filosofia', 'bachillerato', '{1}', 3),
('Z', 'contiene', 'Capacidad humana de pensar y argumentar correctamente, objeto central de la lógica y la epistemología', 'razonamiento', 'filosofia', 'bachillerato', '{1}', 1),

-- Preguntas adicionales para completar 75 de Filosofía Bach 1
('A', 'empieza', 'Filósofo helenístico cínico que vivía en una tinaja y buscaba con un candil a un hombre honesto', 'antisocial', 'filosofia', 'bachillerato', '{1}', 3),
('B', 'empieza', 'Posición filosófica que reduce todos los fenómenos mentales a procesos biológicos cerebrales sin residuo inmaterial', 'biologicismo', 'filosofia', 'bachillerato', '{1}', 3),
('C', 'empieza', 'Fundador del positivismo que propuso la ley de los tres estadios: teológico, metafísico y positivo', 'comte', 'filosofia', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Procedimiento lógico que va de lo general a lo particular, fundamental en la epistemología racionalista', 'deduccion', 'filosofia', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Corriente epistemológica que sostiene que todo conocimiento procede de la experiencia sensible', 'empirismo', 'filosofia', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Posición en filosofía de la mente según la cual los estados mentales se definen por sus relaciones causales', 'funcionalismo', 'filosofia', 'bachillerato', '{1}', 2),
('G', 'empieza', 'Rama de la epistemología que investiga la naturaleza, el alcance y los límites del conocimiento humano', 'gnoseologia', 'filosofia', 'bachillerato', '{1}', 2),
('H', 'empieza', 'Corriente ética que identifica el bien con el placer moderado y la amistad, fundada por Epicuro', 'hedonismo', 'filosofia', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Razonamiento que parte de casos particulares para establecer una conclusión general, cuestionado por Hume', 'induccion', 'filosofia', 'bachillerato', '{1}', 1),
('J', 'empieza', 'Proposición susceptible de ser verdadera o falsa, componente básico del razonamiento lógico en Kant', 'juiciosintetico', 'filosofia', 'bachillerato', '{1}', 2),
('L', 'empieza', 'Filósofo racionalista alemán que propuso la teoría de las mónadas y la armonía preestablecida', 'leibniz', 'filosofia', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Concepto kantiano que designa la realidad tal como es en sí misma, inaccesible al conocimiento humano', 'monadologia', 'filosofia', 'bachillerato', '{1}', 3),
('N', 'empieza', 'Concepto kantiano que designa la cosa en sí, el objeto pensado pero no experimentado', 'noumeno', 'filosofia', 'bachillerato', '{1}', 2),
('O', 'empieza', 'Argumento escolástico que demuestra la existencia de Dios por la necesidad de una causa primera del orden cósmico', 'ordenacion', 'filosofia', 'bachillerato', '{1}', 2),
('P', 'empieza', 'Concepto del neoplatonismo que refiere al ser supremo e inefable del que emana toda la realidad', 'principio', 'filosofia', 'bachillerato', '{1}', 2),
('R', 'empieza', 'Método fenomenológico que pone entre paréntesis las presuposiciones para acceder a las esencias de los fenómenos', 'reduccion', 'filosofia', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Filósofo racionalista holandés que identificó Dios con la Naturaleza en un sistema monista panteísta', 'spinoza', 'filosofia', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Término griego que designa el fin o propósito de un ser, central en la ética y la metafísica aristotélicas', 'teleologia', 'filosofia', 'bachillerato', '{1}', 2),
('U', 'empieza', 'Doctrina ética que juzga la moralidad de una acción por la cantidad de bienestar que produce para el mayor número', 'utilitarismo', 'filosofia', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Movimiento filosófico del siglo XX que exigió la verificación empírica como criterio de significado de los enunciados', 'viena', 'filosofia', 'bachillerato', '{1}', 2),
('X', 'contiene', 'Concepto filosófico que designa lo que hay, lo que es, el conjunto de todo lo real', 'existente', 'filosofia', 'bachillerato', '{1}', 1),
('Y', 'contiene', 'Problema bioético sobre la creación y manipulación de copias genéticas de organismos vivos', 'clonacion', 'filosofia', 'bachillerato', '{1}', 1),
('Z', 'contiene', 'Condición para que una proposición descriptiva sea verdadera según la teoría correspondentista', 'veraz', 'filosofia', 'bachillerato', '{1}', 2),

-- =====================================================
-- FILOSOFÍA BACHILLERATO 2 (75 preguntas)
-- Temas: dualismo platónico, hilemorfismo, pruebas de Dios,
-- mecanicismo cartesiano, problema de la inducción,
-- juicios sintéticos a priori, plusvalía, eterno retorno,
-- razón vital, ética discursiva
-- =====================================================

('A', 'empieza', 'Concepto aristotélico que designa el paso de la potencia al acto, el movimiento como actualización de posibilidades', 'actualizacion', 'filosofia', 'bachillerato', '{2}', 2),
('A', 'empieza', 'Argumento medieval que pretende probar la existencia de Dios a partir de la necesidad de un primer motor inmóvil', 'argumento', 'filosofia', 'bachillerato', '{2}', 1),
('A', 'empieza', 'Concepto marxista referido a la condición del trabajador que se siente extraño respecto al producto de su trabajo', 'alienacion', 'filosofia', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Concepto marxista que designa la estructura económica sobre la que se levanta la superestructura ideológica', 'base', 'filosofia', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Concepto cartesiano que designa al yo pensante como primera certeza indubitable tras la duda metódica', 'cogito', 'filosofia', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Imperativo moral kantiano que exige actuar según una máxima universalizable, sin excepciones', 'categorico', 'filosofia', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Filósofa y filósofo de la Escuela de Fráncfort que junto a Habermas desarrolló la ética del discurso', 'comunicativa', 'filosofia', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Método filosófico cartesiano que consiste en rechazar como falso todo aquello que pueda ser puesto en duda', 'duda', 'filosofia', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Teoría platónica que separa la realidad en dos planos: el mundo sensible y el mundo inteligible de las Ideas', 'dualismo', 'filosofia', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Tipo de materialismo marxista que concibe la historia como lucha de contrarios que se resuelve en una síntesis superior', 'dialectico', 'filosofia', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Concepto nietzscheano según el cual todos los acontecimientos del universo se repiten cíclicamente de forma idéntica', 'eternoretorno', 'filosofia', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Concepto aristotélico que designa la forma o esencia que determina lo que una cosa es necesariamente', 'entelequia', 'filosofia', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Teoría del conocimiento cartesiana que confía en la razón y las ideas innatas como fuente de certeza', 'evidencia', 'filosofia', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Concepto platónico que refiere a las realidades perfectas, inmutables y eternas que constituyen el verdadero ser', 'forma', 'filosofia', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Concepto nietzscheano que designa la energía creadora e instintiva que impulsa al individuo a superarse', 'fuerza', 'filosofia', 'bachillerato', '{2}', 2),
('G', 'empieza', 'Filósofo autor de la teoría del genio maligno como hipótesis radical de duda en las Meditaciones metafísicas', 'geniomaligno', 'filosofia', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Filósofo de la Escuela de Fráncfort que formuló la ética discursiva basada en la acción comunicativa', 'habermas', 'filosofia', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Teoría aristotélica según la cual toda sustancia está compuesta de materia y forma inseparablemente unidas', 'hilemorfismo', 'filosofia', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Tipo de conocimiento kantiano que es universal y necesario pero amplía el saber, como los juicios de la matemática pura', 'intuicion', 'filosofia', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Problema epistemológico planteado por Hume sobre la legitimidad de inferir leyes generales a partir de casos particulares', 'induccion', 'filosofia', 'bachillerato', '{2}', 1),
('J', 'empieza', 'Proposición kantiana que es a la vez ampliativa y válida con independencia de la experiencia, fundamento de la ciencia', 'juiciosinteticoapriori', 'filosofia', 'bachillerato', '{2}', 2),
('K', 'contiene', 'Concepto marxista que designa la clase social poseedora de los medios de producción y explotadora del proletariado', 'burguesia', 'filosofia', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Concepto marxista que designa la lucha entre clases sociales como motor del cambio histórico', 'luchadeclases', 'filosofia', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Visión cartesiana del mundo físico según la cual la naturaleza funciona como una máquina regida por leyes causales', 'mecanicismo', 'filosofia', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Concepto aristotélico que designa el sustrato indeterminado que recibe la forma para constituir la sustancia', 'materia', 'filosofia', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Concepto nietzscheano que designa la negación de todos los valores y sentidos trascendentes de la existencia', 'nihilismo', 'filosofia', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Concepto kantiano referido a la realidad en sí misma, incognoscible, que se opone al fenómeno', 'noumeno', 'filosofia', 'bachillerato', '{2}', 2),
('Ñ', 'contiene', 'Tipo de razón orteguiana que no es pura ni abstracta sino enraizada en la circunstancia vital del individuo', 'companero', 'filosofia', 'bachillerato', '{2}', 3),
('O', 'empieza', 'Filósofo español autor de la teoría de la razón vital y la razón histórica como superación del racionalismo', 'ortega', 'filosofia', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Concepto platónico para el conocimiento verdadero de las Ideas frente a la mera opinión del mundo sensible', 'opinion', 'filosofia', 'bachillerato', '{2}', 2),
('P', 'empieza', 'Concepto marxista que designa la diferencia entre el valor producido por el trabajador y el salario que recibe', 'plusvalia', 'filosofia', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Concepto aristotélico que designa la capacidad de un ser para llegar a ser algo que aún no es en acto', 'potencia', 'filosofia', 'bachillerato', '{2}', 1),
('Q', 'empieza', 'Prueba tomista de la existencia de Dios basada en la imposibilidad de una serie infinita de causas eficientes', 'quintavia', 'filosofia', 'bachillerato', '{2}', 2),
('R', 'empieza', 'Concepto orteguiano que designa una razón inseparable de la vida concreta del sujeto y su circunstancia histórica', 'razonvital', 'filosofia', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Atributo cartesiano de la sustancia pensante, cuya naturaleza es pensar y cuya existencia es indubitable', 'rescogitans', 'filosofia', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Concepto nietzscheano que designa al ser humano que ha superado la moral del rebaño y crea sus propios valores', 'superhombre', 'filosofia', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Concepto marxista referido a las instituciones jurídicas, políticas e ideológicas que se asientan sobre la base económica', 'superestructura', 'filosofia', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Pruebas racionales de la existencia de Dios formuladas por Tomás de Aquino en la Summa Theologica', 'tomistavias', 'filosofia', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Forma a priori de la sensibilidad en Kant que, junto con el espacio, hace posible la experiencia fenoménica', 'tiempo', 'filosofia', 'bachillerato', '{2}', 1),
('U', 'empieza', 'Concepto nietzscheano que designa la revalorización de todos los valores tras la muerte de Dios', 'uebermensch', 'filosofia', 'bachillerato', '{2}', 3),
('V', 'empieza', 'Prueba tomista que parte de los grados de perfección en los seres para demostrar la existencia de un ser perfectísimo', 'via', 'filosofia', 'bachillerato', '{2}', 2),
('V', 'empieza', 'Concepto orteguiano según el cual la vida es la realidad radical desde la que se comprende todo lo demás', 'vivencia', 'filosofia', 'bachillerato', '{2}', 2),
('W', 'contiene', 'Filósofo que anunció la muerte de Dios y la necesidad de una transvaloración de todos los valores morales', 'nietzsche', 'filosofia', 'bachillerato', '{2}', 1),
('X', 'contiene', 'Concepto marxista que designa la apropiación del trabajo ajeno por parte del capitalista sin justa compensación', 'explotacion', 'filosofia', 'bachillerato', '{2}', 1),
('Y', 'contiene', 'Concepto kantiano referido al sujeto que constituye activamente la experiencia mediante las formas a priori', 'trascendentalmente', 'filosofia', 'bachillerato', '{2}', 3),
('Z', 'contiene', 'Concepto orteguiano que designa la necesidad de situar al individuo en su contexto histórico para comprenderlo', 'circunstancializar', 'filosofia', 'bachillerato', '{2}', 3),

-- Preguntas adicionales para completar 75 de Filosofía Bach 2
('A', 'empieza', 'Concepto aristotélico que designa la realización plena de las potencialidades de un ser', 'acto', 'filosofia', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Filósofo racionalista cuyas Meditaciones establecieron el dualismo entre res cogitans y res extensa', 'baruch', 'filosofia', 'bachillerato', '{2}', 3),
('C', 'empieza', 'Categoría kantiana del entendimiento que permite pensar la relación necesaria entre causa y efecto en los fenómenos', 'causalidad', 'filosofia', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Requisito de la ética discursiva de Habermas según el cual las normas morales deben ser aceptadas por todos los afectados', 'discurso', 'filosofia', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Concepto kantiano que designa la forma a priori de la sensibilidad junto con el tiempo', 'espacio', 'filosofia', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Concepto kantiano que designa aquello que aparece al sujeto tras ser configurado por las formas a priori de la sensibilidad', 'fenomeno', 'filosofia', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Idea platónica suprema que ilumina las demás Ideas y es principio del ser y del conocer', 'gradacion', 'filosofia', 'bachillerato', '{2}', 3),
('H', 'empieza', 'Proceso dialectico marxista por el cual la tesis y la antítesis se superan en una síntesis que las integra', 'historicismo', 'filosofia', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Concepto cartesiano referido a las ideas que el sujeto posee desde el nacimiento, no derivadas de la experiencia', 'innatas', 'filosofia', 'bachillerato', '{2}', 1),
('J', 'empieza', 'Proposición kantiana cuyo predicado está contenido en el sujeto y no amplía el conocimiento', 'juicioanalitico', 'filosofia', 'bachillerato', '{2}', 2),
('L', 'empieza', 'Alegoría platónica de la liberación del prisionero que contempla las sombras y asciende hacia la verdad', 'liberacion', 'filosofia', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Concepto nietzscheano que designa la moral de los débiles basada en la culpa, la compasión y la renuncia', 'moraldeesclavos', 'filosofia', 'bachillerato', '{2}', 2),
('N', 'empieza', 'Principio ético kantiano que prohíbe tratar a las personas solo como medios y exige respetarlas como fines en sí mismas', 'norma', 'filosofia', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Situación ideal de habla en la ética discursiva de Habermas donde todos los participantes dialogan sin coacción', 'openness', 'filosofia', 'bachillerato', '{2}', 3),
('P', 'empieza', 'Clase social marxista que solo posee su fuerza de trabajo y la vende al capitalista a cambio de un salario', 'proletariado', 'filosofia', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Concepto orteguiano que complementa la razón vital situando al sujeto en su contexto temporal y cultural', 'razonhistorica', 'filosofia', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Atributo cartesiano de la sustancia material, cuya naturaleza es la extensión en largo, ancho y profundo', 'resextensa', 'filosofia', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Concepto aristotélico que designa al ente individual compuesto de materia y forma, soporte de los accidentes', 'sustancia', 'filosofia', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Concepto marxista referido a la cantidad de trabajo socialmente necesario para producir una mercancía', 'trabajoabstracto', 'filosofia', 'bachillerato', '{2}', 3),
('U', 'empieza', 'Requisito de la ética kantiana según el cual una máxima moral debe poder ser querida como ley para todos los seres racionales', 'universalizabilidad', 'filosofia', 'bachillerato', '{2}', 2),
('V', 'empieza', 'Concepto marxista que distingue entre el valor que tiene un bien por su utilidad y el valor que tiene en el mercado', 'valor', 'filosofia', 'bachillerato', '{2}', 1),
('W', 'contiene', 'Filósofo alemán cuya dialéctica del señor y el siervo influyó decisivamente en la teoría marxista de la alienación', 'hegelianismo', 'filosofia', 'bachillerato', '{2}', 2),
('X', 'contiene', 'Concepto nietzscheano que describe la situación cultural tras la pérdida de los valores trascendentes tradicionales', 'inexistencia', 'filosofia', 'bachillerato', '{2}', 2),
('Y', 'contiene', 'Frase orteguiana que expresa que el ser humano no tiene naturaleza fija sino que se va haciendo a lo largo del tiempo', 'proyectandose', 'filosofia', 'bachillerato', '{2}', 2),
('Z', 'contiene', 'Concepto habermasiano que designa la validez de una norma moral alcanzada mediante el consenso racional', 'razonabilidad', 'filosofia', 'bachillerato', '{2}', 2),

-- Preguntas extra para alcanzar 75 por categoría

-- LENGUA BACH 1: 5 más (70→75)
('B', 'empieza', 'Autor de la novela picaresca El Buscón, que satiriza la sociedad española del siglo XVII con estilo conceptista', 'buscavidas', 'lengua', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Complemento del verbo que recibe directamente la acción, identificable con la pregunta qué o a quién', 'directo', 'lengua', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Tipo de perífrasis verbal que indica una acción futura inminente, como "ir a + infinitivo"', 'futuro', 'lengua', 'bachillerato', '{1}', 1),
('G', 'empieza', 'Obra en prosa didáctica del Renacimiento escrita por fray Antonio de Guevara como espejo de príncipes', 'guevara', 'lengua', 'bachillerato', '{1}', 2),
('T', 'empieza', 'Poema extenso en tercetos encadenados de Garcilaso que introduce el modelo virgiliano en la lírica castellana', 'tercetoencadenado', 'lengua', 'bachillerato', '{1}', 3),

-- LENGUA BACH 2: 7 más (68→75)
('C', 'empieza', 'Autor de La colmena, novela coral de 1951 que retrata sin idealismo la miseria del Madrid de posguerra', 'celacamilo', 'lengua', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Tipo de conector discursivo que introduce una consecuencia lógica, como "por tanto", "en consecuencia"', 'deductivo', 'lengua', 'bachillerato', '{2}', 2),
('G', 'empieza', 'Grupo poético del 27 cuya estética combinó la tradición popular con la vanguardia y la poesía pura', 'generacion', 'lengua', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Recurso de cohesión textual que utiliza sinónimos, hiperónimos o paráfrasis para evitar la repetición léxica', 'hiperonimo', 'lengua', 'bachillerato', '{2}', 2),
('L', 'empieza', 'Género periodístico y literario del costumbrismo cultivado por Larra con intención satírica y reformista', 'larra', 'lengua', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Recurso estilístico del esperpento que animaliza y cosifica a los personajes para subrayar su degradación', 'munecoizacion', 'lengua', 'bachillerato', '{2}', 3),
('P', 'empieza', 'Poeta de la experiencia autor de Habitaciones separadas que cultiva un lirismo urbano e intimista', 'poesiadelaexperiencia', 'lengua', 'bachillerato', '{2}', 2),

-- FILOSOFÍA BACH 1: 7 más (68→75)
('A', 'empieza', 'Concepto fenomenológico que designa la dirección de la conciencia hacia su objeto, según Brentano y Husserl', 'aprehension', 'filosofia', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Problema filosófico sobre si las máquinas pueden pensar, formulado mediante un test por Turing', 'computacional', 'filosofia', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Filósofo cínico que rechazaba toda propiedad y convención, viviendo en la pobreza extrema como forma de libertad', 'diogenes', 'filosofia', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Proceso neoplatónico por el cual la realidad fluye gradualmente desde el Uno hacia niveles inferiores de ser', 'emanacion', 'filosofia', 'bachillerato', '{1}', 2),
('F', 'empieza', 'Criterio epistemológico del positivismo lógico que exige poder refutar una hipótesis para considerarla científica', 'falsabilidad', 'filosofia', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Rama de la filosofía de la mente que estudia la relación entre los procesos cerebrales y la experiencia consciente', 'neurociencia', 'filosofia', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Concepto escolástico que designa las cinco pruebas racionales de la existencia de Dios propuestas por Tomás de Aquino', 'pruebascosmologicas', 'filosofia', 'bachillerato', '{1}', 2),

-- FILOSOFÍA BACH 2: 4 más (71→75)
('C', 'empieza', 'Frase orteguiana que expresa que el individuo es inseparable de su entorno: "yo soy yo y mi..."', 'circunstancia', 'filosofia', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Concepto de la ética discursiva que exige que las normas morales se justifiquen mediante argumentación racional entre iguales', 'eticadiscursiva', 'filosofia', 'bachillerato', '{2}', 1),
('K', 'contiene', 'Filósofo coreano-alemán autor de La sociedad del cansancio que critica el rendimiento como nueva forma de explotación', 'byungchulhan', 'filosofia', 'bachillerato', '{2}', 3),
('L', 'empieza', 'Concepto marxista referido al proceso de acumulación originaria del capital mediante la expropiación de los campesinos', 'latifundismo', 'filosofia', 'bachillerato', '{2}', 3);
