-- Rosco Bachillerato Ciencias Exactas - Lote 2 (375 preguntas adicionales)
-- Vocabulario específico y avanzado, diferente del lote base

INSERT INTO rosco_questions (letter, type, definition, solution, subject_id, level, grades, difficulty) VALUES

-- =====================================================
-- MATEMÁTICAS 1º BACHILLERATO (75 preguntas)
-- Rolle, Bolzano, Weierstrass, Cramer, rango, combinatoria,
-- distribución binomial/normal, intervalos de confianza, cónicas
-- =====================================================

('A', 'empieza', 'Eje mayor o menor de una elipse que determina su forma y tamaño', 'apotema', 'matematicas', 'bachillerato', '{1}', 1),
('A', 'empieza', 'Valor al que se aproxima una función sin llegar a alcanzarlo necesariamente, concepto fundamental del cálculo', 'asintotica', 'matematicas', 'bachillerato', '{1}', 2),
('A', 'empieza', 'Propiedad de una función que garantiza que no presenta saltos ni discontinuidades en un intervalo', 'acotada', 'matematicas', 'bachillerato', '{1}', 2),
('B', 'empieza', 'Teorema que garantiza la existencia de al menos una raíz en un intervalo donde la función continua cambia de signo', 'bolzano', 'matematicas', 'bachillerato', '{1}', 1),
('B', 'empieza', 'Distribución de probabilidad discreta que modela el número de éxitos en n ensayos independientes con probabilidad constante', 'binomial', 'matematicas', 'bachillerato', '{1}', 1),
('B', 'empieza', 'Elemento que pertenece al espacio vectorial y que, al aplicarle la base, reproduce cualquier vector del espacio', 'baricentro', 'matematicas', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Regla que permite resolver sistemas de ecuaciones lineales usando determinantes cuando el determinante principal es distinto de cero', 'cramer', 'matematicas', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Número de subconjuntos de k elementos que se pueden formar de un conjunto de n elementos sin importar el orden', 'combinaciones', 'matematicas', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Curvas de segundo grado obtenidas al cortar un cono con un plano: elipse, hipérbola y parábola', 'conicas', 'matematicas', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Propiedad de una función que no presenta saltos, huecos ni discontinuidades en su dominio', 'continuidad', 'matematicas', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Valor numérico asociado a una matriz cuadrada que indica si el sistema tiene solución única', 'determinante', 'matematicas', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Propiedad de una función que implica que se puede trazar su tangente en cada punto del dominio', 'diferenciable', 'matematicas', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Curva cónica cerrada definida como el lugar geométrico de puntos cuya suma de distancias a dos focos es constante', 'elipse', 'matematicas', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Valor numérico que mide la desviación de una cónica respecto a la circunferencia, entre 0 y 1 para la elipse', 'excentricidad', 'matematicas', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Tipo de suceso en probabilidad que no puede ocurrir junto con otro suceso dado', 'excluyente', 'matematicas', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Cada uno de los dos puntos fijos que definen una elipse o una hipérbola', 'foco', 'matematicas', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Operación matemática que a cada número natural le asigna el producto de todos los enteros positivos menores o iguales que él', 'factorial', 'matematicas', 'bachillerato', '{1}', 1),
('G', 'empieza', 'Distribución de probabilidad continua en forma de campana simétrica, también llamada distribución normal', 'gaussiana', 'matematicas', 'bachillerato', '{1}', 2),
('H', 'empieza', 'Curva cónica abierta formada por dos ramas, lugar geométrico de puntos cuya diferencia de distancias a dos focos es constante', 'hiperbola', 'matematicas', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Afirmación que se plantea en un contraste estadístico y que se busca rechazar o no con los datos muestrales', 'hipotesis', 'matematicas', 'bachillerato', '{1}', 2),
('I', 'empieza', 'Rango de valores dentro del cual se estima que se encuentra el parámetro poblacional con cierta probabilidad', 'intervalo', 'matematicas', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Propiedad que cumplen los sucesos cuando la ocurrencia de uno no afecta la probabilidad del otro', 'independencia', 'matematicas', 'bachillerato', '{1}', 2),
('J', 'empieza', 'En el plano cartesiano, propiedad de dos vectores cuyo producto escalar es cero, indicando perpendicularidad', 'juxtapuesto', 'matematicas', 'bachillerato', '{1}', 3),
('K', 'contiene', 'Estadístico que mide el grado de apuntamiento de una distribución respecto a la normal', 'kurtosis', 'matematicas', 'bachillerato', '{1}', 3),
('L', 'empieza', 'Recta que es tangente a una curva en el infinito, es decir, la curva se aproxima a ella sin cortarla', 'lineal', 'matematicas', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Valor esperado de una variable aleatoria, también llamado esperanza matemática', 'media', 'matematicas', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Subconjunto de elementos de una población seleccionado para inferir propiedades del total', 'muestra', 'matematicas', 'bachillerato', '{1}', 1),
('N', 'empieza', 'Distribución continua simétrica con forma de campana caracterizada por su media y su desviación típica', 'normal', 'matematicas', 'bachillerato', '{1}', 1),
('N', 'empieza', 'Coeficientes que aparecen en el desarrollo del binomio de Newton, dispuestos en el triángulo de Pascal', 'numeros', 'matematicas', 'bachillerato', '{1}', 1),
('Ñ', 'contiene', 'En estadística, tamaño del subconjunto representativo de la población que se extrae para el estudio', 'muestreno', 'matematicas', 'bachillerato', '{1}', 3),
('O', 'empieza', 'Número de formas de elegir k elementos de n donde sí importa el orden de selección', 'ordenaciones', 'matematicas', 'bachillerato', '{1}', 2),
('P', 'empieza', 'Curva cónica abierta con un solo foco, lugar geométrico de puntos equidistantes de un foco y una recta directriz', 'parabola', 'matematicas', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Número de formas de ordenar n elementos distintos, equivalente al factorial de n', 'permutaciones', 'matematicas', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Nivel de confianza complementario al nivel de significación en un contraste de hipótesis estadístico', 'proporcion', 'matematicas', 'bachillerato', '{1}', 2),
('Q', 'contiene', 'Cada uno de los cuatro valores que dividen la distribución ordenada de datos en cuatro partes iguales', 'cuartiquiles', 'matematicas', 'bachillerato', '{1}', 2),
('R', 'empieza', 'Número máximo de filas o columnas linealmente independientes de una matriz', 'rango', 'matematicas', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Teorema que establece que toda función continua y derivable en un intervalo cerrado tiene al menos un punto donde la derivada se anula, si los valores en los extremos coinciden', 'rolle', 'matematicas', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Raíz cuadrada positiva de la varianza, medida de dispersión en las mismas unidades que los datos', 'sigma', 'matematicas', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Tipo de sistema de ecuaciones lineales que tiene exactamente una solución, infinitas o ninguna según el rango', 'sistema', 'matematicas', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Coeficiente que multiplica cada término del desarrollo de un binomio elevado a una potencia natural', 'trinomio', 'matematicas', 'bachillerato', '{1}', 2),
('T', 'empieza', 'Tabla de valores que muestra la probabilidad acumulada de la distribución normal estándar', 'tipificacion', 'matematicas', 'bachillerato', '{1}', 2),
('U', 'empieza', 'Propiedad de un sistema de ecuaciones que tiene una y solo una solución', 'unicidad', 'matematicas', 'bachillerato', '{1}', 2),
('V', 'empieza', 'Agrupaciones ordenadas de k elementos tomados de un conjunto de n, donde importa el orden pero no la repetición', 'variaciones', 'matematicas', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Medida de dispersión que calcula el promedio de las desviaciones al cuadrado respecto a la media', 'varianza', 'matematicas', 'bachillerato', '{1}', 1),
('W', 'contiene', 'Teorema que garantiza que toda función continua en un intervalo cerrado alcanza un máximo y un mínimo absolutos', 'weierstrass', 'matematicas', 'bachillerato', '{1}', 2),
('X', 'contiene', 'Valor de la variable horizontal en un sistema de coordenadas cartesianas o en una ecuación paramétrica', 'aproximacion', 'matematicas', 'bachillerato', '{1}', 1),
('Y', 'contiene', 'Ley de probabilidad que permite calcular la probabilidad de una causa dado un efecto observado', 'bayesiano', 'matematicas', 'bachillerato', '{1}', 3),
('Z', 'contiene', 'Variable estandarizada que resulta de restar la media y dividir por la desviación típica, usada en la normal estándar', 'estandarizada', 'matematicas', 'bachillerato', '{1}', 2),

-- Preguntas extra para completar 75
('A', 'empieza', 'Línea recta que une el centro de una cónica con un foco, determinando la orientación de la curva', 'apocentro', 'matematicas', 'bachillerato', '{1}', 3),
('B', 'empieza', 'Coeficiente que aparece en la fila n-ésima y posición k-ésima del triángulo de Pascal', 'binomico', 'matematicas', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Nivel de seguridad expresado en porcentaje que se asigna al intervalo de estimación de un parámetro', 'confianza', 'matematicas', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Recta fija respecto a la cual se miden las distancias que definen una parábola junto con el foco', 'directriz', 'matematicas', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Margen máximo que se admite entre el estimador muestral y el parámetro poblacional real', 'error', 'matematicas', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Suceso cuya probabilidad de ocurrencia es uno, también llamado suceso seguro', 'fiable', 'matematicas', 'bachillerato', '{1}', 2),
('G', 'empieza', 'Representación visual de una función, conjunto de puntos del plano que satisfacen la ecuación', 'grafica', 'matematicas', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Condición que exige igualdad de valores en los extremos del intervalo para aplicar el teorema de Rolle', 'homogeneo', 'matematicas', 'bachillerato', '{1}', 2),
('I', 'empieza', 'Propiedad de una distribución normal que hace que su gráfica sea igual a ambos lados de la media', 'inflexion', 'matematicas', 'bachillerato', '{1}', 2),
('L', 'empieza', 'Conjunto de puntos que satisface una condición geométrica determinada, como la definición de cónicas', 'lugar', 'matematicas', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Operación que permite obtener nuevas matrices a partir de la combinación de filas y columnas de otras', 'menor', 'matematicas', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Valor de significación que fija la probabilidad máxima de rechazar una hipótesis nula verdadera', 'nivel', 'matematicas', 'bachillerato', '{1}', 2),
('O', 'empieza', 'Propiedad de vectores que forman ángulo recto entre sí, con producto escalar igual a cero', 'ortogonal', 'matematicas', 'bachillerato', '{1}', 2),
('P', 'empieza', 'Valor constante de una población, como la media o la proporción, que se estima con datos muestrales', 'parametro', 'matematicas', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Repetición de un experimento aleatorio un número fijo de veces manteniendo condiciones idénticas', 'repeticion', 'matematicas', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Cada uno de los resultados posibles de un experimento aleatorio', 'suceso', 'matematicas', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Resultado demostrado que permite calcular probabilidades condicionadas invirtiendo causa y efecto', 'teorema', 'matematicas', 'bachillerato', '{1}', 1),
('U', 'empieza', 'Distribución de probabilidad donde todos los resultados tienen la misma probabilidad de ocurrencia', 'uniforme', 'matematicas', 'bachillerato', '{1}', 2),
('V', 'empieza', 'Línea imaginaria perpendicular a la directriz que pasa por el foco de una parábola', 'vertice', 'matematicas', 'bachillerato', '{1}', 1),
('W', 'contiene', 'Resultado que asegura la existencia de extremos absolutos para funciones continuas en compactos, debido a Karl', 'weierstrass', 'matematicas', 'bachillerato', '{1}', 3),
('X', 'contiene', 'Valor máximo o mínimo que alcanza una función en un punto donde la derivada se anula o no existe', 'extremo', 'matematicas', 'bachillerato', '{1}', 1),
('Y', 'contiene', 'Método de inferencia estadística que usa la información previa para actualizar probabilidades', 'bayesiana', 'matematicas', 'bachillerato', '{1}', 3),
('Z', 'contiene', 'Región del plano limitada por los ejes de una cónica, usada para describir su geometría', 'horizontalizar', 'matematicas', 'bachillerato', '{1}', 3),

-- =====================================================
-- MATEMÁTICAS 2º BACHILLERATO (75 preguntas)
-- Integrales impropias, métodos de integración, Green,
-- divergencia, rotacional, Markov, contraste hipótesis,
-- región crítica, programación lineal
-- =====================================================

('A', 'empieza', 'Método de integración que descompone una fracción racional en suma de fracciones más simples', 'arcotangente', 'matematicas', 'bachillerato', '{2}', 2),
('A', 'empieza', 'Tipo de integral cuyo intervalo de integración es infinito o cuyo integrando tiene una singularidad', 'asintotico', 'matematicas', 'bachillerato', '{2}', 2),
('A', 'empieza', 'Región del plano definida por las restricciones de un problema de programación lineal que contiene las soluciones posibles', 'admisible', 'matematicas', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Superficie cerrada que delimita un volumen en el espacio, sobre la que se calcula el flujo de un campo vectorial', 'borde', 'matematicas', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Propiedad de una función que está limitada entre dos valores finitos en todo su dominio', 'bernoulli', 'matematicas', 'bachillerato', '{2}', 2),
('C', 'empieza', 'Propiedad de una integral impropia que tiene un valor finito al calcular el límite correspondiente', 'convergente', 'matematicas', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Procedimiento estadístico para decidir si se rechaza o no una hipótesis nula a partir de datos muestrales', 'contraste', 'matematicas', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Campo vectorial cuya divergencia es cero en todo punto del dominio', 'conservativo', 'matematicas', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Operador diferencial que mide la tasa de expansión de un campo vectorial en un punto dado', 'divergencia', 'matematicas', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Propiedad de una integral impropia cuyo límite no existe o es infinito', 'divergente', 'matematicas', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Relación matemática que indica la probabilidad de ser absorbido por cada estado en una cadena absorbente', 'descomposicion', 'matematicas', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Estado de una cadena de Markov desde el que es posible llegar a cualquier otro estado', 'ergodica', 'matematicas', 'bachillerato', '{2}', 3),
('E', 'empieza', 'Valor numérico obtenido a partir de la muestra que sirve para aproximar un parámetro poblacional desconocido', 'estimador', 'matematicas', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Distribución de probabilidad que modela el tiempo entre sucesos en un proceso de Poisson', 'exponencial', 'matematicas', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Cantidad de campo vectorial que atraviesa una superficie por unidad de tiempo', 'flujo', 'matematicas', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Función que se busca optimizar en un problema de programación lineal sujeta a restricciones', 'funcion', 'matematicas', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Teorema que relaciona la integral de línea alrededor de una curva cerrada con la integral doble sobre la región encerrada', 'green', 'matematicas', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Método iterativo para resolver sistemas de ecuaciones lineales por aproximaciones sucesivas', 'gauss', 'matematicas', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Afirmación sobre un parámetro poblacional que se busca contrastar con evidencia muestral', 'hipotesis', 'matematicas', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Propiedad de un sistema de ecuaciones donde todos los términos independientes son cero', 'homogeneo', 'matematicas', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Tipo de integral cuyo límite superior o inferior es infinito, o cuyo integrando no está acotado en el intervalo', 'impropia', 'matematicas', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Propiedad de los estados de una cadena de Markov cuando es posible ir de cualquiera a cualquier otro', 'irreducible', 'matematicas', 'bachillerato', '{2}', 3),
('J', 'empieza', 'Determinante de la matriz de derivadas parciales de primer orden de una transformación entre coordenadas', 'jacobiano', 'matematicas', 'bachillerato', '{2}', 2),
('K', 'contiene', 'Proceso estocástico donde la probabilidad futura solo depende del estado presente y no de la historia pasada', 'markov', 'matematicas', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Tipo de programación matemática donde tanto la función objetivo como las restricciones son funciones de primer grado', 'lineal', 'matematicas', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Valor al que se acerca una integral impropia cuando el extremo de integración tiende a infinito', 'limite', 'matematicas', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Tabla cuadrada de probabilidades de transición entre estados en un proceso estocástico de memoria uno', 'markoviana', 'matematicas', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Técnica de integración basada en elegir una parte del integrando para derivar y otra para integrar', 'multiplicadores', 'matematicas', 'bachillerato', '{2}', 3),
('N', 'empieza', 'Hipótesis que se asume verdadera por defecto en un contraste y que se intenta refutar con los datos', 'nula', 'matematicas', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Distribución que aproxima a la binomial cuando n es grande y p no es extremo, por el teorema central del límite', 'normal', 'matematicas', 'bachillerato', '{2}', 1),
('Ñ', 'contiene', 'En contraste de hipótesis, diseño de la región donde se acepta o rechaza según la muestra obtenida', 'desentranar', 'matematicas', 'bachillerato', '{2}', 3),
('O', 'empieza', 'Proceso de encontrar el máximo o mínimo de una función objetivo sujeta a restricciones lineales', 'optimizacion', 'matematicas', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Propiedad de vectores mutuamente perpendiculares que forman una base del espacio', 'ortonormal', 'matematicas', 'bachillerato', '{2}', 2),
('P', 'empieza', 'Método de integración que descompone un cociente de polinomios en suma de fracciones con denominadores más simples', 'parciales', 'matematicas', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Método de integración que reemplaza la variable original por otra para simplificar el cálculo', 'partes', 'matematicas', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Probabilidad de obtener un resultado tan extremo como el observado si la hipótesis nula fuera verdadera', 'pvalor', 'matematicas', 'bachillerato', '{2}', 2),
('Q', 'contiene', 'Superficie de segundo grado en el espacio tridimensional como elipsoides, hiperboloides y paraboloides', 'cuadrica', 'matematicas', 'bachillerato', '{2}', 2),
('R', 'empieza', 'Conjunto de valores del estadístico de contraste que llevan a rechazar la hipótesis nula', 'rechazo', 'matematicas', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Operador vectorial que mide la tendencia de rotación de un campo vectorial alrededor de un punto', 'rotacional', 'matematicas', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Desigualdad o igualdad que limita los valores posibles de las variables en programación lineal', 'restriccion', 'matematicas', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Método que resuelve problemas de programación lineal desplazándose por los vértices de la región factible', 'simplex', 'matematicas', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Cambio de variable en una integral que introduce funciones trigonométricas para eliminar raíces cuadradas', 'sustitucion', 'matematicas', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Matriz cuadrada donde cada fila suma uno, usada para describir las transiciones de una cadena de Markov', 'transicion', 'matematicas', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Cambio de variable trigonométrico que simplifica integrales con expresiones radicales cuadráticas', 'trigonometrica', 'matematicas', 'bachillerato', '{2}', 2),
('U', 'empieza', 'Error de tipo II en un contraste: no rechazar la hipótesis nula cuando en realidad es falsa', 'unilateral', 'matematicas', 'bachillerato', '{2}', 2),
('V', 'empieza', 'Punto de la región factible donde se cruzan dos o más restricciones del problema de programación lineal', 'vertice', 'matematicas', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Distribución estacionaria a la que converge una cadena de Markov ergódica tras muchos pasos', 'vector', 'matematicas', 'bachillerato', '{2}', 2),
('W', 'contiene', 'Teorema que afirma que si una función es continua en un intervalo cerrado y acotado, alcanza su máximo y mínimo', 'weierstrass', 'matematicas', 'bachillerato', '{2}', 2),
('X', 'contiene', 'Valor de la función que se obtiene al sustituir los extremos de integración en la primitiva', 'exacto', 'matematicas', 'bachillerato', '{2}', 1),
('Y', 'contiene', 'En contraste bilateral, cada una de las dos colas de la distribución donde se sitúa la región de rechazo', 'bayesiano', 'matematicas', 'bachillerato', '{2}', 3),
('Z', 'contiene', 'Proceso de convertir una variable normal a la estándar restando la media y dividiendo entre la desviación', 'estandarizar', 'matematicas', 'bachillerato', '{2}', 2),

-- Preguntas extra para completar 75
('A', 'empieza', 'Estado de una cadena de Markov que, una vez alcanzado, no se puede abandonar', 'absorbente', 'matematicas', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Contraste donde la hipótesis alternativa indica que el parámetro es distinto, mayor o menor que un valor dado', 'bilateral', 'matematicas', 'bachillerato', '{2}', 2),
('C', 'empieza', 'Zona del eje de valores del estadístico donde la evidencia muestral lleva a rechazar la hipótesis nula', 'critica', 'matematicas', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Propiedad de funciones que permite calcular sus derivadas parciales y aplicar operadores diferenciales', 'derivable', 'matematicas', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Distribución de probabilidad de los posibles valores de un estimador cuando se repite el muestreo', 'estacionaria', 'matematicas', 'bachillerato', '{2}', 3),
('F', 'empieza', 'Punto de la región admisible en programación lineal que satisface todas las restricciones simultáneamente', 'factible', 'matematicas', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Operador vectorial que asigna a cada punto de un campo escalar un vector que indica la dirección de máximo crecimiento', 'gradiente', 'matematicas', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Matriz cuadrada cuyas entradas son las derivadas parciales segundas de una función de varias variables', 'hessiana', 'matematicas', 'bachillerato', '{2}', 3),
('I', 'empieza', 'Operación que consiste en calcular la antiderivada de una función, inversa de la derivación', 'integracion', 'matematicas', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Operador diferencial que combina divergencia y gradiente, suma de las derivadas parciales segundas', 'laplaciano', 'matematicas', 'bachillerato', '{2}', 3),
('M', 'empieza', 'Valor más probable de una variable aleatoria, correspondiente al máximo de la función de densidad', 'moda', 'matematicas', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Vector unitario perpendicular a una superficie en un punto dado, usado en integrales de superficie', 'normal', 'matematicas', 'bachillerato', '{2}', 2),
('O', 'empieza', 'Valor máximo o mínimo de la función objetivo en un problema de programación lineal', 'optimo', 'matematicas', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Función cuya derivada coincide con el integrando, base del cálculo integral', 'primitiva', 'matematicas', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Nivel de significación que fija la probabilidad máxima de cometer un error de tipo I al rechazar la hipótesis nula', 'significacion', 'matematicas', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Resultado que relaciona la integral de un campo vectorial sobre una superficie con la integral de su rotacional', 'stokes', 'matematicas', 'bachillerato', '{2}', 3),

-- =====================================================
-- FÍSICA 1º BACHILLERATO (75 preguntas)
-- MAS, calorimetría, cambios de estado, Faraday electrólisis,
-- geometría molecular, hibridación, fuerzas intermoleculares,
-- disoluciones coloidales
-- =====================================================

('A', 'empieza', 'Separación máxima respecto a la posición de equilibrio en un movimiento armónico simple', 'amplitud', 'fisica', 'bachillerato', '{1}', 1),
('A', 'empieza', 'Mezcla de un metal con uno o más elementos, generalmente otros metales, que mejora propiedades mecánicas', 'aleacion', 'fisica', 'bachillerato', '{1}', 2),
('A', 'empieza', 'Tipo de molécula que atrae al agua gracias a enlaces polares o grupos iónicos en su estructura', 'anfipática', 'fisica', 'bachillerato', '{1}', 3),
('B', 'empieza', 'Instrumento para medir la presión atmosférica basado en la altura de una columna de mercurio', 'barometro', 'fisica', 'bachillerato', '{1}', 1),
('B', 'empieza', 'Efecto por el cual las partículas de un coloide se mueven de forma errática debido al impacto de moléculas del medio', 'browniano', 'fisica', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Rama de la termodinámica que mide el calor intercambiado en procesos físicos y químicos', 'calorimetria', 'fisica', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Dispersión de partículas de tamaño intermedio entre solución verdadera y suspensión, estables en el medio', 'coloide', 'fisica', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Cantidad de calor necesaria para elevar un grado la temperatura de la unidad de masa de una sustancia', 'calorifico', 'fisica', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Fuerza de atracción débil entre moléculas apolares debida a la formación temporal de dipolos instantáneos', 'dispersion', 'fisica', 'bachillerato', '{1}', 2),
('D', 'empieza', 'Mezcla homogénea líquida donde las partículas del soluto son moléculas o iones individuales', 'disolucion', 'fisica', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Separación de moléculas de agua ligadas a una sal hidratada mediante calentamiento', 'deshidratacion', 'fisica', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Proceso por el cual se deposita un metal en un electrodo al pasar corriente eléctrica por una disolución de sus iones', 'electrolisis', 'fisica', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Fenómeno por el cual un coloide dispersa la luz que lo atraviesa haciéndola visible lateralmente', 'efecto', 'fisica', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Suspensión coloidal estable de dos líquidos inmiscibles gracias a un agente emulsionante', 'emulsion', 'fisica', 'bachillerato', '{1}', 2),
('F', 'empieza', 'Ley que establece que la masa depositada en electrólisis es proporcional a la carga eléctrica total que circula', 'faraday', 'fisica', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Número de oscilaciones completas por unidad de tiempo en un movimiento armónico simple', 'frecuencia', 'fisica', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Paso del estado sólido al estado líquido al absorber calor a temperatura constante', 'fusion', 'fisica', 'bachillerato', '{1}', 1),
('G', 'empieza', 'Disposición espacial de los pares de electrones alrededor de un átomo central según el modelo RPECV', 'geometria', 'fisica', 'bachillerato', '{1}', 1),
('G', 'empieza', 'Coloide donde el medio dispersante es un gas y la fase dispersa es un líquido en forma de gotitas diminutas', 'gel', 'fisica', 'bachillerato', '{1}', 2),
('H', 'empieza', 'Mezcla de orbitales atómicos puros que genera orbitales equivalentes dirigidos en el espacio para formar enlaces', 'hibridacion', 'fisica', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Enlace intermolecular especialmente fuerte que se forma entre un hidrógeno unido a F, O o N y un par solitario de otro átomo electronegativo', 'hidrogeno', 'fisica', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Fuerzas de atracción entre moléculas que determinan propiedades como el punto de ebullición y la viscosidad', 'intermoleculares', 'fisica', 'bachillerato', '{1}', 1),
('I', 'empieza', 'Propiedad de un movimiento periódico que indica el tiempo de cada ciclo completo, inverso de la frecuencia', 'isocrono', 'fisica', 'bachillerato', '{1}', 3),
('J', 'empieza', 'Unidad del Sistema Internacional que mide energía, trabajo y cantidad de calor', 'julio', 'fisica', 'bachillerato', '{1}', 1),
('K', 'contiene', 'Escala absoluta de temperatura cuyo cero corresponde a la mínima energía cinética molecular posible', 'kelvin', 'fisica', 'bachillerato', '{1}', 1),
('L', 'empieza', 'Calor necesario para que una sustancia cambie de estado sin variar su temperatura', 'latente', 'fisica', 'bachillerato', '{1}', 1),
('L', 'empieza', 'Fuerzas de atracción entre dipolos permanentes de moléculas polares cercanas', 'london', 'fisica', 'bachillerato', '{1}', 2),
('M', 'empieza', 'Relación entre la masa del soluto y el volumen total de disolución, expresada en mol por litro', 'molaridad', 'fisica', 'bachillerato', '{1}', 1),
('M', 'empieza', 'Tipo de hibridación que genera cuatro orbitales equivalentes en disposición tetraédrica', 'mezcla', 'fisica', 'bachillerato', '{1}', 2),
('N', 'empieza', 'Constante que indica el número de entidades elementales en un mol de sustancia', 'numero', 'fisica', 'bachillerato', '{1}', 1),
('Ñ', 'contiene', 'Fenómeno de dispersión de la luz por partículas coloidales de tamaño comparable a la longitud de onda', 'empequenecido', 'fisica', 'bachillerato', '{1}', 3),
('O', 'empieza', 'Movimiento de ida y vuelta periódico de un sistema alrededor de su posición de equilibrio', 'oscilacion', 'fisica', 'bachillerato', '{1}', 1),
('O', 'empieza', 'Región del espacio donde hay alta probabilidad de encontrar un electrón en un átomo o molécula', 'orbital', 'fisica', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Tiempo que tarda un sistema en completar un ciclo completo de oscilación armónica', 'periodo', 'fisica', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Ángulo inicial que determina la posición del oscilador armónico en el instante cero', 'pendulo', 'fisica', 'bachillerato', '{1}', 1),
('P', 'empieza', 'Propiedad molecular debida a la distribución asimétrica de la densidad electrónica, generando un dipolo', 'polaridad', 'fisica', 'bachillerato', '{1}', 1),
('Q', 'empieza', 'Magnitud que expresa la cantidad de energía térmica absorbida o cedida por un cuerpo en un proceso', 'quimica', 'fisica', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Fuerza que tiende a devolver un oscilador armónico a su posición de equilibrio, proporcional al desplazamiento', 'recuperadora', 'fisica', 'bachillerato', '{1}', 2),
('R', 'empieza', 'Modelo que predice la geometría molecular según la repulsión entre los pares electrónicos de la capa de valencia', 'rpecv', 'fisica', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Paso directo del estado sólido al gaseoso sin pasar por el estado líquido', 'sublimacion', 'fisica', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Mezcla donde la concentración de soluto ha alcanzado el máximo posible a una temperatura dada', 'saturada', 'fisica', 'bachillerato', '{1}', 1),
('S', 'empieza', 'Función trigonométrica que describe la posición del oscilador armónico en función del tiempo', 'senoidal', 'fisica', 'bachillerato', '{1}', 2),
('T', 'empieza', 'Modelo de hibridación que genera cuatro orbitales idénticos con ángulos de enlace de 109,5 grados', 'tetraedrica', 'fisica', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Fenómeno por el que las partículas coloidales dispersan un haz de luz visible', 'tyndall', 'fisica', 'bachillerato', '{1}', 2),
('U', 'empieza', 'Propiedad de una molécula que tiene un solo par de electrones no enlazantes, afectando su geometría molecular', 'unimolecular', 'fisica', 'bachillerato', '{1}', 3),
('V', 'empieza', 'Paso del estado líquido al gaseoso que ocurre a temperatura constante a la presión de saturación', 'vaporizacion', 'fisica', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Magnitud que mide la resistencia de un fluido a fluir, relacionada con las fuerzas intermoleculares', 'viscosidad', 'fisica', 'bachillerato', '{1}', 2),
('W', 'contiene', 'Fuerza débil de atracción entre moléculas apolares debida a dipolos inducidos, de tipo van der', 'waals', 'fisica', 'bachillerato', '{1}', 2),
('X', 'contiene', 'Mezcla de composición fija que hierve a temperatura constante como si fuera una sustancia pura', 'azeotropo', 'fisica', 'bachillerato', '{1}', 3),
('Y', 'contiene', 'Proceso reversible de conversión sol-gel en un coloide liófilo al variar la temperatura', 'tixotropia', 'fisica', 'bachillerato', '{1}', 3),
('Z', 'contiene', 'Propiedad de ciertos cristales de generar corriente eléctrica cuando se les aplica presión mecánica', 'piezoelectricidad', 'fisica', 'bachillerato', '{1}', 3),

-- Preguntas extra para completar 75
('A', 'empieza', 'Dispositivo que mide el calor intercambiado en una reacción o proceso físico', 'adiabático', 'fisica', 'bachillerato', '{1}', 2),
('B', 'empieza', 'Punto en el diagrama de fases donde coexisten los tres estados de la materia simultáneamente', 'bifasico', 'fisica', 'bachillerato', '{1}', 2),
('C', 'empieza', 'Paso del estado gaseoso a líquido por enfriamiento o aumento de presión', 'condensacion', 'fisica', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Cantidad de sustancia disuelta por unidad de volumen o masa de disolución', 'concentracion', 'fisica', 'bachillerato', '{1}', 1),
('D', 'empieza', 'Separación de dos componentes de un coloide mediante una membrana semipermeable que retiene las partículas grandes', 'dialisis', 'fisica', 'bachillerato', '{1}', 2),
('E', 'empieza', 'Proceso donde la vaporización ocurre en toda la masa del líquido a una temperatura característica fija', 'ebullicion', 'fisica', 'bachillerato', '{1}', 1),
('F', 'empieza', 'Constante que indica la carga necesaria para depositar un equivalente-gramo en electrólisis, aproximadamente 96485 C', 'faradio', 'fisica', 'bachillerato', '{1}', 2),
('G', 'empieza', 'Estado intermedio entre sólido y líquido que forman ciertos coloides cuando pierden fluidez', 'gelificacion', 'fisica', 'bachillerato', '{1}', 2),
('H', 'empieza', 'Tipo de orbital híbrido que forma tres enlaces en un plano con ángulos de 120 grados', 'hibrido', 'fisica', 'bachillerato', '{1}', 2),
('I', 'empieza', 'Aparato aislado térmicamente usado para medir el calor de una reacción sin intercambio con el entorno', 'isoterma', 'fisica', 'bachillerato', '{1}', 2),
('L', 'empieza', 'Tipo de coloide donde las partículas dispersas tienen afinidad con el medio dispersante', 'liofilo', 'fisica', 'bachillerato', '{1}', 2),
('M', 'empieza', 'Modelo que explica las propiedades de los gases a partir del movimiento aleatorio de sus partículas', 'molecular', 'fisica', 'bachillerato', '{1}', 1),
('N', 'empieza', 'Punto donde la velocidad del oscilador armónico es máxima y el desplazamiento es cero', 'nodo', 'fisica', 'bachillerato', '{1}', 2),
('O', 'empieza', 'Fenómeno de paso de disolvente a través de una membrana semipermeable hacia la disolución más concentrada', 'osmosis', 'fisica', 'bachillerato', '{1}', 2),
('P', 'empieza', 'Diagrama que representa los estados de agregación de una sustancia según presión y temperatura', 'punto', 'fisica', 'bachillerato', '{1}', 1),
('R', 'empieza', 'Relación entre velocidad angular y período que determina la frecuencia de un movimiento armónico simple', 'resonancia', 'fisica', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Sustancia que se disuelve en el disolvente para formar una disolución homogénea', 'soluto', 'fisica', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Rama de la física que estudia el calor, la temperatura y los intercambios energéticos entre sistemas', 'termodinamica', 'fisica', 'bachillerato', '{1}', 1),
('V', 'empieza', 'Transformación lenta de un líquido a gas que ocurre solo en la superficie libre a cualquier temperatura', 'volatilidad', 'fisica', 'bachillerato', '{1}', 2),

-- =====================================================
-- FÍSICA 2º BACHILLERATO (75 preguntas)
-- Biot-Savart, transformador, efecto fotoeléctrico, espectros,
-- radiactividad, fisión, fusión, dualidad onda-partícula,
-- incertidumbre
-- =====================================================

('A', 'empieza', 'Partícula compuesta por dos protones y dos neutrones emitida en la desintegración radiactiva más pesada', 'alfa', 'fisica', 'bachillerato', '{2}', 1),
('A', 'empieza', 'Número que indica el total de protones y neutrones en el núcleo de un átomo', 'atomico', 'fisica', 'bachillerato', '{2}', 1),
('A', 'empieza', 'Proceso en un reactor nuclear donde las barras de control frenan la reacción reduciendo el número de neutrones', 'absorcion', 'fisica', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Ley que permite calcular el campo magnético generado por un elemento de corriente a cierta distancia', 'biot', 'fisica', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Radiación electromagnética de alta energía emitida por el núcleo cuando pasa de un estado excitado al fundamental', 'beta', 'fisica', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Relación entre la energía y la frecuencia de un fotón que define los paquetes discretos de radiación', 'bohr', 'fisica', 'bachillerato', '{2}', 2),
('C', 'empieza', 'Relación de conversión entre el número de espiras del primario y el secundario en un transformador', 'confinamiento', 'fisica', 'bachillerato', '{2}', 3),
('C', 'empieza', 'Tiempo necesario para que el número de átomos radiactivos de una muestra se reduzca a la mitad', 'cuanto', 'fisica', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Concepto que establece que toda partícula material exhibe también propiedades ondulatorias', 'dualidad', 'fisica', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Proceso de reducción del número de átomos radiactivos de un isótopo con el paso del tiempo', 'desintegracion', 'fisica', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Fenómeno ondulatorio que impide enfocar un haz de partículas más allá del límite impuesto por su longitud de onda', 'difraccion', 'fisica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Distribución de frecuencias de la radiación electromagnética emitida por un elemento al excitarse térmicamente', 'espectro', 'fisica', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Fenómeno por el cual los electrones son arrancados de un metal al incidir luz de frecuencia suficiente', 'fotoelectrico', 'fisica', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Desvío de un haz de electrones al atravesar una rendija, confirmando su naturaleza ondulatoria', 'electron', 'fisica', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Reacción nuclear donde un núcleo pesado se divide en dos fragmentos más ligeros liberando energía', 'fision', 'fisica', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Reacción nuclear donde dos núcleos ligeros se combinan para formar uno más pesado liberando gran cantidad de energía', 'fusion', 'fisica', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Partícula elemental de luz sin masa en reposo que transporta energía proporcional a su frecuencia', 'foton', 'fisica', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Valor mínimo de frecuencia de la radiación incidente que permite arrancar electrones de un metal', 'frecuencia', 'fisica', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Radiación electromagnética de muy alta frecuencia emitida por el núcleo durante transiciones entre niveles energéticos', 'gamma', 'fisica', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Dispositivo que detecta radiación ionizante mediante la ionización de un gas a baja presión en un tubo', 'geiger', 'fisica', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Principio que establece un límite fundamental a la precisión simultánea de posición y momento de una partícula', 'heisenberg', 'fisica', 'bachillerato', '{2}', 1),
('H', 'empieza', 'Semiperiodo radiactivo, tiempo para que la actividad de una muestra radiactiva se reduzca a la mitad', 'hemivida', 'fisica', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Principio que afirma la imposibilidad de conocer simultáneamente con precisión arbitraria posición y velocidad de una partícula', 'incertidumbre', 'fisica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Átomos del mismo elemento con diferente número de neutrones y por tanto distinta masa atómica', 'isotopo', 'fisica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Propiedad de la fuerza electromotriz generada en el secundario de un transformador al variar el flujo magnético', 'inducida', 'fisica', 'bachillerato', '{2}', 1),
('J', 'empieza', 'Unidad de energía equivalente a un newton por metro, usada para cuantificar la energía de los fotones', 'julio', 'fisica', 'bachillerato', '{2}', 1),
('K', 'contiene', 'Energía cinética máxima de los electrones emitidos en el efecto fotoeléctrico, independiente de la intensidad luminosa', 'cinetica', 'fisica', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Longitud de onda asociada a una partícula en movimiento según la relación de De Broglie', 'lambda', 'fisica', 'bachillerato', '{2}', 2),
('L', 'empieza', 'Series espectrales del hidrógeno cuyas líneas están en la zona visible del espectro electromagnético', 'lyman', 'fisica', 'bachillerato', '{2}', 3),
('M', 'empieza', 'Defecto que sufre la masa de un núcleo respecto a la suma de las masas de sus nucleones por separado', 'masico', 'fisica', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Cantidad que relaciona la velocidad de la luz con la equivalencia entre masa y energía según Einstein', 'masa', 'fisica', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Partícula sin carga del núcleo atómico cuya captura puede provocar la fisión de un núcleo pesado', 'neutron', 'fisica', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Tipo de fuerza de muy corto alcance que mantiene unidos a protones y neutrones dentro del núcleo', 'nuclear', 'fisica', 'bachillerato', '{2}', 1),
('Ñ', 'contiene', 'Tamaño del núcleo atómico del orden de femtómetros, extremadamente pequeño comparado con el átomo', 'pequenisimo', 'fisica', 'bachillerato', '{2}', 3),
('O', 'empieza', 'Comportamiento de la materia y la radiación que exhibe simultáneamente propiedades de onda y de partícula', 'ondulatoria', 'fisica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Constante fundamental que relaciona la energía de un fotón con su frecuencia, base de la mecánica cuántica', 'planck', 'fisica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Partícula con carga positiva que forma parte del núcleo atómico junto con los neutrones', 'proton', 'fisica', 'bachillerato', '{2}', 1),
('Q', 'empieza', 'Rama de la física que describe el comportamiento de partículas a escala atómica y subatómica', 'quantica', 'fisica', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Emisión espontánea de partículas o energía por parte de núcleos inestables', 'radiactividad', 'fisica', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Relación entre el número de espiras del primario y del secundario que determina la tensión de salida de un transformador', 'relacion', 'fisica', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Bobina de salida de un transformador donde se induce la fuerza electromotriz por variación de flujo magnético', 'secundario', 'fisica', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Ley que rige la distribución de las líneas espectrales del hidrógeno mediante números enteros cuadrados', 'serie', 'fisica', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Dispositivo eléctrico que transfiere energía entre dos circuitos mediante inducción electromagnética cambiando tensiones', 'transformador', 'fisica', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Fenómeno cuántico por el que una partícula atraviesa una barrera de potencial clásicamente infranqueable', 'tunel', 'fisica', 'bachillerato', '{2}', 2),
('U', 'empieza', 'Elemento radiactivo pesado cuyo isótopo 235 es el combustible principal de los reactores de fisión nuclear', 'uranio', 'fisica', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Unidad de frecuencia que en el efecto fotoeléctrico marca el umbral mínimo para la emisión de electrones', 'voltaje', 'fisica', 'bachillerato', '{2}', 1),
('W', 'contiene', 'Función que describe la probabilidad de encontrar una partícula en una región del espacio según la ecuación de Schrodinger', 'schrodinger', 'fisica', 'bachillerato', '{2}', 3),
('X', 'contiene', 'Tipo de radiación electromagnética de alta energía producida en tubos de rayos catódicos al frenar electrones rápidos', 'rayosx', 'fisica', 'bachillerato', '{2}', 2),
('Y', 'contiene', 'Ecuación de Rydberg que permite calcular las frecuencias de las líneas espectrales del hidrógeno', 'rydberg', 'fisica', 'bachillerato', '{2}', 3),
('Z', 'contiene', 'Número de protones en el núcleo que define el elemento químico y su posición en la tabla periódica', 'atomicoz', 'fisica', 'bachillerato', '{2}', 1),

-- Preguntas extra para completar 75
('A', 'empieza', 'Número de desintegraciones por segundo que experimenta una muestra radiactiva, medida en becquerelios', 'actividad', 'fisica', 'bachillerato', '{2}', 1),
('B', 'empieza', 'Serie espectral del hidrógeno cuyas transiciones terminan en el segundo nivel energético, visible al ojo humano', 'balmer', 'fisica', 'bachillerato', '{2}', 2),
('C', 'empieza', 'Reacción nuclear en cadena donde cada fisión produce neutrones que provocan más fisiones sucesivas', 'cadena', 'fisica', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Longitud de onda asociada a una partícula con momento p, según la fórmula lambda igual a h entre p', 'debroglie', 'fisica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Ecuación que establece la equivalencia entre masa y energía con la velocidad de la luz al cuadrado como factor', 'einstein', 'fisica', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Flujo magnético que atraviesa cada espira de un transformador y que al variar induce una fem', 'flujo', 'fisica', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Unidad de dosis de radiación absorbida equivalente a cien ergios por gramo de tejido', 'gray', 'fisica', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Espectro que muestra líneas discretas brillantes sobre fondo oscuro cuando un gas se excita', 'hertzio', 'fisica', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Proceso por el que un átomo neutro pierde o gana electrones por la acción de radiación energética', 'ionizacion', 'fisica', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Dispositivo que produce luz coherente y monocromática mediante emisión estimulada de radiación', 'laser', 'fisica', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Propiedad cuántica intrínseca de las partículas relacionada con su giro, sin análogo clásico', 'magnetico', 'fisica', 'bachillerato', '{2}', 2),
('N', 'empieza', 'Partículas que componen el núcleo atómico: protones y neutrones considerados conjuntamente', 'nucleones', 'fisica', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Nivel de energía de un electrón en un átomo, definido por números cuánticos y cuantizado', 'orbita', 'fisica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Bobina de entrada de un transformador conectada a la fuente de corriente alterna', 'primario', 'fisica', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Material que frena neutrones rápidos para facilitar la fisión en cadena del uranio-235', 'refrigerante', 'fisica', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Unidad de dosis de radiación biológica efectiva que pondera el tipo de radiación y el tejido afectado', 'sievert', 'fisica', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Periodo de semidesintegración necesario para que la actividad de una muestra se reduzca a la mitad', 'termico', 'fisica', 'bachillerato', '{2}', 2),

-- =====================================================
-- QUÍMICA 2º BACHILLERATO (75 preguntas)
-- Kp/Kc, producto solubilidad, volumetrías, pilas Daniell,
-- potenciales estándar, entalpía enlace, energía activación,
-- isomería óptica, polímeros condensación
-- =====================================================

('A', 'empieza', 'Energía mínima que deben poseer los reactivos para que se produzca una reacción química efectiva', 'activacion', 'quimica', 'bachillerato', '{2}', 1),
('A', 'empieza', 'Electrodo donde se produce la oxidación en una celda electroquímica o pila galvánica', 'anodo', 'quimica', 'bachillerato', '{2}', 1),
('A', 'empieza', 'Tipo de isomería donde dos moléculas son imágenes especulares no superponibles entre sí', 'asimetrico', 'quimica', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Disolución que mantiene su pH prácticamente constante al añadir pequeñas cantidades de ácido o base', 'buffer', 'quimica', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Ecuación que relaciona la constante de velocidad de una reacción con la temperatura y la energía de activación', 'boltzmann', 'quimica', 'bachillerato', '{2}', 2),
('C', 'empieza', 'Electrodo donde se produce la reducción, captando electrones del circuito externo en una pila', 'catodo', 'quimica', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Macromolécula formada por la unión de monómeros con eliminación de moléculas pequeñas como agua', 'condensacion', 'quimica', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Sustancia que aumenta la velocidad de una reacción al disminuir la energía de activación sin consumirse', 'catalizador', 'quimica', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Átomo de carbono unido a cuatro sustituyentes diferentes que genera actividad óptica en la molécula', 'quiral', 'quimica', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Pila electroquímica formada por un electrodo de zinc y otro de cobre en sus respectivas disoluciones salinas', 'daniell', 'quimica', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Propiedad de una molécula ópticamente activa que gira el plano de la luz polarizada hacia la derecha', 'dextrogiro', 'quimica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Energía asociada a la rotura o formación de un enlace químico, medida por mol de enlace', 'entalpia', 'quimica', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Ecuación que relaciona la fuerza electromotriz de una pila con la concentración de los iones mediante logaritmos', 'electrodo', 'quimica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Mezcla de dos enantiómeros en proporción 1:1 que no presenta actividad óptica neta', 'enantiomero', 'quimica', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Fuerza electromotriz de una pila calculada a partir de la diferencia de potenciales estándar de reducción', 'fem', 'quimica', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Indicador que cambia de color al alcanzar el punto de equivalencia en una valoración ácido-base', 'fenolftaleina', 'quimica', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Celda electroquímica que convierte energía química en eléctrica de forma espontánea', 'galvanica', 'quimica', 'bachillerato', '{2}', 1),
('G', 'empieza', 'Energía libre que determina la espontaneidad de una reacción, combinando entalpía y entropía', 'gibbs', 'quimica', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Ley que establece que la entalpía de una reacción global es la suma algebraica de las entalpías de sus etapas', 'hess', 'quimica', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Reacción en la que se produce la ruptura de un enlace éster con agua, proceso inverso de la condensación', 'hidrolisis', 'quimica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Tipo de isomería donde las moléculas difieren en la disposición espacial de sus átomos, no en la conectividad', 'isomeria', 'quimica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Sustancia que al disolverse libera iones positivos y negativos, permitiendo la conducción eléctrica en la disolución', 'ionico', 'quimica', 'bachillerato', '{2}', 1),
('J', 'empieza', 'Unidad de energía del Sistema Internacional utilizada para expresar energías de activación y entalpías de enlace', 'julio', 'quimica', 'bachillerato', '{2}', 1),
('K', 'contiene', 'Constante de equilibrio expresada en función de las presiones parciales de los gases participantes', 'kp', 'quimica', 'bachillerato', '{2}', 1),
('K', 'contiene', 'Constante de equilibrio expresada en función de las concentraciones molares de reactivos y productos', 'kc', 'quimica', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Propiedad de una molécula ópticamente activa que gira el plano de la luz polarizada hacia la izquierda', 'levogiro', 'quimica', 'bachillerato', '{2}', 2),
('L', 'empieza', 'Principio que predice el desplazamiento del equilibrio cuando se modifica concentración, presión o temperatura', 'lechatelier', 'quimica', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Unidad repetitiva más pequeña que forma un polímero al unirse con otras unidades idénticas o similares', 'monomero', 'quimica', 'bachillerato', '{2}', 1),
('M', 'empieza', 'Número de moles de soluto por litro de disolución, medida de concentración básica en volumetrías', 'molaridad', 'quimica', 'bachillerato', '{2}', 1),
('N', 'empieza', 'Ecuación que relaciona el potencial de un electrodo con las concentraciones iónicas y la temperatura', 'nernst', 'quimica', 'bachillerato', '{2}', 2),
('N', 'empieza', 'Polímero sintético de condensación formado por enlaces amida entre grupos amino y carboxilo', 'nailon', 'quimica', 'bachillerato', '{2}', 2),
('Ñ', 'contiene', 'Proceso de enseñanza en laboratorio donde se practica la valoración ácido-base con bureta y matraz', 'ensenanza', 'quimica', 'bachillerato', '{2}', 3),
('O', 'empieza', 'Propiedad de ciertas moléculas de girar el plano de la luz polarizada debido a la presencia de centros quirales', 'optica', 'quimica', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Semirreacción en la que una especie química pierde electrones, aumentando su estado de oxidación', 'oxidacion', 'quimica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Constante de equilibrio para la disolución de una sal poco soluble, producto de las concentraciones iónicas', 'producto', 'quimica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Valor de voltaje de un electrodo medido frente al electrodo estándar de hidrógeno en condiciones normalizadas', 'potencial', 'quimica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Macromolécula de alto peso molecular formada por la repetición de unidades estructurales simples', 'polimero', 'quimica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Polímero de condensación formado por enlaces éster entre un diácido y un diol', 'poliester', 'quimica', 'bachillerato', '{2}', 2),
('Q', 'empieza', 'Centro de asimetría en un carbono con cuatro sustituyentes diferentes que genera enantiómeros', 'quiral', 'quimica', 'bachillerato', '{2}', 2),
('R', 'empieza', 'Semirreacción en la que una especie química gana electrones, disminuyendo su estado de oxidación', 'reduccion', 'quimica', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Mezcla equimolar de los dos enantiómeros de un compuesto quiral que resulta ópticamente inactiva', 'racemico', 'quimica', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Máxima cantidad de soluto que se puede disolver en un volumen de disolvente a temperatura determinada', 'solubilidad', 'quimica', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Puente que conecta las dos semiceldas de una pila permitiendo el paso de iones para mantener la neutralidad eléctrica', 'salino', 'quimica', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Técnica analítica cuantitativa que determina la concentración de un analito añadiendo un reactivo de concentración conocida', 'titulacion', 'quimica', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Polímero termoestable que no puede fundirse ni reformarse una vez endurecido por entrecruzamiento', 'termoestable', 'quimica', 'bachillerato', '{2}', 2),
('U', 'empieza', 'Energía reticular de un compuesto iónico, energía necesaria para separar todos sus iones a distancia infinita', 'umbral', 'quimica', 'bachillerato', '{2}', 3),
('V', 'empieza', 'Análisis cuantitativo basado en medir el volumen de disolución valorante necesario para reaccionar completamente con el analito', 'volumetria', 'quimica', 'bachillerato', '{2}', 1),
('V', 'empieza', 'Diferencia de potencial entre los electrodos de una pila que impulsa el flujo de electrones por el circuito externo', 'voltaje', 'quimica', 'bachillerato', '{2}', 1),
('W', 'contiene', 'Fuerza intermolecular débil presente entre todas las moléculas, debida a fluctuaciones instantáneas de la nube electrónica', 'waals', 'quimica', 'bachillerato', '{2}', 2),
('X', 'contiene', 'Reacción que libera calor al entorno, con variación de entalpía negativa', 'exotermica', 'quimica', 'bachillerato', '{2}', 1),
('Y', 'contiene', 'Reacción de polimerización donde los monómeros se unen perdiendo una molécula pequeña como subproducto', 'poliacrilonitrilo', 'quimica', 'bachillerato', '{2}', 3),
('Z', 'contiene', 'Metal usado como ánodo en la pila Daniell que se oxida cediendo electrones al circuito externo', 'zinc', 'quimica', 'bachillerato', '{2}', 1),

-- Preguntas extra para completar 75
('A', 'empieza', 'Ley que relaciona la velocidad de reacción con las concentraciones de los reactivos elevadas a ciertos exponentes', 'arrhenius', 'quimica', 'bachillerato', '{2}', 2),
('B', 'empieza', 'Instrumento de laboratorio graduado que permite añadir volúmenes precisos de reactivo en una valoración', 'bureta', 'quimica', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Situación donde las velocidades directa e inversa son iguales y las concentraciones no varían con el tiempo', 'constante', 'quimica', 'bachillerato', '{2}', 1),
('D', 'empieza', 'Diagrama que representa la variación de energía a lo largo del camino de reacción, mostrando el estado de transición', 'diagrama', 'quimica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Magnitud termodinámica que mide el desorden o la dispersión de energía en un sistema', 'entropia', 'quimica', 'bachillerato', '{2}', 1),
('E', 'empieza', 'Par de moléculas que son imágenes especulares no superponibles, como las manos derecha e izquierda', 'enantiomeros', 'quimica', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Constante de Faraday que equivale a la carga de un mol de electrones, aproximadamente 96485 culombios', 'faraday', 'quimica', 'bachillerato', '{2}', 2),
('G', 'empieza', 'Grado de avance de una reacción en equilibrio que indica cuánto se desplaza hacia los productos', 'grado', 'quimica', 'bachillerato', '{2}', 2),
('H', 'empieza', 'Electrodo de referencia universal formado por platino en contacto con hidrógeno gas a 1 atm y H+ 1M', 'hidrogeno', 'quimica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Efecto por el cual la adición de un ion común disminuye la solubilidad de una sal poco soluble', 'ionico', 'quimica', 'bachillerato', '{2}', 2),
('L', 'empieza', 'Propiedad de una reacción cuya velocidad depende de las concentraciones según una ley cinética determinada', 'logaritmico', 'quimica', 'bachillerato', '{2}', 3),
('M', 'empieza', 'Etapa más lenta de un mecanismo de reacción que determina la velocidad global del proceso', 'mecanismo', 'quimica', 'bachillerato', '{2}', 2),
('N', 'empieza', 'Punto de una valoración donde los moles de ácido igualan exactamente a los moles de base añadida', 'neutralizacion', 'quimica', 'bachillerato', '{2}', 1),
('O', 'empieza', 'Número que indica cuántos electrones ha ganado o perdido un átomo en un compuesto', 'oxidacion', 'quimica', 'bachillerato', '{2}', 1),
('P', 'empieza', 'Punto exacto de la volumetría donde se han añadido moles equivalentes de valorante y analito', 'punto', 'quimica', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Velocidad a la que disminuye la concentración de reactivos o aumenta la de productos por unidad de tiempo', 'rapidez', 'quimica', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Estado de máxima energía en el camino de reacción, correspondiente al complejo activado', 'situacion', 'quimica', 'bachillerato', '{2}', 3),
('T', 'empieza', 'Polímero que se ablanda al calentarse y puede moldearse repetidamente sin degradarse', 'termoplastico', 'quimica', 'bachillerato', '{2}', 2),
('V', 'empieza', 'Magnitud que mide cuántas moles de reactivo se consumen por unidad de tiempo y de volumen', 'velocidad', 'quimica', 'bachillerato', '{2}', 1),

-- =====================================================
-- PREGUNTAS ADICIONALES PARA COMPLETAR 75 POR ASIGNATURA
-- =====================================================

-- Matemáticas 1º Bach extra (4 más)
('D', 'empieza', 'Elemento de una matriz que resulta de eliminar la fila y columna correspondientes y calcular el determinante del resto', 'adjunto', 'matematicas', 'bachillerato', '{1}', 2),
('S', 'empieza', 'Representación gráfica de la distribución de frecuencias acumuladas de un conjunto de datos estadísticos', 'simetria', 'matematicas', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Operación que intercambia filas por columnas de una matriz, obteniendo una nueva matriz', 'traspuesta', 'matematicas', 'bachillerato', '{1}', 1),
('Z', 'contiene', 'Valor de la variable normal estándar que deja a su izquierda una probabilidad determinada', 'percentilizado', 'matematicas', 'bachillerato', '{1}', 2),

-- Matemáticas 2º Bach extra (8 más)
('A', 'empieza', 'Hipótesis que se acepta si se rechaza la hipótesis nula en un contraste estadístico', 'alternativa', 'matematicas', 'bachillerato', '{2}', 1),
('C', 'empieza', 'Criterio que compara la integral impropia con otra de convergencia conocida para determinar su comportamiento', 'comparacion', 'matematicas', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Teorema que relaciona la integral de superficie de la divergencia de un campo con la integral sobre el volumen encerrado', 'divergencia', 'matematicas', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Error que se comete al rechazar la hipótesis nula cuando en realidad es verdadera', 'error', 'matematicas', 'bachillerato', '{2}', 1),
('F', 'empieza', 'Conjunto de soluciones posibles en programación lineal delimitado por las restricciones del problema', 'frontera', 'matematicas', 'bachillerato', '{2}', 2),
('I', 'empieza', 'Método para evaluar integrales que descompone el integrando en dos factores aplicando la regla del producto inversa', 'integracion', 'matematicas', 'bachillerato', '{2}', 1),
('R', 'empieza', 'Zona de valores del estadístico muestral que conduce al rechazo de la hipótesis nula', 'region', 'matematicas', 'bachillerato', '{2}', 1),
('T', 'empieza', 'Resultado que garantiza la existencia de al menos un punto donde la función alcanza un valor intermedio entre dos dados', 'teorema', 'matematicas', 'bachillerato', '{2}', 1),

-- Física 1º Bach extra (5 más)
('A', 'empieza', 'Movimiento oscilatorio donde la fuerza restauradora es proporcional al desplazamiento desde el equilibrio', 'armonico', 'fisica', 'bachillerato', '{1}', 1),
('C', 'empieza', 'Recipiente aislado térmicamente donde se mide el calor de una reacción o un cambio de estado', 'calorimetro', 'fisica', 'bachillerato', '{1}', 1),
('E', 'empieza', 'Proceso de vaporización que ocurre en la superficie libre de un líquido a cualquier temperatura por debajo de la ebullición', 'evaporacion', 'fisica', 'bachillerato', '{1}', 1),
('H', 'empieza', 'Tipo de enlace entre moléculas de agua donde un átomo de hidrógeno actúa como puente entre dos oxígenos', 'hidrogeno', 'fisica', 'bachillerato', '{1}', 1),
('T', 'empieza', 'Tipo de hibridación que genera tres orbitales equivalentes en un plano con ángulos de 120 grados y uno perpendicular', 'trigonal', 'fisica', 'bachillerato', '{1}', 2),

-- Física 2º Bach extra (8 más)
('C', 'empieza', 'Fenómeno donde un fotón dispersado por un electrón pierde energía y aumenta su longitud de onda', 'compton', 'fisica', 'bachillerato', '{2}', 2),
('D', 'empieza', 'Hipótesis de De Broglie que asigna una longitud de onda a toda partícula material en movimiento', 'debroglie', 'fisica', 'bachillerato', '{2}', 2),
('F', 'empieza', 'Ley que relaciona la fuerza electromotriz inducida con la variación temporal del flujo magnético', 'faraday', 'fisica', 'bachillerato', '{2}', 1),
('L', 'empieza', 'Ley que describe la fuerza entre dos cargas eléctricas como proporcional al producto de las cargas e inversamente al cuadrado de la distancia', 'lenz', 'fisica', 'bachillerato', '{2}', 2),
('M', 'empieza', 'Material que dentro del núcleo de un transformador aumenta el acoplamiento magnético entre bobinas', 'moderador', 'fisica', 'bachillerato', '{2}', 2),
('P', 'empieza', 'Partícula emitida en la desintegración beta positiva, antipartícula del electrón', 'positron', 'fisica', 'bachillerato', '{2}', 2),
('S', 'empieza', 'Propiedad cuántica intrínseca de las partículas que toma valores semienteros para fermiones', 'spin', 'fisica', 'bachillerato', '{2}', 2),
('T', 'empieza', 'Temperatura equivalente a millones de grados necesaria para iniciar la fusión nuclear de hidrógeno', 'termonuclear', 'fisica', 'bachillerato', '{2}', 2),

-- Química 2º Bach extra (4 más)
('C', 'empieza', 'Especie molecular transitoria de alta energía que se forma en el punto máximo del diagrama de energía de reacción', 'complejo', 'quimica', 'bachillerato', '{2}', 2),
('E', 'empieza', 'Proceso no espontáneo donde se usa corriente eléctrica para forzar una reacción redox en sentido contrario al natural', 'electrolisis', 'quimica', 'bachillerato', '{2}', 1),
('I', 'empieza', 'Sustancia que cambia de color señalando el punto final de una valoración ácido-base o redox', 'indicador', 'quimica', 'bachillerato', '{2}', 1),
('S', 'empieza', 'Propiedad de una reacción reversible cuando las velocidades directa e inversa se igualan y las concentraciones permanecen constantes', 'sistema', 'quimica', 'bachillerato', '{2}', 1);

