-- Seed final: historias que completan los huecos detectados en bach
-- Generadas tras comparar con c:/tmp/historias-export/bach-*.json
-- 27 historias nuevas: 8 filosofia (1º) + 5 lengua (1º) + 4 matematicas (1º) + 10 tecnologia (2º)

-- ============================================================
-- FILOSOFIA · 1º Bachillerato (8 historias)
-- ============================================================
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('filosofia', 'bachillerato', '{1}', '["Pitágoras fundó en Crotona una comunidad filosófica religiosa y científica en el siglo VI antes de Cristo","Sostuvo que los números son el principio y la esencia última de toda la realidad","Descubrió las relaciones numéricas que rigen los intervalos musicales en las cuerdas vibrantes","El teorema de Pitágoras establece la relación entre los lados de todo triángulo rectángulo","Su pensamiento influyó decisivamente en Platón al vincular matemáticas y filosofía"]'),
('filosofia', 'bachillerato', '{1}', '["Zenón de Elea formuló paradojas famosas para defender las tesis de su maestro Parménides","La paradoja de Aquiles y la tortuga niega que el héroe pueda alcanzar jamás a la tortuga","La paradoja de la flecha sostiene que una flecha en vuelo está en realidad inmóvil","Zenón usó estas aporías para argumentar contra la posibilidad del movimiento y la pluralidad","Sus paradojas influyeron en el desarrollo posterior del cálculo infinitesimal y la teoría de conjuntos"]'),
('filosofia', 'bachillerato', '{1}', '["Averroes fue un filósofo andalusí del siglo XII nacido en Córdoba bajo dominio almohade","Escribió extensos comentarios a las obras de Aristóteles que lo hicieron célebre en Europa","Defendió la doble verdad que distingue los caminos de la filosofía y la religión revelada","Su racionalismo influyó en los averroístas latinos de la Universidad de París del siglo XIII","La Iglesia condenó varias tesis averroístas considerándolas incompatibles con la fe cristiana"]'),
('filosofia', 'bachillerato', '{1}', '["Maimónides fue un pensador judío cordobés del siglo XII exiliado a El Cairo","Su Guía de perplejos buscaba armonizar la filosofía aristotélica con la teología judía","Sostuvo que solo podemos conocer a Dios mediante atributos negativos diciendo qué no es","Influyó profundamente en Tomás de Aquino y en la escolástica cristiana medieval","Su obra es uno de los grandes puentes entre el pensamiento árabe judío y latino"]'),
('filosofia', 'bachillerato', '{1}', '["Pico della Mirandola escribió el Discurso sobre la dignidad del hombre en 1486","El texto exalta la libertad humana como capacidad de elegir el propio lugar en el cosmos","Dios habría creado al ser humano sin naturaleza fija para que se configure a sí mismo","Esta tesis convierte al hombre en escultor de su propia esencia mediante sus decisiones","La obra es considerada el manifiesto más representativo del humanismo renacentista italiano"]'),
('filosofia', 'bachillerato', '{1}', '["Hegel concibió la historia universal como el despliegue progresivo del espíritu hacia la libertad","Cada pueblo encarna un momento del desarrollo del espíritu en su época histórica","Los grandes individuos históricos ejecutan sin saberlo los fines de la razón universal","La astucia de la razón utiliza las pasiones humanas para alcanzar sus objetivos racionales","La historia culmina para Hegel en el Estado moderno como realización de la libertad ética"]'),
('filosofia', 'bachillerato', '{1}', '["La estética contemporánea cuestiona las nociones tradicionales de belleza y objeto artístico","Walter Benjamin analizó cómo la reproducción técnica destruye el aura de la obra de arte original","Adorno denunció la industria cultural como instrumento de alienación en las sociedades de masas","Arthur Danto propuso que el arte solo puede definirse dentro de un contexto teórico e institucional","El arte conceptual del siglo XX desplazó el valor de la obra hacia la idea que encarna"]'),
('filosofia', 'bachillerato', '{1}', '["Max Scheler desarrolló una antropología filosófica que distingue al ser humano de los demás seres vivos","El animal queda atado a su entorno mientras el hombre se abre reflexivamente al mundo","La capacidad de decir no a los impulsos define la libertad específicamente humana","El espíritu es para Scheler el principio que permite el distanciamiento y la objetividad","Su obra El puesto del hombre en el cosmos sintetiza esta concepción antropológica original"]');

-- ============================================================
-- LENGUA Y LITERATURA · 1º Bachillerato (5 historias)
-- ============================================================
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('lengua', 'bachillerato', '{1}', '["Las glosas Emilianenses del monasterio de San Millán son del siglo X en romance navarro","Contienen anotaciones marginales en romance a textos latinos para facilitar su comprensión","La glosa 89 es considerada la primera oración conservada escrita en lengua romance","Aparecen junto a palabras en vasco mostrando la convivencia lingüística del territorio","Estos documentos son testimonio fundamental de los orígenes del castellano escrito"]'),
('lengua', 'bachillerato', '{1}', '["Gonzalo de Berceo fue el primer poeta castellano con nombre conocido en el siglo XIII","Compuso sus obras en cuaderna vía siguiendo las normas del mester de clerecía","Los Milagros de Nuestra Señora recogen veinticinco relatos de intervenciones marianas","Berceo escribió para los peregrinos del camino a San Millán y Silos con lenguaje accesible","Su obra muestra la dignificación del romance castellano como vehículo literario culto"]'),
('lengua', 'bachillerato', '{1}', '["El Abencerraje es una novela morisca breve publicada a mediados del siglo XVI","Narra la historia de amistad entre el cristiano Rodrigo de Narváez y el moro Abindarráez","El argumento presenta al caballero musulmán como modelo de nobleza y lealtad","La obra idealiza las relaciones entre cristianos y moros fronterizos en la España medieval","Este texto inauguró la corriente maurófila que perduró hasta el Romanticismo español"]'),
('lengua', 'bachillerato', '{1}', '["El léxico español se ha enriquecido con préstamos de diversas lenguas a lo largo de su historia","Los arabismos como aceituna almohada y alcalde proceden de los ocho siglos de presencia árabe","Los galicismos como jardín paje y reproche llegaron del francés sobre todo en los siglos XVIII y XIX","Los italianismos aportaron términos artísticos y musicales como soneto piano y acuarela","Los anglicismos son los préstamos más recientes y abundantes del español contemporáneo"]'),
('lengua', 'bachillerato', '{1}', '["La pragmática estudia el uso del lenguaje en situaciones comunicativas concretas","Austin distinguió entre el acto locutivo ilocutivo y perlocutivo en su teoría de los actos de habla","Grice formuló el principio de cooperación con las cuatro máximas conversacionales","La máxima de cantidad exige aportar solo la información necesaria para el intercambio","Las implicaturas son significados que se transmiten indirectamente al violar estas máximas"]');

-- ============================================================
-- MATEMATICAS · 1º Bachillerato (4 historias)
-- ============================================================
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('matematicas', 'bachillerato', '{1}', '["Para resolver un triángulo cualquiera del que conocemos tres lados aplicamos el teorema del coseno","Despejamos uno de los ángulos usando la fórmula cos(A) = (b² + c² - a²) / (2bc)","Calculamos A aplicando el arcocoseno al cociente obtenido en el paso anterior","Usamos el teorema del seno para hallar un segundo ángulo a partir del primero","El tercer ángulo se obtiene restando los otros dos a 180 grados finalmente"]'),
('matematicas', 'bachillerato', '{1}', '["Para descomponer un vector en una base ortonormal calculamos sus componentes en cada eje","La proyección sobre el eje X se obtiene multiplicando el módulo por el coseno del ángulo","La proyección sobre el eje Y se obtiene multiplicando el módulo por el seno del ángulo","Escribimos el vector como combinación lineal de los vectores unitarios i y j","Comprobamos que la suma de los cuadrados de las componentes coincide con el cuadrado del módulo"]'),
('matematicas', 'bachillerato', '{1}', '["Para calcular las variaciones con repetición de n elementos tomados de k en k aplicamos la fórmula VR = n elevado a k","El razonamiento es que cada posición puede ocuparla cualquiera de los n elementos disponibles","Si lanzamos tres monedas distintas hay 2 elevado a 3 = 8 resultados posibles","Para las contraseñas de 4 dígitos tenemos 10 elevado a 4 = 10000 combinaciones diferentes","Esta fórmula es la base del cálculo de espacios muestrales en muchos problemas de probabilidad"]'),
('matematicas', 'bachillerato', '{1}', '["Una sucesión recurrente se define dando los primeros términos y una fórmula para los siguientes","La sucesión de Fibonacci comienza con 1 y 1 y cada término es suma de los dos anteriores","Para calcular el término vigésimo aplicamos la recurrencia veinte veces paso a paso","Existe la fórmula cerrada de Binet que usa el número áureo para calcular cualquier término","La razón entre términos consecutivos tiende al número áureo cuando el índice crece indefinidamente"]');

-- ============================================================
-- TECNOLOGIA · 2º Bachillerato (10 historias)
-- ============================================================
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('tecnologia', 'bachillerato', '{2}', '["Un decodificador binario recibe n líneas de entrada y activa una de sus 2 elevado a n salidas","En el decodificador 3 a 8 tres entradas binarias seleccionan una de las ocho posibles salidas","Cada combinación de entrada pone a nivel alto únicamente la salida correspondiente a ese número","Las demás salidas permanecen a nivel bajo durante toda la operación del circuito","Se utiliza en la selección de memoria en el direccionamiento de buses y en pantallas multiplexadas"]'),
('tecnologia', 'bachillerato', '{2}', '["La memoria caché es una memoria rápida que almacena datos e instrucciones de uso frecuente","Se sitúa entre el procesador y la memoria principal para reducir tiempos de acceso","La caché L1 está integrada en el propio núcleo del procesador con mínima latencia","La caché L2 y L3 tienen mayor capacidad pero tardan algo más en responder a las peticiones","El principio de localidad temporal y espacial hace que la caché aumente drásticamente el rendimiento"]'),
('tecnologia', 'bachillerato', '{2}', '["Una red WiFi doméstica se configura instalando un router conectado a la línea del proveedor de Internet","El router asigna direcciones IP locales mediante el protocolo DHCP a cada dispositivo conectado","El estándar 802.11ac opera en la banda de 5 GHz ofreciendo mayor velocidad y menos interferencias","Se activa el cifrado WPA3 para proteger las comunicaciones del ataque de intrusos externos","El router traduce las direcciones privadas a la dirección pública mediante el mecanismo NAT"]'),
('tecnologia', 'bachillerato', '{2}', '["Un modelo de clasificación supervisada se entrena con datos etiquetados previamente por expertos","El algoritmo aprende a asignar cada ejemplo a una categoría usando sus características de entrada","Durante la validación cruzada se evalúa el modelo con datos que no ha visto en el entrenamiento","La matriz de confusión resume aciertos y errores distinguiendo falsos positivos y negativos","Métricas como precisión recall y F1 cuantifican la calidad del clasificador entrenado finalmente"]'),
('tecnologia', 'bachillerato', '{2}', '["Una pasarela IoT recopila datos de sensores inalámbricos desplegados en una explotación agrícola","Los sensores miden humedad del suelo temperatura ambiente y radiación solar cada quince minutos","La pasarela utiliza LoRaWAN para recibir los datos con bajo consumo a varios kilómetros de distancia","Los datos se envían a la nube mediante una conexión móvil 4G para su procesamiento centralizado","Un panel de control web permite al agricultor activar el riego cuando detecta condiciones críticas"]'),
('tecnologia', 'bachillerato', '{2}', '["Un ataque de denegación de servicio distribuido satura un servidor con peticiones masivas","Los atacantes utilizan una botnet formada por miles de dispositivos comprometidos por malware","Cada bot envía peticiones simultáneas al objetivo consumiendo su ancho de banda y recursos","El servidor legítimo no puede atender a los usuarios reales debido a la sobrecarga generada","Los cortafuegos y servicios anti-DDoS filtran el tráfico malicioso manteniendo el servicio operativo"]'),
('tecnologia', 'bachillerato', '{2}', '["La fabricación industrial 4.0 integra maquinaria sensores y software en un ecosistema interconectado","Los gemelos digitales replican virtualmente cada máquina de la planta con sus parámetros reales","Los datos de producción se analizan en tiempo real para detectar desviaciones del proceso","El mantenimiento predictivo anticipa averías analizando vibraciones temperatura y consumo eléctrico","La información se comparte con clientes y proveedores a través de plataformas en la nube seguras"]'),
('tecnologia', 'bachillerato', '{2}', '["Un sistema de visión artificial comienza con una cámara que captura imágenes del objeto a analizar","La imagen se preprocesa aplicando filtros de reducción de ruido y ajuste de contraste","Los algoritmos de segmentación identifican los contornos y regiones relevantes dentro de la imagen","Una red neuronal convolucional extrae características y clasifica el objeto detectado","El sistema envía el resultado a un robot o a un PLC que toma la decisión correspondiente"]'),
('tecnologia', 'bachillerato', '{2}', '["El protocolo MODBUS RTU es un estándar de comunicación serie usado en automatización industrial","Un maestro consulta a varios esclavos por el mismo bus RS485 en modo multipunto","Cada esclavo tiene una dirección única que el maestro incluye al inicio del mensaje","El esclavo direccionado responde con los datos solicitados incluyendo un código de verificación CRC","Este protocolo es ampliamente utilizado en PLCs variadores y equipos de medida industriales"]'),
('tecnologia', 'bachillerato', '{2}', '["Un contenedor Docker empaqueta una aplicación junto con todas sus dependencias y librerías","La imagen base se define en un Dockerfile que describe paso a paso la construcción del entorno","El comando docker build genera la imagen lista para ejecutarse en cualquier máquina compatible","Docker Hub aloja imágenes públicas que pueden descargarse y ejecutarse en segundos","Kubernetes orquesta múltiples contenedores en clúster gestionando escalado y alta disponibilidad automáticamente"]');
