-- Seed de frases para Ordena la Frase: Tutoría Bachillerato 1º y 2º
-- 100 frases para 1º Bachillerato + 100 frases para 2º Bachillerato

-- =====================================================
-- 1º BACHILLERATO (100 frases)
-- =====================================================

INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La transición de la ESO al Bachillerato exige una mayor autonomía en la gestión del aprendizaje');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Elegir un itinerario académico coherente con tus intereses facilita la motivación a largo plazo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El método Cornell organiza los apuntes en tres zonas para favorecer el repaso activo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La técnica Pomodoro alterna bloques de concentración intensa con descansos breves y reparadores');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La ansiedad anticipatoria ante los exámenes suele reducirse con ejercicios de respiración diafragmática');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El autoconocimiento profesional empieza por identificar tus fortalezas, intereses y valores personales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La elaboración de un mapa conceptual ayuda a jerarquizar conceptos clave de forma visual');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Dormir entre siete y nueve horas consolida la memoria aprendida durante el día');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La asertividad permite defender tus opiniones sin agredir ni someterte al criterio ajeno');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Un buen estudiante sabe reconocer cuándo necesita pedir ayuda a un docente');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El pensamiento crítico exige cuestionar la fuente y la intención de cada información');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las redes sociales pueden distorsionar la percepción de la vida de los demás');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Reducir el tiempo frente a pantallas mejora la calidad del sueño nocturno');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La procrastinación suele esconder miedo al fracaso o perfeccionismo mal gestionado');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Dividir una tarea grande en pequeños pasos facilita empezar y mantener el ritmo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El feedback constructivo se centra en conductas concretas y no en juicios personales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Conocer tus sesgos cognitivos te permite tomar decisiones más racionales y reflexivas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La inteligencia emocional incluye reconocer, comprender y regular las propias emociones');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Un ambiente ordenado de estudio reduce las distracciones y favorece la concentración profunda');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El perfeccionismo extremo puede paralizar el avance y generar malestar emocional continuado');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La orientación vocacional ayuda a descubrir qué profesiones encajan con tu perfil');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El bachillerato general ofrece una formación amplia antes de especializarte en la universidad');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La ciencia, la tecnología, las humanidades y las artes son itinerarios complementarios');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La empatía activa consiste en escuchar con atención plena sin interrumpir ni juzgar');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las habilidades sociales se entrenan con práctica constante en situaciones cotidianas reales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La negociación efectiva busca acuerdos en los que ambas partes ganen algo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La toma de decisiones mejora cuando se valoran pros y contras de cada opción');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El consumo responsable de pantallas previene problemas de sueño y rendimiento académico');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Una dieta equilibrada influye directamente en tu capacidad de concentración y memoria');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El ejercicio físico regular reduce el estrés y mejora el estado de ánimo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La prevención de adicciones empieza por conocer los riesgos reales del consumo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Saber decir no ante la presión del grupo es un signo de madurez');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La ciudadanía digital implica respetar a los demás también en el entorno online');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La huella digital que dejas hoy puede afectar a tu futuro profesional');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Verificar las fuentes antes de compartir una noticia combate la desinformación en redes');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La igualdad de género se construye cuestionando los estereotipos presentes en nuestra cultura');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Denunciar cualquier forma de discriminación es un deber cívico y ético fundamental');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El voluntariado es una forma práctica de ejercer la solidaridad activa');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Participar en actividades del centro desarrolla habilidades de liderazgo y trabajo en equipo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El delegado representa la voz del grupo en las reuniones con el profesorado');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La escucha activa implica prestar atención verbal y no verbal al interlocutor');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La gestión del tiempo se basa en distinguir lo urgente de lo importante');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Una agenda semanal bien planificada evita la acumulación de tareas al final');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las técnicas de relajación muscular progresiva ayudan a reducir la tensión antes del examen');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El mindfulness entrena la atención plena al momento presente sin emitir juicios');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las emociones son mensajes internos que aportan información valiosa sobre tus necesidades');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Reconocer la tristeza y aceptarla es el primer paso para superarla');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Pedir ayuda psicológica cuando lo necesitas es un acto de valentía');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La resiliencia es la capacidad de superar situaciones adversas saliendo fortalecido de ellas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Fijarse metas SMART implica definirlas específicas, medibles, alcanzables, realistas y temporales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La motivación intrínseca es más duradera que la motivación basada en recompensas externas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Celebrar los pequeños logros refuerza el hábito y mantiene alta la motivación');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La técnica Feynman consiste en explicar un concepto con palabras sencillas para comprenderlo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El repaso espaciado refuerza la memoria a largo plazo mejor que el atracón');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Estudiar haciéndose preguntas es más eficaz que releer pasivamente los apuntes subrayados');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La autoevaluación sincera te permite detectar tus puntos débiles a tiempo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Los grupos de estudio bien organizados pueden reforzar la comprensión compartiendo dudas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El silencio y la desconexión del móvil son aliados clave del estudio profundo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Planificar una sesión antes de empezar evita perder tiempo decidiendo por dónde continuar');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las pausas activas cada cuarenta minutos mantienen la atención en niveles óptimos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La calidad del descanso condiciona directamente la calidad del aprendizaje posterior');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Hidratarse correctamente durante las horas de estudio mejora la agilidad mental');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Dejar preparado el material la noche anterior reduce el estrés matinal del examen');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Visualizarse haciendo bien el examen es una técnica útil contra los nervios');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Leer todas las preguntas antes de empezar ayuda a administrar el tiempo total');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Repartir el tiempo según el valor de cada pregunta es una estrategia inteligente');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Si te bloqueas en una pregunta, pasa a la siguiente y vuelve después');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Revisar las respuestas al final permite detectar errores cometidos por prisas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Aceptar que puedes equivocarte elimina parte de la presión autoimpuesta durante el examen');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El diálogo interno positivo influye en la confianza con la que afrontas los retos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Cambiar la narrativa del fracaso por aprendizaje fortalece tu mentalidad de crecimiento');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La mentalidad de crecimiento sostiene que las capacidades se desarrollan con esfuerzo sostenido');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Comparar tu progreso contigo mismo es más útil que compararte con tus compañeros');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La autonomía emocional implica no depender de la aprobación constante de los demás');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las amistades sanas se basan en reciprocidad, respeto y apoyo mutuo sincero');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Identificar relaciones tóxicas es el primer paso para alejarse de ellas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Poner límites claros en una relación protege tu bienestar emocional personal');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La comunicación no violenta describe hechos, sentimientos, necesidades y peticiones concretas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Discutir con respeto no significa renunciar a defender tu propia posición');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Pedir perdón cuando te equivocas fortalece la confianza en las relaciones humanas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La gratitud diaria es un hábito poderoso que mejora el bienestar psicológico');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Escribir un diario personal ayuda a ordenar pensamientos y procesar experiencias difíciles');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La salud mental es tan importante como la salud física del cuerpo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Normalizar el acceso a terapia reduce el estigma alrededor de los problemas emocionales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El consumo de alcohol en la adolescencia afecta al desarrollo del cerebro');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La evidencia científica demuestra que el cannabis perjudica la memoria y la concentración');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las apuestas online pueden generar adicción conductual con graves consecuencias personales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El uso abusivo del móvil se relaciona con niveles más altos de ansiedad');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Establecer horarios sin pantallas antes de dormir mejora la conciliación del sueño');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La educación afectivo-sexual se basa en el consentimiento, el respeto y la información');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La diversidad sexual y de género forma parte natural de cualquier sociedad humana');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Respetar a todas las personas independientemente de su identidad es un principio básico');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El lenguaje inclusivo visibiliza colectivos tradicionalmente silenciados en la comunicación pública');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La ética digital protege tus datos personales y los de las demás personas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Las contraseñas robustas son la primera línea de defensa de tu identidad digital');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Pensar antes de publicar evita arrepentirse después por contenidos compartidos impulsivamente');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'El ciberacoso deja huellas psicológicas tan dañinas como las del acoso presencial');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Conservar capturas de pantalla puede servir como prueba ante situaciones de acoso');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'La presión del grupo no justifica realizar acciones contra tus valores personales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{1}', 'Tener proyectos vitales más allá del instituto enriquece tu crecimiento personal integral');

-- =====================================================
-- 2º BACHILLERATO (100 frases)
-- =====================================================

INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La EBAU es un proceso que requiere planificación estratégica desde el inicio del curso');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La nota de admisión se calcula combinando el expediente académico y la prueba universitaria');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las materias de la fase específica permiten subir la nota hasta un máximo de cuatro puntos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Conocer los parámetros de ponderación de las universidades es clave para decidir tus optativas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La preinscripción universitaria se realiza tras conocer las calificaciones oficiales de la EBAU');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Elegir varias opciones por orden de preferencia amplía tus posibilidades de acceso');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Visitar las jornadas de puertas abiertas ayuda a conocer la realidad de cada campus');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los ciclos formativos de grado superior son una alternativa profesional de alta empleabilidad');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La FP dual combina formación en el centro educativo con prácticas en empresas reales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Informarse sobre salidas profesionales de cada grado reduce la incertidumbre en la elección');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las becas y ayudas al estudio permiten acceder a la universidad a más estudiantes');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los plazos de solicitud de becas deben marcarse en el calendario con antelación');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El Erasmus ofrece una experiencia internacional transformadora tanto académica como vital');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Aprender idiomas amplía notablemente las opciones académicas y laborales en un mundo globalizado');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los MOOC y cursos abiertos complementan la formación universitaria con contenidos especializados');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Construir un buen currículum implica destacar logros medibles y no solo funciones realizadas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Una carta de presentación personalizada marca la diferencia frente a plantillas genéricas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Preparar una entrevista exige investigar previamente la empresa y conocer su cultura');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Responder con ejemplos concretos fortalece cualquier afirmación durante una entrevista de trabajo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El lenguaje no verbal transmite gran parte del mensaje en una primera impresión');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La marca personal online refleja tu identidad profesional ante reclutadores y empresas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Un perfil profesional cuidado en LinkedIn abre puertas desde etapas tempranas de formación');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las soft skills como la comunicación o la adaptabilidad son muy valoradas profesionalmente');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Demostrar proactividad en las tareas mejora tu imagen ante cualquier evaluador o responsable');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El pensamiento crítico te protege frente a manipulaciones y bulos en medios digitales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Distinguir opinión de hecho es una habilidad esencial para el ciudadano del siglo veintiuno');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Contrastar varias fuentes antes de formarte una opinión reduce el sesgo de confirmación');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los algoritmos de redes sociales muestran contenidos afines que pueden crear burbujas informativas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Salir de tu zona de confort informativa te expone a perspectivas diversas y enriquecedoras');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La inteligencia artificial puede ser herramienta útil si se utiliza de forma crítica');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Copiar textos generados por IA sin entenderlos no aporta aprendizaje real al estudiante');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La ética del uso de IA en educación es un debate actual de gran importancia');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Citar correctamente las fuentes respeta la propiedad intelectual y evita caer en plagio');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La rigurosidad académica es un valor que se cultiva desde las primeras investigaciones');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La gestión del estrés en segundo de bachillerato requiere rutinas estables y realistas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La ansiedad anticipatoria ante la EBAU se alivia con simulacros regulares previos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Realizar exámenes cronometrados entrena la resistencia mental necesaria durante la prueba real');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Corregir tus propios errores con calma es una de las mejores estrategias de aprendizaje');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Llevar un registro de dudas acumuladas permite abordarlas en bloques durante las revisiones');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Distribuir el temario a lo largo del curso evita la sobrecarga cognitiva del final');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las noches anteriores a un examen deben priorizar el descanso antes que el estudio');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Confiar en la preparación realizada genera tranquilidad durante el desarrollo del examen');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La alimentación saludable en épocas de exámenes estabiliza los niveles de energía mental');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Mantener la actividad física aunque sea moderada libera tensión acumulada por el estudio');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Reservar momentos de ocio evita el desgaste emocional por la presión sostenida académica');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Hablar con alguien de confianza alivia el peso emocional de las expectativas propias');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El burnout académico se previene equilibrando esfuerzo, descanso y autocuidado diario');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Reconocer los síntomas de agotamiento mental es el primer paso para combatirlo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'No existen trayectorias únicas hacia el éxito profesional en el mundo actual');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Cambiar de opinión sobre tu futuro profesional forma parte natural del aprendizaje vital');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La formación continua es una necesidad en cualquier carrera profesional actual');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las profesiones del futuro exigirán capacidad de adaptación al cambio tecnológico constante');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El emprendimiento es una salida profesional viable que requiere preparación y mentalidad específica');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Fracasar en un proyecto no equivale a fracasar como persona o profesional');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La perseverancia supera muchas veces al talento natural en los caminos largos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El aprendizaje por proyectos desarrolla competencias transversales muy valoradas por las empresas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El liderazgo ético se basa en inspirar con el ejemplo y no en imponer');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Delegar con confianza es una de las habilidades clave del buen liderazgo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Trabajar en equipo diverso amplía la mirada y mejora los resultados colectivos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los desacuerdos bien gestionados enriquecen la toma de decisiones grupales en un proyecto');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La mediación entre partes en conflicto requiere imparcialidad y escucha activa constante');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La negociación integrativa persigue soluciones creativas más allá de las posturas iniciales');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las reuniones efectivas comienzan con un orden del día claro y acordado');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Dar feedback constructivo implica centrarse en la conducta y no en la persona');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Recibir críticas con apertura es una oportunidad valiosa de crecimiento personal y profesional');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El respeto a la diversidad cultural enriquece cualquier entorno de convivencia o trabajo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La igualdad real entre géneros requiere cambios estructurales y compromiso cotidiano de todos');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La brecha salarial sigue siendo una realidad que combatir con políticas activas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La corresponsabilidad doméstica es un pilar fundamental de la igualdad real en familias');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los derechos humanos son universales, indivisibles e inherentes a toda persona sin excepción');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La participación cívica se ejerce votando, asociándose y colaborando con la comunidad');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El compromiso con el medio ambiente es una obligación intergeneracional ineludible hoy');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La sostenibilidad debe integrarse en las decisiones personales, profesionales y políticas diarias');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los Objetivos de Desarrollo Sostenible marcan una hoja de ruta hacia 2030');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La ciudadanía global implica entender los problemas locales en su dimensión planetaria');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Ser consumidor responsable reduce la huella ecológica individual de manera significativa');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las decisiones financieras informadas protegen tu economía a corto y largo plazo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Entender conceptos básicos como interés compuesto evita decisiones económicas perjudiciales en el futuro');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Ahorrar desde joven es un hábito que multiplica las oportunidades futuras disponibles');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Las deudas por consumo innecesario son trampas financieras que conviene evitar siempre');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Diferenciar necesidades de deseos simplifica la gestión personal de tu presupuesto mensual');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La mayoría de edad conlleva responsabilidades legales que conviene conocer con tiempo');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Firmar un contrato sin leerlo es una imprudencia que puede salir muy cara');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Conocer tus derechos como estudiante universitario facilita la defensa ante eventuales injusticias administrativas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La independencia emocional respecto a la familia forma parte del proceso madurativo natural');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Mantener vínculos sanos con la familia no implica renunciar a la propia autonomía');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Comunicar abiertamente tus dudas con tus padres facilita el apoyo mutuo en transiciones');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Asumir decisiones propias exige aceptar también las consecuencias que puedan derivarse de ellas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los errores vistos como aprendizaje fortalecen tu carácter y tu capacidad de adaptación');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Tener un plan B reduce la angustia ante resultados inesperados en pruebas importantes');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Si el resultado de la EBAU no es el esperado existen alternativas válidas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Repetir la EBAU es una opción legítima para mejorar la nota de admisión');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Los años sabáticos bien planificados pueden aportar claridad vocacional y experiencia personal');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Estudiar fuera de casa desarrolla autonomía y competencias de gestión cotidiana personal');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Adaptarse a una residencia o piso compartido implica respeto, diálogo y convivencia activa');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Llevar cuentas mensuales de gastos evita sorpresas a final del mes universitario');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Combinar estudios con un trabajo a tiempo parcial exige una planificación muy rigurosa');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El voluntariado universitario refuerza competencias transversales y redes profesionales valiosas');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'La huella digital que construyes hoy acompaña tu trayectoria durante toda la vida');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'Cuidar tu reputación online forma parte esencial de tu marca personal profesional');
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES ('tutoria', 'bachillerato', '{2}', 'El final del bachillerato no es una meta sino el comienzo de otra etapa');
