-- ============================================================
-- Frases nuevas para Ordena la Frase — ESO
-- Programación (50 por curso × 4 cursos = 200 frases)
-- Robótica (60 por curso × 4 cursos = 240 frases)
-- Total: 440 frases
-- ============================================================

-- Programación 1º ESO (50 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('programacion', 'eso', '{1}', 'Un algoritmo es una secuencia de instrucciones ordenadas para resolver un problema concreto'),
('programacion', 'eso', '{1}', 'Scratch utiliza bloques de colores que se encajan como piezas de un rompecabezas'),
('programacion', 'eso', '{1}', 'La secuencia es el orden en el que el ordenador ejecuta las instrucciones del programa'),
('programacion', 'eso', '{1}', 'Un sprite es un personaje o elemento gráfico que se mueve por el escenario en Scratch'),
('programacion', 'eso', '{1}', 'El escenario de Scratch es el fondo donde ocurren las acciones de nuestro programa'),
('programacion', 'eso', '{1}', 'Los bloques de movimiento permiten desplazar al sprite por la pantalla en cualquier dirección'),
('programacion', 'eso', '{1}', 'Un evento es una acción que inicia la ejecución de un grupo de bloques en el programa'),
('programacion', 'eso', '{1}', 'La bandera verde de Scratch sirve para iniciar la ejecución del programa principal'),
('programacion', 'eso', '{1}', 'Los bloques de apariencia cambian el disfraz y el tamaño del sprite en pantalla'),
('programacion', 'eso', '{1}', 'Un mensaje en Scratch permite que dos sprites se comuniquen entre sí durante el programa'),
('programacion', 'eso', '{1}', 'El bloque repetir ejecuta las instrucciones que contiene un número determinado de veces'),
('programacion', 'eso', '{1}', 'La descomposición consiste en dividir un problema grande en partes más pequeñas y sencillas'),
('programacion', 'eso', '{1}', 'Un diagrama de flujo representa de forma visual los pasos de un algoritmo con flechas'),
('programacion', 'eso', '{1}', 'El pensamiento computacional nos ayuda a resolver problemas de forma lógica y ordenada'),
('programacion', 'eso', '{1}', 'Los bloques de sonido permiten reproducir música y efectos dentro de un proyecto de Scratch'),
('programacion', 'eso', '{1}', 'Un programa es un conjunto de instrucciones que el ordenador puede ejecutar de forma automática'),
('programacion', 'eso', '{1}', 'La abstracción consiste en quedarse solo con la información importante e ignorar los detalles'),
('programacion', 'eso', '{1}', 'El reconocimiento de patrones nos permite encontrar similitudes entre diferentes problemas'),
('programacion', 'eso', '{1}', 'Un bucle infinito repite las instrucciones sin parar hasta que detenemos el programa manualmente'),
('programacion', 'eso', '{1}', 'El bloque condicional si-entonces ejecuta unas instrucciones solo cuando se cumple una condición'),
('programacion', 'eso', '{1}', 'Los sensores de Scratch detectan si el sprite toca un borde o choca con otro objeto'),
('programacion', 'eso', '{1}', 'Un fondo del escenario se puede cambiar usando los bloques de apariencia del escenario'),
('programacion', 'eso', '{1}', 'Las coordenadas X e Y indican la posición exacta del sprite dentro del escenario'),
('programacion', 'eso', '{1}', 'El eje X representa la posición horizontal y el eje Y la posición vertical en pantalla'),
('programacion', 'eso', '{1}', 'Un error de lógica hace que el programa funcione pero no haga lo que esperábamos'),
('programacion', 'eso', '{1}', 'El depurador nos ayuda a encontrar errores revisando el programa paso a paso con cuidado'),
('programacion', 'eso', '{1}', 'Las instrucciones de un algoritmo deben ser claras y no dejar lugar a la ambigüedad'),
('programacion', 'eso', '{1}', 'Un proyecto de Scratch puede contener varios sprites que interactúan entre sí al ejecutarse'),
('programacion', 'eso', '{1}', 'Los operadores matemáticos permiten realizar sumas restas multiplicaciones y divisiones en el código'),
('programacion', 'eso', '{1}', 'El bloque preguntar muestra un cuadro de texto donde el usuario puede escribir su respuesta'),
('programacion', 'eso', '{1}', 'La variable respuesta almacena lo que el usuario escribió en el último cuadro de pregunta'),
('programacion', 'eso', '{1}', 'Un clon en Scratch es una copia temporal del sprite que puede actuar de forma independiente'),
('programacion', 'eso', '{1}', 'Los bloques de lápiz permiten dibujar líneas y figuras geométricas en el escenario de Scratch'),
('programacion', 'eso', '{1}', 'El bloque esperar detiene la ejecución durante unos segundos antes de continuar con la siguiente instrucción'),
('programacion', 'eso', '{1}', 'Las extensiones de Scratch añaden funciones nuevas como traducción de texto o síntesis de voz'),
('programacion', 'eso', '{1}', 'Un algoritmo debe tener un inicio claro y un final definido para que funcione correctamente'),
('programacion', 'eso', '{1}', 'La creatividad es fundamental para diseñar programas originales que resuelvan problemas reales'),
('programacion', 'eso', '{1}', 'El pensamiento lógico nos permite encadenar instrucciones en el orden correcto sin saltarnos pasos'),
('programacion', 'eso', '{1}', 'Un juego en Scratch necesita un sistema de puntuación para motivar al jugador a mejorar'),
('programacion', 'eso', '{1}', 'Los bloques de control deciden cuántas veces se repiten las acciones o cuándo se ejecutan'),
('programacion', 'eso', '{1}', 'Compartir un proyecto en la comunidad de Scratch permite que otros usuarios lo vean y remixen'),
('programacion', 'eso', '{1}', 'El diseño de un videojuego empieza por definir las reglas y los objetivos del juego'),
('programacion', 'eso', '{1}', 'Un algoritmo de la vida cotidiana es seguir una receta de cocina paso a paso sin saltarse nada'),
('programacion', 'eso', '{1}', 'La iteración permite mejorar un programa repitiendo el proceso de diseño prueba y corrección'),
('programacion', 'eso', '{1}', 'Los bloques de operadores comparan valores y devuelven verdadero o falso según la condición'),
('programacion', 'eso', '{1}', 'El trabajo en equipo facilita la creación de proyectos de programación más grandes y completos'),
('programacion', 'eso', '{1}', 'Un personaje animado en Scratch cambia de disfraz rápidamente para simular el movimiento'),
('programacion', 'eso', '{1}', 'La programación visual con bloques es más sencilla porque evita los errores de escritura del código'),
('programacion', 'eso', '{1}', 'El orden de las instrucciones es fundamental porque cambiar un paso puede alterar todo el resultado'),
('programacion', 'eso', '{1}', 'Un buen programador prueba su código varias veces para asegurarse de que funciona en todos los casos');

-- Programación 2º ESO (50 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('programacion', 'eso', '{2}', 'Una variable de tipo entero almacena números sin decimales como la edad o la puntuación del juego'),
('programacion', 'eso', '{2}', 'Las cadenas de texto son secuencias de caracteres encerradas entre comillas dobles o simples'),
('programacion', 'eso', '{2}', 'El bucle for repite un bloque de código un número determinado de veces usando un contador'),
('programacion', 'eso', '{2}', 'El bucle while ejecuta las instrucciones repetidamente mientras la condición indicada sea verdadera'),
('programacion', 'eso', '{2}', 'Una función recibe datos de entrada los procesa y devuelve un resultado como salida'),
('programacion', 'eso', '{2}', 'Los parámetros de una función son los valores que le pasamos para que trabaje con ellos'),
('programacion', 'eso', '{2}', 'El valor de retorno es el dato que la función devuelve al programa principal tras ejecutarse'),
('programacion', 'eso', '{2}', 'Un condicional anidado es una estructura si-entonces dentro de otra estructura si-entonces'),
('programacion', 'eso', '{2}', 'El operador AND devuelve verdadero solo cuando las dos condiciones que conecta son verdaderas'),
('programacion', 'eso', '{2}', 'El operador OR devuelve verdadero cuando al menos una de las dos condiciones es verdadera'),
('programacion', 'eso', '{2}', 'El operador NOT invierte el valor lógico convirtiendo verdadero en falso y viceversa'),
('programacion', 'eso', '{2}', 'Un acumulador es una variable que va sumando valores dentro de un bucle para obtener un total'),
('programacion', 'eso', '{2}', 'El contador es una variable que se incrementa en uno cada vez que el bucle completa una vuelta'),
('programacion', 'eso', '{2}', 'La estructura si-si no permite ejecutar un bloque de código u otro según el resultado de la condición'),
('programacion', 'eso', '{2}', 'Un diagrama de flujo utiliza rombos para representar decisiones y rectángulos para las acciones'),
('programacion', 'eso', '{2}', 'La entrada de datos permite al usuario introducir información que el programa necesita para funcionar'),
('programacion', 'eso', '{2}', 'La salida de datos muestra al usuario los resultados que el programa ha calculado o procesado'),
('programacion', 'eso', '{2}', 'Los operadores de comparación permiten verificar si dos valores son iguales mayores o menores'),
('programacion', 'eso', '{2}', 'Una variable booleana solo puede contener dos valores posibles que son verdadero o falso'),
('programacion', 'eso', '{2}', 'El alcance de una variable determina en qué partes del programa puede ser utilizada'),
('programacion', 'eso', '{2}', 'La modularidad divide el programa en funciones independientes que se pueden probar por separado'),
('programacion', 'eso', '{2}', 'Un error de sintaxis ocurre cuando el programador no respeta las reglas gramaticales del lenguaje'),
('programacion', 'eso', '{2}', 'Las pruebas del programa verifican que todas las funciones producen los resultados esperados correctamente'),
('programacion', 'eso', '{2}', 'La tabla de seguimiento permite rastrear el valor de las variables durante la ejecución del algoritmo'),
('programacion', 'eso', '{2}', 'Un número aleatorio generado por el programa sirve para crear situaciones impredecibles en los juegos'),
('programacion', 'eso', '{2}', 'El tipo de dato float almacena números con parte decimal como la temperatura o el precio'),
('programacion', 'eso', '{2}', 'La conversión de tipos transforma un dato de un formato a otro como de texto a número entero'),
('programacion', 'eso', '{2}', 'Un programa interactivo responde a las acciones del usuario en tiempo real mediante eventos'),
('programacion', 'eso', '{2}', 'La estructura repetir hasta ejecuta las instrucciones y luego comprueba si debe detenerse'),
('programacion', 'eso', '{2}', 'Los comentarios del código son notas que el programador escribe para explicar lo que hace cada parte'),
('programacion', 'eso', '{2}', 'Una librería es un conjunto de funciones ya programadas que podemos reutilizar en nuestros proyectos'),
('programacion', 'eso', '{2}', 'La eficiencia del código se mide por la rapidez y la cantidad de recursos que necesita para ejecutarse'),
('programacion', 'eso', '{2}', 'El operador módulo devuelve el resto de una división entera y es útil para detectar números pares'),
('programacion', 'eso', '{2}', 'Una animación por código se crea cambiando las propiedades de un objeto en cada fotograma del bucle'),
('programacion', 'eso', '{2}', 'La programación por bloques enseña los mismos conceptos que la programación textual de forma visual'),
('programacion', 'eso', '{2}', 'Un menú de opciones permite al usuario elegir entre varias acciones disponibles dentro del programa'),
('programacion', 'eso', '{2}', 'La validación de datos comprueba que la información introducida por el usuario es correcta y válida'),
('programacion', 'eso', '{2}', 'Un bucle controlado por centinela se detiene cuando el usuario introduce un valor especial de salida'),
('programacion', 'eso', '{2}', 'El flujo de ejecución describe el camino que sigue el programa desde la primera hasta la última instrucción'),
('programacion', 'eso', '{2}', 'Las constantes son valores que se definen una vez y no pueden modificarse durante la ejecución'),
('programacion', 'eso', '{2}', 'Un algoritmo de búsqueda lineal recorre todos los elementos de la lista hasta encontrar el buscado'),
('programacion', 'eso', '{2}', 'La legibilidad del código mejora cuando usamos nombres descriptivos para las variables y funciones'),
('programacion', 'eso', '{2}', 'Un array permite guardar varios datos del mismo tipo en una sola variable organizada por posiciones'),
('programacion', 'eso', '{2}', 'El índice de un array indica la posición donde se encuentra cada elemento dentro de la estructura'),
('programacion', 'eso', '{2}', 'La depuración paso a paso permite observar cómo cambian las variables en cada línea del programa'),
('programacion', 'eso', '{2}', 'Un programa debe manejar los errores del usuario mostrando mensajes claros en lugar de fallar'),
('programacion', 'eso', '{2}', 'La planificación del programa incluye definir los objetivos las entradas las salidas y el proceso'),
('programacion', 'eso', '{2}', 'El operador de concatenación une dos cadenas de texto para formar una nueva cadena más larga'),
('programacion', 'eso', '{2}', 'La estructura switch permite elegir entre múltiples opciones según el valor de una variable'),
('programacion', 'eso', '{2}', 'Un buen algoritmo debe ser finito correcto y lo más eficiente posible en el uso de recursos');

-- Programación 3º ESO (50 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('programacion', 'eso', '{3}', 'Python utiliza la función print para mostrar mensajes y resultados por la consola del programa'),
('programacion', 'eso', '{3}', 'La función input en Python permite al usuario introducir datos desde el teclado durante la ejecución'),
('programacion', 'eso', '{3}', 'Una lista en Python puede contener elementos de diferentes tipos como números cadenas y booleanos'),
('programacion', 'eso', '{3}', 'El método append añade un nuevo elemento al final de una lista existente en Python'),
('programacion', 'eso', '{3}', 'La función len devuelve la cantidad de elementos que contiene una lista o la longitud de una cadena'),
('programacion', 'eso', '{3}', 'Un bucle for in recorre automáticamente todos los elementos de una lista de principio a fin'),
('programacion', 'eso', '{3}', 'El slicing permite extraer una porción de una lista o cadena indicando las posiciones de inicio y fin'),
('programacion', 'eso', '{3}', 'Las tuplas son secuencias inmutables de datos que no pueden modificarse después de ser creadas'),
('programacion', 'eso', '{3}', 'Un diccionario en Python almacena datos en pares clave-valor para acceder rápidamente a la información'),
('programacion', 'eso', '{3}', 'La función range genera una secuencia de números que se usa habitualmente dentro de los bucles for'),
('programacion', 'eso', '{3}', 'El manejo de excepciones con try-except evita que el programa se detenga por un error inesperado'),
('programacion', 'eso', '{3}', 'Una función definida con def puede recibir parámetros y devolver un valor usando la palabra return'),
('programacion', 'eso', '{3}', 'Los métodos de cadena como upper y lower transforman el texto a mayúsculas o minúsculas respectivamente'),
('programacion', 'eso', '{3}', 'La función sorted ordena los elementos de una lista sin modificar la lista original en Python'),
('programacion', 'eso', '{3}', 'Las listas por comprensión crean nuevas listas aplicando una expresión a cada elemento de forma compacta'),
('programacion', 'eso', '{3}', 'El operador in comprueba si un elemento existe dentro de una lista una cadena o un diccionario'),
('programacion', 'eso', '{3}', 'La función int convierte una cadena de texto numérica en un número entero para poder operar con ella'),
('programacion', 'eso', '{3}', 'El formato de cadenas con f-strings permite insertar variables directamente dentro del texto en Python'),
('programacion', 'eso', '{3}', 'Un módulo es un archivo de Python que contiene funciones y variables reutilizables en otros programas'),
('programacion', 'eso', '{3}', 'La sentencia import permite cargar módulos externos para ampliar las funcionalidades del programa'),
('programacion', 'eso', '{3}', 'El módulo random ofrece funciones para generar números aleatorios y seleccionar elementos al azar'),
('programacion', 'eso', '{3}', 'El módulo math proporciona funciones matemáticas avanzadas como raíz cuadrada y valor absoluto'),
('programacion', 'eso', '{3}', 'Una variable local solo existe dentro de la función donde fue definida y no es accesible fuera'),
('programacion', 'eso', '{3}', 'El tipo de dato set almacena elementos únicos sin repeticiones y sin un orden determinado'),
('programacion', 'eso', '{3}', 'La lectura de archivos con open permite procesar datos almacenados en ficheros de texto externos'),
('programacion', 'eso', '{3}', 'La escritura de archivos permite guardar los resultados del programa de forma permanente en el disco'),
('programacion', 'eso', '{3}', 'Un bucle anidado es un bucle dentro de otro que se usa para recorrer estructuras de datos bidimensionales'),
('programacion', 'eso', '{3}', 'La función map aplica una misma operación a todos los elementos de una lista de forma simultánea'),
('programacion', 'eso', '{3}', 'El método split divide una cadena de texto en una lista de subcadenas usando un separador dado'),
('programacion', 'eso', '{3}', 'El método join une los elementos de una lista en una sola cadena de texto con un separador'),
('programacion', 'eso', '{3}', 'Los valores por defecto en los parámetros de una función se usan cuando no se pasa ningún argumento'),
('programacion', 'eso', '{3}', 'La recursividad en Python permite que una función se llame a sí misma para resolver subproblemas'),
('programacion', 'eso', '{3}', 'El depurador de Python permite ejecutar el código línea a línea para encontrar errores de lógica'),
('programacion', 'eso', '{3}', 'Una función lambda es una función anónima que se define en una sola línea para tareas simples'),
('programacion', 'eso', '{3}', 'El método pop elimina y devuelve el último elemento de una lista o el elemento en un índice dado'),
('programacion', 'eso', '{3}', 'La función enumerate devuelve cada elemento de una lista junto con su posición durante la iteración'),
('programacion', 'eso', '{3}', 'Los operadores de asignación compuesta como más-igual suman un valor a la variable y guardan el resultado'),
('programacion', 'eso', '{3}', 'El algoritmo de ordenación burbuja compara elementos adyacentes y los intercambia si están desordenados'),
('programacion', 'eso', '{3}', 'La complejidad de un algoritmo indica cuánto tiempo y memoria necesita al aumentar el tamaño de datos'),
('programacion', 'eso', '{3}', 'Un entorno virtual de Python aísla las dependencias de cada proyecto para evitar conflictos entre versiones'),
('programacion', 'eso', '{3}', 'El gestor de paquetes pip permite instalar librerías de terceros desde el repositorio oficial PyPI'),
('programacion', 'eso', '{3}', 'La función filter selecciona los elementos de una lista que cumplen una condición determinada'),
('programacion', 'eso', '{3}', 'Un archivo CSV almacena datos tabulares separados por comas que Python puede leer y procesar fácilmente'),
('programacion', 'eso', '{3}', 'El módulo turtle de Python permite crear gráficos y animaciones moviendo una tortuga por la pantalla'),
('programacion', 'eso', '{3}', 'La documentación de una función se escribe dentro de comillas triples justo debajo de la definición'),
('programacion', 'eso', '{3}', 'Los diccionarios anidados permiten crear estructuras de datos complejas con varios niveles de profundidad'),
('programacion', 'eso', '{3}', 'El método items del diccionario devuelve todos los pares clave-valor para recorrerlos en un bucle'),
('programacion', 'eso', '{3}', 'La programación funcional utiliza funciones puras que no modifican el estado externo del programa'),
('programacion', 'eso', '{3}', 'El método strip elimina los espacios en blanco al inicio y al final de una cadena de texto'),
('programacion', 'eso', '{3}', 'Las pruebas unitarias verifican que cada función individual del programa produce el resultado esperado');

-- Programación 4º ESO (50 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('programacion', 'eso', '{4}', 'Una clase en programación orientada a objetos define las propiedades y los métodos de un tipo de objeto'),
('programacion', 'eso', '{4}', 'Un objeto es una instancia concreta de una clase que posee valores propios para sus atributos'),
('programacion', 'eso', '{4}', 'El constructor de una clase es el método especial que se ejecuta automáticamente al crear un objeto'),
('programacion', 'eso', '{4}', 'La herencia permite crear una clase nueva que reutiliza los atributos y métodos de otra ya existente'),
('programacion', 'eso', '{4}', 'El polimorfismo permite que diferentes clases respondan de forma distinta al mismo nombre de método'),
('programacion', 'eso', '{4}', 'El encapsulamiento oculta los detalles internos de un objeto y solo expone lo estrictamente necesario'),
('programacion', 'eso', '{4}', 'Una base de datos relacional organiza la información en tablas relacionadas mediante claves primarias y foráneas'),
('programacion', 'eso', '{4}', 'La consulta SELECT de SQL permite recuperar datos específicos de una o varias tablas de la base de datos'),
('programacion', 'eso', '{4}', 'La cláusula WHERE filtra los registros de una consulta SQL según una condición lógica determinada'),
('programacion', 'eso', '{4}', 'La sentencia INSERT INTO añade nuevos registros a una tabla existente de la base de datos'),
('programacion', 'eso', '{4}', 'La normalización de bases de datos reduce la redundancia organizando los datos en tablas relacionadas'),
('programacion', 'eso', '{4}', 'HTML define la estructura del contenido de una página web mediante etiquetas de apertura y cierre'),
('programacion', 'eso', '{4}', 'CSS separa la presentación visual del contenido permitiendo cambiar el diseño sin modificar el HTML'),
('programacion', 'eso', '{4}', 'JavaScript permite añadir interactividad y comportamiento dinámico a las páginas web del lado del cliente'),
('programacion', 'eso', '{4}', 'El modelo de cajas de CSS define el margen el borde el relleno y el contenido de cada elemento HTML'),
('programacion', 'eso', '{4}', 'Un formulario HTML recoge datos del usuario y los envía al servidor para su procesamiento posterior'),
('programacion', 'eso', '{4}', 'La metodología ágil organiza el desarrollo de software en ciclos cortos con entregas incrementales'),
('programacion', 'eso', '{4}', 'El control de versiones con Git permite registrar cada cambio en el código y volver a versiones anteriores'),
('programacion', 'eso', '{4}', 'Un repositorio de código almacena todos los archivos del proyecto junto con su historial de cambios'),
('programacion', 'eso', '{4}', 'La arquitectura cliente-servidor separa la lógica de presentación de la lógica de procesamiento de datos'),
('programacion', 'eso', '{4}', 'Una API es una interfaz que permite a dos aplicaciones diferentes comunicarse e intercambiar datos'),
('programacion', 'eso', '{4}', 'El formato JSON organiza los datos en pares clave-valor y es el estándar para el intercambio de información web'),
('programacion', 'eso', '{4}', 'El diseño responsive adapta automáticamente la apariencia de la web al tamaño de cada dispositivo'),
('programacion', 'eso', '{4}', 'Las media queries de CSS aplican estilos diferentes según las características de la pantalla del dispositivo'),
('programacion', 'eso', '{4}', 'Un framework es un conjunto de herramientas y librerías que facilitan el desarrollo de aplicaciones'),
('programacion', 'eso', '{4}', 'La sentencia UPDATE modifica los valores de uno o varios campos en los registros existentes de una tabla'),
('programacion', 'eso', '{4}', 'La sentencia DELETE elimina registros de una tabla de la base de datos según la condición especificada'),
('programacion', 'eso', '{4}', 'Las relaciones uno a muchos conectan un registro de una tabla con varios registros de otra tabla'),
('programacion', 'eso', '{4}', 'El diagrama entidad-relación representa gráficamente las tablas y sus conexiones en la base de datos'),
('programacion', 'eso', '{4}', 'Un proyecto de desarrollo web completo incluye planificación diseño implementación pruebas y despliegue'),
('programacion', 'eso', '{4}', 'El selector CSS identifica los elementos HTML a los que se les aplicarán las reglas de estilo definidas'),
('programacion', 'eso', '{4}', 'Flexbox es un sistema de diseño CSS que organiza los elementos en filas o columnas de forma flexible'),
('programacion', 'eso', '{4}', 'CSS Grid permite crear diseños de página basados en cuadrículas con filas y columnas definidas'),
('programacion', 'eso', '{4}', 'El DOM es la representación en forma de árbol de todos los elementos de una página web en el navegador'),
('programacion', 'eso', '{4}', 'Los eventos del DOM permiten ejecutar funciones de JavaScript cuando el usuario interactúa con la página'),
('programacion', 'eso', '{4}', 'La validación del lado del cliente comprueba los datos del formulario antes de enviarlos al servidor'),
('programacion', 'eso', '{4}', 'El principio DRY significa no repetir código y reutilizar funciones en lugar de duplicar instrucciones'),
('programacion', 'eso', '{4}', 'Las pruebas de integración verifican que los distintos módulos del programa funcionan correctamente juntos'),
('programacion', 'eso', '{4}', 'Un diagrama de clases muestra las relaciones entre las clases y sus atributos y métodos principales'),
('programacion', 'eso', '{4}', 'La documentación técnica del proyecto explica cómo funciona el código para facilitar su mantenimiento futuro'),
('programacion', 'eso', '{4}', 'El patrón de diseño MVC separa el modelo de datos la vista de presentación y el controlador de lógica'),
('programacion', 'eso', '{4}', 'Las funciones de agregación SQL como COUNT y SUM calculan valores a partir de un conjunto de registros'),
('programacion', 'eso', '{4}', 'La cláusula JOIN combina datos de dos o más tablas relacionadas en una sola consulta SQL'),
('programacion', 'eso', '{4}', 'El almacenamiento local del navegador permite guardar datos en el dispositivo del usuario sin servidor'),
('programacion', 'eso', '{4}', 'La accesibilidad web garantiza que las personas con diversidad funcional puedan usar las páginas correctamente'),
('programacion', 'eso', '{4}', 'Un método estático pertenece a la clase y no a un objeto concreto y se puede llamar sin crear instancias'),
('programacion', 'eso', '{4}', 'La sobrecarga de métodos permite definir varias versiones del mismo método con diferentes parámetros'),
('programacion', 'eso', '{4}', 'El despliegue de una aplicación web consiste en publicarla en un servidor para que los usuarios la utilicen'),
('programacion', 'eso', '{4}', 'Las variables de sesión almacenan datos del usuario mientras navega por las diferentes páginas del sitio'),
('programacion', 'eso', '{4}', 'La optimización del código mejora el rendimiento reduciendo el tiempo de ejecución y el consumo de memoria');

-- Robótica 1º ESO (60 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('robotica', 'eso', '{1}', 'Un circuito eléctrico necesita una fuente de energía un conductor y un receptor para funcionar'),
('robotica', 'eso', '{1}', 'El interruptor es un componente que abre o cierra el paso de la corriente eléctrica en un circuito'),
('robotica', 'eso', '{1}', 'La resistencia eléctrica se opone al paso de la corriente y se mide en ohmios'),
('robotica', 'eso', '{1}', 'Un diodo LED emite luz cuando la corriente eléctrica lo atraviesa en la dirección correcta'),
('robotica', 'eso', '{1}', 'El motor eléctrico transforma la energía eléctrica en movimiento giratorio para mover el robot'),
('robotica', 'eso', '{1}', 'Un sensor de luz detecta la cantidad de luminosidad del ambiente que rodea al robot'),
('robotica', 'eso', '{1}', 'El sensor de temperatura mide los grados de calor o frío del entorno donde se encuentra el robot'),
('robotica', 'eso', '{1}', 'Las pilas proporcionan la energía eléctrica necesaria para que los componentes del robot funcionen'),
('robotica', 'eso', '{1}', 'Un circuito en serie conecta todos los componentes uno detrás de otro en un único camino'),
('robotica', 'eso', '{1}', 'Un circuito en paralelo ofrece varios caminos diferentes para que circule la corriente eléctrica'),
('robotica', 'eso', '{1}', 'El voltaje es la fuerza que impulsa a los electrones a moverse a través del circuito eléctrico'),
('robotica', 'eso', '{1}', 'La corriente eléctrica es el flujo de electrones que circula por un conductor como un cable'),
('robotica', 'eso', '{1}', 'Un robot móvil necesita al menos dos ruedas motorizadas para poder desplazarse por el suelo'),
('robotica', 'eso', '{1}', 'El sensor de contacto detecta cuando el robot choca contra un objeto y envía una señal al controlador'),
('robotica', 'eso', '{1}', 'La estructura mecánica del robot determina su forma su resistencia y sus posibilidades de movimiento'),
('robotica', 'eso', '{1}', 'Un engranaje transmite el movimiento de un eje a otro cambiando la velocidad o la dirección del giro'),
('robotica', 'eso', '{1}', 'La polea es una rueda con una ranura por donde pasa una cuerda para levantar o mover objetos'),
('robotica', 'eso', '{1}', 'Una palanca es una barra rígida que gira sobre un punto de apoyo para multiplicar la fuerza aplicada'),
('robotica', 'eso', '{1}', 'El plano inclinado facilita subir objetos pesados usando una superficie en pendiente en lugar de levantarlos'),
('robotica', 'eso', '{1}', 'Los materiales conductores como el cobre permiten el paso de la corriente eléctrica con facilidad'),
('robotica', 'eso', '{1}', 'Los materiales aislantes como el plástico impiden el paso de la corriente eléctrica protegiéndonos'),
('robotica', 'eso', '{1}', 'Un esquema eléctrico representa los componentes y las conexiones del circuito usando símbolos normalizados'),
('robotica', 'eso', '{1}', 'La programación del robot consiste en escribir las instrucciones que debe seguir para completar su tarea'),
('robotica', 'eso', '{1}', 'El bloque de movimiento indica al robot cuántos centímetros debe avanzar hacia delante o hacia atrás'),
('robotica', 'eso', '{1}', 'El bloque de giro ordena al robot que rote un número determinado de grados hacia la izquierda o derecha'),
('robotica', 'eso', '{1}', 'Un robot sigue-líneas utiliza sensores de infrarrojos para detectar una línea oscura sobre fondo claro'),
('robotica', 'eso', '{1}', 'La rueda loca es una rueda libre que gira en cualquier dirección y sirve de apoyo al robot'),
('robotica', 'eso', '{1}', 'Un mecanismo de biela-manivela transforma el movimiento circular en movimiento de vaivén lineal'),
('robotica', 'eso', '{1}', 'La caja de cambios o reductora reduce la velocidad del motor para aumentar la fuerza del robot'),
('robotica', 'eso', '{1}', 'Un sensor de sonido detecta los niveles de ruido del ambiente y reacciona ante sonidos fuertes'),
('robotica', 'eso', '{1}', 'El sistema de transmisión lleva el movimiento desde el motor hasta las ruedas o los ejes del robot'),
('robotica', 'eso', '{1}', 'Un robot explorador puede recorrer un laberinto usando sensores para detectar las paredes y los giros'),
('robotica', 'eso', '{1}', 'La energía solar se puede aprovechar con paneles fotovoltaicos para alimentar pequeños robots educativos'),
('robotica', 'eso', '{1}', 'Las piezas de construcción robótica encajan entre sí para formar estructuras sólidas y funcionales'),
('robotica', 'eso', '{1}', 'Un tornillo sin fin transmite el movimiento entre ejes perpendiculares con una gran reducción de velocidad'),
('robotica', 'eso', '{1}', 'La cadena cinemática es el conjunto de piezas que transmiten el movimiento desde el motor hasta el efector'),
('robotica', 'eso', '{1}', 'Un robot puede repetir la misma tarea muchas veces sin cansarse ni cometer errores por fatiga'),
('robotica', 'eso', '{1}', 'La simulación virtual permite probar el comportamiento del robot antes de construirlo físicamente'),
('robotica', 'eso', '{1}', 'Un proyecto de robótica incluye las fases de diseño construcción programación pruebas y mejora continua'),
('robotica', 'eso', '{1}', 'El cuaderno técnico documenta cada paso del proyecto para poder reproducirlo o mejorarlo en el futuro'),
('robotica', 'eso', '{1}', 'La seguridad en el taller exige usar gafas de protección al cortar o manipular piezas metálicas'),
('robotica', 'eso', '{1}', 'Las leyes de Asimov establecen que un robot nunca debe causar daño a un ser humano por acción u omisión'),
('robotica', 'eso', '{1}', 'Un robot recogedor utiliza una pala o pinza para agarrar objetos y depositarlos en otro lugar'),
('robotica', 'eso', '{1}', 'La cremallera es un mecanismo que convierte el giro de un engranaje en desplazamiento en línea recta'),
('robotica', 'eso', '{1}', 'El eje de un motor es la barra cilíndrica que transmite la rotación a las ruedas o mecanismos del robot'),
('robotica', 'eso', '{1}', 'Un robot aspirador doméstico usa sensores para mapear la habitación y evitar chocar con los muebles'),
('robotica', 'eso', '{1}', 'La electrónica básica estudia los componentes fundamentales como resistencias diodos y condensadores'),
('robotica', 'eso', '{1}', 'Un multímetro es un instrumento que mide voltaje corriente y resistencia en circuitos eléctricos'),
('robotica', 'eso', '{1}', 'Las ruedas dentadas o engranajes transmiten el movimiento entre dos ejes que giran a velocidades distintas'),
('robotica', 'eso', '{1}', 'Un sensor magnético detecta la presencia de imanes y campos magnéticos cercanos al robot'),
('robotica', 'eso', '{1}', 'La fuerza de rozamiento se opone al movimiento del robot y depende del tipo de superficie del suelo'),
('robotica', 'eso', '{1}', 'El diseño del chasis debe ser compacto y equilibrado para que el robot se desplace de forma estable'),
('robotica', 'eso', '{1}', 'Un robot con orugas tiene mejor tracción en terrenos irregulares que uno con ruedas convencionales'),
('robotica', 'eso', '{1}', 'La tecnología nos permite construir máquinas que realizan tareas peligrosas en lugar de las personas'),
('robotica', 'eso', '{1}', 'El trabajo cooperativo en grupo mejora el resultado final del proyecto de robótica gracias a las ideas compartidas'),
('robotica', 'eso', '{1}', 'Una correa de transmisión conecta dos poleas y permite transferir el movimiento entre ejes separados'),
('robotica', 'eso', '{1}', 'La velocidad de un motor se mide en revoluciones por minuto y determina la rapidez del robot'),
('robotica', 'eso', '{1}', 'Un pulsador es un botón que solo deja pasar la corriente mientras lo mantenemos presionado con el dedo'),
('robotica', 'eso', '{1}', 'El prototipo es la primera versión funcional del robot que se construye para probar el diseño inicial'),
('robotica', 'eso', '{1}', 'La retroalimentación permite al robot ajustar sus acciones comparando el resultado real con el esperado');

-- Robótica 2º ESO (60 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('robotica', 'eso', '{2}', 'La placa Arduino se programa mediante el entorno de desarrollo integrado Arduino IDE desde el ordenador'),
('robotica', 'eso', '{2}', 'La función setup en Arduino se ejecuta una sola vez al encender la placa para configurar los pines'),
('robotica', 'eso', '{2}', 'La función loop en Arduino se repite continuamente ejecutando las instrucciones del programa principal'),
('robotica', 'eso', '{2}', 'Los pines digitales de Arduino pueden configurarse como entrada para leer sensores o salida para activar actuadores'),
('robotica', 'eso', '{2}', 'La señal analógica varía de forma continua mientras que la señal digital solo tiene dos estados posibles'),
('robotica', 'eso', '{2}', 'Un sensor de distancia por ultrasonidos emite ondas sonoras y mide el tiempo que tardan en rebotar'),
('robotica', 'eso', '{2}', 'La protoboard permite montar circuitos electrónicos temporales sin necesidad de soldar los componentes'),
('robotica', 'eso', '{2}', 'El sensor de humedad detecta la cantidad de agua presente en el suelo para sistemas de riego automático'),
('robotica', 'eso', '{2}', 'Un motor paso a paso gira en incrementos exactos permitiendo un control preciso de la posición angular'),
('robotica', 'eso', '{2}', 'El puente H es un circuito que permite cambiar el sentido de giro del motor de corriente continua'),
('robotica', 'eso', '{2}', 'La función digitalWrite envía una señal alta o baja a un pin digital de la placa Arduino'),
('robotica', 'eso', '{2}', 'La función analogRead lee el valor de un sensor conectado a una entrada analógica de Arduino'),
('robotica', 'eso', '{2}', 'El monitor serie de Arduino IDE muestra en pantalla los datos que envía la placa para depuración'),
('robotica', 'eso', '{2}', 'Un shield es una placa que se apila sobre Arduino para añadir funciones como control de motores o WiFi'),
('robotica', 'eso', '{2}', 'La alimentación externa proporciona mayor corriente que el puerto USB para mover motores potentes'),
('robotica', 'eso', '{2}', 'Un relé electromagnético permite controlar dispositivos de alto voltaje usando señales de baja tensión'),
('robotica', 'eso', '{2}', 'El fotorresistor o LDR cambia su resistencia eléctrica según la cantidad de luz que recibe del entorno'),
('robotica', 'eso', '{2}', 'Un display LCD muestra mensajes de texto y datos numéricos del programa del robot en tiempo real'),
('robotica', 'eso', '{2}', 'La matriz de LED permite crear imágenes y animaciones sencillas controlando cada punto de luz individualmente'),
('robotica', 'eso', '{2}', 'Un sensor piezoeléctrico genera electricidad cuando se deforma y puede detectar vibraciones o presión'),
('robotica', 'eso', '{2}', 'El divisor de tensión usa dos resistencias para obtener un voltaje menor a partir de uno mayor'),
('robotica', 'eso', '{2}', 'Los transistores amplifican señales pequeñas y funcionan como interruptores electrónicos controlados por corriente'),
('robotica', 'eso', '{2}', 'La banda elástica transmite movimiento entre ejes y se puede fabricar con materiales reciclados'),
('robotica', 'eso', '{2}', 'Un robot sumo intenta empujar al oponente fuera de un círculo usando fuerza y sensores de borde'),
('robotica', 'eso', '{2}', 'La competición de robots velocistas premia al robot que completa el circuito en el menor tiempo posible'),
('robotica', 'eso', '{2}', 'Un sensor de gas detecta la presencia de sustancias peligrosas en el aire como humo o metano'),
('robotica', 'eso', '{2}', 'El regulador de voltaje mantiene constante la tensión de alimentación independientemente de las fluctuaciones'),
('robotica', 'eso', '{2}', 'La modularidad del diseño permite sustituir piezas del robot sin necesidad de reconstruirlo desde cero'),
('robotica', 'eso', '{2}', 'Un sensor de color identifica los colores de los objetos usando componentes de luz roja verde y azul'),
('robotica', 'eso', '{2}', 'La señal PWM modula el ancho del pulso para controlar la velocidad de los motores de forma gradual'),
('robotica', 'eso', '{2}', 'El control proporcional ajusta la respuesta del robot de forma progresiva según la magnitud del error'),
('robotica', 'eso', '{2}', 'Una tira de LED neopíxel permite programar individualmente el color y brillo de cada diodo de la cadena'),
('robotica', 'eso', '{2}', 'El diodo de protección evita que la corriente inversa generada por los motores dañe la placa de control'),
('robotica', 'eso', '{2}', 'Un robot teleoperado recibe las órdenes de un mando a distancia controlado por un operador humano'),
('robotica', 'eso', '{2}', 'La comunicación infrarroja permite enviar y recibir datos sin cables usando haces de luz invisibles'),
('robotica', 'eso', '{2}', 'Un sensor barométrico mide la presión atmosférica y puede estimar la altitud del robot sobre el nivel del mar'),
('robotica', 'eso', '{2}', 'El acelerómetro detecta cambios en la velocidad y la orientación del robot midiendo la aceleración en tres ejes'),
('robotica', 'eso', '{2}', 'Un motor de vibración produce pequeños temblores que se usan como alerta táctil en dispositivos electrónicos'),
('robotica', 'eso', '{2}', 'La soldadura con estaño une permanentemente los componentes electrónicos a la placa de circuito impreso'),
('robotica', 'eso', '{2}', 'El esquema eléctrico es el plano del circuito que indica cómo conectar cada componente correctamente'),
('robotica', 'eso', '{2}', 'Un robot de rescate puede buscar supervivientes en edificios derrumbados usando cámaras y sensores de calor'),
('robotica', 'eso', '{2}', 'La rueda de codificación permite medir con precisión la distancia que ha recorrido cada rueda del robot'),
('robotica', 'eso', '{2}', 'Un brazo robótico sencillo puede tener tres articulaciones que imitan el hombro el codo y la muñeca'),
('robotica', 'eso', '{2}', 'El diseño asistido por ordenador o CAD permite crear modelos tridimensionales de las piezas del robot'),
('robotica', 'eso', '{2}', 'La corriente alterna cambia de dirección periódicamente mientras que la continua fluye siempre en el mismo sentido'),
('robotica', 'eso', '{2}', 'Un fusible protege el circuito cortando la corriente cuando supera un valor máximo de seguridad'),
('robotica', 'eso', '{2}', 'La documentación del proyecto incluye esquemas fotografías el código fuente y una descripción del funcionamiento'),
('robotica', 'eso', '{2}', 'Un sensor de final de carrera detecta que una pieza ha llegado al límite de su recorrido mecánico'),
('robotica', 'eso', '{2}', 'El programa del robot debe incluir rutinas de seguridad que lo detengan en caso de fallo imprevisto'),
('robotica', 'eso', '{2}', 'La programación textual con Arduino utiliza el lenguaje C simplificado con funciones específicas para la placa'),
('robotica', 'eso', '{2}', 'Un circuito integrado contiene miles de transistores miniaturizados dentro de un solo encapsulado pequeño'),
('robotica', 'eso', '{2}', 'La corriente máxima que soporta un pin de Arduino es de cuarenta miliamperios para evitar daños'),
('robotica', 'eso', '{2}', 'Un mando por Bluetooth permite controlar el robot de forma inalámbrica desde un teléfono móvil o tableta'),
('robotica', 'eso', '{2}', 'La lectura de los sensores debe realizarse con frecuencia suficiente para que el robot reaccione a tiempo'),
('robotica', 'eso', '{2}', 'Un robot pintor puede trazar líneas y formas geométricas controlando un rotulador con servomotores'),
('robotica', 'eso', '{2}', 'El ahorro energético en robótica se consigue apagando los componentes que no se estén usando en cada momento'),
('robotica', 'eso', '{2}', 'La tracción diferencial permite girar el robot haciendo que cada rueda gire a una velocidad diferente'),
('robotica', 'eso', '{2}', 'Un sensor de inclinación detecta si el robot se ha volcado midiendo el ángulo respecto a la horizontal'),
('robotica', 'eso', '{2}', 'El bucle principal del programa lee los sensores procesa la información y activa los actuadores correspondientes'),
('robotica', 'eso', '{2}', 'La presentación del proyecto ante la clase desarrolla la capacidad de comunicación y la confianza del alumno');

-- Robótica 3º ESO (60 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('robotica', 'eso', '{3}', 'La automatización industrial reemplaza tareas manuales repetitivas por procesos controlados por máquinas programables'),
('robotica', 'eso', '{3}', 'Un sistema de control de lazo cerrado ajusta la salida comparando el resultado con el valor deseado'),
('robotica', 'eso', '{3}', 'El control PID utiliza tres componentes proporcional integral y derivativo para minimizar el error del sistema'),
('robotica', 'eso', '{3}', 'El diseño 3D con software CAD permite modelar piezas mecánicas antes de fabricarlas con la impresora'),
('robotica', 'eso', '{3}', 'El formato STL es el estándar para exportar modelos tridimensionales que se imprimirán en 3D'),
('robotica', 'eso', '{3}', 'La impresora 3D de filamento deposita capas de plástico fundido para construir un objeto capa a capa'),
('robotica', 'eso', '{3}', 'El material PLA es biodegradable y se usa con frecuencia en impresión 3D por su facilidad de manejo'),
('robotica', 'eso', '{3}', 'Un actuador lineal convierte el giro de un motor en un desplazamiento recto de avance y retroceso'),
('robotica', 'eso', '{3}', 'La domótica aplica la automatización al hogar controlando iluminación calefacción y seguridad de forma centralizada'),
('robotica', 'eso', '{3}', 'Un sensor de corriente mide la intensidad eléctrica que consume un motor para detectar sobrecargas'),
('robotica', 'eso', '{3}', 'La comunicación Bluetooth permite conectar el robot a dispositivos móviles sin cables en distancias cortas'),
('robotica', 'eso', '{3}', 'El módulo WiFi ESP8266 conecta proyectos de Arduino a internet para enviar y recibir datos remotamente'),
('robotica', 'eso', '{3}', 'Un sistema IoT recoge datos de sensores los envía a la nube y permite consultarlos desde cualquier lugar'),
('robotica', 'eso', '{3}', 'El protocolo I2C conecta múltiples dispositivos al microcontrolador usando solo dos líneas de comunicación'),
('robotica', 'eso', '{3}', 'Un servomotor digital ofrece mayor precisión y respuesta más rápida que un servomotor analógico convencional'),
('robotica', 'eso', '{3}', 'La placa de circuito impreso PCB conecta los componentes electrónicos mediante pistas de cobre grabadas'),
('robotica', 'eso', '{3}', 'El corte láser permite fabricar piezas planas de madera o metacrilato con formas complejas y precisas'),
('robotica', 'eso', '{3}', 'Un sistema de riego automático usa sensores de humedad y electroválvulas controladas por un microcontrolador'),
('robotica', 'eso', '{3}', 'La estación meteorológica robótica mide temperatura humedad presión y velocidad del viento automáticamente'),
('robotica', 'eso', '{3}', 'Las interrupciones permiten al microcontrolador responder inmediatamente a eventos urgentes sin esperar al bucle'),
('robotica', 'eso', '{3}', 'Un optoacoplador aísla eléctricamente dos partes del circuito usando luz infrarroja como medio de transmisión'),
('robotica', 'eso', '{3}', 'La máquina de estados finitos organiza el comportamiento del robot en estados con transiciones definidas'),
('robotica', 'eso', '{3}', 'Un convertidor analógico-digital transforma señales continuas del sensor en valores numéricos que procesa el microcontrolador'),
('robotica', 'eso', '{3}', 'La alimentación con paneles solares hace que los proyectos robóticos sean más sostenibles y autónomos'),
('robotica', 'eso', '{3}', 'Un motor brushless no tiene escobillas y ofrece mayor eficiencia y durabilidad que los motores con escobillas'),
('robotica', 'eso', '{3}', 'El variador de frecuencia o ESC controla la velocidad y el sentido de giro de un motor sin escobillas'),
('robotica', 'eso', '{3}', 'La programación multitarea permite al robot ejecutar varias funciones aparentemente al mismo tiempo con eficiencia'),
('robotica', 'eso', '{3}', 'Un sistema SCADA supervisa y controla procesos industriales en tiempo real desde una pantalla centralizada'),
('robotica', 'eso', '{3}', 'La cinta transportadora automatizada traslada objetos entre estaciones de trabajo en una línea de producción'),
('robotica', 'eso', '{3}', 'Un sensor de presión mide la fuerza aplicada sobre una superficie y la convierte en una señal eléctrica'),
('robotica', 'eso', '{3}', 'El microcontrolador ATmega328 es el procesador que utiliza la placa Arduino Uno para ejecutar programas'),
('robotica', 'eso', '{3}', 'La memoria EEPROM permite almacenar datos de forma permanente incluso cuando se desconecta la alimentación'),
('robotica', 'eso', '{3}', 'Un robot cartesiano se mueve en los tres ejes X Y Z usando guías lineales y motores paso a paso'),
('robotica', 'eso', '{3}', 'El modelado paramétrico define las piezas 3D usando medidas y restricciones que se pueden modificar fácilmente'),
('robotica', 'eso', '{3}', 'Un bus de comunicación SPI permite intercambiar datos a alta velocidad entre el microcontrolador y los periféricos'),
('robotica', 'eso', '{3}', 'La placa Raspberry Pi funciona como un ordenador completo capaz de ejecutar un sistema operativo Linux'),
('robotica', 'eso', '{3}', 'Un sistema de localización GPS determina la posición del robot en coordenadas de latitud y longitud'),
('robotica', 'eso', '{3}', 'La topología de red en estrella conecta todos los dispositivos a un nodo central que gestiona la comunicación'),
('robotica', 'eso', '{3}', 'El protocolo de comunicación serial UART transmite datos bit a bit entre dos dispositivos conectados por cable'),
('robotica', 'eso', '{3}', 'Un robot delta utiliza tres brazos paralelos para mover su efector final con gran velocidad y precisión'),
('robotica', 'eso', '{3}', 'La realimentación negativa corrige automáticamente las desviaciones del sistema para mantener el valor objetivo'),
('robotica', 'eso', '{3}', 'Un puente de Wheatstone mide con precisión resistencias desconocidas comparándolas con valores de referencia'),
('robotica', 'eso', '{3}', 'La energía cinética del robot depende de su masa y de la velocidad a la que se desplaza'),
('robotica', 'eso', '{3}', 'Un encoder incremental genera pulsos que permiten calcular la velocidad y la dirección del movimiento'),
('robotica', 'eso', '{3}', 'La calibración del sensor ajusta sus lecturas para que coincidan con los valores reales medidos con instrumentos'),
('robotica', 'eso', '{3}', 'Un robot SCARA tiene articulaciones horizontales ideales para tareas de montaje y empaquetado en la industria'),
('robotica', 'eso', '{3}', 'La simulación con software como Tinkercad permite probar circuitos virtualmente antes de montarlos con componentes reales'),
('robotica', 'eso', '{3}', 'El análisis de fallos ayuda a identificar las causas de los errores del robot para evitar que se repitan'),
('robotica', 'eso', '{3}', 'Un amplificador operacional aumenta la señal débil de un sensor para que el microcontrolador pueda leerla correctamente'),
('robotica', 'eso', '{3}', 'La eficiencia energética del robot se mejora reduciendo el peso optimizando el código y usando componentes de bajo consumo'),
('robotica', 'eso', '{3}', 'Un detector de metales usa una bobina que genera un campo magnético para encontrar objetos metálicos enterrados'),
('robotica', 'eso', '{3}', 'La programación orientada a eventos responde a señales externas como la pulsación de un botón o una lectura del sensor'),
('robotica', 'eso', '{3}', 'Un sistema embebido es un ordenador especializado integrado dentro de un dispositivo electrónico mayor'),
('robotica', 'eso', '{3}', 'El bus CAN se usa en automoción para que los diferentes sistemas del vehículo se comuniquen entre sí'),
('robotica', 'eso', '{3}', 'La electrónica de potencia gestiona corrientes altas para controlar motores industriales y calefactores'),
('robotica', 'eso', '{3}', 'Un oscilador de cristal proporciona la señal de reloj precisa que necesita el microcontrolador para funcionar'),
('robotica', 'eso', '{3}', 'La redundancia de sensores mejora la fiabilidad del sistema usando varios sensores para medir lo mismo'),
('robotica', 'eso', '{3}', 'Un filtro paso bajo elimina las señales de alta frecuencia y deja pasar solo las variaciones lentas del sensor'),
('robotica', 'eso', '{3}', 'La robótica agrícola utiliza tractores autónomos y drones para optimizar el cultivo y reducir el uso de agua'),
('robotica', 'eso', '{3}', 'El mantenimiento preventivo revisa periódicamente los componentes del robot para anticipar posibles averías');

-- Robótica 4º ESO (60 frases nuevas)
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('robotica', 'eso', '{4}', 'Una red neuronal convolucional procesa imágenes para que el robot pueda reconocer objetos y rostros humanos'),
('robotica', 'eso', '{4}', 'El aprendizaje por refuerzo entrena al robot premiando las acciones correctas y penalizando las incorrectas'),
('robotica', 'eso', '{4}', 'Un dron multirrotor utiliza cuatro o más hélices para elevarse y desplazarse en cualquier dirección'),
('robotica', 'eso', '{4}', 'El controlador de vuelo del dron procesa los datos del giroscopio y acelerómetro para mantener la estabilidad'),
('robotica', 'eso', '{4}', 'La planificación de trayectorias calcula la ruta óptima para que el robot llegue a su destino evitando obstáculos'),
('robotica', 'eso', '{4}', 'El algoritmo SLAM permite al robot crear un mapa del entorno mientras se localiza dentro de él simultáneamente'),
('robotica', 'eso', '{4}', 'La fusión de sensores combina datos de múltiples fuentes para obtener una medición más precisa y fiable'),
('robotica', 'eso', '{4}', 'Un sistema de reconocimiento de voz permite controlar el robot mediante comandos hablados en lenguaje natural'),
('robotica', 'eso', '{4}', 'La cinemática inversa calcula los ángulos de cada articulación para que el efector alcance una posición deseada'),
('robotica', 'eso', '{4}', 'Un actuador piezoeléctrico produce movimientos muy pequeños y precisos al aplicarle una tensión eléctrica'),
('robotica', 'eso', '{4}', 'La plataforma ROS facilita el desarrollo de software robótico proporcionando librerías y herramientas estandarizadas'),
('robotica', 'eso', '{4}', 'Un brazo robótico industrial de seis ejes puede alcanzar cualquier punto de su espacio de trabajo'),
('robotica', 'eso', '{4}', 'La computación de borde procesa los datos cerca del sensor reduciendo la latencia de la respuesta del robot'),
('robotica', 'eso', '{4}', 'El procesamiento de imágenes con OpenCV permite al robot detectar contornos colores y patrones en tiempo real'),
('robotica', 'eso', '{4}', 'Un sistema multiagente coordina varios robots autónomos para completar una tarea de forma cooperativa'),
('robotica', 'eso', '{4}', 'La impresión 3D en metal permite fabricar piezas funcionales de alta resistencia para robots industriales'),
('robotica', 'eso', '{4}', 'El gemelo digital replica virtualmente el robot físico para simular su comportamiento antes de actuar'),
('robotica', 'eso', '{4}', 'Un exoesqueleto robótico amplifica la fuerza del usuario permitiéndole levantar cargas pesadas sin esfuerzo'),
('robotica', 'eso', '{4}', 'La robótica blanda utiliza materiales flexibles que se deforman para adaptarse a objetos frágiles o irregulares'),
('robotica', 'eso', '{4}', 'Un sensor Lidar mide distancias mediante pulsos láser y crea nubes de puntos tridimensionales del entorno'),
('robotica', 'eso', '{4}', 'La visión estéreo usa dos cámaras separadas para calcular la profundidad de los objetos como hacen nuestros ojos'),
('robotica', 'eso', '{4}', 'El aprendizaje profundo o deep learning utiliza redes neuronales con muchas capas para tareas complejas'),
('robotica', 'eso', '{4}', 'Un sistema de navegación autónoma combina GPS sensores inerciales y visión artificial para desplazarse solo'),
('robotica', 'eso', '{4}', 'La robótica quirúrgica permite realizar operaciones con mayor precisión y menores incisiones que la cirugía manual'),
('robotica', 'eso', '{4}', 'El protocolo MQTT gestiona la comunicación ligera entre dispositivos IoT con un modelo de publicación y suscripción'),
('robotica', 'eso', '{4}', 'Un microcontrolador de 32 bits ofrece mayor capacidad de cálculo que uno de 8 bits para tareas complejas'),
('robotica', 'eso', '{4}', 'La inteligencia artificial generativa puede diseñar estructuras mecánicas optimizadas que un humano no imaginaría'),
('robotica', 'eso', '{4}', 'El mantenimiento predictivo usa sensores e inteligencia artificial para anticipar averías antes de que ocurran'),
('robotica', 'eso', '{4}', 'Un vehículo autónomo combina cámaras radar y Lidar para conducir de forma segura sin intervención humana'),
('robotica', 'eso', '{4}', 'La fabricación aditiva construye piezas añadiendo material capa a capa en lugar de mecanizar un bloque sólido'),
('robotica', 'eso', '{4}', 'Un robot humanoide social interactúa con personas mediante expresiones faciales gestos y lenguaje hablado'),
('robotica', 'eso', '{4}', 'La ciberseguridad en robótica protege los sistemas conectados contra ataques que podrían tomar el control del robot'),
('robotica', 'eso', '{4}', 'El edge computing reduce la dependencia de la nube procesando datos críticos directamente en el dispositivo'),
('robotica', 'eso', '{4}', 'Un enjambre robótico distribuye tareas entre muchos robots simples que cooperan para lograr objetivos complejos'),
('robotica', 'eso', '{4}', 'La transferencia de aprendizaje permite reutilizar un modelo entrenado para una tarea en otra tarea similar'),
('robotica', 'eso', '{4}', 'Un sensor de fuerza y par mide las fuerzas de contacto para que el robot manipule objetos con delicadeza'),
('robotica', 'eso', '{4}', 'La regulación europea sobre inteligencia artificial clasifica los sistemas por niveles de riesgo para proteger a los ciudadanos'),
('robotica', 'eso', '{4}', 'Un dron de ala fija tiene mayor autonomía de vuelo que un multirrotor pero no puede mantenerse estático'),
('robotica', 'eso', '{4}', 'La fotogrametría con drones crea modelos tridimensionales del terreno a partir de múltiples fotografías aéreas'),
('robotica', 'eso', '{4}', 'El aprendizaje no supervisado encuentra patrones ocultos en los datos sin necesidad de etiquetas previas'),
('robotica', 'eso', '{4}', 'Un sistema de recarga inalámbrica permite al robot cargar su batería por inducción sin conectar cables'),
('robotica', 'eso', '{4}', 'La biomecánica inspira el diseño de prótesis robóticas que imitan el movimiento natural de las extremidades humanas'),
('robotica', 'eso', '{4}', 'El protocolo WebSocket permite la comunicación bidireccional en tiempo real entre el robot y una interfaz web'),
('robotica', 'eso', '{4}', 'Un motor lineal produce desplazamiento recto directo sin necesidad de convertir movimiento rotatorio'),
('robotica', 'eso', '{4}', 'La computación cuántica promete resolver en segundos problemas de optimización que tardarían años en ordenadores clásicos'),
('robotica', 'eso', '{4}', 'Un robot de inspección examina infraestructuras como puentes tuberías y líneas eléctricas en zonas de difícil acceso'),
('robotica', 'eso', '{4}', 'La economía circular en robótica promueve el reciclaje de componentes electrónicos y la reparabilidad del hardware'),
('robotica', 'eso', '{4}', 'Un sistema de localización por balizas UWB ofrece posicionamiento interior de alta precisión para robots en edificios'),
('robotica', 'eso', '{4}', 'La ética de la inteligencia artificial debate los límites de la autonomía de las máquinas en la sociedad'),
('robotica', 'eso', '{4}', 'El diseño centrado en el usuario garantiza que los robots sean intuitivos seguros y accesibles para todas las personas'),
('robotica', 'eso', '{4}', 'Un controlador difuso toma decisiones basándose en reglas lingüísticas como mucho poco o suficiente'),
('robotica', 'eso', '{4}', 'La telepresencia robótica permite participar en reuniones o visitar lugares remotos mediante un robot con cámara'),
('robotica', 'eso', '{4}', 'Un sensor capacitivo detecta la proximidad de objetos y personas sin necesidad de contacto físico directo'),
('robotica', 'eso', '{4}', 'La robótica espacial desarrolla vehículos autónomos capaces de explorar la superficie de otros planetas'),
('robotica', 'eso', '{4}', 'El aprendizaje federado entrena modelos de inteligencia artificial distribuyendo el cálculo entre múltiples dispositivos'),
('robotica', 'eso', '{4}', 'Un actuador de aleación con memoria de forma cambia su geometría al calentarse y recupera su forma al enfriarse'),
('robotica', 'eso', '{4}', 'La normativa de seguridad ISO 10218 establece los requisitos para el uso seguro de robots industriales'),
('robotica', 'eso', '{4}', 'El análisis del ciclo de vida evalúa el impacto ambiental del robot desde la fabricación hasta su reciclaje'),
('robotica', 'eso', '{4}', 'Un robot colaborativo avanzado detecta la intención del operario y adapta su velocidad para evitar accidentes'),
('robotica', 'eso', '{4}', 'La innovación tecnológica responsable busca que los avances en robótica beneficien a toda la sociedad de forma equitativa');
