-- =============================================================================
-- SEED: Frases en francés para "Ordena la Frase" — ESO
-- Total: 224 frases nuevas (14 + 45 + 80 + 85)
-- =============================================================================

-- =============================================================================
-- 1º ESO (A1 básico) — 14 frases nuevas
-- Temas: presentarse, familia, colegio, colores, números
-- =============================================================================
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('frances', 'eso', '{1}', 'Je m''appelle Marie et j''habite à Madrid avec ma famille'),
('frances', 'eso', '{1}', 'Ma mère travaille dans une école près de la maison'),
('frances', 'eso', '{1}', 'Mon père a quarante-trois ans et il est très gentil'),
('frances', 'eso', '{1}', 'J''ai un petit frère qui s''appelle Lucas et une grande sœur'),
('frances', 'eso', '{1}', 'Dans ma trousse il y a trois crayons rouges et une gomme'),
('frances', 'eso', '{1}', 'La salle de classe a vingt-cinq chaises et un grand tableau'),
('frances', 'eso', '{1}', 'Nous avons cours de mathématiques le lundi et le mercredi matin'),
('frances', 'eso', '{1}', 'Mon cartable est bleu et celui de mon amie est jaune'),
('frances', 'eso', '{1}', 'Le numéro de ma maison est le trente-sept dans cette rue'),
('frances', 'eso', '{1}', 'Ma grand-mère cuisine un gâteau au chocolat tous les dimanches'),
('frances', 'eso', '{1}', 'Il y a douze mois dans une année et sept jours par semaine'),
('frances', 'eso', '{1}', 'Je prends le petit déjeuner avec du lait et des céréales'),
('frances', 'eso', '{1}', 'Mes parents parlent espagnol à la maison mais je veux parler français'),
('frances', 'eso', '{1}', 'La cour de récréation est grande et nous jouons au ballon');

-- =============================================================================
-- 2º ESO (A1-A2) — 45 frases nuevas
-- Temas: passé composé, hobbies, viajes, alimentación, comparativos
-- =============================================================================
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('frances', 'eso', '{2}', 'Hier j''ai mangé une salade verte et un morceau de poulet grillé'),
('frances', 'eso', '{2}', 'Nous sommes allés à la plage pendant les vacances d''été dernier'),
('frances', 'eso', '{2}', 'Elle a acheté un beau cadeau pour l''anniversaire de son frère'),
('frances', 'eso', '{2}', 'Ils ont visité le musée du Louvre et ils ont vu la Joconde'),
('frances', 'eso', '{2}', 'Tu as fait tes devoirs de français avant de sortir avec tes amis'),
('frances', 'eso', '{2}', 'Le week-end dernier nous avons joué au football dans le parc'),
('frances', 'eso', '{2}', 'J''ai pris le train pour aller chez mes grands-parents à Lyon'),
('frances', 'eso', '{2}', 'Mon hobby préféré est la natation car j''adore nager en été'),
('frances', 'eso', '{2}', 'Elle joue de la guitare depuis trois ans et elle progresse beaucoup'),
('frances', 'eso', '{2}', 'Nous aimons regarder des films français avec des sous-titres en espagnol'),
('frances', 'eso', '{2}', 'Le dimanche je fais du vélo avec mon père dans la campagne'),
('frances', 'eso', '{2}', 'Il collectionne des timbres de tous les pays du monde entier'),
('frances', 'eso', '{2}', 'Pendant les vacances nous avons campé dans une forêt près de la rivière'),
('frances', 'eso', '{2}', 'L''avion est parti à huit heures du matin vers la ville de Marseille'),
('frances', 'eso', '{2}', 'Nous avons réservé une chambre d''hôtel avec vue sur la mer bleue'),
('frances', 'eso', '{2}', 'Il a voyagé en Italie avec sa famille et il a adoré Rome'),
('frances', 'eso', '{2}', 'J''ai visité un château magnifique dans la vallée de la Loire cet été'),
('frances', 'eso', '{2}', 'Pour le dîner je voudrais une soupe de légumes et du pain frais'),
('frances', 'eso', '{2}', 'Au marché on peut acheter des fruits frais et des légumes de saison'),
('frances', 'eso', '{2}', 'Elle préfère le jus d''orange au café parce que c''est plus sain'),
('frances', 'eso', '{2}', 'Le boulanger prépare des croissants chauds et des baguettes chaque matin'),
('frances', 'eso', '{2}', 'Nous avons goûté une tarte aux pommes délicieuse chez la voisine'),
('frances', 'eso', '{2}', 'Il faut manger cinq portions de fruits et légumes par jour'),
('frances', 'eso', '{2}', 'La pizza est plus grande que le sandwich mais moins chère que le steak'),
('frances', 'eso', '{2}', 'Mon frère est plus grand que moi mais je suis plus rapide'),
('frances', 'eso', '{2}', 'Cette ville est aussi belle que Paris mais elle est moins touristique'),
('frances', 'eso', '{2}', 'Le français est plus difficile que l''anglais mais c''est une belle langue'),
('frances', 'eso', '{2}', 'Ma chambre est plus petite que celle de ma sœur mais plus lumineuse'),
('frances', 'eso', '{2}', 'Le bus est moins rapide que le métro pour aller au centre-ville'),
('frances', 'eso', '{2}', 'J''ai lu un livre très intéressant sur les aventures d''un jeune explorateur'),
('frances', 'eso', '{2}', 'Nous avons écouté une chanson française très populaire à la radio hier'),
('frances', 'eso', '{2}', 'Elle est allée au supermarché pour acheter du lait et du beurre'),
('frances', 'eso', '{2}', 'Ils ont dansé toute la soirée à la fête de fin d''année'),
('frances', 'eso', '{2}', 'Tu es arrivé en retard parce que le bus avait du retard ce matin'),
('frances', 'eso', '{2}', 'Après le cours de sport nous avons bu de l''eau et mangé des fruits'),
('frances', 'eso', '{2}', 'Ma meilleure amie m''a offert un bracelet pour mon anniversaire en mars'),
('frances', 'eso', '{2}', 'Le professeur a corrigé nos examens et les résultats sont très bons'),
('frances', 'eso', '{2}', 'Je suis allé au cinéma avec mes cousins pour voir un film comique'),
('frances', 'eso', '{2}', 'Nous avons appris une nouvelle recette de crêpes avec du Nutella et des fraises'),
('frances', 'eso', '{2}', 'Il a neigé toute la nuit et ce matin les rues sont blanches'),
('frances', 'eso', '{2}', 'Le restaurant italien est meilleur que le restaurant chinois de notre quartier'),
('frances', 'eso', '{2}', 'Samedi prochain nous allons faire les courses au grand centre commercial'),
('frances', 'eso', '{2}', 'J''ai découvert un nouveau jeu vidéo qui est très amusant et éducatif'),
('frances', 'eso', '{2}', 'Ma tante habite à Bordeaux et elle nous invite chaque été chez elle'),
('frances', 'eso', '{2}', 'Les crêpes bretonnes sont les meilleures de toute la gastronomie française');

-- =============================================================================
-- 3º ESO (A2) — 80 frases nuevas
-- Temas: imparfait, futur simple, pronoms relatifs, medioambiente, cultura francesa
-- =============================================================================
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('frances', 'eso', '{3}', 'Quand j''étais petit je jouais dans le jardin avec mon chien tous les jours'),
('frances', 'eso', '{3}', 'Avant nous habitions dans un appartement mais maintenant nous avons une maison'),
('frances', 'eso', '{3}', 'Ma grand-mère racontait toujours des histoires passionnantes avant de dormir'),
('frances', 'eso', '{3}', 'Il faisait très chaud cet été-là et nous allions souvent à la piscine'),
('frances', 'eso', '{3}', 'Quand elle était jeune ma mère voyageait souvent en France avec ses parents'),
('frances', 'eso', '{3}', 'Les enfants couraient dans le parc pendant que les parents discutaient tranquillement'),
('frances', 'eso', '{3}', 'Autrefois les gens écrivaient des lettres mais aujourd''hui ils envoient des messages'),
('frances', 'eso', '{3}', 'Je lisais un roman quand soudain le téléphone a sonné dans la cuisine'),
('frances', 'eso', '{3}', 'Nous regardions la télévision tous les soirs après avoir fini nos devoirs'),
('frances', 'eso', '{3}', 'Il pleuvait beaucoup ce jour-là et les rues étaient complètement inondées'),
('frances', 'eso', '{3}', 'L''année prochaine je voyagerai en France pour améliorer mon niveau de français'),
('frances', 'eso', '{3}', 'Nous visiterons les châteaux de la Loire pendant les prochaines vacances de printemps'),
('frances', 'eso', '{3}', 'Tu finiras tes études dans quatre ans et tu pourras travailler ensuite'),
('frances', 'eso', '{3}', 'Ils construiront un nouveau parc écologique dans notre quartier l''année prochaine'),
('frances', 'eso', '{3}', 'Elle deviendra médecin quand elle aura terminé ses études à l''université'),
('frances', 'eso', '{3}', 'Le gouvernement investira davantage dans les énergies renouvelables à l''avenir'),
('frances', 'eso', '{3}', 'Nous organiserons une fête de fin d''année pour célébrer nos réussites ensemble'),
('frances', 'eso', '{3}', 'Il fera probablement beau demain et nous pourrons aller à la montagne'),
('frances', 'eso', '{3}', 'Les scientifiques découvriront peut-être un remède contre cette maladie très bientôt'),
('frances', 'eso', '{3}', 'Dans dix ans les voitures électriques remplaceront les voitures à essence partout'),
('frances', 'eso', '{3}', 'La fille qui porte une jupe bleue est la meilleure élève de la classe'),
('frances', 'eso', '{3}', 'Le livre que j''ai lu la semaine dernière parle de l''histoire de France'),
('frances', 'eso', '{3}', 'La ville où je suis né se trouve dans le sud de l''Espagne'),
('frances', 'eso', '{3}', 'L''homme dont je t''ai parlé hier est un célèbre écrivain français contemporain'),
('frances', 'eso', '{3}', 'La raison pour laquelle il étudie le français est qu''il veut vivre à Paris'),
('frances', 'eso', '{3}', 'Le professeur avec qui nous avons parlé est spécialiste de la littérature française'),
('frances', 'eso', '{3}', 'L''école dans laquelle j''étudie offre des cours de français et d''allemand'),
('frances', 'eso', '{3}', 'Le film que nous avons regardé hier soir a gagné un prix international'),
('frances', 'eso', '{3}', 'La chanteuse dont les chansons sont très populaires donnera un concert à Madrid'),
('frances', 'eso', '{3}', 'Le moment où il a marqué le but tout le stade s''est levé'),
('frances', 'eso', '{3}', 'Il faut protéger l''environnement pour que les générations futures puissent vivre bien'),
('frances', 'eso', '{3}', 'Le réchauffement climatique est un problème grave qui affecte toute la planète'),
('frances', 'eso', '{3}', 'Nous devons recycler le plastique le verre et le papier pour réduire la pollution'),
('frances', 'eso', '{3}', 'Les forêts tropicales disparaissent à cause de la déforestation et de l''agriculture intensive'),
('frances', 'eso', '{3}', 'L''eau potable est une ressource précieuse que nous devons économiser chaque jour'),
('frances', 'eso', '{3}', 'Les panneaux solaires permettent de produire de l''électricité sans polluer l''atmosphère'),
('frances', 'eso', '{3}', 'La biodiversité est menacée par la destruction des habitats naturels dans le monde'),
('frances', 'eso', '{3}', 'Chaque citoyen peut contribuer à la protection de l''environnement avec des gestes simples'),
('frances', 'eso', '{3}', 'Les transports en commun polluent moins que les voitures individuelles en ville'),
('frances', 'eso', '{3}', 'Il est important de réduire notre consommation d''énergie pour limiter les émissions de gaz'),
('frances', 'eso', '{3}', 'La Tour Eiffel a été construite en mille huit cent quatre-vingt-neuf pour l''Exposition universelle'),
('frances', 'eso', '{3}', 'Le fromage et le vin sont deux symboles très importants de la culture française'),
('frances', 'eso', '{3}', 'La fête nationale française est célébrée le quatorze juillet avec des feux d''artifice'),
('frances', 'eso', '{3}', 'Le musée d''Orsay à Paris expose des œuvres impressionnistes de Monet et Renoir'),
('frances', 'eso', '{3}', 'La baguette française a été inscrite au patrimoine culturel immatériel de l''humanité'),
('frances', 'eso', '{3}', 'Le Festival de Cannes réunit chaque année les meilleurs cinéastes du monde entier'),
('frances', 'eso', '{3}', 'La cuisine française est considérée comme l''une des meilleures du monde entier'),
('frances', 'eso', '{3}', 'Victor Hugo a écrit des romans célèbres comme Notre-Dame de Paris au dix-neuvième siècle'),
('frances', 'eso', '{3}', 'Les Français célèbrent la Chandeleur en mangeant des crêpes le deux février'),
('frances', 'eso', '{3}', 'Le château de Versailles est un monument historique visité par des millions de touristes'),
('frances', 'eso', '{3}', 'Pendant que je faisais mes devoirs mon frère jouait de la guitare dans sa chambre'),
('frances', 'eso', '{3}', 'Elle a réussi son examen parce qu''elle avait étudié pendant plusieurs semaines'),
('frances', 'eso', '{3}', 'Si nous avons le temps demain nous irons nous promener au bord du fleuve'),
('frances', 'eso', '{3}', 'Il m''a dit qu''il viendrait à la fête si ses parents lui donnaient la permission'),
('frances', 'eso', '{3}', 'Après avoir terminé le repas nous sommes sortis faire une promenade dans le quartier'),
('frances', 'eso', '{3}', 'Bien que le temps soit mauvais nous avons décidé de faire une randonnée'),
('frances', 'eso', '{3}', 'La pollution des océans met en danger la vie de nombreuses espèces marines'),
('frances', 'eso', '{3}', 'Les éoliennes sont une source d''énergie renouvelable de plus en plus utilisée'),
('frances', 'eso', '{3}', 'Le développement durable cherche à satisfaire les besoins du présent sans compromettre l''avenir'),
('frances', 'eso', '{3}', 'La Méditerranée est une mer qui baigne les côtes de la France et de l''Espagne'),
('frances', 'eso', '{3}', 'Les Alpes françaises attirent des milliers de skieurs pendant la saison d''hiver'),
('frances', 'eso', '{3}', 'Antoine de Saint-Exupéry a écrit Le Petit Prince qui est traduit en de nombreuses langues'),
('frances', 'eso', '{3}', 'La francophonie regroupe tous les pays du monde où l''on parle la langue française'),
('frances', 'eso', '{3}', 'Les marchés provençaux sont célèbres pour leurs olives leur lavande et leurs épices'),
('frances', 'eso', '{3}', 'Le système scolaire français est différent du système éducatif espagnol sur plusieurs points'),
('frances', 'eso', '{3}', 'Autrefois les gens n''avaient pas Internet et ils cherchaient les informations dans les encyclopédies'),
('frances', 'eso', '{3}', 'Je me souviens que quand j''étais enfant nous passions les étés chez mes cousins'),
('frances', 'eso', '{3}', 'L''année prochaine les élèves participeront à un échange scolaire avec un lycée de Bordeaux'),
('frances', 'eso', '{3}', 'Tu devras choisir entre le français et l''allemand comme deuxième langue étrangère'),
('frances', 'eso', '{3}', 'Le professeur dont les cours sont les plus intéressants enseigne l''histoire et la géographie'),
('frances', 'eso', '{3}', 'C''est la première fois que je visite un pays francophone et je suis très content'),
('frances', 'eso', '{3}', 'La réduction des déchets plastiques est un objectif prioritaire pour les prochaines décennies'),
('frances', 'eso', '{3}', 'Grâce aux nouvelles technologies nous pouvons communiquer avec des personnes du monde entier'),
('frances', 'eso', '{3}', 'Le Petit Prince demande au narrateur de lui dessiner un mouton dans le désert'),
('frances', 'eso', '{3}', 'Les crêpes se préparent avec de la farine des œufs du lait et du beurre'),
('frances', 'eso', '{3}', 'La Seine traverse la ville de Paris et passe sous de nombreux ponts historiques'),
('frances', 'eso', '{3}', 'Mon correspondant français m''a envoyé une lettre pour me raconter sa vie quotidienne'),
('frances', 'eso', '{3}', 'Quand il faisait beau nous nous promenions le long de la côte atlantique'),
('frances', 'eso', '{3}', 'Les jeunes Français aiment écouter de la musique et sortir avec leurs amis le week-end'),
('frances', 'eso', '{3}', 'Il est nécessaire de trier les déchets pour protéger notre planète et ses ressources');

-- =============================================================================
-- 4º ESO (A2-B1) — 85 frases nuevas
-- Temas: subjonctif, conditionnel, argumentation, littérature, société
-- =============================================================================
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('frances', 'eso', '{4}', 'Il faut que nous fassions des efforts pour réduire notre empreinte carbone quotidienne'),
('frances', 'eso', '{4}', 'Je souhaite que mes parents comprennent l''importance de voyager à l''étranger'),
('frances', 'eso', '{4}', 'Il est nécessaire que chaque élève puisse s''exprimer librement pendant les débats en classe'),
('frances', 'eso', '{4}', 'Bien qu''il soit fatigué il continue de travailler sur son projet de recherche'),
('frances', 'eso', '{4}', 'Le professeur veut que nous lisions au moins trois romans français cette année'),
('frances', 'eso', '{4}', 'Il est possible que le changement climatique provoque des catastrophes naturelles plus fréquentes'),
('frances', 'eso', '{4}', 'Je doute que cette solution soit suffisante pour résoudre le problème de la pollution'),
('frances', 'eso', '{4}', 'Il est important que les jeunes prennent conscience de leurs responsabilités envers la société'),
('frances', 'eso', '{4}', 'Avant que tu partes il faut que tu finisses de ranger ta chambre'),
('frances', 'eso', '{4}', 'Pour que le projet réussisse il faut que tous les membres de l''équipe collaborent'),
('frances', 'eso', '{4}', 'Si j''avais plus de temps libre je voyagerais dans tous les pays francophones'),
('frances', 'eso', '{4}', 'Si nous étions riches nous construirions des écoles dans les pays en développement'),
('frances', 'eso', '{4}', 'Elle aimerait devenir diplomate pour travailler dans les relations internationales un jour'),
('frances', 'eso', '{4}', 'Si tu étudiais davantage tu pourrais obtenir de meilleures notes aux examens'),
('frances', 'eso', '{4}', 'Nous voudrions organiser un voyage scolaire à Paris pour visiter les musées et monuments'),
('frances', 'eso', '{4}', 'Si les gouvernements investissaient dans l''éducation le monde serait un meilleur endroit'),
('frances', 'eso', '{4}', 'J''aurais aimé assister au concert de musique classique à l''Opéra de Paris'),
('frances', 'eso', '{4}', 'Il aurait fallu prendre le métro au lieu du taxi pour éviter les embouteillages'),
('frances', 'eso', '{4}', 'Si elle avait su la vérité elle aurait pris une décision complètement différente'),
('frances', 'eso', '{4}', 'Nous aurions pu arriver à l''heure si le train n''avait pas eu de retard'),
('frances', 'eso', '{4}', 'D''une part les réseaux sociaux facilitent la communication mais d''autre part ils créent des dépendances'),
('frances', 'eso', '{4}', 'En premier lieu il faut analyser les causes du problème avant de proposer des solutions'),
('frances', 'eso', '{4}', 'Par conséquent les citoyens doivent participer activement à la vie démocratique de leur pays'),
('frances', 'eso', '{4}', 'Néanmoins certains experts affirment que la situation pourrait s''améliorer dans les prochaines années'),
('frances', 'eso', '{4}', 'En conclusion la coopération internationale est essentielle pour faire face aux défis du monde actuel'),
('frances', 'eso', '{4}', 'Toutefois il ne faut pas oublier que chaque individu peut contribuer au changement social'),
('frances', 'eso', '{4}', 'De plus les nouvelles technologies offrent des opportunités inédites pour l''apprentissage des langues étrangères'),
('frances', 'eso', '{4}', 'En revanche l''utilisation excessive des écrans peut avoir des conséquences négatives sur la santé'),
('frances', 'eso', '{4}', 'Autrement dit la liberté d''expression est un droit fondamental dans toute société démocratique'),
('frances', 'eso', '{4}', 'Il est indéniable que la diversité culturelle enrichit notre société de manière significative'),
('frances', 'eso', '{4}', 'Albert Camus explore le thème de l''absurde dans son roman L''Étranger publié en mille neuf cent quarante-deux'),
('frances', 'eso', '{4}', 'Les fables de La Fontaine utilisent des animaux pour critiquer les défauts de la société'),
('frances', 'eso', '{4}', 'Molière est considéré comme le plus grand auteur de comédies de la littérature française'),
('frances', 'eso', '{4}', 'Le mouvement romantique en France a mis l''accent sur les émotions et la nature'),
('frances', 'eso', '{4}', 'Dans Germinal Zola dénonce les conditions de vie terribles des mineurs au dix-neuvième siècle'),
('frances', 'eso', '{4}', 'Baudelaire a révolutionné la poésie française avec son recueil Les Fleurs du Mal en 1857'),
('frances', 'eso', '{4}', 'Le théâtre classique français respectait les trois unités de temps de lieu et d''action'),
('frances', 'eso', '{4}', 'Marcel Proust est célèbre pour son œuvre monumentale À la recherche du temps perdu'),
('frances', 'eso', '{4}', 'Les contes de Perrault comme Cendrillon et Le Petit Chaperon Rouge sont connus dans le monde entier'),
('frances', 'eso', '{4}', 'Simone de Beauvoir a contribué de manière décisive au mouvement féministe avec ses écrits philosophiques'),
('frances', 'eso', '{4}', 'L''égalité entre les hommes et les femmes est un principe fondamental des droits de l''homme'),
('frances', 'eso', '{4}', 'La mondialisation a transformé les échanges économiques et culturels entre les pays du monde'),
('frances', 'eso', '{4}', 'Le bénévolat est une activité qui permet aux jeunes de s''engager pour des causes solidaires'),
('frances', 'eso', '{4}', 'Les inégalités sociales restent un défi majeur que les sociétés modernes doivent affronter ensemble'),
('frances', 'eso', '{4}', 'La laïcité est un principe fondateur de la République française depuis la loi de 1905'),
('frances', 'eso', '{4}', 'Les médias jouent un rôle essentiel dans la formation de l''opinion publique des citoyens'),
('frances', 'eso', '{4}', 'L''immigration a contribué à enrichir la diversité culturelle et linguistique de la société française'),
('frances', 'eso', '{4}', 'Le droit à l''éducation est inscrit dans la Déclaration universelle des droits de l''homme'),
('frances', 'eso', '{4}', 'La transition écologique nécessite la participation active de tous les acteurs de la société'),
('frances', 'eso', '{4}', 'Les jeunes d''aujourd''hui sont plus sensibilisés aux problèmes environnementaux que les générations précédentes'),
('frances', 'eso', '{4}', 'Quoique les progrès technologiques soient remarquables ils ne peuvent pas résoudre tous les problèmes'),
('frances', 'eso', '{4}', 'Il serait souhaitable que les pays développés aident les nations les plus vulnérables'),
('frances', 'eso', '{4}', 'Pourvu que nous agissions maintenant il sera encore possible de sauver les espèces en danger'),
('frances', 'eso', '{4}', 'À condition que chacun fasse un effort nous pourrons construire un monde plus juste'),
('frances', 'eso', '{4}', 'Sans que personne ne s''en rende compte les glaciers fondent à une vitesse alarmante'),
('frances', 'eso', '{4}', 'Si j''avais la possibilité de changer quelque chose dans le monde je combattrais la pauvreté'),
('frances', 'eso', '{4}', 'Les habitants des grandes villes souffriraient moins si les transports publics étaient plus efficaces'),
('frances', 'eso', '{4}', 'Il faudrait que les entreprises respectent davantage les normes environnementales pour protéger la planète'),
('frances', 'eso', '{4}', 'Au cas où il pleuvrait demain nous pourrions visiter le musée au lieu du jardin'),
('frances', 'eso', '{4}', 'Même si la situation est difficile nous ne devons jamais perdre l''espoir de réussir'),
('frances', 'eso', '{4}', 'Selon certains sociologues les réseaux sociaux modifient profondément les relations interpersonnelles des adolescents'),
('frances', 'eso', '{4}', 'Force est de constater que le numérique a bouleversé notre façon de travailler et d''apprendre'),
('frances', 'eso', '{4}', 'Il convient de souligner que l''apprentissage d''une langue étrangère développe l''ouverture d''esprit'),
('frances', 'eso', '{4}', 'On ne saurait nier que la lecture régulière améliore considérablement le vocabulaire et l''expression écrite'),
('frances', 'eso', '{4}', 'À supposer que le budget soit suffisant nous organiserions un échange culturel avec un lycée parisien'),
('frances', 'eso', '{4}', 'La Déclaration des droits de l''homme et du citoyen de 1789 a inspiré de nombreuses constitutions'),
('frances', 'eso', '{4}', 'Le système de sécurité sociale français garantit l''accès aux soins médicaux pour tous les citoyens'),
('frances', 'eso', '{4}', 'La gastronomie française a été classée au patrimoine culturel immatériel de l''UNESCO en 2010'),
('frances', 'eso', '{4}', 'Le mouvement des Lumières au dix-huitième siècle a promu la raison et la liberté individuelle'),
('frances', 'eso', '{4}', 'Jean-Jacques Rousseau a influencé la pensée politique moderne avec son Contrat social publié en 1762'),
('frances', 'eso', '{4}', 'Les impressionnistes comme Monet et Degas ont transformé l''art de la peinture au dix-neuvième siècle'),
('frances', 'eso', '{4}', 'La Résistance française pendant la Seconde Guerre mondiale a joué un rôle crucial pour la libération'),
('frances', 'eso', '{4}', 'L''Union européenne a été fondée pour garantir la paix et la coopération entre les nations'),
('frances', 'eso', '{4}', 'Le commerce équitable propose une alternative plus juste aux échanges commerciaux traditionnels entre les pays'),
('frances', 'eso', '{4}', 'L''intelligence artificielle soulève des questions éthiques importantes que la société doit débattre ensemble'),
('frances', 'eso', '{4}', 'La protection des données personnelles est devenue un enjeu majeur à l''ère du numérique'),
('frances', 'eso', '{4}', 'Afin que les élèves progressent le professeur adapte sa pédagogie aux besoins de chacun'),
('frances', 'eso', '{4}', 'Malgré les difficultés économiques les associations caritatives continuent de venir en aide aux plus démunis'),
('frances', 'eso', '{4}', 'En dépit des critiques le projet de loi sur l''environnement a été adopté par l''Assemblée nationale'),
('frances', 'eso', '{4}', 'Tant que nous n''aurons pas changé nos habitudes de consommation la planète continuera de souffrir'),
('frances', 'eso', '{4}', 'Il est regrettable que tant de jeunes abandonnent leurs études avant d''obtenir un diplôme'),
('frances', 'eso', '{4}', 'Voltaire utilisait l''ironie et la satire pour dénoncer l''intolérance et les injustices de son époque'),
('frances', 'eso', '{4}', 'Le naturalisme de Zola cherchait à représenter la réalité sociale de manière scientifique et objective'),
('frances', 'eso', '{4}', 'Les existentialistes comme Sartre affirmaient que l''homme est condamné à être libre et responsable'),
('frances', 'eso', '{4}', 'La francophonie représente un espace culturel et linguistique de plus de trois cents millions de locuteurs');
