-- =====================================================================
-- SEED: Ordena la Historia - Bachillerato (huecos EBAU)
-- Completa las historias que faltaban para alcanzar 50 por asignatura/curso.
-- Total: 125 historias nuevas (todas únicas y distintas a las existentes)
-- Fecha: 2026-04-11
-- =====================================================================

-- ---------------------------------------------------------------------
-- TECNOLOGIA - 1º BACHILLERATO (19 historias)
-- Energías renovables, electrónica, materiales, fabricación, automatización
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('tecnologia', 'bachillerato', '{1}', '["Un colector solar térmico capta la radiación del Sol mediante una placa absorbedora oscura","La placa calienta un fluido caloportador que circula por serpentines en su interior","El fluido caliente cede su energía al agua sanitaria a través de un intercambiador de calor","El agua caliente se almacena en un depósito aislado para el consumo diferido del edificio","Un sistema auxiliar de apoyo calienta el agua cuando la radiación solar resulta insuficiente"]'),
('tecnologia', 'bachillerato', '{1}', '["Una central hidroeléctrica aprovecha la energía potencial del agua embalsada en un pantano","El agua desciende por una tubería forzada ganando velocidad y energía cinética","En la base, el chorro impacta sobre los álabes de una turbina haciéndola girar","Un alternador acoplado al eje transforma el giro en electricidad de corriente alterna","Un transformador eleva la tensión antes de inyectar la energía a la red de transporte"]'),
('tecnologia', 'bachillerato', '{1}', '["La biomasa es materia orgánica de origen vegetal o animal utilizable como combustible","Los residuos forestales y agrícolas se trituran y se convierten en pellets compactos","Los pellets se queman en una caldera especial produciendo calor a alta eficiencia","El calor generado se transfiere al circuito de calefacción y al agua caliente sanitaria","El CO2 emitido forma parte del ciclo corto del carbono haciendo la biomasa neutra en emisiones"]'),
('tecnologia', 'bachillerato', '{1}', '["La energía geotérmica aprovecha el calor procedente del interior de la Tierra","En zonas volcánicas existen yacimientos de vapor a alta temperatura a pocos kilómetros","Se perforan pozos para extraer el vapor que sube por su propia presión natural","El vapor mueve una turbina conectada a un generador eléctrico como en una central térmica","El agua condensada se reinyecta al subsuelo para cerrar el ciclo de forma sostenible"]'),
('tecnologia', 'bachillerato', '{1}', '["La energía mareomotriz transforma el movimiento de las mareas en electricidad útil","Una presa cierra un estuario creando un embalse que se llena durante la pleamar","Cuando baja la marea, el agua almacenada se libera a través de turbinas especiales","Las turbinas bulbo giran en ambos sentidos aprovechando el flujo en las dos direcciones","Los generadores producen electricidad previsible ya que las mareas siguen un ciclo conocido"]'),
('tecnologia', 'bachillerato', '{1}', '["La palanca es una máquina simple formada por una barra rígida y un punto de apoyo","La relación entre fuerza y carga depende de las distancias al fulcro según la ley de la palanca","En la palanca de primer género, el fulcro se sitúa entre la fuerza aplicada y la carga","En la de segundo género, la carga está entre el fulcro y el punto donde aplicamos la fuerza","En la de tercer género, la fuerza se aplica entre el fulcro y la carga como en unas pinzas"]'),
('tecnologia', 'bachillerato', '{1}', '["El plano inclinado reduce la fuerza necesaria para elevar una carga a una altura determinada","La fuerza aplicada disminuye cuanto menor es el ángulo de inclinación del plano","A cambio, debemos recorrer una distancia mayor manteniéndose constante el trabajo realizado","El rendimiento real es inferior al teórico debido al rozamiento entre la carga y la superficie","Este principio se aplica en rampas, tornillos, cuñas y carreteras de montaña en zigzag"]'),
('tecnologia', 'bachillerato', '{1}', '["Una pieza mecánica se mide con instrumentos de metrología según la precisión requerida","El calibre o pie de rey mide longitudes exteriores, interiores y profundidades con décimas de milímetro","El micrómetro de exteriores alcanza una precisión de centésimas mediante un tornillo calibrado","El reloj comparador detecta variaciones muy pequeñas apoyándose sobre una superficie de referencia","Las galgas patrón sirven para calibrar los instrumentos y garantizar la trazabilidad de las medidas"]'),
('tecnologia', 'bachillerato', '{1}', '["La fundición en molde de arena permite fabricar piezas metálicas de geometría compleja","Se construye un modelo de madera con la forma exacta de la pieza que se quiere obtener","El modelo se introduce en arena compactada formando una cavidad al retirarlo del molde","El metal fundido se vierte en la cavidad y se deja enfriar hasta que solidifica","Tras romper el molde, se retira la pieza y se eliminan rebabas y bebederos sobrantes"]'),
('tecnologia', 'bachillerato', '{1}', '["La forja conforma el metal por deformación plástica mediante golpes o presión","Primero se calienta la pieza metálica hasta alcanzar su temperatura de forja adecuada","En estado plástico, el material se golpea con martillos o se prensa en matrices","La deformación afina la estructura interna del metal mejorando sus propiedades mecánicas","La pieza final se enfría controladamente y se mecaniza para obtener las dimensiones definitivas"]'),
('tecnologia', 'bachillerato', '{1}', '["La soldadura TIG utiliza un electrodo de tungsteno no consumible en atmósfera inerte","Un gas protector como argón rodea el electrodo evitando la oxidación del baño de fusión","El arco eléctrico entre el electrodo y la pieza funde los bordes que se quieren unir","Se añade material de aportación manualmente con una varilla cuando es necesario","Este proceso ofrece cordones limpios y precisos en aceros inoxidables, aluminio y titanio"]'),
('tecnologia', 'bachillerato', '{1}', '["Una máquina CNC ejecuta automáticamente operaciones de mecanizado siguiendo un programa","El diseñador crea la geometría de la pieza en un software CAD tridimensional","Un programa CAM genera las trayectorias de herramienta en código G estándar","La máquina interpreta las instrucciones moviendo los ejes con motores servo precisos","El control numérico garantiza piezas idénticas con tolerancias de centésimas de milímetro"]'),
('tecnologia', 'bachillerato', '{1}', '["Los materiales compuestos combinan dos o más materiales para obtener propiedades mejoradas","Una matriz, normalmente plástica, rodea a un refuerzo que aporta la resistencia principal","La fibra de vidrio embebida en resina de poliéster forma un laminado ligero y resistente","La fibra de carbono con resina epoxi se utiliza en aeronáutica y alta competición","Estos materiales ofrecen una relación resistencia-peso muy superior a los metales tradicionales"]'),
('tecnologia', 'bachillerato', '{1}', '["El vidrio se obtiene fundiendo sílice con carbonato sódico y caliza a unos 1500 grados","La mezcla fundida se moldea por soplado, laminado o flotación sobre estaño líquido","Al enfriarse, el vidrio conserva una estructura amorfa sin ordenación cristalina regular","El templado térmico mejora su resistencia mediante enfriamiento rápido y controlado","El vidrio laminado con una lámina de PVB aporta seguridad en parabrisas y cristaleras"]'),
('tecnologia', 'bachillerato', '{1}', '["La madera laminada encolada se fabrica uniendo tablas finas con sus vetas paralelas","Las tablas se seleccionan para eliminar nudos y defectos que reducirían la resistencia","Se aplican adhesivos estructurales y se prensan bajo presión controlada hasta curar","El resultado es una pieza larga y estable capaz de cubrir grandes luces sin deformarse","Se emplea en vigas, pórticos y estructuras singulares donde el acero resultaría excesivo"]'),
('tecnologia', 'bachillerato', '{1}', '["El hormigón armado combina la resistencia a compresión del hormigón con la tracción del acero","Se colocan barras corrugadas de acero en el interior del encofrado antes del vertido","El hormigón fresco rellena el molde envolviendo completamente las armaduras metálicas","Durante el fraguado se produce la adherencia que hace trabajar ambos materiales como uno solo","La dosificación de cemento, áridos y agua determina la resistencia final a los 28 días"]'),
('tecnologia', 'bachillerato', '{1}', '["Una fotorresistencia LDR varía su resistencia eléctrica según la intensidad de luz recibida","En oscuridad, la resistencia alcanza valores del orden de los megaohmios","Con luz intensa, la resistencia cae hasta pocos centenares de ohmios","Conectada en un divisor de tensión, la LDR genera una señal analógica proporcional al nivel lumínico","Este sensor se utiliza en alumbrados automáticos, cámaras fotográficas y detectores crepusculares"]'),
('tecnologia', 'bachillerato', '{1}', '["Un relé electromecánico permite controlar un circuito de potencia con una señal de control pequeña","Una bobina recorrida por corriente crea un campo magnético al alimentarse","El campo atrae una armadura móvil que cierra o abre unos contactos metálicos","Los contactos conmutan cargas de alta intensidad sin poner en peligro el circuito de mando","El diseño proporciona aislamiento galvánico entre el circuito de control y el de potencia"]'),
('tecnologia', 'bachillerato', '{1}', '["Un motor asíncrono trifásico gira por inducción electromagnética sin contacto eléctrico en el rotor","El estátor contiene tres bobinados desfasados 120 grados alimentados por corriente alterna","La corriente crea un campo magnético giratorio a la frecuencia de sincronismo de la red","El campo induce corrientes en el rotor de jaula de ardilla provocando fuerzas tangenciales","El rotor gira ligeramente más despacio que el campo, generando el llamado deslizamiento"]');

-- ---------------------------------------------------------------------
-- HISTORIA DEL MUNDO CONTEMPORANEO - 1º BACHILLERATO (15 historias)
-- Rev. Francesa, Industrialización, WWI, WWII, Guerra Fría, descolonización
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('historia-mundo', 'bachillerato', '{1}', '["El Congreso de Viena se reunió en 1814 para reorganizar Europa tras la caída de Napoleón","Las potencias vencedoras restauraron a las antiguas dinastías legítimas en sus tronos","Metternich diseñó un sistema de equilibrio basado en el principio de intervención conservadora","La Santa Alianza reunió a Rusia, Austria y Prusia para defender el orden tradicional","El nuevo mapa europeo ignoró los sentimientos nacionales y liberales del siglo XIX"]'),
('historia-mundo', 'bachillerato', '{1}', '["La revolución de 1830 en Francia estalló contra el autoritarismo de Carlos X","Las Tres Jornadas Gloriosas de julio derribaron al último rey Borbón absolutista","Luis Felipe de Orleans aceptó una nueva carta constitucional moderadamente liberal","La monarquía burguesa favoreció los intereses de la alta burguesía financiera","La revolución inspiró movimientos similares en Bélgica, Polonia e Italia durante ese mismo año"]'),
('historia-mundo', 'bachillerato', '{1}', '["La Comuna de París se proclamó en marzo de 1871 tras la derrota frente a Prusia","Los obreros parisinos tomaron el control de la ciudad ante el gobierno de Thiers","Adoptaron medidas sociales avanzadas como la autogestión de fábricas abandonadas","El gobierno se refugió en Versalles y organizó la reconquista militar de la capital","La Semana Sangrienta de mayo acabó con miles de communards ejecutados o deportados"]'),
('historia-mundo', 'bachillerato', '{1}', '["La Guerra de Crimea enfrentó a Rusia con una coalición europea entre 1853 y 1856","Francia, Reino Unido y el Imperio Otomano se unieron para frenar la expansión rusa","El conflicto se libró sobre todo en la península de Crimea en torno a Sebastopol","Fue la primera guerra moderna con uso masivo del telégrafo, el ferrocarril y la prensa","La derrota rusa evidenció su atraso industrial y aceleró las reformas del zar Alejandro II"]'),
('historia-mundo', 'bachillerato', '{1}', '["La unificación italiana fue dirigida por el reino de Piamonte-Cerdeña y su primer ministro Cavour","Cavour utilizó la diplomacia y la alianza con Francia para expulsar a Austria del norte peninsular","Garibaldi desembarcó en Sicilia con los mil camisas rojas conquistando el sur del reino borbónico","Los plebiscitos sancionaron la unión de los distintos territorios bajo Víctor Manuel II","Roma se incorporó en 1870 completando la unificación tras la retirada francesa del Vaticano"]'),
('historia-mundo', 'bachillerato', '{1}', '["El Tratado de Versalles de 1919 impuso durísimas condiciones a Alemania como potencia derrotada","Se declaró a Alemania única responsable moral del estallido de la Gran Guerra","Debía pagar gigantescas reparaciones económicas a los países vencedores de la contienda","Perdió sus colonias y territorios europeos como Alsacia, Lorena y el corredor de Danzig","Las humillantes cláusulas alimentaron el resentimiento que desembocaría en el auge del nazismo"]'),
('historia-mundo', 'bachillerato', '{1}', '["Benito Mussolini fundó los Fascios de Combate en Milán en marzo de 1919","Su movimiento combinaba nacionalismo radical, antimarxismo y culto a la violencia callejera","En octubre de 1922 organizó la Marcha sobre Roma presionando al rey Víctor Manuel III","El monarca le encargó formar gobierno evitando así un enfrentamiento armado abierto","Mussolini impuso progresivamente una dictadura totalitaria que suprimió los partidos políticos"]'),
('historia-mundo', 'bachillerato', '{1}', '["Adolf Hitler y el partido nazi se aprovecharon de la crisis económica alemana tras 1929","En las elecciones de 1932 el NSDAP se convirtió en la primera fuerza política del Reichstag","El presidente Hindenburg nombró canciller a Hitler en enero de 1933 para contener la agitación","El incendio del Reichstag sirvió de excusa para suprimir las libertades constitucionales","La muerte de Hindenburg en 1934 permitió a Hitler concentrar todos los poderes como Führer"]'),
('historia-mundo', 'bachillerato', '{1}', '["La crisis de los misiles de Cuba enfrentó a EEUU y la URSS en octubre de 1962","Aviones espía norteamericanos detectaron la instalación de misiles soviéticos en la isla caribeña","Kennedy decretó un bloqueo naval y exigió la retirada inmediata del armamento nuclear","Durante trece días el mundo vivió al borde de una guerra atómica a escala global","Jruschov aceptó retirar los misiles a cambio de que EEUU desmantelase los suyos en Turquía"]'),
('historia-mundo', 'bachillerato', '{1}', '["La Guerra de Vietnam enfrentó al norte comunista contra el sur apoyado por Estados Unidos","EEUU intervino masivamente desde 1965 enviando medio millón de soldados al país asiático","El Vietcong empleó tácticas de guerrilla aprovechando la espesa selva tropical del territorio","La ofensiva del Tet de 1968 demostró que la victoria americana era imposible pese a su poder","En 1975 las tropas del norte tomaron Saigón reunificando Vietnam bajo el régimen comunista"]'),
('historia-mundo', 'bachillerato', '{1}', '["El mayo francés de 1968 comenzó como una protesta estudiantil en la universidad de Nanterre","Las barricadas del Barrio Latino enfrentaron a los jóvenes con la policía del régimen de De Gaulle","La revuelta estudiantil provocó una huelga general que paralizó la economía del país","Los manifestantes exigían cambios culturales, sexuales y políticos frente a la sociedad tradicional","De Gaulle superó la crisis en elecciones anticipadas pero dimitió al año siguiente"]'),
('historia-mundo', 'bachillerato', '{1}', '["El Muro de Berlín se levantó en 1961 para frenar la fuga masiva de alemanes orientales","Durante casi tres décadas separó físicamente las dos mitades de la antigua capital","En noviembre de 1989, la presión popular llevó al gobierno a abrir los pasos fronterizos","Miles de berlineses subieron al muro y comenzaron a derribarlo con sus propias manos","La caída del muro aceleró la reunificación alemana que se completó en octubre de 1990"]'),
('historia-mundo', 'bachillerato', '{1}', '["La Unión Soviética se disolvió oficialmente en diciembre de 1991 tras años de crisis","Las repúblicas bálticas habían declarado su independencia aprovechando la perestroika","Un intento de golpe de Estado conservador en agosto de 1991 fracasó gracias a Yeltsin","Las antiguas repúblicas firmaron los acuerdos de Belavezha disolviendo la URSS","Gorbachov dimitió como presidente y la bandera soviética fue arriada del Kremlin"]'),
('historia-mundo', 'bachillerato', '{1}', '["La protesta de Tiananmen estalló en Pekín en la primavera de 1989","Miles de estudiantes ocuparon la plaza reclamando reformas democráticas al Partido Comunista","Las manifestaciones se extendieron a otras ciudades chinas con apoyo de trabajadores","El gobierno declaró la ley marcial y envió al Ejército Popular contra los manifestantes","La represión del 4 de junio dejó centenares de muertos y cerró cualquier apertura política"]'),
('historia-mundo', 'bachillerato', '{1}', '["Los atentados del 11 de septiembre de 2001 cambiaron la política internacional del nuevo siglo","Diecinueve terroristas de Al Qaeda secuestraron cuatro aviones comerciales en suelo estadounidense","Dos aparatos impactaron contra las Torres Gemelas de Nueva York derribándolas por completo","Un tercer avión chocó contra el Pentágono y el cuarto se estrelló en Pensilvania","La respuesta de EEUU inició la guerra global contra el terrorismo y la invasión de Afganistán"]');

-- ---------------------------------------------------------------------
-- LATIN - 1º BACHILLERATO (14 historias)
-- Morfología, historia romana republicana, mitología
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('latin', 'bachillerato', '{1}', '["La segunda declinación latina agrupa sustantivos con tema en o mayoritariamente masculinos","El nominativo singular termina en -us para los masculinos y en -um para los neutros","El genitivo singular termina siempre en -i siendo la marca más característica de la declinación","Dominus, domini, señor, y bellum, belli, guerra, son dos modelos típicos de esta declinación","Algunos sustantivos como puer o ager pierden la desinencia -us en el nominativo singular"]'),
('latin', 'bachillerato', '{1}', '["La tercera declinación latina es la más numerosa y variada de todas","Agrupa sustantivos con tema en consonante y sustantivos con tema en vocal -i","El nominativo singular presenta formas muy diversas sin desinencia característica","El genitivo singular siempre acaba en -is siendo la marca que identifica la declinación","Rex, regis, rey, y civis, civis, ciudadano, son dos modelos fundamentales de aprendizaje"]'),
('latin', 'bachillerato', '{1}', '["La cuarta declinación latina tiene el tema en -u y contiene pocos sustantivos","El nominativo singular termina en -us para los masculinos y en -u para los neutros","El genitivo singular siempre termina en -us marcando la pertenencia a esta declinación","Manus, manus, mano, es una excepción femenina frecuente y bien atestiguada","Cornu, cornus, cuerno, representa el modelo neutro característico de esta declinación"]'),
('latin', 'bachillerato', '{1}', '["La quinta declinación latina es la menos numerosa y tiene el tema en -e","El nominativo singular termina en -es y el genitivo singular en -ei característicamente","Res, rei, cosa, y dies, diei, día, son los únicos sustantivos usados en todo el plural","La mayoría de los sustantivos de esta declinación son femeninos salvo dies que puede ser masculino","Aparece sobre todo en palabras abstractas como spes, fides y facies"]'),
('latin', 'bachillerato', '{1}', '["El pretérito imperfecto de indicativo latino expresa acciones pasadas habituales o duraderas","Se forma añadiendo al tema de presente la marca temporal -ba- seguida de las desinencias","En la primera conjugación la marca completa es -bam, -bas, -bat, -bamus, -batis, -bant","Amabam significa yo amaba y habeo en imperfecto da habebam o yo tenía","Es el tiempo típico de descripciones y acciones repetidas del pasado en las narraciones"]'),
('latin', 'bachillerato', '{1}', '["El pretérito perfecto de indicativo latino expresa una acción completamente terminada en el pasado","Se forma a partir del tema de perfecto propio de cada verbo latino","Las desinencias son -i, -isti, -it, -imus, -istis, -erunt para todas las conjugaciones","Amavi significa amé o he amado dependiendo del contexto concreto de la frase","Este tiempo corresponde aproximadamente al pretérito perfecto simple del español moderno"]'),
('latin', 'bachillerato', '{1}', '["El pretérito pluscuamperfecto latino expresa una acción pasada anterior a otra también pasada","Se forma sobre el tema de perfecto añadiendo las desinencias -eram, -eras, -erat, -eramus, -eratis, -erant","Amaveram significa yo había amado siguiendo el modelo regular de la primera conjugación","Tiene el mismo valor que el pluscuamperfecto español en oraciones con anterioridad","Aparece con frecuencia en las narraciones históricas de Livio, César y Tácito"]'),
('latin', 'bachillerato', '{1}', '["El futuro imperfecto latino expresa una acción que ocurrirá en un momento posterior","En la primera y segunda conjugación se forma con la marca temporal -bi- característica","Amabo significa yo amaré y habebo significa yo tendré siguiendo este patrón","En la tercera y cuarta conjugación se utilizan desinencias diferentes con vocal -a- o -e-","Legam significa yo leeré y audiam quiere decir yo escucharé en esos grupos verbales"]'),
('latin', 'bachillerato', '{1}', '["El imperativo latino expresa órdenes directas al interlocutor sin marca de persona","El imperativo de presente activo solo tiene formas para la segunda persona singular y plural","La segunda del singular coincide con el tema puro del presente: ama, mone, lege, audi","La segunda del plural añade la desinencia -te al tema: amate, monete, legite, audite","Existe también un imperativo de futuro usado en leyes, máximas y fórmulas solemnes"]'),
('latin', 'bachillerato', '{1}', '["Marte era el dios romano de la guerra y una de las divinidades más antiguas del panteón","Era considerado padre de Rómulo y Remo y por tanto ancestro mítico de los romanos","Los sacerdotes salios danzaban armados en su honor durante el mes que llevaba su nombre","Los romanos le consagraron un campo en las afueras de la ciudad para ejercicios militares","Se identificó parcialmente con el Ares griego pero conservó un carácter más solemne y protector"]'),
('latin', 'bachillerato', '{1}', '["Venus era la diosa romana del amor, la belleza y la fertilidad en la mitología","Los romanos la identificaron con la Afrodita griega adoptando sus mitos principales","Según la leyenda había dado a luz a Eneas padre del linaje de los romanos","La familia Julia afirmaba descender directamente de Venus a través del héroe troyano","Julio César y Augusto le dedicaron templos destacados para legitimar su ascendencia divina"]'),
('latin', 'bachillerato', '{1}', '["Hércules era el héroe romano equivalente al Heracles griego, hijo de Júpiter y Alcmena","Juno le impuso doce trabajos imposibles como castigo a su ira celosa","Mató al león de Nemea estrangulándolo con sus propias manos de forma legendaria","Derrotó a la Hidra de Lerna cortando sus cabezas y cauterizando los muñones","Tras completar sus doce trabajos alcanzó la inmortalidad en el Olimpo junto a los dioses"]'),
('latin', 'bachillerato', '{1}', '["La República romana se organizó políticamente tras la expulsión del rey Tarquinio el Soberbio","El poder ejecutivo recayó en dos cónsules elegidos anualmente por los comicios centuriados","El Senado reunía a los antiguos magistrados como órgano consultivo y depositario de la tradición","Las asambleas del pueblo votaban las leyes y elegían a los distintos magistrados de la ciudad","El cursus honorum establecía la carrera política ascendente por cuestor, edil, pretor y cónsul"]'),
('latin', 'bachillerato', '{1}', '["El conflicto patricio-plebeyo enfrentó a las dos clases de la Roma republicana durante siglos","Los plebeyos reclamaban derechos políticos, civiles y económicos frente al monopolio patricio","En el 494 a.C. protagonizaron la primera secesión retirándose al Monte Sagrado","Obtuvieron el tribunado de la plebe como magistratura exclusivamente plebeya con veto","La Ley Hortensia del 287 a.C. equiparó plenamente las leyes plebiscitarias y cerró el conflicto"]');

-- ---------------------------------------------------------------------
-- LATIN - 2º BACHILLERATO (13 historias)
-- EBAU: Virgilio, Cicerón, Ovidio, Horacio, sintaxis avanzada, subordinadas
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('latin', 'bachillerato', '{2}', '["La Eneida de Virgilio narra en doce libros las aventuras del héroe troyano Eneas","Los seis primeros libros relatan el viaje de Eneas desde Troya hasta las costas del Lacio","En el libro cuarto Dido reina de Cartago se enamora del héroe y se suicida tras su partida","Los seis últimos libros describen las guerras de Eneas contra los pueblos del Lacio","El poema termina con la muerte de Turno y consagra el origen mítico de Roma y de Augusto"]'),
('latin', 'bachillerato', '{2}', '["Cicerón pronunció las Catilinarias en el 63 a.C. siendo cónsul de la República","Lucio Sergio Catilina conspiraba para derrocar al gobierno mediante un levantamiento armado","El primer discurso comienza con la célebre frase: ¿Hasta cuándo abusarás de nuestra paciencia, Catilina?","Los cuatro discursos fueron pronunciados en el Senado y en el foro para denunciar la conjura","Catilina huyó de Roma y murió en batalla mientras sus cómplices fueron ejecutados por orden del Senado"]'),
('latin', 'bachillerato', '{2}', '["César escribió los Comentarios de la Guerra de las Galias en ocho libros entre 58 y 51 a.C.","La obra narra en tercera persona las campañas militares del propio autor en la Galia","El primer libro comienza con la célebre descripción: Galia est omnis divisa in partes tres","El sexto libro incluye un excurso etnográfico sobre las costumbres de galos y germanos","César redactó los Comentarios en un latín claro y directo como propaganda política en Roma"]'),
('latin', 'bachillerato', '{2}', '["Salustio compuso la Conjuración de Catilina como primera monografía histórica latina","Narra los acontecimientos del 63 a.C. recogiendo también los retratos morales de los protagonistas","Presenta a Catilina como símbolo de la decadencia moral de la República romana tardía","Contrapone las figuras antitéticas de Catón el Joven y César como modelos opuestos","Su estilo conciso e incisivo lo distingue claramente de la abundancia ciceroniana anterior"]'),
('latin', 'bachillerato', '{2}', '["Las oraciones subordinadas finales latinas expresan el propósito o fin de la acción principal","Se introducen con la conjunción ut afirmativa o ne cuando son negativas","El verbo subordinado va en modo subjuntivo siguiendo la regla de la consecutio temporum","Veni ut te viderem significa vine para verte en tiempo pasado","Con verbos de movimiento también puede expresarse la finalidad con el gerundivo en acusativo"]'),
('latin', 'bachillerato', '{2}', '["El cum histórico narrativo es una subordinada temporal-causal característica del latín clásico","Se construye con la conjunción cum seguida del verbo en modo subjuntivo imperfecto o pluscuamperfecto","Indica las circunstancias temporales o causales en que se desarrolló la acción principal","Cum Caesar in Galliam venisset significa habiendo llegado César a la Galia","Aparece con enorme frecuencia en las narraciones históricas de Tito Livio y Tácito"]'),
('latin', 'bachillerato', '{2}', '["El ablativo absoluto es una construcción latina sin equivalente directo en español","Se compone de un sustantivo en ablativo y un participio concertado con él","Funciona como subordinada adverbial indicando tiempo, causa, condición o concesión","Caesare duce significa siendo César general o bajo el mando de César","Urbe capta quiere decir tomada la ciudad con valor temporal o causal"]'),
('latin', 'bachillerato', '{2}', '["El gerundio y el gerundivo latinos expresan la acción verbal con valor nominal","El gerundio es un sustantivo verbal declinable solo en acusativo, genitivo, dativo y ablativo","Ars amandi significa el arte de amar usando el genitivo del gerundio","El gerundivo es un adjetivo verbal pasivo con valor de obligación o posibilidad","Cuando el gerundio tiene complemento directo se sustituye obligatoriamente por el gerundivo concordado"]'),
('latin', 'bachillerato', '{2}', '["Tibulo y Propercio cultivaron la elegía latina amorosa durante la época de Augusto","Tibulo escribió elegías dedicadas a sus amadas Delia y Némesis con un tono melancólico","Propercio compuso cuatro libros centrados en su relación con Cintia con un estilo más erudito","Ambos poetas exaltaron el servitium amoris como sometimiento voluntario a la amada","La elegía latina combinó la tradición griega con las experiencias personales del autor"]'),
('latin', 'bachillerato', '{2}', '["Juvenal escribió dieciséis sátiras en hexámetros durante el Imperio temprano","Sus sátiras critican con virulencia los vicios y corrupciones de la sociedad romana","Retrata a Roma como una ciudad invivible para el ciudadano honesto y modesto","Acuñó frases célebres como panem et circenses y mens sana in corpore sano","Su tono indignado inspiró la sátira moral de toda la literatura europea posterior"]'),
('latin', 'bachillerato', '{2}', '["Quintiliano nació en Calagurris, la actual Calahorra, en la provincia romana de Hispania","Fue nombrado profesor oficial de retórica por el emperador Vespasiano con sueldo público","Escribió la Institutio Oratoria en doce libros como tratado completo de formación del orador","Definió al orador ideal como vir bonus dicendi peritus, hombre bueno experto en el decir","Su obra influyó decisivamente en la pedagogía humanista del Renacimiento europeo"]'),
('latin', 'bachillerato', '{2}', '["Nerón accedió al trono imperial en el año 54 d.C. con tan solo diecisiete años","Durante los primeros años gobernó bien bajo la tutela de Séneca y del prefecto Burro","Se le atribuyó el incendio de Roma en el 64 d.C. que culpó a los cristianos","Persiguió violentamente a los cristianos siendo según la tradición responsable de la muerte de Pedro y Pablo","Abandonado por el ejército y el Senado se suicidó en el año 68 d.C. con la frase Qualis artifex pereo"]'),
('latin', 'bachillerato', '{2}', '["Trajano fue el primer emperador romano nacido fuera de Italia en la provincia de Hispania","Había nacido en Itálica, cerca de la actual Sevilla, en una familia senatorial romanizada","Bajo su mando el Imperio alcanzó su máxima extensión territorial con la conquista de Dacia","Construyó el foro de Trajano en Roma con la célebre columna que narra sus campañas","El Senado le concedió el título de Optimus Princeps como reconocimiento a su buen gobierno"]');

-- ---------------------------------------------------------------------
-- LENGUA CASTELLANA Y LITERATURA - 2º BACHILLERATO (12 historias)
-- EBAU: Gen 98/27, novela posguerra, poesía siglo XX, teatro
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('lengua', 'bachillerato', '{2}', '["Antonio Machado publicó Campos de Castilla en 1912 tras trasladarse a enseñar a Soria","El libro abandona el intimismo modernista anterior por una mirada comprometida con España","Los poemas describen los paisajes castellanos reflejando el atraso y la decadencia nacional","La muerte de su joven esposa Leonor impregna el libro de un profundo dolor personal","La segunda edición añadió los Proverbios y cantares con aforismos filosóficos y éticos"]'),
('lengua', 'bachillerato', '{2}', '["Pío Baroja publicó El árbol de la ciencia en 1911 como una de sus novelas más logradas","El protagonista Andrés Hurtado estudia medicina en Madrid durante el cambio de siglo","La obra presenta una visión pesimista sobre la vida y la sociedad española de la época","Las conversaciones filosóficas con su tío Iturrioz transmiten el escepticismo de Schopenhauer","Desengañado, Andrés termina suicidándose ante la imposibilidad de conciliar acción y pensamiento"]'),
('lengua', 'bachillerato', '{2}', '["Pedro Salinas cultivó una poesía amorosa profundamente intelectual dentro de la Generación del 27","La voz a ti debida de 1933 explora el amor como experiencia reveladora del mundo","El tú amado se convierte en el centro organizador de toda la realidad del poeta","Razón de amor y Largo lamento completan su trilogía amorosa fundamental","Su obra posterior al exilio combina reflexión existencial y denuncia del progreso destructivo"]'),
('lengua', 'bachillerato', '{2}', '["Luis Cernuda reunió toda su poesía bajo el título La realidad y el deseo","El título resume la tensión fundamental entre el mundo tal como es y como debería ser","Los placeres prohibidos expresó abiertamente su homosexualidad en la España de los años treinta","Donde habite el olvido evoca el dolor de un amor imposible en tono elegíaco","En el exilio mexicano compuso Desolación de la Quimera como despedida amarga y lúcida"]'),
('lengua', 'bachillerato', '{2}', '["Antonio Buero Vallejo estrenó Historia de una escalera en 1949 tras salir de la cárcel","La obra describe la frustración de tres generaciones de vecinos de una casa humilde madrileña","Los personajes comparten sueños que nunca llegan a cumplirse por falta de oportunidades","La escalera funciona como espacio simbólico donde se repite el ciclo de la miseria","Ganó el premio Lope de Vega e inauguró el teatro realista serio de la posguerra"]'),
('lengua', 'bachillerato', '{2}', '["Miguel Delibes publicó Cinco horas con Mario en 1966 como novela experimental","Carmen habla en un largo monólogo junto al cadáver de su marido recién fallecido","A través de sus reproches se reconstruye el retrato de dos Españas enfrentadas","Mario representaba al intelectual progresista y Carmen a la mujer tradicional conservadora","La novela denuncia sin estridencias la incomunicación y el autoritarismo del franquismo"]'),
('lengua', 'bachillerato', '{2}', '["Ana María Matute desarrolló una narrativa personal marcada por la guerra y la infancia perdida","Su trilogía Los mercaderes reconstruye la España rural desgarrada por el conflicto civil","Primera memoria de 1959 recibió el premio Nadal por su sensibilidad lírica y simbólica","Olvidado rey Gudú mezcla fantasía épica con reflexión moral sobre el poder y la crueldad","Fue la tercera mujer en ingresar en la Real Academia Española como miembro de pleno derecho"]'),
('lengua', 'bachillerato', '{2}', '["Juan Ramón Jiménez evolucionó hacia la poesía pura a partir del Diario de un poeta recién casado","El viaje a Nueva York de 1916 supuso una ruptura definitiva con el modernismo anterior","Su nueva poética buscaba la esencia desnuda liberada de cualquier ornamento superfluo","Eternidades y Piedra y cielo desarrollan esta depuración estética de rasgos casi místicos","Recibió el Premio Nobel de Literatura en 1956 durante su exilio americano en Puerto Rico"]'),
('lengua', 'bachillerato', '{2}', '["Juan Marsé publicó Últimas tardes con Teresa en 1966 ganando el premio Biblioteca Breve","La novela narra la relación imposible entre el Pijoaparte charnego y Teresa universitaria burguesa","El contraste entre sus clases sociales se convierte en un retrato crítico de la Barcelona franquista","Marsé disecciona con ironía los falsos compromisos políticos de la burguesía progresista","La obra inaugura el ciclo narrativo del autor centrado en los barrios populares barceloneses"]'),
('lengua', 'bachillerato', '{2}', '["La poesía española de las últimas décadas ha estado marcada por la experiencia personal","La poesía de la experiencia representada por Luis García Montero busca un tono coloquial","Jaime Gil de Biedma había sido precursor con Las personas del verbo en los años sesenta","La otra sentimentalidad reaccionó contra el culturalismo hermético de los novísimos anteriores","Autoras como Blanca Andreu y Ana Rossetti renovaron los temas con una voz propia contundente"]'),
('lengua', 'bachillerato', '{2}', '["El postismo surgió en Madrid en 1945 como intento de recuperar las vanguardias perdidas","Carlos Edmundo de Ory fue su principal teórico junto a Eduardo Chicharro y Silvano Sernesi","El movimiento reivindicó la libertad imaginativa del surrealismo frente al realismo impuesto","Cultivaron el humor absurdo, el juego verbal y las imágenes insólitas de raíz onírica","Su escasa difusión inicial no impidió que influyera en poetas posteriores como Ángel Crespo"]'),
('lengua', 'bachillerato', '{2}', '["La columna periodística se consolidó como género literario en la prensa española","Azorín y Julio Camba habían sido grandes maestros del artículo en la primera mitad del siglo","Francisco Umbral desarrolló una prosa brillante y personalísima durante décadas de colaboración","Manuel Vicent y Rosa Montero han continuado la tradición con un estilo literario cuidado","El columnismo actual combina la reflexión ensayística con la opinión breve sobre la actualidad"]');

-- ---------------------------------------------------------------------
-- HISTORIA DEL ARTE - 2º BACHILLERATO (11 historias)
-- EBAU: Velázquez, Goya, vanguardias siglo XX, arte español
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('arte', 'bachillerato', '{2}', '["Goya pintó Los fusilamientos del tres de mayo en 1814 tras la Guerra de la Independencia","El cuadro muestra la ejecución de patriotas madrileños por el ejército napoleónico","La figura central viste camisa blanca y levanta los brazos en gesto crístico","La luz de un farol ilumina dramáticamente a las víctimas frente a la oscuridad de los verdugos","La obra inauguró la pintura moderna al denunciar los horrores de la guerra sin idealización"]'),
('arte', 'bachillerato', '{2}', '["Miguel Ángel pintó la bóveda de la Capilla Sixtina entre 1508 y 1512 por encargo de Julio II","La bóveda representa nueve escenas del Génesis enmarcadas por una arquitectura ilusoria","La Creación de Adán es la imagen más célebre con los dedos que casi se rozan","Veinte años después, el papa Paulo III le encargó el enorme fresco del Juicio Final en el muro testero","La obra combina anatomía monumental, color intenso y una composición de fuerza sobrehumana"]'),
('arte', 'bachillerato', '{2}', '["Gian Lorenzo Bernini fue el gran escultor y arquitecto del Barroco romano","Esculpió el Éxtasis de Santa Teresa en mármol para la capilla Cornaro combinando mística y teatro","Su David capta el instante previo al lanzamiento de la piedra con tensión dinámica","Diseñó la columnata elíptica de la plaza de San Pedro como abrazo acogedor del Vaticano","Obras como el baldaquino y la cátedra de San Pedro sellaron su dominio del arte religioso barroco"]'),
('arte', 'bachillerato', '{2}', '["El Greco nació en Creta y se formó en Venecia estudiando la obra de Tintoretto","Tras pasar por Roma se instaló definitivamente en Toledo desde 1577","El entierro del conde de Orgaz sintetiza su estilo con figuras alargadas y composición en dos mundos","Utilizó colores ácidos y contrastes dramáticos anticipando recursos modernos","Su expresividad manierista fue redescubierta a principios del siglo XX por las vanguardias europeas"]'),
('arte', 'bachillerato', '{2}', '["La catedral de Burgos se comenzó en 1221 bajo el reinado de Fernando III el Santo","Su planta de cruz latina sigue el modelo de las grandes catedrales góticas francesas","Las agujas caladas de las torres de la fachada occidental se añadieron en el siglo XV","El cimborrio renacentista y la capilla del Condestable enriquecieron el templo posteriormente","Fue declarada Patrimonio de la Humanidad por la UNESCO como obra cumbre del gótico hispano"]'),
('arte', 'bachillerato', '{2}', '["El monasterio de El Escorial fue mandado construir por Felipe II en 1563","El arquitecto Juan Bautista de Toledo inició el proyecto sobrio de gusto herreriano","Juan de Herrera completó el conjunto imponiendo el estilo desornamentado que lleva su nombre","El edificio cumple funciones de palacio, monasterio, basílica, panteón real y biblioteca","Su planta se ha relacionado simbólicamente con la parrilla del martirio de san Lorenzo"]'),
('arte', 'bachillerato', '{2}', '["El fauvismo estalló en el Salón de Otoño parisino de 1905 como primera vanguardia del siglo XX","Los fauves liberaron el color de toda función descriptiva aplicándolo en tonos puros y estridentes","Henri Matisse encabezó el movimiento con obras como La alegría de vivir y La danza","Derain y Vlaminck pintaron paisajes con colores arbitrarios de enorme fuerza expresiva","El fauvismo fue breve pero decisivo al abrir el camino hacia la abstracción posterior"]'),
('arte', 'bachillerato', '{2}', '["Juan Gris desarrolló la fase sintética del cubismo junto a Picasso y Braque","Su primera etapa analítica descomponía los objetos en facetas geométricas rigurosas","Pronto evolucionó hacia composiciones más planas con colores intensos y formas ordenadas","Integró collages con papeles pintados y recortes tipográficos en sus bodegones cubistas","Su estilo influyó en la pintura española de vanguardia durante las décadas siguientes"]'),
('arte', 'bachillerato', '{2}', '["El Museo del Prado se fundó en 1819 por iniciativa de Fernando VII","El edificio neoclásico había sido proyectado por Juan de Villanueva como gabinete de historia natural","La reina Isabel de Braganza había impulsado la idea de reunir la colección real en un museo público","Sus colecciones proceden principalmente del patrimonio artístico de la corona española","Alberga las obras maestras de Velázquez, Goya, Tiziano, Rubens y El Greco reconocidas mundialmente"]'),
('arte', 'bachillerato', '{2}', '["El expresionismo abstracto se desarrolló en Nueva York tras la Segunda Guerra Mundial","Jackson Pollock inventó el dripping derramando pintura sobre lienzos extendidos en el suelo","La pintura gestual, llamada action painting, convirtió el acto de pintar en protagonista de la obra","Mark Rothko desarrolló en paralelo una pintura de grandes campos de color de carga espiritual","Esta corriente consolidó a Nueva York como nueva capital mundial del arte contemporáneo"]'),
('arte', 'bachillerato', '{2}', '["La Alhambra de Granada es el mayor palacio nazarí conservado de la arquitectura islámica","Los sultanes Yusuf I y Muhammad V construyeron los principales palacios en el siglo XIV","El patio de los Leones reúne una fuente central rodeada por arcadas de columnas estilizadas","El salón de los Embajadores destaca por su cúpula de mocárabes de enorme complejidad","Sus yeserías, azulejos y epigrafías árabes culminan el arte andalusí justo antes de la Reconquista"]');

-- ---------------------------------------------------------------------
-- FILOSOFIA - 2º BACHILLERATO (11 historias)
-- EBAU: Platón, Aristóteles, Descartes, Hume, Kant, Marx, Nietzsche, Ortega
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('filosofia', 'bachillerato', '{2}', '["La alegoría de la caverna aparece en el libro VII de la República de Platón","Unos prisioneros encadenados desde niños solo ven sombras proyectadas en la pared","Uno de ellos es liberado y descubre los objetos reales y la luz del sol exterior","Al regresar y contar lo visto es ridiculizado y los demás incluso querrían matarlo","La alegoría ilustra el ascenso del alma desde la ignorancia hacia el conocimiento del Bien"]'),
('filosofia', 'bachillerato', '{2}', '["La República de Platón expone el proyecto de una ciudad ideal regida por la justicia","La justicia consiste en que cada parte del alma y del estado cumpla su función propia","Los tres estamentos son los filósofos gobernantes, los guardianes y los productores","Solo los filósofos son dignos de gobernar por haber contemplado la Idea del Bien","La sociedad justa reproduce en el exterior la armonía interior del alma bien ordenada"]'),
('filosofia', 'bachillerato', '{2}', '["Aristóteles dedicó la Ética a Nicómaco a la cuestión de la felicidad humana","La felicidad o eudemonía es el fin último al que tienden todas las acciones humanas","Consiste en la actividad del alma conforme a la virtud durante toda una vida completa","La virtud se adquiere por el hábito como término medio entre dos vicios opuestos","La vida contemplativa o teorética es considerada la forma más perfecta de felicidad humana"]'),
('filosofia', 'bachillerato', '{2}', '["Aristóteles sostuvo en la Política que el ser humano es un animal político por naturaleza","Solo en la polis o ciudad-estado puede desarrollarse plenamente como ciudadano","La familia es la primera comunidad natural seguida por la aldea y finalmente la polis","El bien común de la ciudad tiene prioridad sobre los intereses privados de sus miembros","Las distintas formas de gobierno se distinguen según busquen el bien común o el particular"]'),
('filosofia', 'bachillerato', '{2}', '["Descartes distinguió dos tipos de sustancias completamente diferentes en el ser humano","La res cogitans es la sustancia pensante cuya esencia es el pensamiento consciente","La res extensa es la sustancia corporal cuya esencia es la extensión en el espacio","El dualismo cartesiano plantea el difícil problema de cómo se comunican ambas sustancias","Descartes situó en la glándula pineal el punto de contacto entre el alma y el cuerpo"]'),
('filosofia', 'bachillerato', '{2}', '["Spinoza desarrolló un monismo metafísico radical en su Ética demostrada geométricamente","Sostuvo que solo existe una única sustancia infinita identificada con Dios o Naturaleza","Todo lo que existe es modo de esa sustancia única no una realidad independiente","Pensamiento y extensión son atributos infinitos de la misma sustancia divina","Su panteísmo le valió la excomunión de la comunidad judía de Ámsterdam en 1656"]'),
('filosofia', 'bachillerato', '{2}', '["Leibniz propuso que la realidad se compone de infinitas sustancias simples llamadas mónadas","Cada mónada es un punto metafísico sin partes, sin ventanas e irreductible a otras","Las mónadas no interactúan entre sí pero reflejan todo el universo desde su perspectiva","Dios estableció desde la creación una armonía preestablecida entre todas las mónadas","Este sistema metafísico intentó conciliar la libertad humana con la omnisciencia divina"]'),
('filosofia', 'bachillerato', '{2}', '["Hegel desarrolló una filosofía del espíritu absoluto que se despliega en la historia","La dialéctica hegeliana avanza mediante una tesis, una antítesis y una síntesis superadora","El espíritu objetivo se manifiesta en el derecho, la moralidad y la eticidad estatal","El espíritu absoluto alcanza su plenitud en el arte, la religión y la filosofía","La Fenomenología del Espíritu describe el itinerario de la conciencia hacia el saber absoluto"]'),
('filosofia', 'bachillerato', '{2}', '["Schopenhauer publicó El mundo como voluntad y representación en 1819","El mundo que percibimos es solo representación del sujeto según las formas del espacio y tiempo","Detrás de los fenómenos se encuentra la voluntad como esencia ciega de toda la realidad","La voluntad provoca un deseo insaciable que conduce inevitablemente al sufrimiento humano","La liberación del sufrimiento se alcanza mediante el arte, la compasión y la ascética"]'),
('filosofia', 'bachillerato', '{2}', '["Wittgenstein publicó el Tractatus Logico-Philosophicus en 1921 como tratado de filosofía del lenguaje","El libro expone siete proposiciones fundamentales desarrolladas en forma de aforismos numerados","El mundo es la totalidad de los hechos y el lenguaje debe reflejarlos isomorfamente","De lo que no se puede hablar mejor es callarse reza su famosa sentencia final","En su segunda etapa desarrolló la teoría de los juegos del lenguaje en las Investigaciones filosóficas"]'),
('filosofia', 'bachillerato', '{2}', '["John Rawls publicó Teoría de la justicia en 1971 renovando la filosofía política contemporánea","Propuso un experimento mental con una posición original bajo un velo de ignorancia","Los individuos eligen los principios de justicia sin conocer su propia posición social","Bajo estas condiciones elegirían el principio de mayor igualdad compatible con la libertad","El segundo principio permite las desigualdades solo si benefician a los menos aventajados de la sociedad"]');

-- ---------------------------------------------------------------------
-- HISTORIA DE ESPAÑA - 2º BACHILLERATO (16 historias)
-- EBAU: Al-Ándalus, Cádiz 1812, Restauración, II República, Guerra Civil, Transición
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('historia-espana', 'bachillerato', '{2}', '["Abderramán III proclamó el Califato de Córdoba independiente de Bagdad en el 929","Al-Ándalus alcanzó su máxima extensión, esplendor económico y prestigio cultural bajo su gobierno","La biblioteca de Al-Hakam II llegó a contar con cientos de miles de volúmenes","Almanzor ejerció la dictadura militar como hachib bajo el débil califa Hisham II","El califato cordobés se hundió en una guerra civil y se fragmentó en reinos de taifas en 1031"]'),
('historia-espana', 'bachillerato', '{2}', '["Don Pelayo protagonizó la batalla de Covadonga hacia el año 718 según la tradición","La victoria de los astures frente a una partida musulmana tuvo una modesta importancia militar","La historiografía cristiana posterior la convirtió en el mito fundacional de la Reconquista","A partir de esa victoria surgió el reino de Asturias como primer núcleo cristiano peninsular","Alfonso I extendió el territorio aprovechando la rebelión bereber de mediados del siglo VIII"]'),
('historia-espana', 'bachillerato', '{2}', '["Alfonso X el Sabio reinó en Castilla y León desde 1252 hasta 1284","Impulsó la Escuela de Traductores de Toledo con colaboradores cristianos, judíos y musulmanes","Promulgó Las Partidas como recopilación jurídica inspirada en el derecho romano","Ordenó redactar la Estoria de España y la General Estoria en castellano en lugar del latín","Su pretensión al trono imperial germánico, llamada Fecho del Imperio, arruinó las finanzas del reino"]'),
('historia-espana', 'bachillerato', '{2}', '["La dinastía Trastámara accedió al trono de Castilla tras la guerra civil entre Pedro I y su hermano","Enrique II de Trastámara inauguró la nueva dinastía en 1369 tras la batalla de Montiel","Juan II y Enrique IV protagonizaron reinados convulsos con fuertes enfrentamientos nobiliarios","Isabel, hermanastra de Enrique IV, se casó con Fernando de Aragón en 1469","La muerte de Enrique IV en 1474 desencadenó la guerra de sucesión que consolidó a los Reyes Católicos"]'),
('historia-espana', 'bachillerato', '{2}', '["Felipe IV heredó la monarquía hispánica en 1621 en plena decadencia del siglo XVII","Delegó el gobierno en el conde-duque de Olivares como valido todopoderoso durante veinte años","Olivares impulsó la Unión de Armas para repartir el esfuerzo bélico entre todos los reinos","El proyecto centralizador provocó las rebeliones de Cataluña y Portugal en 1640","La caída de Olivares en 1643 no evitó la paz humillante de Westfalia y la pérdida de hegemonía"]'),
('historia-espana', 'bachillerato', '{2}', '["Carlos III reinó en España entre 1759 y 1788 como máximo exponente del despotismo ilustrado","Rodeado de ministros reformistas como Floridablanca y Campomanes modernizó la administración","Impulsó la colonización de Sierra Morena fundando nuevas poblaciones con colonos europeos","Expulsó a los jesuitas en 1767 siguiendo el ejemplo de otras monarquías ilustradas","Los motines de Esquilache en 1766 le obligaron a suavizar sus reformas modernizadoras"]'),
('historia-espana', 'bachillerato', '{2}', '["El motín de Aranjuez estalló en marzo de 1808 contra el valido Manuel Godoy","Los partidarios de Fernando VII aprovecharon la presencia de tropas francesas en España","Carlos IV se vio obligado a destituir a Godoy y a abdicar en favor de su hijo Fernando VII","Napoleón convocó a ambos reyes en Bayona y les forzó a cederle la corona española","Bonaparte entregó entonces el trono de España a su hermano José Bonaparte"]'),
('historia-espana', 'bachillerato', '{2}', '["La Guerra de la Independencia enfrentó a los españoles con el ejército napoleónico desde 1808","El levantamiento popular del dos de mayo en Madrid marcó el inicio de la resistencia","Las Juntas Provinciales asumieron el poder en ausencia del rey legítimo Fernando VII","La guerra de guerrillas desgastó al ejército francés imposibilitando la pacificación del territorio","La victoria de Wellington en Vitoria en 1813 expulsó definitivamente a los franceses"]'),
('historia-espana', 'bachillerato', '{2}', '["El pronunciamiento del coronel Rafael del Riego en enero de 1820 inició el Trienio Liberal","El ejército destinado a América se sublevó en Las Cabezas de San Juan contra Fernando VII","Riego obligó al rey a jurar la Constitución de 1812 restableciendo el régimen liberal","Los liberales se dividieron entre moderados, que apoyaban al rey, y exaltados radicales","Los Cien Mil Hijos de San Luis franceses invadieron España en 1823 reponiendo el absolutismo"]'),
('historia-espana', 'bachillerato', '{2}', '["La Revolución de 1868 llamada la Gloriosa destronó a Isabel II de España","El general Prim, Serrano y el almirante Topete protagonizaron el levantamiento en Cádiz","Las tropas isabelinas fueron derrotadas en Alcolea y la reina partió hacia el exilio francés","El Sexenio Democrático inició una etapa de búsqueda de un sistema político estable","Las Cortes Constituyentes aprobaron la Constitución de 1869 de carácter marcadamente democrático"]'),
('historia-espana', 'bachillerato', '{2}', '["La Primera República española se proclamó el 11 de febrero de 1873 tras la abdicación de Amadeo","Figueras fue su primer presidente seguido por Pi y Margall, Salmerón y Castelar","La República tuvo que enfrentar simultáneamente tres conflictos bélicos muy graves","La tercera guerra carlista, la insurrección cantonal y la guerra de Cuba debilitaron al gobierno","El golpe del general Pavía en enero de 1874 disolvió las Cortes republicanas"]'),
('historia-espana', 'bachillerato', '{2}', '["El desastre de Annual tuvo lugar en julio de 1921 en el Protectorado español de Marruecos","Las fuerzas del caudillo rifeño Abd el-Krim derrotaron a las tropas españolas del general Silvestre","Más de diez mil soldados españoles murieron en la catastrófica retirada del ejército colonial","El expediente Picasso intentó depurar las responsabilidades militares y políticas del desastre","La crisis desencadenó el golpe de Primo de Rivera en septiembre de 1923 con apoyo real"]'),
('historia-espana', 'bachillerato', '{2}', '["El bienio reformista de la Segunda República duró desde 1931 hasta las elecciones de 1933","Manuel Azaña presidió el gobierno con socialistas y republicanos de izquierda reformistas","Se aprobaron leyes de reforma agraria, militar, religiosa y del Estatuto de Cataluña","La Sanjurjada de agosto de 1932 fue el primer intento militar de derribar la República","Los sucesos de Casas Viejas desacreditaron al gobierno y provocaron elecciones anticipadas"]'),
('historia-espana', 'bachillerato', '{2}', '["El bienio radical-cedista comenzó tras la victoria electoral de las derechas en 1933","El Partido Radical de Lerroux gobernó con el apoyo parlamentario de la CEDA de Gil Robles","La entrada de ministros cedistas en el gobierno provocó la revolución de octubre de 1934","La insurrección obrera de Asturias fue reprimida con dureza por las fuerzas legionarias","Los escándalos del estraperlo y de Nombela desgastaron al Partido Radical hasta su hundimiento"]'),
('historia-espana', 'bachillerato', '{2}', '["El Frente Popular ganó las elecciones de febrero de 1936 por un estrecho margen","La coalición reunía a republicanos de izquierda, socialistas y comunistas contra las derechas","Manuel Azaña accedió a la presidencia de la República en sustitución de Alcalá-Zamora","Un clima de violencia política creciente marcó los meses previos al alzamiento militar","El asesinato de Calvo Sotelo el 13 de julio precipitó el golpe de Estado del 18 de julio"]'),
('historia-espana', 'bachillerato', '{2}', '["El Plan de Estabilización de 1959 puso fin a la autarquía económica del primer franquismo","Los tecnócratas del Opus Dei sustituyeron a los falangistas en las carteras económicas","El plan liberalizó el comercio exterior, devaluó la peseta y controló el gasto público","Los Planes de Desarrollo de los años sesenta impulsaron el despegue industrial del país","El turismo masivo y las remesas de emigrantes aportaron las divisas que financiaron la modernización"]');

-- ---------------------------------------------------------------------
-- MATEMATICAS - 2º BACHILLERATO (7 historias)
-- EBAU: integrales, optimización, geometría 3D, probabilidad/estadística
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('matematicas', 'bachillerato', '{2}', '["Para calcular el volumen de un tetraedro de vértices A, B, C y D utilizamos el producto mixto","Formamos los vectores AB, AC y AD restando las coordenadas del primer vértice a los otros tres","El producto mixto se calcula como el determinante de la matriz 3x3 con esos tres vectores","El valor absoluto del producto mixto nos da el volumen del paralelepípedo formado","El volumen del tetraedro es la sexta parte del valor absoluto de ese producto mixto"]'),
('matematicas', 'bachillerato', '{2}', '["El teorema de la probabilidad total calcula P(A) usando un sistema completo de sucesos","Sean B1, B2, ..., Bn sucesos incompatibles cuya unión es todo el espacio muestral","La probabilidad total es P(A) = P(A|B1)·P(B1) + P(A|B2)·P(B2) + ... + P(A|Bn)·P(Bn)","Se aplica cuando conocemos las probabilidades condicionadas y las probabilidades a priori","El teorema de Bayes permite invertir la condición calculando P(Bi|A) a partir de P(A|Bi)"]'),
('matematicas', 'bachillerato', '{2}', '["Para realizar un contraste de hipótesis sobre una proporción partimos de la proporción poblacional p0","Planteamos H0: p = p0 frente a H1 con la alternativa según el tipo de contraste","Calculamos el estadístico z = (p̂ - p0) / raíz(p0·(1-p0)/n) con la proporción muestral p̂","Fijamos el nivel de significación alfa y determinamos la región crítica en la normal estándar","Si el estadístico cae en la región crítica rechazamos H0 con el nivel de significación elegido"]'),
('matematicas', 'bachillerato', '{2}', '["Para calcular el área bajo una función positiva en un intervalo planteamos la integral definida","Identificamos los límites de integración como los extremos a y b del intervalo pedido","Calculamos una primitiva F de la función f mediante las técnicas de integración","Aplicamos la regla de Barrow evaluando F(b) - F(a) como valor numérico","El resultado obtenido es directamente el área bajo la curva ya que la función es positiva"]'),
('matematicas', 'bachillerato', '{2}', '["Para representar una función racional estudiamos primero su dominio excluyendo los ceros del denominador","Calculamos las asíntotas verticales en los puntos donde se anula el denominador pero no el numerador","La asíntota horizontal se obtiene calculando el límite cuando x tiende a más y menos infinito","Si no existe asíntota horizontal pero los grados difieren en uno, hay una asíntota oblicua y = mx + n","Con esta información y el estudio de crecimiento dibujamos la gráfica completa de la función"]'),
('matematicas', 'bachillerato', '{2}', '["Para hallar la perpendicular común a dos rectas que se cruzan en el espacio formamos el vector director","El vector director de la perpendicular común es el producto vectorial de los directores de ambas rectas","Construimos los planos que contienen cada recta y el vector perpendicular común recién hallado","La perpendicular común es la intersección de esos dos planos auxiliares construidos","Los puntos de corte con cada recta son los pies de la perpendicular más próxima entre ambas"]'),
('matematicas', 'bachillerato', '{2}', '["Para construir un intervalo de confianza para una proporción partimos de una muestra aleatoria","Calculamos la proporción muestral p̂ como el cociente de éxitos entre el tamaño n","Fijamos el nivel de confianza y obtenemos el valor crítico z_alfa/2 de la normal estándar","El error máximo admisible es E = z_alfa/2 · raíz(p̂·(1-p̂)/n)","El intervalo de confianza es (p̂ - E, p̂ + E) con la proporción poblacional como incógnita"]');

-- ---------------------------------------------------------------------
-- QUIMICA - 2º BACHILLERATO (7 historias)
-- EBAU: termodinámica, equilibrio, ácido-base, redox, orgánica
-- ---------------------------------------------------------------------
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES
('quimica', 'bachillerato', '{2}', '["Una sustitución nucleófila SN1 ocurre en halogenuros de alquilo terciarios en disolución polar","En la primera etapa el halogenuro se ioniza formando un carbocatión plano relativamente estable","El ion haluro se libera actuando como grupo saliente en una etapa lenta limitante","El nucleófilo ataca al carbocatión por cualquiera de sus dos caras con igual probabilidad","Si el carbono era quiral se obtiene una mezcla racémica de ambos enantiómeros"]'),
('quimica', 'bachillerato', '{2}', '["El agua se autoioniza en pequeñísima proporción según H2O ⇌ H+ + OH-","A 25 grados centígrados el producto iónico del agua Kw vale 1 por 10 elevado a menos 14","En agua pura las concentraciones de H+ y OH- son iguales a 10 elevado a menos 7 molar","El pH se define como el logaritmo cambiado de signo de la concentración de protones","Una disolución es ácida si pH < 7, básica si pH > 7 y neutra si pH = 7"]'),
('quimica', 'bachillerato', '{2}', '["Para preparar una disolución por dilución partimos de una disolución madre concentrada","Aplicamos la fórmula de conservación de moles M1·V1 = M2·V2 entre ambas disoluciones","Despejamos el volumen V1 necesario de la disolución madre para obtener la concentración deseada","Con una pipeta graduada medimos exactamente ese volumen y lo vertemos en un matraz aforado","Enrasamos con agua destilada hasta la marca del volumen final homogeneizando por inversión"]'),
('quimica', 'bachillerato', '{2}', '["La primera ley de Faraday relaciona la masa depositada con la carga eléctrica circulada","La segunda ley indica que la masa es proporcional al equivalente electroquímico del elemento","La carga total se calcula como Q = I·t donde I es la intensidad y t el tiempo","Los moles de electrones son n(e-) = Q/F siendo F la constante de Faraday 96500 culombios","La masa depositada es m = n(e-)·M/z con M masa atómica y z la carga del ion"]'),
('quimica', 'bachillerato', '{2}', '["El modelo atómico de Bohr explicó los espectros del átomo de hidrógeno","El electrón gira en órbitas circulares estacionarias con energías discretas cuantizadas","En su estado fundamental el electrón ocupa la órbita más cercana al núcleo","Al absorber un fotón salta a una órbita superior más energética temporalmente","Al volver al nivel inicial emite un fotón con energía igual a la diferencia entre niveles"]'),
('quimica', 'bachillerato', '{2}', '["La entalpía de combustión se determina experimentalmente en una bomba calorimétrica","Se introduce una masa conocida de combustible en el recipiente hermético cargado con oxígeno","La muestra se quema mediante una chispa eléctrica liberando su energía en forma de calor","El calor absorbido por el agua del calorímetro se calcula con Q = m·c·deltaT","Dividiendo el calor entre los moles de combustible obtenemos la entalpía molar de combustión"]'),
('quimica', 'bachillerato', '{2}', '["Un catalizador aumenta la velocidad de una reacción sin consumirse en el proceso global","Su acción consiste en proporcionar un camino alternativo con menor energía de activación","La ecuación de Arrhenius k = A·e^(-Ea/RT) muestra que una menor Ea implica mayor constante k","El catalizador no modifica la variación de entalpía ni la posición del equilibrio termodinámico","Tampoco altera las concentraciones finales pero permite alcanzarlas en un tiempo mucho menor"]');
