-- Seed de historias para Ordena la Historia: Tutoría Bachillerato 1º y 2º
-- 50 historias para 1º Bachillerato + 50 historias para 2º Bachillerato

-- =====================================================
-- 1º BACHILLERATO (50 historias)
-- =====================================================

INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Llegar al bachillerato supone un salto notable de exigencia respecto a la etapa anterior","El primer paso es asumir que estudiar requerirá más horas y mayor autonomía personal","Elaborar un horario semanal realista permite distribuir materias y descansos de forma equilibrada","Revisar ese horario cada quince días ayuda a ajustarlo a la carga real del curso","Con el tiempo, este hábito convierte la planificación en una herramienta natural de éxito"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El método Cornell divide la página en tres zonas: apuntes, palabras clave y resumen","Durante la clase se escriben las ideas principales en la columna más amplia","Al terminar, se extraen las palabras clave en el margen izquierdo de la página","Al final de la sesión se redacta un resumen breve con las ideas esenciales","Esa triple revisión convierte los apuntes en una herramienta eficaz de repaso activo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La técnica Pomodoro propone estudiar en bloques de unos veinticinco minutos concentrados","Después de cada bloque se realiza una pausa de cinco minutos sin pantallas","Tras cuatro pomodoros seguidos se hace un descanso más largo de quince minutos","Este ritmo evita la fatiga mental y mantiene alta la calidad del estudio","Muchos estudiantes descubren que rinden más en menos tiempo usando este sistema"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La ansiedad ante un examen es una respuesta natural del organismo ante la presión","El primer paso es reconocerla sin juzgarla como algo negativo o vergonzoso","Aplicar respiración diafragmática durante unos minutos reduce la activación fisiológica del cuerpo","Recordar que la preparación previa ha sido adecuada aporta confianza interior al estudiante","Con estas herramientas, la ansiedad deja de ser un obstáculo y se convierte en impulso"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La asertividad es una habilidad social que se aprende con la práctica cotidiana","Consiste en expresar opiniones, sentimientos y necesidades respetando a los demás","Una persona asertiva defiende su postura sin caer en la agresividad ni en la sumisión","Utiliza mensajes en primera persona del tipo yo siento o yo necesito","Este estilo comunicativo fortalece las relaciones y protege tu bienestar emocional diario"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El autoconocimiento profesional es la base de cualquier decisión académica coherente","Primero identificas tus fortalezas observando qué tareas se te dan mejor","Después exploras tus intereses anotando las actividades que te generan mayor curiosidad","Finalmente valoras tus valores personales: qué es importante para ti en un trabajo","Con estas tres piezas puedes empezar a imaginar itinerarios profesionales alineados contigo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Los mapas conceptuales ayudan a organizar la información de forma jerárquica y visual","Se empieza escribiendo el concepto central dentro de un círculo destacado","A continuación se derivan los conceptos secundarios unidos por líneas con conectores","Cada conexión lleva una palabra que explica la relación entre los conceptos vinculados","El resultado final es una radiografía visual clara que facilita el repaso comprensivo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El sueño cumple una función esencial en la consolidación de la memoria aprendida","Durante la noche el cerebro procesa y almacena lo estudiado durante el día","Dormir menos de siete horas reduce notablemente la capacidad de concentración al día siguiente","Establecer una rutina estable con horarios fijos mejora la calidad del descanso profundo","Por eso, estudiar menos y dormir mejor suele rendir más que lo contrario"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La procrastinación aparece cuando pospones una tarea pese a saber que deberías hacerla","Suele estar motivada por miedo al fracaso o por perfeccionismo mal canalizado","Un truco eficaz consiste en comprometerte a trabajar solo cinco minutos en la tarea","Una vez que has empezado, la inercia suele mantenerte concentrado durante más tiempo","Repetir esta estrategia convierte el arranque en una acción automática y sin resistencia"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La inteligencia emocional incluye cuatro grandes componentes muy interrelacionados entre sí","El primero es reconocer tus propias emociones en el momento en que aparecen","El segundo es regularlas evitando que se disparen impulsivamente sin control alguno","El tercero consiste en detectar las emociones de los demás con empatía activa","El cuarto es usar esa información para construir relaciones sanas y duraderas"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Elegir modalidad de bachillerato es una decisión que conviene preparar con tiempo","Primero investigas qué materias y contenidos ofrece cada itinerario disponible en el centro","Después comparas con los grados universitarios o ciclos que te interesan más","Luego hablas con tu tutor y con orientación para contrastar tus ideas iniciales","Con esa información, tomas una decisión informada y coherente con tus objetivos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El pensamiento crítico empieza cuestionando la fuente de cualquier información que recibes","Después analizas las intenciones que puede tener quien emite ese mensaje concreto","A continuación buscas datos adicionales en medios diversos y contrastas versiones","Valoras si los argumentos se apoyan en hechos verificables o en opiniones","Finalmente formas tu propia opinión con base sólida y sin dejarte llevar"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El uso excesivo del móvil suele empezar de forma casi imperceptible para ti","Consultas primero algunas notificaciones, luego sigues con redes sociales durante largos minutos","Al final del día te das cuenta de que has perdido horas valiosas","Establecer momentos libres de pantalla devuelve el control sobre tu tiempo personal","Con pequeños cambios recuperas atención, sueño y capacidad de concentración en tus estudios"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La comunicación no violenta propone una estructura concreta para expresar conflictos interpersonales","Primero describes los hechos objetivos sin añadir interpretaciones ni juicios de valor","A continuación expresas cómo te sientes ante esa situación en concreto","Después identificas la necesidad que no está siendo atendida en tu caso","Finalmente formulas una petición clara, concreta y razonable al interlocutor"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La mentalidad de crecimiento se opone a la mentalidad fija en un aspecto esencial","Una persona con mentalidad fija cree que la inteligencia es estable y no cambia","Una persona con mentalidad de crecimiento entiende que las capacidades se desarrollan con esfuerzo","Ante un error, la primera se rinde mientras la segunda busca aprender","Esta diferencia de enfoque explica gran parte del éxito académico a largo plazo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Las metas SMART son una herramienta sencilla y eficaz para planificar objetivos","La S indica que deben ser específicas y no vagas ni generales","La M señala que han de ser medibles con criterios objetivos concretos","La A y la R recuerdan que deben ser alcanzables y realistas","La T añade un plazo temporal que empuja a actuar sin demora"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La técnica Feynman es un método infalible para comprobar si entiendes un concepto","Primero eliges el concepto que quieres dominar y lo estudias con atención","Después intentas explicarlo con palabras sencillas como si hablaras con un niño","Allí donde te atascas descubres exactamente qué parte no has comprendido bien","Vuelves al material, repasas esa laguna y repites el proceso hasta fluir"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El repaso espaciado aprovecha el funcionamiento natural de la memoria humana","Consiste en revisar el material con intervalos de tiempo cada vez más amplios","Primero repasas al día siguiente, luego a los tres días, después a la semana","Este patrón fortalece la huella mnemónica mucho más que el estudio masivo final","Estudios científicos confirman que es una de las técnicas más efectivas disponibles"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La resolución de conflictos empieza siempre por mantener la calma emocional del momento","A continuación ambas partes exponen su versión sin interrupciones mutuas ni descalificaciones","Se identifican los puntos de acuerdo y los puntos de desacuerdo con precisión","Después se buscan soluciones creativas que satisfagan al máximo los intereses de ambos","Finalmente se consensúa una salida y se establece un seguimiento para su cumplimiento"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La rueda de la vida es una herramienta de autoevaluación personal muy útil","Se dibuja un círculo dividido en áreas como estudios, familia, amigos y salud","En cada área puntúas de uno a diez tu grado de satisfacción actual","Al unir los puntos obtienes una imagen visual clara de tu equilibrio vital","Las áreas con menor puntuación se convierten en zonas prioritarias de trabajo personal"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El estrés académico puede manejarse con un conjunto de estrategias complementarias eficaces","La planificación previa reduce la acumulación de tareas en los momentos críticos","El ejercicio físico libera endorfinas que alivian la tensión acumulada del cuerpo","El contacto con personas cercanas aporta apoyo emocional esencial en épocas difíciles","Combinar estas estrategias permite atravesar periodos exigentes sin comprometer la salud mental"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Un ambiente de estudio adecuado influye directamente en la calidad del aprendizaje","Elige un espacio con buena iluminación preferentemente natural durante las horas diurnas","Mantén la mesa despejada con solo los materiales necesarios para la sesión actual","Silencia las notificaciones del móvil o déjalo fuera del alcance de tu vista","Con estas condiciones, tu concentración se sostiene durante periodos más largos y productivos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La elaboración de un buen resumen requiere varias lecturas del mismo texto","En la primera lectura captas la idea general sin subrayar todavía nada","En la segunda lectura identificas las ideas principales y secundarias claramente","En la tercera lectura redactas el resumen con tus propias palabras sin copiar","Este proceso fuerza la comprensión profunda y mejora la retención del contenido"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Cuando detectas una situación de acoso en tu entorno no puedes quedarte indiferente","Lo primero es no participar ni reírte de las agresiones contra la víctima","Después puedes ofrecer apoyo a la persona afectada en un momento discreto","A continuación informas a un adulto de confianza del centro educativo","Esta actitud colectiva es clave para romper la cadena del acoso escolar"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Los hábitos saludables se construyen sobre pequeñas rutinas sostenidas en el tiempo","Comienza eligiendo una sola conducta concreta que quieras incorporar a tu vida","Asóciala a otra actividad ya consolidada para que el recordatorio sea automático","Mantén la práctica diaria durante al menos tres semanas sin excepciones importantes","Cuando se vuelve automática, añades un siguiente hábito al andamiaje previamente establecido"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El perfeccionismo puede convertirse en un obstáculo serio para tu bienestar personal","Esperar resultados impecables en todo genera una presión autoimpuesta agotadora","Aceptar que el ochenta por ciento de perfección es suficiente libera una enorme energía","Este principio permite avanzar sin quedarte bloqueado en detalles irrelevantes del trabajo","Con el tiempo descubres que la calidad real aumenta al reducir el perfeccionismo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Las redes sociales muestran una versión cuidadosamente editada de la vida de otros","Comparar tu día cotidiano con esas imágenes irreales genera frustración y malestar","Reducir el tiempo de consumo y seguir cuentas realistas mitiga este efecto negativo","Recordar que no ves la vida completa sino unos pocos instantes seleccionados ayuda","Con esta perspectiva crítica protegerás tu autoestima del impacto del mundo online"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La escucha activa es una competencia comunicativa fundamental en cualquier relación humana","Implica prestar atención plena a quien habla sin pensar en tu próxima intervención","Utilizas señales verbales y no verbales para mostrar que estás realmente escuchando","Reformulas lo que has entendido para confirmar que habéis comprendido bien el mensaje","Esta práctica sencilla transforma la calidad de las conversaciones personales que mantienes"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La educación financiera básica es una herramienta imprescindible para tu vida adulta","El primer paso es llevar un registro sencillo de ingresos y gastos mensuales","Después identificas categorías de gasto innecesario que puedes reducir sin sacrificio","Estableces un porcentaje de ahorro fijo aunque sea pequeño al principio","Con el tiempo ese hábito construye una base económica sólida para el futuro"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El voluntariado aporta beneficios a la comunidad y también a quien lo realiza","Elige una causa que conecte con tus valores personales más profundos","Busca organizaciones cercanas que busquen personas con disponibilidad horaria parecida a la tuya","Comprométete con una frecuencia realista compatible con tus obligaciones de estudio","La experiencia enriquecerá tu crecimiento personal y tu currículum de forma notable"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La presión del grupo puede empujarte a hacer cosas que no compartes","Saber decir no con firmeza es una muestra de madurez y autonomía","Puedes explicar brevemente tu motivo sin necesidad de largas justificaciones defensivas","Si la presión persiste, alejarte del grupo es una opción completamente válida","Tus valores merecen más peso que la aprobación inmediata de personas ocasionales"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El diálogo interno influye de forma decisiva en tu rendimiento y bienestar","Un diálogo negativo constante genera ansiedad y reduce tu confianza en ti mismo","Detectar esos pensamientos automáticos es el primer paso para modificarlos con calma","Sustitúyelos por afirmaciones realistas basadas en hechos concretos de tu experiencia","Con práctica diaria tu voz interior se convierte en aliada en lugar de enemiga"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El mindfulness es una práctica que entrena la atención plena al momento presente","Sentado cómodamente, cierras los ojos y llevas la atención a tu respiración","Cuando aparecen pensamientos, los observas sin juzgarlos y vuelves a la respiración","Diez minutos diarios de esta práctica aportan beneficios notables al cabo de semanas","La mente entrenada se mantiene más serena ante situaciones cotidianas de presión"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Las relaciones tóxicas tienen señales de alerta reconocibles con atención plena","Sientes tensión constante y caminas sobre cáscaras de huevo en presencia de esa persona","Tu autoestima disminuye tras cada interacción con ella en lugar de crecer","Aparecen críticas frecuentes, control o descalificaciones disfrazadas de bromas hirientes","Detectar estas señales a tiempo permite establecer distancia antes de mayores daños"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Poner límites es una forma esencial de autocuidado emocional en tus relaciones","Primero identificas qué situaciones específicas te generan malestar o agotamiento recurrente","A continuación decides de forma clara qué comportamientos no quieres seguir aceptando","Comunicas tu límite con respeto pero con firmeza sin abrir negociaciones innecesarias","Mantenerlos con coherencia es lo que los convierte en realmente efectivos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La huella digital se construye con cada publicación, búsqueda o interacción online","Los datos que generas permanecen en la red mucho más tiempo del imaginado","Cualquier empresa o universidad puede buscar información tuya antes de una decisión","Pensar antes de publicar evita arrepentimientos futuros por contenidos impulsivos","Una reputación digital cuidada te abre puertas en lugar de cerrarlas"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Verificar una noticia antes de compartirla es una responsabilidad ciudadana en la era digital","Primero buscas la fuente original del titular que ha llegado a tus manos","A continuación compruebas si otros medios fiables confirman esa misma información","Si no hay confirmación independiente, te abstienes de reenviar el contenido","Con este sencillo hábito frenas la propagación de bulos y desinformación generalizada"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El consumo de alcohol en adolescentes afecta a un cerebro todavía en desarrollo","Los estudios científicos muestran daños cognitivos asociados a la ingesta temprana frecuente","La maduración de zonas clave del cerebro se completa hacia los veinticinco años","Retrasar el inicio del consumo protege capacidades de memoria y aprendizaje futuras","Conocer estos datos ayuda a tomar decisiones informadas en contextos sociales concretos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La gratitud es una práctica psicológica que mejora el bienestar emocional sostenido","Dedicar unos minutos al día a anotar tres cosas por las que estás agradecido","Con el tiempo tu cerebro entrena el foco hacia los aspectos positivos de la realidad","La ciencia ha demostrado reducciones claras de ansiedad en personas que practican gratitud","Es un hábito sencillo con un impacto profundo y accesible a cualquier edad"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La autoeficacia es la creencia en tu capacidad para lograr un objetivo concreto","Se construye a partir de pequeños éxitos acumulados que refuerzan la confianza","También se nutre de ver a personas parecidas a ti que alcanzan metas similares","La forma de interpretar tus emociones ante el reto influye en esta creencia","Una alta autoeficacia predice mejor rendimiento académico a medio y largo plazo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Las jornadas de puertas abiertas de las universidades son una oportunidad muy valiosa","Te permiten conocer directamente las instalaciones, profesorado y ambiente del campus","Preparar preguntas concretas antes de la visita maximiza el provecho de la experiencia","Hablar con estudiantes actuales aporta una visión realista difícil de obtener de otra forma","Asistir a varias opciones facilita una decisión final informada y coherente con tus prioridades"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Estudiar un idioma exige combinar diversas estrategias complementarias para ser efectivo","La exposición pasiva con series y canciones amplía vocabulario de forma gradual","La práctica activa con ejercicios y conversaciones consolida las estructuras aprendidas","Intercambios con personas nativas aceleran la fluidez y mejoran la pronunciación natural","Con constancia y paciencia, los progresos se vuelven visibles en cuestión de meses"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La autoestima sana se construye sobre la aceptación realista de uno mismo","Reconocer tus fortalezas sin exagerarlas te permite aprovecharlas con confianza en cualquier reto","Aceptar tus debilidades sin minusvalorarte te empuja a trabajar en ellas con constancia","No depender de la mirada externa otorga autonomía emocional y estabilidad interior","Esta base firme sostiene decisiones coherentes en momentos de incertidumbre o presión"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["El trabajo en equipo en el instituto te prepara para el mundo profesional","Primero se establecen unos objetivos comunes claros para todo el grupo","A continuación se reparten las tareas según habilidades e intereses individuales","Se acuerda una forma de comunicación regular con reuniones breves y efectivas","Finalmente se evalúa el proceso para aprender de los errores cometidos como grupo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Cuidar tu salud mental empieza por atender las señales tempranas de malestar","Tristeza persistente, pérdida de interés o problemas de sueño son indicios claros","Hablar con alguien de confianza abre una primera vía de alivio y perspectiva","Si los síntomas persisten, buscar ayuda profesional es un paso valiente y necesario","La salud mental merece la misma atención que cualquier otro aspecto del cuerpo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La educación afectivo-sexual se basa en información, respeto y consentimiento explícito","Conocer tu cuerpo y el de los demás forma parte del autocuidado básico","El consentimiento debe ser libre, informado, entusiasta y reversible en todo momento","Respetar los límites propios y ajenos es un principio innegociable de cualquier relación","Esta base sólida protege tu bienestar y el de las personas con quienes interactúas"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La igualdad de género se construye desde cada pequeña decisión cotidiana","Revisar estereotipos sobre profesiones, tareas o emociones es un primer paso imprescindible","Cuestionar comentarios machistas en tu entorno ayuda a transformar mentalidades colectivas","Tratar a las personas por sus cualidades individuales y no por su género avanza hacia la igualdad","Cada gesto cuenta en la construcción de una sociedad más justa y equitativa"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La técnica del cronograma inverso es útil para grandes trabajos académicos pendientes","Partes de la fecha de entrega final y vas hacia atrás en el tiempo","Identificas las fases principales del trabajo y les asignas una fecha límite propia","Añades márgenes de seguridad para imprevistos frecuentes durante el proceso","Esta planificación previa reduce muchísimo el estrés en las últimas semanas"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["La automotivación es la chispa que sostiene tu esfuerzo durante cursos largos","Conectar cada tarea con un propósito mayor la dota de significado profundo","Visualizar tu objetivo final de forma regular refuerza la motivación en los momentos bajos","Celebrar los pequeños avances libera dopamina y mantiene viva la ilusión del proyecto","Con estos mecanismos internos no dependes solo de estímulos externos para avanzar"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{1}', '["Los sesgos cognitivos son atajos mentales que a veces distorsionan nuestras decisiones","El sesgo de confirmación nos lleva a buscar solo datos que apoyan nuestras ideas","El sesgo de disponibilidad da más peso a lo que recordamos con facilidad","Conocer estos sesgos nos permite pensar de forma más crítica y equilibrada","Los pensadores maduros revisan sus propias conclusiones buscando activamente información contraria"]');

-- =====================================================
-- 2º BACHILLERATO (50 historias)
-- =====================================================

INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La EBAU es un momento decisivo que exige una estrategia de preparación bien pensada","Empiezas el curso haciendo un calendario con los temas de cada asignatura hasta mayo","A lo largo del año incorporas exámenes antiguos a tu rutina de estudio semanal","En la recta final te centras en revisar errores frecuentes y aclarar dudas concretas","Con este plan la prueba llega cuando ya has practicado la mayoría de escenarios"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La nota de admisión a un grado universitario se calcula con una fórmula concreta","Se toma un sesenta por ciento de la nota media del bachillerato","Se suma un cuarenta por ciento de la fase de acceso de la EBAU","A esa suma se pueden añadir hasta cuatro puntos de la fase específica","Esos puntos extra dependen de las ponderaciones que aplica cada universidad concreta"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Elegir grado universitario es una decisión importante que merece tiempo de reflexión","Primero exploras tus intereses reales y las materias que disfrutas estudiando","Después investigas los planes de estudio de varios grados que pueden encajar","Contrastas las salidas profesionales reales con los datos de empleabilidad disponibles","Finalmente decides con información suficiente y no solo por modas o prestigio aparente"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Los ciclos formativos de grado superior son una alternativa excelente a la universidad","Ofrecen una formación muy práctica y conectada con las necesidades reales del mercado","Las tasas de empleabilidad son a menudo comparables o superiores a muchos grados","La FP dual permite combinar aprendizaje en el aula con experiencia en empresas","Considerar esta opción amplía tu abanico de caminos profesionales tras el bachillerato"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La preparación para una entrevista profesional requiere varios pasos previos esenciales","Primero investigas la empresa, su historia, sus valores y sus proyectos actuales","Después repasas tu propio currículum preparando ejemplos concretos para cada apartado","Practicas respuestas a las preguntas más habituales ante un espejo o con alguien","El día de la entrevista llegas descansado, vestido adecuadamente y puntual al lugar"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Un buen currículum es una herramienta de marketing personal bien diseñada","El encabezado debe contener tus datos de contacto y un titular profesional claro","A continuación viene la formación académica en orden cronológico inverso con detalles","La experiencia se describe con verbos de acción y logros medibles concretos","Cierras con habilidades, idiomas y certificaciones relevantes para el puesto al que optas"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La marca personal online se construye con intención y continuidad durante meses","Primero decides qué imagen profesional quieres proyectar a un eventual reclutador","Después eliges las plataformas adecuadas según tu perfil y tu sector objetivo","Publicas contenido relevante con regularidad y participas en conversaciones de tu área","Con el tiempo, tu presencia digital se convierte en un currículum vivo y visible"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Las soft skills son competencias transversales muy valoradas en cualquier profesión","Incluyen comunicación efectiva, trabajo en equipo, resolución de problemas y liderazgo","Se desarrollan con práctica cotidiana en entornos colaborativos y de reto","Participar en proyectos grupales y voluntariados entrena estas habilidades de forma natural","Muchas empresas las consideran tan decisivas como los conocimientos técnicos específicos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La ansiedad ante la EBAU se gestiona con una combinación de estrategias complementarias","La preparación rigurosa desde el principio es la base que genera mayor tranquilidad","La realización de simulacros cronometrados entrena el cuerpo para las condiciones reales","Las técnicas de respiración y relajación reducen la activación fisiológica en momentos críticos","El descanso adecuado antes del examen consolida la información y protege la lucidez mental"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La preinscripción universitaria es un proceso con plazos concretos que conviene respetar","Tras conocer tu nota de EBAU, accedes al distrito único de tu comunidad","Eliges por orden de preferencia hasta un número determinado de titulaciones","Las plazas se asignan comparando tu nota con las notas de corte de cada grado","Si no entras en primera opción, existen adjudicaciones posteriores con nuevas oportunidades"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Solicitar una beca requiere planificación previa y atención a los detalles administrativos","Primero compruebas los requisitos económicos y académicos que exige la convocatoria","Después reúnes toda la documentación necesaria antes de abrir el proceso en línea","Cumplimentas la solicitud con calma comprobando cada dato antes de enviarla","Guardas los justificantes y haces seguimiento del estado hasta la resolución final"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El pensamiento crítico en la era digital es una herramienta de supervivencia intelectual","Ante cualquier información, lo primero es verificar la fuente y su trayectoria","A continuación compruebas si otros medios independientes confirman los mismos datos","Analizas los posibles intereses ocultos detrás del mensaje y su forma de presentación","Con este filtro evitas caer en manipulaciones o en bulos muy sofisticados"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Los algoritmos de redes sociales te muestran contenido afín a tus intereses previos","Esto genera burbujas informativas donde apenas te encuentras con ideas distintas","Con el tiempo esa exposición sesgada refuerza tus creencias y reduce tu pluralidad","Diversificar fuentes y seguir voces discrepantes amplía tu perspectiva sobre la realidad","Esta higiene informativa es esencial para tomar decisiones con criterio propio"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La inteligencia artificial generativa plantea un desafío ético en el entorno académico","Puede ser una herramienta útil si la usas para explorar y comprender ideas","Usarla para copiar respuestas sin entenderlas no genera aprendizaje ni competencias reales","Cada estudiante debe encontrar un uso honesto que potencie su propia comprensión","El criterio personal y la transparencia son claves en este nuevo escenario tecnológico"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El burnout académico es un agotamiento profundo que puede aparecer en cursos exigentes","Los primeros síntomas son cansancio constante, desmotivación y dificultad de concentración mental","Si se ignora, puede derivar en problemas de salud física y emocional más graves","La prevención pasa por equilibrar estudio, descanso, ocio y relaciones personales","Reconocer las señales a tiempo permite actuar antes de llegar al colapso"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El feedback constructivo es un arte que conviene dominar para crecer profesionalmente","Al darlo, se centra en conductas concretas observables y no en juicios personales","Se acompaña de ejemplos específicos y de propuestas de mejora alcanzables","Al recibirlo, se escucha sin interrumpir ni ponerse a la defensiva instintivamente","Tomarlo como información útil en lugar de ataque personal acelera tu desarrollo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La negociación efectiva busca soluciones en las que ambas partes ganen algo","El primer paso es preparar tus intereses reales antes de sentarte a negociar","A continuación escuchas activamente los intereses del otro sin suponer ni prejuzgar","Exploras juntos opciones creativas que satisfagan las necesidades centrales de ambos","Cierras el acuerdo con compromisos concretos y un plan de seguimiento posterior"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El liderazgo ético se basa en inspirar con el ejemplo y no en imponer","Un buen líder escucha a su equipo antes de tomar decisiones importantes","Delega tareas con confianza respetando la autonomía de quienes las ejecutan","Reconoce los logros colectivos y asume la responsabilidad en los momentos difíciles","Con esta actitud construye equipos motivados y comprometidos con el objetivo común"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La toma de decisiones complejas requiere un proceso estructurado con varios pasos","Primero defines con claridad el problema que quieres resolver sin confusiones","A continuación generas todas las opciones posibles sin descartar ninguna todavía","Evalúas cada opción en función de criterios relevantes y sus consecuencias previsibles","Eliges la mejor alternativa posible y te comprometes con su ejecución"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La independencia progresiva respecto a la familia forma parte del proceso madurativo","Empiezas asumiendo pequeñas decisiones cotidianas con responsabilidad y coherencia personal","Después gestionas tus propios tiempos, estudios y ocio sin necesidad de supervisión externa","Más adelante administras tu economía y planificas proyectos de mayor alcance","Este camino natural consolida una autonomía madura y un vínculo familiar sano"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Las becas Erasmus ofrecen una experiencia internacional transformadora durante los estudios universitarios","Vivir en otro país amplía tu perspectiva cultural y personal de forma muy notable","Aprendes a desenvolverte en un idioma extranjero con contextos reales cotidianos","Estableces una red de contactos internacional que permanece durante tu trayectoria profesional","Los beneficios suelen superar con mucho los retos iniciales de la adaptación"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La educación financiera a los dieciocho años previene errores económicos futuros","Aprendes primero a distinguir entre necesidades reales y deseos de consumo impulsivo","Después incorporas el hábito del ahorro regular por pequeño que sea","Comprendes cómo funcionan conceptos básicos como interés, deuda, inversión y diversificación","Con esta base tomas decisiones económicas alineadas con tus objetivos personales"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Afrontar un resultado de EBAU inferior al esperado exige perspectiva y estrategia","El primer paso es aceptar la realidad sin dramatizar ni minimizarla","A continuación exploras opciones reales: repetir prueba, otro grado, otra universidad o ciclo","Consultas con tu tutor y orientador sobre las alternativas concretas más adecuadas","Con información y calma, encuentras un camino coherente aunque sea distinto al inicial"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Preparar la mudanza a otra ciudad para estudiar requiere planificación anticipada","Primero investigas las opciones de alojamiento: residencia, piso compartido o familiar","Revisas los costes de vida en esa ciudad para ajustar tu presupuesto mensual","Organizas los trámites administrativos como empadronamiento o apertura de cuenta bancaria","Con todo previsto, tu llegada se convierte en un comienzo ordenado y tranquilo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Convivir en un piso compartido exige respeto, diálogo y normas acordadas","Desde el principio se establece un reparto justo de tareas domésticas rotativas","Se pacta cómo gestionar los gastos comunes de suministros y compras","Se respetan los horarios y espacios personales de cada compañero sin invadirlos","Un diálogo fluido ante cualquier problema evita que pequeños roces crezcan innecesariamente"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La prevención de adicciones se basa en información veraz y toma de decisiones","Conoces los efectos reales del alcohol, el cannabis y otras sustancias en el cerebro","Entiendes que las adicciones conductuales como el juego online también pueden atraparte","Desarrollas estrategias para decir no ante la presión del grupo en contextos sociales","Con este conocimiento, tus decisiones se alinean con el cuidado de tu salud"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La salud mental requiere la misma atención que la salud física del cuerpo","Detectar síntomas como tristeza persistente, ansiedad frecuente o insomnio es el primer paso","Hablar con alguien de confianza abre una vía inicial de alivio y perspectiva","Si los síntomas persisten, acudir a un profesional es una decisión madura y valiente","Normalizar esta búsqueda de ayuda rompe estigmas y protege tu bienestar a largo plazo"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El perfeccionismo extremo puede convertirse en un enemigo silencioso del rendimiento","Esperar resultados impecables en todo momento genera una presión insostenible con el tiempo","Aparecen bloqueos, retrasos en entregas y un malestar emocional constante y agotador","Aceptar que lo suficientemente bueno es mejor que nada libera energía y creatividad","Esta flexibilidad no baja la calidad sino que la multiplica con menos sufrimiento"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La resiliencia es la capacidad de superar la adversidad saliendo fortalecido del proceso","Se apoya en factores como el optimismo realista y una red de apoyo sólida","Implica reinterpretar los reveses como oportunidades de aprendizaje en lugar de fracasos","Se cultiva con prácticas diarias como la autocompasión y la gratitud","Las personas resilientes afrontan los retos con mayor serenidad y claridad mental"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La economía circular es un modelo productivo alternativo al consumo lineal tradicional","En el modelo lineal se extrae, se produce, se usa y se tira","En el modelo circular los materiales se reutilizan, reparan y reciclan de forma continua","Este enfoque reduce residuos y aprovecha mejor los recursos limitados del planeta","Adoptarlo a nivel personal contribuye de forma tangible a la sostenibilidad global"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Los Objetivos de Desarrollo Sostenible son una agenda común hasta el año 2030","Incluyen metas como la erradicación de la pobreza y el acceso universal a educación","Abordan también la igualdad de género, la acción climática y la paz","Cada persona puede contribuir con decisiones cotidianas alineadas con estos objetivos","El cambio colectivo empieza con la suma de muchos compromisos individuales concretos"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Convertirse en mayor de edad supone un cambio legal importante para ti","Adquieres capacidad plena para firmar contratos y asumir obligaciones jurídicas directamente","También puedes votar en elecciones y participar formalmente en la vida política","Conocer tus nuevos derechos y deberes evita sorpresas desagradables y malentendidos","Esta madurez legal va acompañada de una mayor responsabilidad personal cotidiana"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Leer un contrato antes de firmarlo es un hábito imprescindible en la vida adulta","Primero identificas las partes implicadas y el objeto concreto del contrato","Revisas las obligaciones que asumes y los plazos que debes cumplir","Compruebas las cláusulas de rescisión y las posibles penalizaciones económicas asociadas","Si algo no queda claro, consultas antes de firmar con tu nombre"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La brecha de género en la elección de grados sigue siendo una realidad","Ciertos itinerarios científicos y tecnológicos presentan aún una baja proporción femenina","Visibilizar referentes diversos ayuda a romper los estereotipos sobre determinadas profesiones","Fomentar vocaciones desde etapas tempranas transforma paulatinamente esta distribución desigual","La igualdad real se construye sobre decisiones libres y sin condicionantes culturales"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El ciberacoso en entornos escolares deja huellas psicológicas tan dañinas como las presenciales","La víctima se siente vigilada y atrapada incluso en su propio hogar","Las consecuencias emocionales pueden incluir ansiedad, aislamiento y pérdida de autoestima","La primera recomendación es no responder, conservar pruebas y contactar con un adulto","Bloquear al agresor y denunciar por los cauces adecuados interrumpe el daño"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La ética digital se extiende a muchos aspectos invisibles de tu vida cotidiana","Respetar los datos personales propios y ajenos protege la privacidad de todos","No descargar contenido pirata respeta el trabajo de quienes lo han creado","Citar correctamente las fuentes en tus trabajos reconoce la propiedad intelectual","Estas pequeñas decisiones definen el tipo de ciudadano digital que eliges ser"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["Las profesiones del futuro exigirán adaptabilidad al cambio tecnológico constante y acelerado","Los empleos más repetitivos están siendo automatizados con rapidez en muchos sectores","Surgen nuevas ocupaciones relacionadas con datos, inteligencia artificial y sostenibilidad","La capacidad de aprender a lo largo de la vida se convierte en esencial","Prepararse para reinventarse varias veces es una de las claves actuales del éxito"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El emprendimiento es una salida profesional viable que requiere una preparación específica","Primero detectas un problema real que afecta a un grupo concreto de personas","Diseñas una solución diferente que aporte valor a ese mercado potencial","Validas la idea con clientes reales antes de invertir demasiados recursos","Si funciona, escalas el proyecto con paciencia, constancia y capacidad de adaptación"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La mentoría es una relación de aprendizaje entre alguien con experiencia y una persona joven","El mentor comparte conocimientos, contactos y perspectivas durante un periodo acordado","El mentorizado aporta entusiasmo, preguntas y compromiso con su propio desarrollo","Ambos se benefician del intercambio con un enriquecimiento mutuo que fortalece vínculos","Buscar un mentor en tu área de interés acelera tu crecimiento profesional notablemente"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La orientación académica requiere información actualizada y asesoramiento personalizado especializado","El departamento de orientación del instituto es un primer recurso muy valioso","Las ferias universitarias ofrecen contacto directo con centros y representantes académicos","Las páginas oficiales de universidades aportan datos fiables sobre notas y planes de estudio","Combinar estas fuentes permite tomar decisiones bien fundamentadas sobre el futuro"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La despedida del bachillerato es un momento simbólico cargado de emociones mezcladas","Se cierra una etapa vital con amistades, profesores y rutinas compartidas durante años","Se abre otra llena de incertidumbre pero también de oportunidades nuevas","Permitirse sentir nostalgia y ilusión al mismo tiempo es parte del proceso","Guardar lo aprendido y avanzar con esperanza es la actitud más sana posible"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El año sabático bien planificado puede ser una opción válida para algunos estudiantes","Sirve para ganar claridad vocacional a través de experiencias diversas y reales","Puede incluir trabajo, voluntariado, viajes culturales o formación específica breve","Exige disciplina personal para no convertirlo en un año perdido sin rumbo","Con propósito y reflexión, aporta madurez difícil de obtener en el aula"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La gestión del tiempo en segundo de bachillerato se complica con nuevas exigencias","Primero divides la semana en bloques fijos asignando cada asignatura a su hueco","Incluyes también espacio para descanso, deporte y vida social sin descuidarlos","Revisas el plan semanalmente ajustando lo que no ha funcionado con flexibilidad","Este método dinámico te permite mantener el ritmo sin sacrificar tu bienestar"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La comunicación intercultural es una competencia muy valiosa en el mundo globalizado","Implica comprender que los códigos culturales varían entre países y regiones","Requiere respeto ante costumbres, valores y formas de relacionarse distintas a las propias","Evitar generalizaciones y estereotipos protege la calidad del intercambio humano","Esta habilidad abre puertas en carreras internacionales y relaciones personales enriquecedoras"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La reputación online se construye poco a poco con cada interacción digital","Un comentario impulsivo puede marcar tu imagen mucho después de haberlo publicado","Los reclutadores suelen buscar información sobre candidatos antes de contratarlos","Cuidar el contenido que compartes es una inversión en tu futuro profesional","La coherencia entre tu yo online y tu yo real fortalece tu credibilidad total"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La técnica del bloque único consiste en reservar tres horas seguidas de estudio profundo","Durante ese bloque no revisas mensajes, redes sociales ni notificaciones de ningún tipo","Te concentras en una sola tarea compleja avanzando con continuidad sostenida","Al terminar, haces una pausa real alejándote por completo del escritorio","Este método produce avances notables en tareas que requieren concentración profunda prolongada"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La elección entre universidad pública y privada es una decisión a ponderar con calma","La pública ofrece precios más accesibles y prestigio académico consolidado","La privada puede aportar grupos más reducidos y ciertas especializaciones concretas","El criterio relevante debe ser la calidad del plan de estudios y no el prestigio percibido","Analizar tus objetivos y recursos con realismo ayuda a tomar la mejor decisión"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La participación ciudadana se ejerce de muchas maneras más allá del voto","Puedes asociarte a colectivos que trabajen por causas que te importen","Participas en iniciativas cívicas locales con tu tiempo y tus ideas","Compartes información veraz en redes y rebates bulos con datos contrastados","Cada acción suma en la construcción de una sociedad más participativa y sana"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La resistencia al fracaso es una competencia clave en la vida adulta madura","Aceptar que errar forma parte natural de cualquier aprendizaje real alivia la presión","Analizar el fracaso con calma revela lecciones muy valiosas para la próxima vez","Reintentar con el ajuste incorporado es lo que distingue a quienes avanzan","Con esta actitud, cada caída se convierte en un peldaño hacia el crecimiento"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["La autoeficacia profesional se construye con pequeños éxitos acumulados a lo largo del tiempo","Cada tarea cumplida refuerza la creencia en tu propia capacidad de logro","Observar a personas parecidas a ti que han alcanzado metas similares te inspira","Las emociones ante los retos influyen en tu percepción de poder afrontarlos","Una alta autoeficacia predice mejor rendimiento en formación y primeros años laborales"]');
INSERT INTO ordena_historias (subject_id, level, grades, sentences) VALUES ('tutoria', 'bachillerato', '{2}', '["El final del bachillerato simboliza un umbral hacia una etapa nueva y desafiante","Has adquirido conocimientos, valores y experiencias que te acompañarán durante mucho tiempo","Los vínculos construidos con compañeros y profesores perduran más allá del aula","Delante aparecen oportunidades que exigirán tus mejores cualidades personales","Afrontar este comienzo con ilusión y preparación es la mejor manera de cruzar ese umbral"]');
