-- =====================================================
-- Frases nuevas para Valenciano ESO - Ordena la Frase
-- Total: 154 frases (26 + 39 + 57 + 32)
-- =====================================================

-- Valenciano 1º ESO (26 frases nuevas)
-- Temas: ortografía básica, categories gramaticals, la frase, diftongs
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('valenciano', 'eso', '{1}', 'Els diftongs creixents es formen quan una vocal dèbil va davant d''una vocal forta'),
('valenciano', 'eso', '{1}', 'Les paraules agudes porten accent gràfic quan acaben en vocal, en ese o en ene'),
('valenciano', 'eso', '{1}', 'El substantiu és la categoria gramatical que designa persones, animals, coses o idees'),
('valenciano', 'eso', '{1}', 'L''adjectiu qualificatiu acompanya el substantiu i n''expressa una qualitat o característica'),
('valenciano', 'eso', '{1}', 'El verb és el nucli del predicat i indica l''acció que realitza el subjecte'),
('valenciano', 'eso', '{1}', 'La frase nominal està formada per un determinant, un nucli i un complement del nom'),
('valenciano', 'eso', '{1}', 'Les vocals obertes del valencià són la a, la e oberta i la o oberta'),
('valenciano', 'eso', '{1}', 'Els determinants articles definits en valencià són el, la, els i les'),
('valenciano', 'eso', '{1}', 'La dièresi s''escriu sobre la u per indicar que es pronuncia en els grups güe i güi'),
('valenciano', 'eso', '{1}', 'El subjecte i el predicat són les dues parts fonamentals d''una oració gramatical'),
('valenciano', 'eso', '{1}', 'Les preposicions són paraules invariables que unixen elements dins d''una oració'),
('valenciano', 'eso', '{1}', 'Els pronoms personals forts de primera persona són jo per al singular i nosaltres per al plural'),
('valenciano', 'eso', '{1}', 'La lletra hac no representa cap so en valencià però s''escriu per tradició etimològica'),
('valenciano', 'eso', '{1}', 'El diftong decreixent es forma quan la vocal forta va seguida d''una vocal dèbil'),
('valenciano', 'eso', '{1}', 'Les conjuncions coordinants unixen paraules o oracions que tenen la mateixa funció sintàctica'),
('valenciano', 'eso', '{1}', 'L''adverbi és una paraula invariable que modifica el significat del verb o de l''adjectiu'),
('valenciano', 'eso', '{1}', 'El plural dels substantius acabats en vocal àtona es forma afegint una essa final'),
('valenciano', 'eso', '{1}', 'La síl·laba tònica és aquella que es pronuncia amb més intensitat dins d''una paraula'),
('valenciano', 'eso', '{1}', 'Les paraules esdrúixoles sempre porten accent gràfic sobre la síl·laba tònica'),
('valenciano', 'eso', '{1}', 'El guionet s''utilitza per unir els pronoms febles al verb en les formes imperatives'),
('valenciano', 'eso', '{1}', 'L''apòstrof substitueix la vocal final d''un article quan la paraula següent comença per vocal'),
('valenciano', 'eso', '{1}', 'Els signes d''interrogació i d''exclamació en valencià només es col·loquen al final de la frase'),
('valenciano', 'eso', '{1}', 'La essa sorda i la essa sonora es diferencien pel context fonètic en què apareixen'),
('valenciano', 'eso', '{1}', 'El punt i coma s''utilitza per separar oracions relacionades dins d''un mateix paràgraf'),
('valenciano', 'eso', '{1}', 'Les paraules planes porten accent gràfic quan no acaben en vocal, en essa o en ene'),
('valenciano', 'eso', '{1}', 'El complement directe rep l''acció del verb i es pot substituir per un pronom feble');

-- Valenciano 2º ESO (39 frases nuevas)
-- Temas: pronoms febles, oració composta, literatura medieval, Tirant lo Blanch
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('valenciano', 'eso', '{2}', 'Els pronoms febles es col·loquen davant del verb en les formes conjugades de l''indicatiu'),
('valenciano', 'eso', '{2}', 'La combinació de pronoms febles segueix un ordre establit per la normativa valenciana'),
('valenciano', 'eso', '{2}', 'Joanot Martorell va escriure el Tirant lo Blanch, una obra mestra de la literatura medieval'),
('valenciano', 'eso', '{2}', 'El Tirant lo Blanch narra les aventures d''un cavaller que lluita contra els turcs otomans'),
('valenciano', 'eso', '{2}', 'L''oració composta coordinada uneix dues oracions independents mitjançant una conjunció'),
('valenciano', 'eso', '{2}', 'Les conjuncions adversatives com però i sinó expressen contrast entre dues idees oposades'),
('valenciano', 'eso', '{2}', 'La literatura medieval valenciana va viure el seu segle d''or durant el segle quinze'),
('valenciano', 'eso', '{2}', 'El pronom feble en substitueix un complement que porta la preposició de davant'),
('valenciano', 'eso', '{2}', 'Les oracions juxtaposades s''uneixen sense cap nexe i se separen per signes de puntuació'),
('valenciano', 'eso', '{2}', 'Isabel de Villena va escriure la Vita Christi, una obra religiosa de gran valor literari'),
('valenciano', 'eso', '{2}', 'El pronom feble hi substitueix complements introduïts per preposicions com a o en'),
('valenciano', 'eso', '{2}', 'Les conjuncions disjuntives com o i o bé presenten una alternativa entre dues opcions'),
('valenciano', 'eso', '{2}', 'L''Espill de Jaume Roig és un poema narratiu escrit en versos curts de quatre síl·labes'),
('valenciano', 'eso', '{2}', 'El pronom feble ho substitueix una oració completa o un complement amb valor neutre'),
('valenciano', 'eso', '{2}', 'Les conjuncions copulatives com i i ni serveixen per sumar o acumular elements en la frase'),
('valenciano', 'eso', '{2}', 'La impremta de València va publicar el Tirant lo Blanch l''any mil quatre-cents noranta'),
('valenciano', 'eso', '{2}', 'El complement indirecte indica la persona que rep el benefici o el perjudici de l''acció'),
('valenciano', 'eso', '{2}', 'Ausiàs March és considerat el primer gran poeta que va escriure exclusivament en valencià'),
('valenciano', 'eso', '{2}', 'Les oracions coordinades explicatives utilitzen nexes com és a dir o o siga'),
('valenciano', 'eso', '{2}', 'El pronom feble li és la forma de datiu singular per al complement indirecte de tercera persona'),
('valenciano', 'eso', '{2}', 'Roís de Corella va cultivar la prosa humanista i va influir en la narrativa del segle quinze'),
('valenciano', 'eso', '{2}', 'Les oracions coordinades distributives presenten accions alternes amb nexes com ara o ara'),
('valenciano', 'eso', '{2}', 'El pronom feble els pot funcionar com a acusatiu plural o com a datiu plural segons el context'),
('valenciano', 'eso', '{2}', 'La poesia trobadoresca va influir en els primers textos literaris escrits en llengua valenciana'),
('valenciano', 'eso', '{2}', 'El Misteri d''Elx és una representació teatral medieval que es conserva viva fins als nostres dies'),
('valenciano', 'eso', '{2}', 'Les oracions subordinades depenen d''una oració principal i no tenen sentit complet per si soles'),
('valenciano', 'eso', '{2}', 'El pronom feble es pot tenir valor reflexiu quan el subjecte i el complement coincideixen'),
('valenciano', 'eso', '{2}', 'Les cròniques medievals de Jaume Primer narren la conquesta del Regne de València'),
('valenciano', 'eso', '{2}', 'La concordança entre el subjecte i el verb obliga a mantenir el mateix nombre i persona'),
('valenciano', 'eso', '{2}', 'El Llibre dels Fets és una autobiografia reial que descriu les gestes de Jaume Primer'),
('valenciano', 'eso', '{2}', 'El pronom feble la substitueix un complement directe femení singular en tercera persona'),
('valenciano', 'eso', '{2}', 'Les Regles d''esquivar vocables dificulten la comprensió dels criteris ortogràfics antics'),
('valenciano', 'eso', '{2}', 'L''oració composta subordinada conté una oració que funciona com a complement d''una altra'),
('valenciano', 'eso', '{2}', 'Sant Vicent Ferrer va ser un orador medieval que predicava en valencià per tot Europa'),
('valenciano', 'eso', '{2}', 'El pronom feble ens representa la primera persona del plural com a complement directe o indirecte'),
('valenciano', 'eso', '{2}', 'La novel·la cavalleresca del Tirant destaca pel seu realisme enfront d''altres obres fantàstiques'),
('valenciano', 'eso', '{2}', 'Les conjuncions consecutives com per tant i doncs introdueixen una conseqüència lògica'),
('valenciano', 'eso', '{2}', 'El pronom feble us correspon a la segona persona del plural i funciona com a datiu o acusatiu'),
('valenciano', 'eso', '{2}', 'La València medieval va ser un centre cultural on coincidiren escriptors de gran renom literari');

-- Valenciano 3º ESO (57 frases nuevas)
-- Temas: subordinació, literatura dels segles XVI-XIX, Ausiàs March, normativa
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('valenciano', 'eso', '{3}', 'Les oracions subordinades substantives fan la funció de subjecte o de complement directe del verb principal'),
('valenciano', 'eso', '{3}', 'Ausiàs March va introduir la introspecció sentimental com a tema central de la seua poesia lírica'),
('valenciano', 'eso', '{3}', 'Les subordinades adjectives o de relatiu modifiquen un substantiu de l''oració principal amb informació addicional'),
('valenciano', 'eso', '{3}', 'La Decadència és el període en què la literatura valenciana va perdre prestigi entre els segles setze i dinou'),
('valenciano', 'eso', '{3}', 'El nexe que introdueix les oracions subordinades substantives és la conjunció que seguida d''un verb conjugat'),
('valenciano', 'eso', '{3}', 'Teodor Llorente va ser un poeta clau de la Renaixença valenciana amb obres com el Llibret de Versos'),
('valenciano', 'eso', '{3}', 'Les subordinades adverbials de temps indiquen quan es produeix l''acció de l''oració principal'),
('valenciano', 'eso', '{3}', 'La normativa de l''Acadèmia Valenciana de la Llengua regula l''ortografia i la gramàtica del valencià'),
('valenciano', 'eso', '{3}', 'Les subordinades causals expressen el motiu o la raó per la qual ocorre l''acció principal'),
('valenciano', 'eso', '{3}', 'Ausiàs March distingia entre l''amor honest i l''amor sensual en els seus poemes més coneguts'),
('valenciano', 'eso', '{3}', 'El pronom relatiu que és invariable i pot referir-se a persones o coses sense distinció'),
('valenciano', 'eso', '{3}', 'La Renaixença valenciana va recuperar la consciència lingüística i literària durant el segle dinou'),
('valenciano', 'eso', '{3}', 'Les subordinades condicionals estableixen una condició necessària perquè es complisca l''acció principal'),
('valenciano', 'eso', '{3}', 'Constantí Llombart va fundar la societat Lo Rat Penat per a promoure la llengua i la cultura valencianes'),
('valenciano', 'eso', '{3}', 'El pronom relatiu el qual concorda en gènere i nombre amb l''antecedent que substitueix'),
('valenciano', 'eso', '{3}', 'Les subordinades concessives introduïdes per encara que expressen un obstacle que no impedeix l''acció'),
('valenciano', 'eso', '{3}', 'La poesia d''Ausiàs March abandona la tradició trobadoresca i utilitza el valencià sense occitanismes'),
('valenciano', 'eso', '{3}', 'Les Normes de Castelló de mil nou-cents trenta-dos van unificar l''ortografia del valencià modern'),
('valenciano', 'eso', '{3}', 'Les subordinades finals expressen la finalitat o l''objectiu amb què es realitza l''acció del verb principal'),
('valenciano', 'eso', '{3}', 'Durant la Decadència el valencià va quedar relegat a l''àmbit familiar i a la literatura popular'),
('valenciano', 'eso', '{3}', 'El mode subjuntiu s''utilitza en les oracions subordinades que expressen desig, dubte o possibilitat'),
('valenciano', 'eso', '{3}', 'Joan Roís de Corella va escriure la Tragèdia de Caldesa considerada la primera novel·la curta en valencià'),
('valenciano', 'eso', '{3}', 'Les subordinades comparatives estableixen una comparació de superioritat, igualtat o inferioritat entre elements'),
('valenciano', 'eso', '{3}', 'La diglòssia és la situació en què una llengua de prestigi conviu amb una altra d''ús familiar'),
('valenciano', 'eso', '{3}', 'Les subordinades consecutives expressen una conseqüència derivada de la intensitat de l''acció principal'),
('valenciano', 'eso', '{3}', 'Bernat i Baldoví va ser un escriptor popular del segle dinou que cultivà el sainet en valencià'),
('valenciano', 'eso', '{3}', 'L''oració subordinada de relatiu explicativa va entre comes i afegeix informació no essencial'),
('valenciano', 'eso', '{3}', 'El procés de normativització del valencià va buscar dotar la llengua d''unes regles ortogràfiques estables'),
('valenciano', 'eso', '{3}', 'L''oració subordinada de relatiu especificativa restringeix el significat de l''antecedent sense comes'),
('valenciano', 'eso', '{3}', 'Ausiàs March va organitzar els seus poemes en cicles temàtics com els cants d''amor i els cants de mort'),
('valenciano', 'eso', '{3}', 'Les subordinades modals introduïdes per com o segons indiquen la manera en què es realitza l''acció'),
('valenciano', 'eso', '{3}', 'La literatura del Barroc valencià va produir obres religioses i populars de menor projecció culta'),
('valenciano', 'eso', '{3}', 'El connector perquè funciona com a causal quan porta accent i com a final quan no en porta'),
('valenciano', 'eso', '{3}', 'Les Normes de Castelló van ser signades per escriptors i entitats culturals de tot el territori valencià'),
('valenciano', 'eso', '{3}', 'Les subordinades locatives introduïdes per on indiquen el lloc on es desenvolupa l''acció del verb'),
('valenciano', 'eso', '{3}', 'El segle d''or valencià va produir obres cabdals com el Tirant, l''Espill i els poemes d''Ausiàs March'),
('valenciano', 'eso', '{3}', 'La concordança del participi amb el complement directe és obligatòria quan aquest va davant del verb'),
('valenciano', 'eso', '{3}', 'La Renaixença va impulsar els Jocs Florals com a certàmens literaris per a dignificar la llengua'),
('valenciano', 'eso', '{3}', 'El gerundi expressa una acció simultània o anterior a la del verb principal de l''oració'),
('valenciano', 'eso', '{3}', 'Joan Fuster va ser un assagista del segle vint que va reflexionar sobre la identitat valenciana'),
('valenciano', 'eso', '{3}', 'Les perífrasis verbals d''obligació com haver de més infinitiu indiquen necessitat de fer una acció'),
('valenciano', 'eso', '{3}', 'La interferència lingüística del castellà sobre el valencià produeix fenòmens com el castellanisme lèxic'),
('valenciano', 'eso', '{3}', 'L''infinitiu pot funcionar com a nucli d''una oració subordinada substantiva en funció de subjecte'),
('valenciano', 'eso', '{3}', 'Vicent Andrés Estellés va renovar la poesia valenciana contemporània amb un llenguatge directe i popular'),
('valenciano', 'eso', '{3}', 'Les oracions passives es formen amb el verb ser més el participi del verb principal concordat'),
('valenciano', 'eso', '{3}', 'L''Acadèmia Valenciana de la Llengua va ser creada l''any mil nou-cents noranta-huit per llei autonòmica'),
('valenciano', 'eso', '{3}', 'El complement agent de l''oració passiva s''introdueix amb la preposició per i indica qui fa l''acció'),
('valenciano', 'eso', '{3}', 'La premsa en valencià va aparéixer durant el segle dinou com a instrument de difusió cultural'),
('valenciano', 'eso', '{3}', 'Les oracions impersonals no tenen subjecte gramatical i es formen amb verbs com haver-hi o caldre'),
('valenciano', 'eso', '{3}', 'Manuel Sanchis Guarner va ser un filòleg que va contribuir a la codificació del valencià modern'),
('valenciano', 'eso', '{3}', 'El complement predicatiu concorda amb el subjecte o amb el complement directe en gènere i nombre'),
('valenciano', 'eso', '{3}', 'La literatura de la Renaixença va posar les bases per a la recuperació literària del valencià culte'),
('valenciano', 'eso', '{3}', 'Les oracions de relatiu lliures no tenen antecedent explícit i funcionen com a substantives'),
('valenciano', 'eso', '{3}', 'Enric Valor va escriure rondalles que van preservar la tradició oral valenciana en forma literària'),
('valenciano', 'eso', '{3}', 'El complement circumstancial de manera respon a la pregunta com es realitza l''acció del verb'),
('valenciano', 'eso', '{3}', 'L''ús del subjuntiu en les subordinades depén del verb de l''oració principal i del seu significat'),
('valenciano', 'eso', '{3}', 'La normalització lingüística és el procés social per a recuperar l''ús del valencià en tots els àmbits');

-- Valenciano 4º ESO (32 frases nuevas)
-- Temas: literatura contemporània, comentari de text, registres lingüístics
INSERT INTO ordena_frases (subject_id, level, grades, sentence) VALUES
('valenciano', 'eso', '{4}', 'El comentari de text requereix identificar el tema, l''estructura, els recursos expressius i la intenció comunicativa'),
('valenciano', 'eso', '{4}', 'El registre col·loquial es caracteritza per l''espontaneïtat, la subjectivitat i l''ús de frases fetes'),
('valenciano', 'eso', '{4}', 'Mercè Rodoreda va influir en la narrativa valenciana contemporània amb el seu estil introspectiu i simbòlic'),
('valenciano', 'eso', '{4}', 'El registre formal s''utilitza en contextos acadèmics i professionals amb un lèxic precís i estructurat'),
('valenciano', 'eso', '{4}', 'La generació dels setanta va renovar la literatura valenciana amb autors compromesos socialment'),
('valenciano', 'eso', '{4}', 'L''anàlisi morfosintàctica consisteix a identificar la categoria gramatical i la funció de cada paraula'),
('valenciano', 'eso', '{4}', 'El registre literari empra figures retòriques com la metàfora, la comparació i la personificació'),
('valenciano', 'eso', '{4}', 'Joan Francesc Mira va escriure narrativa i assaig que reflexiona sobre la societat valenciana actual'),
('valenciano', 'eso', '{4}', 'La coherència textual exigeix que totes les idees d''un text estiguen relacionades amb el tema principal'),
('valenciano', 'eso', '{4}', 'El registre científic utilitza un vocabulari tècnic, oracions impersonals i un to objectiu i neutre'),
('valenciano', 'eso', '{4}', 'Isabel Clara Simó va tractar en les seues novel·les temes socials amb una prosa directa i combativa'),
('valenciano', 'eso', '{4}', 'La cohesió textual s''aconsegueix mitjançant connectors, pronoms, sinònims i la repetició lèxica controlada'),
('valenciano', 'eso', '{4}', 'El registre periodístic combina la funció informativa amb l''ús d''un llenguatge clar i accessible'),
('valenciano', 'eso', '{4}', 'Vicent Andrés Estellés va convertir el quotidià en matèria poètica amb un to popular i reivindicatiu'),
('valenciano', 'eso', '{4}', 'Les tipologies textuals bàsiques són la narració, la descripció, l''exposició, l''argumentació i el diàleg'),
('valenciano', 'eso', '{4}', 'El registre administratiu s''identifica per l''ús de fórmules fixes, un to impersonal i vocabulari jurídic'),
('valenciano', 'eso', '{4}', 'Carmelina Sánchez-Cutillas va guanyar el premi Octubre amb la novel·la Matèria de Bretanya l''any setanta-six'),
('valenciano', 'eso', '{4}', 'L''argumentació requereix una tesi clara, arguments sòlids i una conclusió que reforce la idea defensada'),
('valenciano', 'eso', '{4}', 'La variació diatòpica del valencià inclou diferències lèxiques i fonètiques entre comarques i zones'),
('valenciano', 'eso', '{4}', 'El teatre independent valencià de postguerra va buscar nous espais i públics fora dels circuits comercials'),
('valenciano', 'eso', '{4}', 'El text expositiu organitza la informació de manera clara seguint una estructura de presentació i desenvolupament'),
('valenciano', 'eso', '{4}', 'La variació diafàsica depén de la situació comunicativa i determina el grau de formalitat del discurs'),
('valenciano', 'eso', '{4}', 'Josep Piera va aportar una poesia reflexiva i mediterrània vinculada a la tradició d''Ausiàs March'),
('valenciano', 'eso', '{4}', 'El text argumentatiu utilitza connectors causals, consecutius i contraargumentatius per estructurar les idees'),
('valenciano', 'eso', '{4}', 'La variació diastràtica reflecteix diferències lingüístiques relacionades amb el nivell sociocultural del parlant'),
('valenciano', 'eso', '{4}', 'Ferran Torrent va popularitzar la novel·la negra en valencià amb personatges urbans i llenguatge col·loquial'),
('valenciano', 'eso', '{4}', 'El resum d''un text ha de recollir les idees principals amb paraules pròpies i sense opinions personals'),
('valenciano', 'eso', '{4}', 'La sociolingüística estudia la relació entre la llengua i la societat, incloent-hi el bilingüisme i la diglòssia'),
('valenciano', 'eso', '{4}', 'Lluís Alpera va contribuir a la poesia valenciana contemporània amb obres de caràcter social i reflexiu'),
('valenciano', 'eso', '{4}', 'Les figures retòriques de pensament com la ironia i la hipèrbole reforcen el missatge del text literari'),
('valenciano', 'eso', '{4}', 'La Llei d''Ús i Ensenyament del Valencià de mil nou-cents vuitanta-tres va establir el marc legal bilingüe'),
('valenciano', 'eso', '{4}', 'El comentari crític d''un text literari inclou la contextualització històrica, l''anàlisi formal i la valoració personal');
