-- Seed: Detective de Palabras - Bachillerato Idiomas (inglés, francés, valenciano)
-- 240 frases nuevas (40 por combo x 6 combos)
-- Temáticas: cultura, literatura, historia, sociedad del idioma correspondiente
-- Nivel: B1-B2 (1º Bach) / B2-C1 (2º Bach)

-- =============================================================================
-- INGLÉS - 1º BACHILLERATO (40 frases) - B1-B2
-- Shakespeare, British history, science, literature
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('ingles', 'bachillerato', '{1}', 'William Shakespeare was born in Stratford upon Avon in the sixteenth century and became the greatest English playwright'),
('ingles', 'bachillerato', '{1}', 'The Globe Theatre in London was the original stage where many of Shakespeare plays were first performed'),
('ingles', 'bachillerato', '{1}', 'Charles Dickens wrote Oliver Twist to expose the terrible conditions faced by poor children in Victorian England'),
('ingles', 'bachillerato', '{1}', 'The Industrial Revolution began in Britain during the eighteenth century and transformed the whole world economy'),
('ingles', 'bachillerato', '{1}', 'Isaac Newton discovered the laws of gravity while watching an apple fall from a tree in his garden'),
('ingles', 'bachillerato', '{1}', 'The British Empire at its peak controlled about one quarter of the total land surface of the Earth'),
('ingles', 'bachillerato', '{1}', 'Queen Victoria reigned for over sixty years and her era is known as the Victorian period in history'),
('ingles', 'bachillerato', '{1}', 'Jane Austen wrote Pride and Prejudice which explores love marriage and social class in Regency England'),
('ingles', 'bachillerato', '{1}', 'The Beatles became the most famous rock band in history and changed popular music forever during the sixties'),
('ingles', 'bachillerato', '{1}', 'Big Ben is actually the name of the bell inside the clock tower at the Palace of Westminster'),
('ingles', 'bachillerato', '{1}', 'Stonehenge is a prehistoric monument in Wiltshire whose exact purpose still remains a mystery to archaeologists'),
('ingles', 'bachillerato', '{1}', 'The London Underground is the oldest subway system in the world and started operating in eighteen sixty three'),
('ingles', 'bachillerato', '{1}', 'Winston Churchill led the United Kingdom through the most difficult years of the Second World War'),
('ingles', 'bachillerato', '{1}', 'Edinburgh is the capital of Scotland and hosts the largest arts festival in the world every August'),
('ingles', 'bachillerato', '{1}', 'The British Parliament is divided into two chambers the House of Commons and the House of Lords'),
('ingles', 'bachillerato', '{1}', 'Charles Darwin developed the theory of evolution after travelling around the world on a ship called Beagle'),
('ingles', 'bachillerato', '{1}', 'The Tower of London has served as a royal palace a prison and a treasury throughout its long history'),
('ingles', 'bachillerato', '{1}', 'Agatha Christie is the best selling novelist of all time with her famous detective Hercule Poirot'),
('ingles', 'bachillerato', '{1}', 'The Magna Carta was signed in twelve fifteen and became a symbol of rights and liberties in England'),
('ingles', 'bachillerato', '{1}', 'Oxford and Cambridge are two of the oldest and most prestigious universities in the English speaking world'),
('ingles', 'bachillerato', '{1}', 'The Lake District in northern England inspired many Romantic poets like William Wordsworth and Samuel Coleridge'),
('ingles', 'bachillerato', '{1}', 'Alexander Fleming accidentally discovered penicillin in his laboratory and saved millions of human lives'),
('ingles', 'bachillerato', '{1}', 'Sherlock Holmes is the fictional detective created by Arthur Conan Doyle who lives at Baker Street'),
('ingles', 'bachillerato', '{1}', 'The Thames is the most important river in England and flows through the centre of London city'),
('ingles', 'bachillerato', '{1}', 'J K Rowling wrote the Harry Potter series in Edinburgh cafes while she was a single mother'),
('ingles', 'bachillerato', '{1}', 'The Scottish Highlands offer some of the most beautiful and dramatic natural landscapes in Great Britain'),
('ingles', 'bachillerato', '{1}', 'Buckingham Palace has been the official London residence of British monarchs since the year eighteen thirty seven'),
('ingles', 'bachillerato', '{1}', 'Romeo and Juliet tells the tragic story of two young lovers from rival families in the city of Verona'),
('ingles', 'bachillerato', '{1}', 'The Beatles were formed in Liverpool and their members were John Paul George and Ringo Starr'),
('ingles', 'bachillerato', '{1}', 'Emily Bronte wrote Wuthering Heights a novel about passion and revenge set in the Yorkshire moors'),
('ingles', 'bachillerato', '{1}', 'The English breakfast traditionally includes eggs bacon sausages beans mushrooms tomatoes and toast with tea'),
('ingles', 'bachillerato', '{1}', 'Christopher Wren designed Saint Paul Cathedral after the Great Fire of London destroyed most of the city'),
('ingles', 'bachillerato', '{1}', 'Lewis Carroll wrote Alice in Wonderland while working as a mathematics teacher at Oxford University'),
('ingles', 'bachillerato', '{1}', 'The Roman Empire occupied Britain for nearly four hundred years and left behind roads walls and cities'),
('ingles', 'bachillerato', '{1}', 'Robin Hood is a legendary hero who supposedly lived in Sherwood Forest stealing from the rich and giving to the poor'),
('ingles', 'bachillerato', '{1}', 'The Prime Meridian passes through Greenwich in London and divides the world into east and west hemispheres'),
('ingles', 'bachillerato', '{1}', 'King Arthur is a legendary British king whose stories are linked to the knights of the Round Table'),
('ingles', 'bachillerato', '{1}', 'Shakespeare wrote thirty seven plays including tragedies comedies and historical dramas during his lifetime'),
('ingles', 'bachillerato', '{1}', 'The Union Jack combines the crosses of Saint George Saint Andrew and Saint Patrick in one single flag'),
('ingles', 'bachillerato', '{1}', 'Fish and chips became the traditional takeaway meal in Britain during the nineteenth century near working class towns');

-- =============================================================================
-- INGLÉS - 2º BACHILLERATO (40 frases) - B2-C1
-- Advanced culture, philosophy, politics, economics
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('ingles', 'bachillerato', '{2}', 'Adam Smith published The Wealth of Nations and laid the foundations of modern economic and market theory'),
('ingles', 'bachillerato', '{2}', 'John Locke argued that government legitimacy derives from the consent of the governed and natural rights'),
('ingles', 'bachillerato', '{2}', 'The Glorious Revolution of sixteen eighty eight established constitutional monarchy as the basis of British government'),
('ingles', 'bachillerato', '{2}', 'George Orwell wrote Nineteen Eighty Four as a warning against totalitarianism and the dangers of mass surveillance'),
('ingles', 'bachillerato', '{2}', 'The Brexit referendum in twenty sixteen marked a historical turning point in relations between Britain and Europe'),
('ingles', 'bachillerato', '{2}', 'Virginia Woolf revolutionised modernist literature with her stream of consciousness technique in novels like Mrs Dalloway'),
('ingles', 'bachillerato', '{2}', 'The Bank of England was founded in sixteen ninety four and remains one of the oldest central banks in existence'),
('ingles', 'bachillerato', '{2}', 'Thomas Hobbes defended in Leviathan that absolute sovereignty was necessary to prevent the state of nature'),
('ingles', 'bachillerato', '{2}', 'The British Welfare State was established after the Second World War following the Beveridge Report recommendations'),
('ingles', 'bachillerato', '{2}', 'James Joyce wrote Ulysses in Paris as a modernist masterpiece that revolutionised the novel as a literary form'),
('ingles', 'bachillerato', '{2}', 'Margaret Thatcher became the first female Prime Minister and implemented economic policies known as Thatcherism'),
('ingles', 'bachillerato', '{2}', 'T S Eliot wrote The Waste Land capturing the sense of spiritual desolation after the First World War'),
('ingles', 'bachillerato', '{2}', 'The Enlightenment period produced philosophers such as David Hume who questioned the foundations of human knowledge'),
('ingles', 'bachillerato', '{2}', 'John Maynard Keynes developed economic theories advocating government intervention during times of financial crisis'),
('ingles', 'bachillerato', '{2}', 'Aldous Huxley imagined in Brave New World a dystopian society controlled through pleasure and genetic engineering'),
('ingles', 'bachillerato', '{2}', 'The Commonwealth of Nations is an association of fifty six countries most of them former British colonies'),
('ingles', 'bachillerato', '{2}', 'Oscar Wilde satirised Victorian society in plays like The Importance of Being Earnest and novels about moral decay'),
('ingles', 'bachillerato', '{2}', 'The Suffragette movement fought for decades until women finally achieved the right to vote in nineteen eighteen'),
('ingles', 'bachillerato', '{2}', 'Samuel Beckett wrote Waiting for Godot as an absurdist play questioning the meaning of human existence itself'),
('ingles', 'bachillerato', '{2}', 'The British Royal Family retains a ceremonial role despite the country being a constitutional parliamentary democracy'),
('ingles', 'bachillerato', '{2}', 'Alan Turing cracked the Enigma code during the war and later founded the principles of modern computer science'),
('ingles', 'bachillerato', '{2}', 'The Romantic movement in British literature celebrated nature emotion and the individual imagination over cold reason'),
('ingles', 'bachillerato', '{2}', 'Graham Greene explored themes of faith betrayal and moral ambiguity in novels like The Power and the Glory'),
('ingles', 'bachillerato', '{2}', 'The Magna Carta established for the first time that even the king must be subject to the rule of law'),
('ingles', 'bachillerato', '{2}', 'William Blake combined poetry and visual art in his illuminated books such as Songs of Innocence and Experience'),
('ingles', 'bachillerato', '{2}', 'The Battle of Trafalgar secured British naval supremacy for over a century under the command of Admiral Nelson'),
('ingles', 'bachillerato', '{2}', 'Kazuo Ishiguro won the Nobel Prize in Literature for novels exploring memory identity and historical trauma'),
('ingles', 'bachillerato', '{2}', 'The British Museum in London contains millions of artefacts representing cultures from all around the world'),
('ingles', 'bachillerato', '{2}', 'Doris Lessing examined gender politics and colonialism in novels set in Africa and post war London'),
('ingles', 'bachillerato', '{2}', 'The Financial Crisis of two thousand eight began with the collapse of major American and British banking institutions'),
('ingles', 'bachillerato', '{2}', 'Ian McEwan explores moral dilemmas and human relationships in contemporary novels such as Atonement and Enduring Love'),
('ingles', 'bachillerato', '{2}', 'The House of Lords is the upper chamber of the British Parliament and includes both hereditary and life peers'),
('ingles', 'bachillerato', '{2}', 'Bertrand Russell was a philosopher mathematician and social activist who won the Nobel Prize in Literature in nineteen fifty'),
('ingles', 'bachillerato', '{2}', 'Salman Rushdie explored postcolonial themes in Midnight Children which won the Booker Prize in nineteen eighty one'),
('ingles', 'bachillerato', '{2}', 'The National Health Service provides free healthcare to all British citizens and is funded through general taxation'),
('ingles', 'bachillerato', '{2}', 'William Golding wrote Lord of the Flies as a dark allegory about human nature and the fragility of civilisation'),
('ingles', 'bachillerato', '{2}', 'The Declaration of Human Rights was largely influenced by British philosophical traditions concerning liberty and justice'),
('ingles', 'bachillerato', '{2}', 'Joseph Conrad wrote Heart of Darkness based on his experiences navigating rivers during the colonial era'),
('ingles', 'bachillerato', '{2}', 'Stephen Hawking revolutionised our understanding of black holes and wrote popular books about the nature of time and space'),
('ingles', 'bachillerato', '{2}', 'Harold Pinter developed a theatrical style characterised by ambiguous dialogue pauses and underlying menace on stage');

-- =============================================================================
-- FRANCÉS - 1º BACHILLERATO (40 frases) - B1-B2
-- Victor Hugo, Révolution française, culture
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('frances', 'bachillerato', '{1}', 'Victor Hugo a écrit Les Misérables un roman qui dénonce les injustices sociales de la France du dix-neuvième siècle'),
('frances', 'bachillerato', '{1}', 'La Révolution française a commencé en mil sept cent quatre-vingt-neuf avec la prise de la Bastille'),
('frances', 'bachillerato', '{1}', 'Napoléon Bonaparte est devenu empereur des Français et a conquis une grande partie de l''Europe continentale'),
('frances', 'bachillerato', '{1}', 'La tour Eiffel a été construite pour l''Exposition universelle de mil huit cent quatre-vingt-neuf à Paris'),
('frances', 'bachillerato', '{1}', 'Le Louvre est le musée le plus visité du monde et abrite la célèbre peinture de la Joconde'),
('frances', 'bachillerato', '{1}', 'Jeanne d''Arc est une héroïne française qui a combattu les Anglais pendant la guerre de Cent Ans'),
('frances', 'bachillerato', '{1}', 'Alexandre Dumas a écrit Les Trois Mousquetaires un roman d''aventures très populaire dans le monde entier'),
('frances', 'bachillerato', '{1}', 'La Déclaration des droits de l''homme et du citoyen a été adoptée pendant la Révolution française'),
('frances', 'bachillerato', '{1}', 'Molière est considéré comme le plus grand auteur de comédies de la littérature française classique'),
('frances', 'bachillerato', '{1}', 'Le château de Versailles a été construit par le roi Louis quatorze et il représente le pouvoir absolu'),
('frances', 'bachillerato', '{1}', 'Jules Verne a imaginé des voyages extraordinaires dans ses romans comme Vingt mille lieues sous les mers'),
('frances', 'bachillerato', '{1}', 'Le croissant et la baguette sont deux symboles gastronomiques de la culture française reconnus partout dans le monde'),
('frances', 'bachillerato', '{1}', 'Charles de Gaulle a dirigé la Résistance française pendant la Seconde Guerre mondiale depuis Londres'),
('frances', 'bachillerato', '{1}', 'La cathédrale Notre-Dame de Paris a été gravement endommagée par un incendie au mois d''avril deux mille dix-neuf'),
('frances', 'bachillerato', '{1}', 'Claude Monet est le fondateur du mouvement impressionniste et il a peint de nombreux tableaux de son jardin à Giverny'),
('frances', 'bachillerato', '{1}', 'Le Petit Prince est un conte philosophique écrit par Antoine de Saint-Exupéry pendant son exil aux États-Unis'),
('frances', 'bachillerato', '{1}', 'La devise de la République française est liberté égalité fraternité et elle date de la Révolution'),
('frances', 'bachillerato', '{1}', 'Jean de La Fontaine a composé des fables qui utilisent des animaux pour critiquer la société de son époque'),
('frances', 'bachillerato', '{1}', 'Le Moulin Rouge est un cabaret mythique situé dans le quartier de Montmartre au nord de Paris'),
('frances', 'bachillerato', '{1}', 'Marie Curie a reçu deux prix Nobel pour ses recherches sur la radioactivité des éléments chimiques'),
('frances', 'bachillerato', '{1}', 'Le Tour de France est la course cycliste la plus célèbre du monde et se déroule au mois de juillet'),
('frances', 'bachillerato', '{1}', 'Louis Pasteur a découvert le vaccin contre la rage et a révolutionné la médecine moderne avec ses recherches'),
('frances', 'bachillerato', '{1}', 'La Marseillaise est l''hymne national français composé pendant la Révolution par Claude Joseph Rouget de Lisle'),
('frances', 'bachillerato', '{1}', 'Gustave Flaubert a écrit Madame Bovary un roman réaliste qui a provoqué un scandale à sa publication'),
('frances', 'bachillerato', '{1}', 'Le Mont Saint-Michel est une île rocheuse de Normandie célèbre pour son abbaye médiévale et ses marées'),
('frances', 'bachillerato', '{1}', 'Honoré de Balzac a écrit La Comédie humaine une série de romans qui décrivent la société française du dix-neuvième siècle'),
('frances', 'bachillerato', '{1}', 'La Francophonie regroupe les pays où le français est parlé officiellement ou comme langue de culture importante'),
('frances', 'bachillerato', '{1}', 'Édith Piaf est une chanteuse française célèbre pour des titres comme La vie en rose et Non je ne regrette rien'),
('frances', 'bachillerato', '{1}', 'Le festival de Cannes est l''un des festivals de cinéma les plus prestigieux du monde et a lieu chaque année en mai'),
('frances', 'bachillerato', '{1}', 'Auguste Rodin est un sculpteur français célèbre pour des œuvres comme Le Penseur et Le Baiser'),
('frances', 'bachillerato', '{1}', 'La galette des rois est une tradition française que l''on mange au mois de janvier pour célébrer l''Épiphanie'),
('frances', 'bachillerato', '{1}', 'Coco Chanel a révolutionné la mode féminine en créant des vêtements élégants et confortables pour les femmes modernes'),
('frances', 'bachillerato', '{1}', 'Le Mont Blanc est la plus haute montagne d''Europe occidentale et se trouve à la frontière entre la France et l''Italie'),
('frances', 'bachillerato', '{1}', 'Jean-Paul Sartre est un philosophe existentialiste qui a refusé le prix Nobel de littérature en mil neuf cent soixante-quatre'),
('frances', 'bachillerato', '{1}', 'Les frères Lumière ont inventé le cinématographe et ont organisé la première projection publique de films à Paris'),
('frances', 'bachillerato', '{1}', 'Le Quartier latin est un quartier historique de Paris où se trouvent la Sorbonne et de nombreuses autres universités'),
('frances', 'bachillerato', '{1}', 'Édouard Manet est considéré comme un précurseur de l''impressionnisme avec des tableaux comme Le déjeuner sur l''herbe'),
('frances', 'bachillerato', '{1}', 'La Provence est une région du sud de la France célèbre pour ses champs de lavande et sa cuisine méditerranéenne'),
('frances', 'bachillerato', '{1}', 'Émile Zola a défendu le capitaine Dreyfus avec son article J''accuse publié dans le journal L''Aurore'),
('frances', 'bachillerato', '{1}', 'Le château de Chambord est le plus grand château de la Loire et a été construit pendant la Renaissance française');

-- =============================================================================
-- FRANCÉS - 2º BACHILLERATO (40 frases) - B2-C1
-- Camus, philosophie, Belle Époque, société
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('frances', 'bachillerato', '{2}', 'Albert Camus a écrit L''Étranger un roman existentialiste qui explore l''absurdité de la condition humaine moderne'),
('frances', 'bachillerato', '{2}', 'Simone de Beauvoir a publié Le Deuxième Sexe un essai fondateur du féminisme contemporain en mil neuf cent quarante-neuf'),
('frances', 'bachillerato', '{2}', 'Marcel Proust a écrit À la recherche du temps perdu une œuvre monumentale sur la mémoire et le temps qui passe'),
('frances', 'bachillerato', '{2}', 'La Belle Époque désigne la période d''optimisme et de progrès culturel en France entre mil huit cent soixante-dix et la Première Guerre'),
('frances', 'bachillerato', '{2}', 'René Descartes a formulé le célèbre principe je pense donc je suis qui fonde la philosophie moderne occidentale'),
('frances', 'bachillerato', '{2}', 'Charles Baudelaire a publié Les Fleurs du mal une œuvre poétique qui a scandalisé la société bourgeoise de son époque'),
('frances', 'bachillerato', '{2}', 'Michel Foucault a analysé les mécanismes du pouvoir et du savoir dans des ouvrages comme Surveiller et punir'),
('frances', 'bachillerato', '{2}', 'Voltaire a défendu la tolérance et la liberté d''expression dans ses contes philosophiques comme Candide ou l''optimisme'),
('frances', 'bachillerato', '{2}', 'Arthur Rimbaud a révolutionné la poésie française avec des œuvres comme Le Bateau ivre avant d''abandonner la littérature'),
('frances', 'bachillerato', '{2}', 'Jean-Jacques Rousseau a développé l''idée du contrat social qui a profondément influencé la Révolution française'),
('frances', 'bachillerato', '{2}', 'André Breton a fondé le mouvement surréaliste qui voulait libérer l''imagination et l''inconscient de toute contrainte rationnelle'),
('frances', 'bachillerato', '{2}', 'Jean-Luc Godard a été l''une des figures principales de la Nouvelle Vague qui a révolutionné le cinéma français'),
('frances', 'bachillerato', '{2}', 'Guy de Maupassant a écrit des centaines de nouvelles qui dépeignent avec précision la société française du dix-neuvième siècle'),
('frances', 'bachillerato', '{2}', 'La philosophie des Lumières a préparé intellectuellement la Révolution avec des penseurs comme Montesquieu et Diderot'),
('frances', 'bachillerato', '{2}', 'Mai soixante-huit a été un mouvement social et culturel qui a profondément transformé la société française contemporaine'),
('frances', 'bachillerato', '{2}', 'Paul Verlaine et Arthur Rimbaud ont entretenu une relation tumultueuse qui a marqué la poésie symboliste française'),
('frances', 'bachillerato', '{2}', 'Emmanuel Macron est devenu président de la République française en deux mille dix-sept à l''âge de trente-neuf ans'),
('frances', 'bachillerato', '{2}', 'Le structuralisme est un courant intellectuel développé en France par des penseurs comme Claude Lévi-Strauss et Roland Barthes'),
('frances', 'bachillerato', '{2}', 'Édith Piaf a incarné l''âme populaire française avec des chansons inoubliables sur l''amour et la souffrance humaine'),
('frances', 'bachillerato', '{2}', 'Louis Aragon a été un poète surréaliste puis engagé qui a célébré l''amour et la Résistance dans ses œuvres'),
('frances', 'bachillerato', '{2}', 'La laïcité est un principe fondamental de la République française qui sépare strictement l''État et les religions'),
('frances', 'bachillerato', '{2}', 'Jacques Derrida a fondé la déconstruction un courant philosophique qui remet en question les oppositions binaires traditionnelles'),
('frances', 'bachillerato', '{2}', 'L''Académie française a été créée par le cardinal de Richelieu pour veiller sur la langue française et son évolution'),
('frances', 'bachillerato', '{2}', 'Stéphane Mallarmé a développé une poésie symboliste hermétique qui cherche à suggérer plutôt qu''à décrire directement'),
('frances', 'bachillerato', '{2}', 'La Quatrième République française a été marquée par l''instabilité gouvernementale et la décolonisation difficile'),
('frances', 'bachillerato', '{2}', 'Pierre Bourdieu a analysé les mécanismes de reproduction sociale et culturelle dans la société française contemporaine'),
('frances', 'bachillerato', '{2}', 'André Malraux a été ministre de la Culture sous de Gaulle et a créé les Maisons de la Culture dans toute la France'),
('frances', 'bachillerato', '{2}', 'Françoise Sagan a publié Bonjour tristesse à dix-huit ans et ce roman est devenu un symbole de la jeunesse libérée'),
('frances', 'bachillerato', '{2}', 'L''affaire Dreyfus a profondément divisé la société française entre la fin du dix-neuvième et le début du vingtième siècle'),
('frances', 'bachillerato', '{2}', 'Marguerite Duras a écrit L''Amant un roman autobiographique qui a obtenu le prix Goncourt en mil neuf cent quatre-vingt-quatre'),
('frances', 'bachillerato', '{2}', 'Le nouveau roman est un mouvement littéraire qui a rejeté les conventions narratives traditionnelles dans les années cinquante'),
('frances', 'bachillerato', '{2}', 'Georges Pompidou a succédé à de Gaulle à la présidence et a lancé le projet culturel du centre Beaubourg à Paris'),
('frances', 'bachillerato', '{2}', 'Annie Ernaux a reçu le prix Nobel de littérature en deux mille vingt-deux pour son œuvre autobiographique et sociologique'),
('frances', 'bachillerato', '{2}', 'Le colonialisme français en Algérie a entraîné une guerre sanglante qui s''est terminée par l''indépendance en mil neuf cent soixante-deux'),
('frances', 'bachillerato', '{2}', 'Claude Debussy a composé des œuvres impressionnistes comme La Mer qui ont renouvelé complètement le langage musical'),
('frances', 'bachillerato', '{2}', 'Jean Renoir a réalisé La Règle du jeu un film considéré comme l''un des chefs-d''œuvre absolus du cinéma mondial'),
('frances', 'bachillerato', '{2}', 'Le mouvement des gilets jaunes a commencé en deux mille dix-huit comme une protestation contre la hausse des taxes sur le carburant'),
('frances', 'bachillerato', '{2}', 'Olympe de Gouges a rédigé la Déclaration des droits de la femme pendant la Révolution française et a été guillotinée ensuite'),
('frances', 'bachillerato', '{2}', 'Michel Houellebecq est un écrivain contemporain controversé qui explore l''aliénation de l''individu dans la société occidentale moderne'),
('frances', 'bachillerato', '{2}', 'La Cinquième République a été fondée par Charles de Gaulle en mil neuf cent cinquante-huit avec une constitution très présidentielle');

-- =============================================================================
-- VALENCIANO - 1º BACHILLERATO (40 frases) - B1-B2
-- Ausiàs March, literatura medieval, Renaixença
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('valenciano', 'bachillerato', '{1}', 'Ausiàs March és considerat el poeta més important de la literatura valenciana medieval del segle quinze'),
('valenciano', 'bachillerato', '{1}', 'Joanot Martorell va escriure el Tirant lo Blanc una de les primeres novel·les modernes de la literatura europea'),
('valenciano', 'bachillerato', '{1}', 'El Segle d''Or valencià correspon al segle quinze quan València era una de les ciutats més riques de la Mediterrània'),
('valenciano', 'bachillerato', '{1}', 'Jaume el Conqueridor va fundar el Regne de València l''any mil dos-cents trenta-huit després de la conquesta cristiana'),
('valenciano', 'bachillerato', '{1}', 'La Llotja de la Seda de València és una obra mestra de l''arquitectura gòtica civil declarada Patrimoni de la Humanitat'),
('valenciano', 'bachillerato', '{1}', 'Sant Vicent Ferrer va ser un predicador valencià famós per la seua eloqüència i els seus sermons públics medievals'),
('valenciano', 'bachillerato', '{1}', 'Jordi de Sant Jordi va ser un poeta valencià del segle quinze que va escriure en la tradició trobadoresca occitana'),
('valenciano', 'bachillerato', '{1}', 'La Renaixença va ser un moviment cultural del segle dinou que va recuperar l''ús literari de la llengua valenciana'),
('valenciano', 'bachillerato', '{1}', 'Teodor Llorente és considerat el patriarca de la Renaixença valenciana i va fundar el diari Las Provincias'),
('valenciano', 'bachillerato', '{1}', 'Les Normes de Castelló de l''any mil nou-cents trenta-dos van establir les regles ortogràfiques del valencià modern'),
('valenciano', 'bachillerato', '{1}', 'Vicent Andrés Estellés és un dels poetes valencians més importants del segle vint amb una obra immensa'),
('valenciano', 'bachillerato', '{1}', 'La ciutat de València va ser fundada pels romans l''any cent trenta-huit abans de Crist amb el nom de Valentia Edetanorum'),
('valenciano', 'bachillerato', '{1}', 'Les Falles de València són una festa declarada Patrimoni Cultural Immaterial de la Humanitat per la Unesco'),
('valenciano', 'bachillerato', '{1}', 'Sor Isabel de Villena va escriure la Vita Christi una obra religiosa important de la literatura medieval valenciana'),
('valenciano', 'bachillerato', '{1}', 'Joan Roís de Corella va ser un escriptor valencià del segle quinze influït per l''humanisme renaixentista italià'),
('valenciano', 'bachillerato', '{1}', 'La Catedral de València conserva el Sant Calze que segons la tradició és el utilitzat per Jesucrist en l''Últim Sopar'),
('valenciano', 'bachillerato', '{1}', 'Roís de Corella va escriure la Tragèdia de Caldesa una obra que barreja elements clàssics amb la tradició cavalleresca'),
('valenciano', 'bachillerato', '{1}', 'La llengua valenciana forma part del diasistema lingüístic compartit amb el català i el balear amb les seues varietats pròpies'),
('valenciano', 'bachillerato', '{1}', 'El Misteri d''Elx és una representació medieval conservada ininterrompudament i declarada Patrimoni de la Humanitat'),
('valenciano', 'bachillerato', '{1}', 'L''obra Curial e Güelfa és una novel·la cavalleresca anònima escrita en valencià durant el segle quinze'),
('valenciano', 'bachillerato', '{1}', 'Jacint Verdaguer va ser un poeta que va influir en la literatura valenciana amb la seua obra èpica L''Atlàntida'),
('valenciano', 'bachillerato', '{1}', 'Constantí Llombart va fundar la societat Lo Rat Penat per a promoure la cultura i la llengua valenciana'),
('valenciano', 'bachillerato', '{1}', 'La Mare de Déu dels Desemparats és la patrona de la ciutat de València i es celebra el segon diumenge de maig'),
('valenciano', 'bachillerato', '{1}', 'Les Corts Valencianes són la institució que representa el poble valencià i té la seua seu al palau dels Borja'),
('valenciano', 'bachillerato', '{1}', 'El Tribunal de les Aigües de València es reuneix cada dijous davant la porta dels Apòstols de la Catedral'),
('valenciano', 'bachillerato', '{1}', 'Joan Fuster va publicar Nosaltres els valencians un assaig fonamental per a entendre la identitat valenciana contemporània'),
('valenciano', 'bachillerato', '{1}', 'L''Arxiu del Regne de València conserva documents històrics des de l''època de Jaume primer fins a l''abolició dels Furs'),
('valenciano', 'bachillerato', '{1}', 'Els Furs de València eren les lleis pròpies del Regne de València abolides per Felip cinqué després de la batalla d''Almansa'),
('valenciano', 'bachillerato', '{1}', 'La senyera valenciana és la bandera oficial de la Comunitat Valenciana amb quatre barres roges i una franja blava coronada'),
('valenciano', 'bachillerato', '{1}', 'Francesc Eiximenis va ser un frare franciscà que va escriure Lo Crestià una enciclopèdia del saber medieval en valencià'),
('valenciano', 'bachillerato', '{1}', 'L''Albufera de València és un parc natural situat al sud de la ciutat famós pels seus arrossars i per la paella'),
('valenciano', 'bachillerato', '{1}', 'La paella valenciana és un plat tradicional elaborat amb arròs pollastre conill verdures i safrà de manera autèntica'),
('valenciano', 'bachillerato', '{1}', 'La Universitat de València va ser fundada l''any mil quatre-cents noranta-nou i és una de les més antigues d''Espanya'),
('valenciano', 'bachillerato', '{1}', 'El Palau de la Generalitat Valenciana és un edifici gòtic que ha sigut la seu del govern valencià des de l''edat mitjana'),
('valenciano', 'bachillerato', '{1}', 'La festa de Moros i Cristians d''Alcoi commemora la reconquesta cristiana de la ciutat al segle tretze cada any'),
('valenciano', 'bachillerato', '{1}', 'Les Torres de Serrans són una de les portes medievals de la muralla de València construïdes al segle catorze'),
('valenciano', 'bachillerato', '{1}', 'El Mercat Central de València és un dels mercats d''aliments frescos més grans i més bonics de tota Europa'),
('valenciano', 'bachillerato', '{1}', 'Blasco Ibáñez va nàixer a València i va escriure Canyes i fang una novel·la ambientada a l''Albufera valenciana'),
('valenciano', 'bachillerato', '{1}', 'Santiago Calatrava és un arquitecte valencià famós per haver dissenyat la Ciutat de les Arts i les Ciències de València'),
('valenciano', 'bachillerato', '{1}', 'La paraula Llevant designa la regió oriental d''Espanya on es parla valencià i es troben platges molt turístiques');

-- =============================================================================
-- VALENCIANO - 2º BACHILLERATO (40 frases) - B2-C1
-- Estellés, literatura contemporània, EBAU
-- =============================================================================
INSERT INTO detective_sentences (subject_id, level, grades, sentence) VALUES
('valenciano', 'bachillerato', '{2}', 'Vicent Andrés Estellés va escriure el Llibre de meravelles una obra fonamental de la poesia valenciana del segle vint'),
('valenciano', 'bachillerato', '{2}', 'Joan Fuster va publicar Nosaltres els valencians l''any mil nou-cents seixanta-dos i va provocar un gran debat identitari'),
('valenciano', 'bachillerato', '{2}', 'Enric Valor va recollir les rondalles valencianes i va contribuir decisivament a la normalització lingüística del valencià modern'),
('valenciano', 'bachillerato', '{2}', 'Maria Beneyto va ser una poetessa valenciana que va escriure tant en valencià com en castellà durant la postguerra'),
('valenciano', 'bachillerato', '{2}', 'L''Acadèmia Valenciana de la Llengua és la institució oficial que regula l''ús normatiu del valencià contemporani'),
('valenciano', 'bachillerato', '{2}', 'Manuel Sanchis Guarner va ser un filòleg valencià que va lluitar per la dignificació lingüística i cultural del valencià'),
('valenciano', 'bachillerato', '{2}', 'Carmelina Sánchez-Cutillas va escriure Matèria de Bretanya una novel·la poètica ambientada en la seua infantesa a Altea'),
('valenciano', 'bachillerato', '{2}', 'L''Estatut d''Autonomia de la Comunitat Valenciana va ser aprovat l''any mil nou-cents huitanta-dos amb el valencià com a llengua pròpia'),
('valenciano', 'bachillerato', '{2}', 'Joan Francesc Mira és un antropòleg i escriptor valencià autor d''una traducció monumental de la Divina Comèdia de Dant'),
('valenciano', 'bachillerato', '{2}', 'Isabel-Clara Simó va escriure Júlia una novel·la ambientada a Alcoi durant les revoltes obreres del segle dinou'),
('valenciano', 'bachillerato', '{2}', 'Ferran Torrent és un dels escriptors més llegits del panorama literari valencià contemporani amb novel·les de gènere negre'),
('valenciano', 'bachillerato', '{2}', 'Estellés va dedicar la seua obra Mural del País Valencià a la descripció poètica de tots els pobles del territori valencià'),
('valenciano', 'bachillerato', '{2}', 'La Batalla de València va ser un conflicte identitari i lingüístic ocorregut durant la transició democràtica espanyola'),
('valenciano', 'bachillerato', '{2}', 'L''escola valenciana ha sigut un moviment cívic per defensar l''ensenyament en valencià des dels anys huitanta del segle vint'),
('valenciano', 'bachillerato', '{2}', 'Vicent Marçà va ser un dramaturg valencià que va renovar el teatre contemporani amb obres compromeses socialment'),
('valenciano', 'bachillerato', '{2}', 'El Consell Valencià de Cultura és un òrgan consultiu que assessora les institucions en matèria cultural i patrimonial'),
('valenciano', 'bachillerato', '{2}', 'La literatura valenciana de postguerra va patir la repressió franquista però va sobreviure gràcies a escriptors resistents'),
('valenciano', 'bachillerato', '{2}', 'Raimon és un cantautor valencià nascut a Xàtiva que va donar veu al moviment de la Nova Cançó durant el franquisme'),
('valenciano', 'bachillerato', '{2}', 'Al Tall és un grup de música folk valenciana que ha recuperat les tradicions musicals populars i les ha modernitzades'),
('valenciano', 'bachillerato', '{2}', 'Ovidi Montllor va ser un cantautor i actor alcoià que va compartir escenaris amb els grans poetes valencians contemporanis'),
('valenciano', 'bachillerato', '{2}', 'El model lingüístic del valencià administratiu ha sigut elaborat per l''Acadèmia amb criteris de claredat i precisió'),
('valenciano', 'bachillerato', '{2}', 'La prosa assagística de Joan Fuster ha influït profundament el pensament contemporani sobre la identitat dels valencians'),
('valenciano', 'bachillerato', '{2}', 'Ramon Llull és considerat el pare de la llengua literària catalana i les seues obres van influir la tradició valenciana medieval'),
('valenciano', 'bachillerato', '{2}', 'Marc Granell és un poeta contemporani nascut a València autor d''una obra que reflexiona sobre el pas del temps i la memòria'),
('valenciano', 'bachillerato', '{2}', 'La novel·la Paraules d''Opòton el Vell de Joan Francesc Mira reflexiona sobre la identitat i la història des d''una perspectiva original'),
('valenciano', 'bachillerato', '{2}', 'Les varietats dialectals del valencià inclouen el tortosí el valencià central i el meridional amb característiques fonètiques pròpies'),
('valenciano', 'bachillerato', '{2}', 'El moviment cultural valencianista ha promogut durant dècades l''estudi i la difusió de la llengua i la literatura pròpies'),
('valenciano', 'bachillerato', '{2}', 'Eduard Escalante va ser un sainetista valencià del segle dinou que va retratar els costums populars de la ciutat de València'),
('valenciano', 'bachillerato', '{2}', 'El Cant de la Sibil·la és una representació musical medieval conservada a Mallorca i relacionada amb la tradició litúrgica valenciana'),
('valenciano', 'bachillerato', '{2}', 'Rafael Chirbes va ser un escriptor valencià autor de novel·les crítiques amb la societat espanyola contemporània com Crematori'),
('valenciano', 'bachillerato', '{2}', 'La poesia d''Estellés recupera la veu popular valenciana amb versos que reivindiquen la dignitat de la gent senzilla del territori'),
('valenciano', 'bachillerato', '{2}', 'Salvador Espriu ha influït molts poetes valencians contemporanis amb la seua obra La pell de brau i el seu compromís cívic'),
('valenciano', 'bachillerato', '{2}', 'El valencià té estatus de llengua oficial juntament amb el castellà segons l''Estatut d''Autonomia de la Comunitat Valenciana'),
('valenciano', 'bachillerato', '{2}', 'La Generalitat Valenciana promou diverses polítiques lingüístiques per afavorir l''ús social del valencià en tots els àmbits públics'),
('valenciano', 'bachillerato', '{2}', 'Martí Domínguez és un escriptor i biòleg valencià autor de novel·les que uneixen ciència història i literatura amb mestria'),
('valenciano', 'bachillerato', '{2}', 'L''obra poètica d''Ausiàs March trenca amb la tradició trobadoresca i introdueix una nova veu personal en la literatura europea'),
('valenciano', 'bachillerato', '{2}', 'Silvestre Vilaplana és un escriptor alcoià autor de novel·les ambientades en la història medieval i moderna valenciana'),
('valenciano', 'bachillerato', '{2}', 'La censura franquista va prohibir l''edició de llibres en valencià durant dècades fins a la recuperació democràtica posterior'),
('valenciano', 'bachillerato', '{2}', 'Gemma Pasqual és una escriptora valenciana autora de narrativa juvenil compromesa amb els valors cívics i democràtics actuals'),
('valenciano', 'bachillerato', '{2}', 'La literatura valenciana actual compta amb veus diverses que enriqueixen el panorama cultural amb propostes innovadores i creatives');
