// Datos de las misiones para "Misiones Robóticas".
// Cada curso (1-4 ESO) tiene 5 misiones con dificultad creciente.
// Todos los mapas son de 8x8 con el mismo tamaño de casilla.
//
// Coordenadas: (0,0) es la esquina superior izquierda.
// Direcciones: 'N' (arriba), 'E' (derecha), 'S' (abajo), 'W' (izquierda).
// Tipos de celda en `grid`:
//   '.' vacia, '#' muro, 'H' agujero (fin de partida si caes),
//   'T' meta, 'I' item (a recoger), 'R' robot.

// Bloques disponibles por curso (catálogo progresivo)
export const GRADE_BLOCKS = {
  '1': { simple: ['move', 'turnL', 'turnR'],            loops: ['repeat'],          conds: [],                actions: ['pick'] },
  '2': { simple: ['move', 'turnL', 'turnR', 'turn180'], loops: ['repeat'],          conds: ['if'],            actions: ['pick'] },
  '3': { simple: ['move', 'turnL', 'turnR', 'turn180'], loops: ['repeat', 'while'], conds: ['if', 'ifelse'],  actions: ['pick'] },
  '4': { simple: ['move', 'turnL', 'turnR', 'turn180'], loops: ['repeat', 'while'], conds: ['if', 'ifelse'],  actions: ['pick'] },
};

// Opciones de condiciones que aparecen en los bloques if/while
export const CONDITIONS = [
  { id: 'canMove',       label: 'Puede avanzar' },
  { id: 'obstacleAhead', label: 'Hay obstáculo delante' },
  { id: 'itemHere',      label: 'Hay un ítem aquí' },
  { id: 'onTarget',      label: 'Estoy en la meta' },
  { id: 'notOnTarget',   label: 'No estoy en la meta' },
];

// ---------- 1º ESO ----------
const grade1 = [
  {
    id: 'mr-1-1',
    title: '1. Primer paso',
    description: 'Dirige al robot hasta la meta en línea recta.',
    hint: 'Avanza 5 veces o usa un bucle Repetir 5 (Avanza).',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', '.', 'T', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 2,
  },
  {
    id: 'mr-1-2',
    title: '2. Gira y avanza',
    description: 'Llega a la meta girando en una esquina.',
    hint: 'Avanza 5, gira a la derecha, avanza 4 hasta la meta.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', 'T', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 3,
  },
  {
    id: 'mr-1-3',
    title: '3. Recoge el cristal',
    description: 'Pasa por el ítem y luego llega a la meta.',
    hint: 'Avanza 3, recoge, avanza 3 hasta la meta.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', 'I', '.', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 1 },
    suggestedBlocks: 4,
  },
  {
    id: 'mr-1-4',
    title: '4. Patrulla cuadrada',
    description: 'Recoge los dos ítems del cuadrado y llega a la meta usando un bucle.',
    hint: 'Repetir 2 veces (avanza 3, recoge, gira derecha) y después avanza 3.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', 'I', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'T', '.', '.', 'I', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 5,
  },
  {
    id: 'mr-1-5',
    title: '5. Pasillo con giros',
    description: 'Recorre el pasillo hasta la meta esquivando los muros.',
    hint: 'Repetir 5 (avanza), gira derecha, repetir 5 (avanza).',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', 'T', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 5,
  },
  {
    id: 'mr-1-6',
    title: '6. Tres cristales en fila',
    description: 'Recoge los tres cristales que hay en la fila usando un bucle.',
    hint: 'Repetir 3 (repetir 2 avanza, recoge), avanza.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', 'I', '.', 'I', '.', 'I', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-1-7',
    title: '7. Doble esquina',
    description: 'Un muro te obliga a dar dos giros para llegar a la meta.',
    hint: 'Avanza 2, gira derecha, avanza 4, gira izquierda, avanza 4.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '#', '.', '.', '.'],
      ['.', '.', '.', '.', '#', '.', '.', '.'],
      ['.', '.', '.', '.', '#', '.', '.', '.'],
      ['.', '.', '.', '.', '#', '#', '#', '#'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 7,
  },
  {
    id: 'mr-1-8',
    title: '8. Patrulla grande',
    description: 'Recoge dos cristales recorriendo un cuadrado de 4 casillas de lado.',
    hint: 'Repetir 2 (avanza 4, recoge, gira derecha), avanza 4.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'T', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-1-9',
    title: '9. Zigzag de cristales',
    description: 'Recoge los tres cristales siguiendo un camino en zigzag.',
    hint: 'Avanza 2, recoge, gira derecha, avanza 3, recoge, gira izquierda, avanza 3, recoge, gira derecha, avanza 3.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', 'I', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', 'I', '.', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', 'T', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-1-10',
    title: '10. Laberinto corto',
    description: 'Sigue los pasillos hasta la meta.',
    hint: 'Avanza por cada tramo girando en las esquinas. Usa Repetir para no repetir el bloque avanza.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '#', '.', '#'],
      ['#', '#', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 12,
  },
];

// ---------- 2º ESO ----------
const grade2 = [
  {
    id: 'mr-2-1',
    title: '1. Recoge los cristales',
    description: 'Avanza por la fila recogiendo solo los ítems con un condicional.',
    hint: 'Repetir 7 (avanza, si hay ítem aquí recoge).',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', '.', 'I', '.', '.', 'I', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 4,
  },
  {
    id: 'mr-2-2',
    title: '2. Esquiva el muro',
    description: 'Un pequeño muro bloquea el camino: rodéalo con condicionales.',
    hint: 'Avanza; si hay obstáculo delante, rodea girando a la izquierda y volviendo a la derecha.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', '.', '#', '.', '.', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 9,
  },
  {
    id: 'mr-2-3',
    title: '3. Laberinto en forma de L',
    description: 'Atraviesa el laberinto y llega a la meta.',
    hint: 'Avanza 5, gira derecha, avanza 3, gira derecha, avanza 5.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', 'T', '#', '#', '#', '#', '#', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 8,
  },
  {
    id: 'mr-2-4',
    title: '4. Patrulla automática',
    description: 'Recoge los tres ítems del cuadrado patrullando automáticamente.',
    hint: 'Repetir 3 veces (avanza 4, si hay ítem recoge, gira derecha), luego avanza 4.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'T', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', 'I', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-2-5',
    title: '5. Pasillo con recogidas',
    description: 'Atraviesa el pasillo recogiendo los cristales del camino.',
    hint: 'Repetir 5 (avanza, si hay ítem recoge), gira derecha, repetir 6 (avanza, si hay ítem recoge).',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', 'I', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', 'I', '#'],
      ['#', '.', '.', '.', '.', '.', 'T', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 8,
  },
  {
    id: 'mr-2-6',
    title: '6. Pasillo con obstáculos',
    description: 'Avanza; si hay obstáculo delante, gira y rodéalo automáticamente.',
    hint: 'Repetir 12 (si hay obstáculo delante, gira derecha; si no, avanza).',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-2-7',
    title: '7. Cristales en cuadro',
    description: 'Recoge los cuatro cristales de las esquinas de un cuadrado.',
    hint: 'Repetir 4 (avanza 4, gira derecha, si hay ítem recoge).',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', 'R', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'N',
    objectives: { reachTarget: true, collectItems: 4 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-2-8',
    title: '8. Laberinto con ítem',
    description: 'Encuentra el cristal en el laberinto y llega a la meta.',
    hint: 'Avanza por el pasillo principal; al pasar por el ítem recógelo con "Si hay ítem aquí".',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', 'I', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 1 },
    suggestedBlocks: 10,
  },
  {
    id: 'mr-2-9',
    title: '9. Fila accidentada',
    description: 'Avanza por la fila esquivando los muros y recogiendo todos los cristales.',
    hint: 'Repetir suficientes veces: si hay ítem recoge; si hay obstáculo gira; si no avanza.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', 'I', '#', 'I', '#', 'I', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 18,
  },
  {
    id: 'mr-2-10',
    title: '10. Circuito con cristales',
    description: 'Recoge tres cristales y llega a la meta sorteando los muros.',
    hint: 'Avanza por el circuito, usando "Si hay ítem recoge" dentro del bucle principal.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '#', '.', 'I', '#'],
      ['#', '#', '#', '.', '#', '.', '#', '#'],
      ['#', 'I', '.', '.', '.', '.', '#', '#'],
      ['#', '#', '#', '.', '#', '#', '#', '#'],
      ['#', 'T', '.', '.', '#', '#', '#', '#'],
      ['#', '#', '#', 'I', '#', '#', '#', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 16,
  },
];

// ---------- 3º ESO ----------
const grade3 = [
  {
    id: 'mr-3-1',
    title: '1. Mientras puedas',
    description: 'Avanza hasta el muro recogiendo los cristales, luego rodea hasta la meta.',
    hint: 'Mientras puedas avanzar: avanza y recoge si hay ítem. Después gira y llega a la meta.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', 'I', '.', 'I', '.', '.', '#'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 8,
  },
  {
    id: 'mr-3-2',
    title: '2. Sigue el pasillo',
    description: 'El pasillo gira. Úsalo con "Mientras" y "Si…/Si no" para recorrerlo automáticamente.',
    hint: 'Mientras no estés en la meta: si hay obstáculo delante, gira derecha; si no, avanza.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '#', '#', '#'],
      ['#', '#', '#', '#', '.', '#', '#', '#'],
      ['#', '#', '#', '#', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '.', '#', '#', '#'],
      ['#', '#', '#', '#', 'T', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-3-3',
    title: '3. Cuidado con los agujeros',
    description: 'Recoge los ítems sin caer en los agujeros. Un paso y fin de misión.',
    hint: 'Avanza por la fila superior recogiendo ítems. Los agujeros están en la fila de abajo: evítalos.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', 'I', '.', 'I', '.', '.', 'T'],
      ['.', 'H', '.', 'H', '.', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2, noDeath: true },
    suggestedBlocks: 7,
  },
  {
    id: 'mr-3-4',
    title: '4. Exploración completa',
    description: 'Recoge los cuatro ítems repartidos por la sala antes de llegar a la meta.',
    hint: 'Barre la sala en zigzag usando Mientras. Recoge cada vez que encuentres un ítem.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', 'I', '.', '.', 'I', '.', '#'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['#', '.', '.', 'I', '.', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4 },
    suggestedBlocks: 12,
  },
  {
    id: 'mr-3-5',
    title: '5. Laberinto en espiral',
    description: 'Sal del laberinto en espiral. Usa Mientras con condicionales.',
    hint: 'Mientras no llegues: si puedes avanzar, avanza; si no, gira a la derecha.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '#', 'T', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-3-6',
    title: '6. Recoge mientras puedas',
    description: 'Recorre la fila con "Mientras" y recoge los cristales que encuentres.',
    hint: 'Mientras puedas avanzar: avanza y, si hay ítem aquí, recoge.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', 'I', '.', 'I', '.', 'I', '.', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 5,
  },
  {
    id: 'mr-3-7',
    title: '7. Giro en T',
    description: 'Recorre el pasillo en forma de T automáticamente.',
    hint: 'Mientras no estés en la meta: si puedes avanzar, avanza; si no, gira derecha.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '.', '#', '#', '#'],
      ['#', '#', '#', '#', '.', '#', '#', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', 'T', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-3-8',
    title: '8. Campo minado',
    description: 'Recoge dos cristales sin caer en los agujeros. Un paso en falso y pierdes.',
    hint: 'Usa "Si puedes avanzar" y "Si no" para navegar sin caer.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', 'I', '.', '.', '.', '.'],
      ['.', 'H', '.', '.', '.', 'H', '.', '.'],
      ['.', '.', '.', 'H', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', 'H', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', 'H', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2, noDeath: true },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-3-9',
    title: '9. Explorador eficiente',
    description: 'Recorre la sala en zigzag recogiendo los cinco cristales.',
    hint: 'Usa Mientras para avanzar hasta el muro, luego gira para cambiar de fila.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '#'],
      ['R', 'I', '.', 'I', '.', 'I', '.', '#'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['#', 'I', '.', '.', '.', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 5 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-3-10',
    title: '10. Gran laberinto',
    description: 'Sal del laberinto recogiendo un cristal por el camino.',
    hint: 'Mientras no estés en la meta: si puedes avanzar avanza; si no gira derecha. Recoge al pasar.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', 'I', '.', '#'],
      ['#', '#', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', 'T', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', '#', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 1 },
    suggestedBlocks: 9,
  },
];

// ---------- 4º ESO ----------
const grade4 = [
  {
    id: 'mr-4-1',
    title: '1. Robot aspirador',
    description: 'Recoge los seis ítems repartidos por toda la sala barriendo en zigzag.',
    hint: 'Repetir 3 filas: mientras puedas avanzar, avanza y recoge; luego da media vuelta y baja a la siguiente fila.',
    grid: [
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['I', '.', 'I', '.', 'I', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-4-2',
    title: '2. Entregas en serie',
    description: 'Recoge tres ítems en un circuito con agujeros y muros. No caigas.',
    hint: 'Avanza con cuidado: si hay obstáculo rodéalo; si hay agujero esquívalo cambiando de fila.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '.', 'H', '.', '#'],
      ['#', '.', '#', 'I', '.', '#', '.', '#'],
      ['#', '.', '#', '.', '.', '#', '.', '#'],
      ['#', '.', 'I', '.', 'H', '#', 'I', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3, noDeath: true },
    suggestedBlocks: 18,
  },
  {
    id: 'mr-4-3',
    title: '3. Rescate en el laberinto',
    description: 'Recoge el cristal escondido al fondo del laberinto y llega a la meta.',
    hint: 'Sigue el pasillo con Mientras + Si/Si no. Recoge el ítem y continúa hasta la meta.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', 'I', '.', '.', '.', '#', '.', '#'],
      ['#', '#', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', 'T', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 1 },
    suggestedBlocks: 16,
  },
  {
    id: 'mr-4-4',
    title: '4. Patrulla eficiente',
    description: 'Recoge los seis ítems minimizando los bloques. Cada bloque cuenta.',
    hint: 'Repetir 3 (mientras puedas avanzar: avanza y recoge; gira 180°; avanza; gira derecha).',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', 'I', '.', 'I', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', 'I', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 10,
  },
  {
    id: 'mr-4-5',
    title: '5. Reto intermedio',
    description: 'Laberinto con ítems y agujeros. Demuestra tu dominio de los bucles y condicionales.',
    hint: 'Usa Mientras + Si/Si no anidados. Detecta obstáculos, recoge ítems, esquiva agujeros.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '#', 'I', '.', '#'],
      ['#', '.', '#', '.', '#', '.', 'H', '#'],
      ['#', '.', '#', '.', '.', '.', '.', '#'],
      ['#', 'I', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', 'I', '.', 'H', '.', '#'],
      ['#', '#', '.', '#', '#', '#', '.', '#'],
      ['#', 'T', '.', '.', 'I', '.', '.', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4, noDeath: true },
    suggestedBlocks: 22,
  },
  {
    id: 'mr-4-6',
    title: '6. Aspirador optimizado',
    description: 'Recoge los 8 cristales de la rejilla y llega a la meta.',
    hint: 'Mientras puedas avanzar, avanza y recoge. Repite por filas con media vuelta.',
    grid: [
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'I'],
      ['I', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 8 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-4-7',
    title: '7. Rescate doble',
    description: 'Dos cristales atrapados en celdas separadas por muros. Encuéntralos.',
    hint: 'Sigue los pasillos con Mientras + Si/Si no; recoge los ítems al pasar.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '#', 'I', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '#', '#', '#', 'I', '#', '.', '#'],
      ['#', 'T', '#', '#', '#', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 2 },
    suggestedBlocks: 16,
  },
  {
    id: 'mr-4-8',
    title: '8. Sensor experto',
    description: 'Navega un circuito con obstáculos usando solo condicionales.',
    hint: 'Mientras no estés en la meta: si puedes avanzar, avanza; si no, gira derecha.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '#', '.', '.', '#'],
      ['#', '#', '#', '.', '#', '.', '#', '#'],
      ['#', '.', '.', '.', '#', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 7,
  },
  {
    id: 'mr-4-9',
    title: '9. Almacén',
    description: 'Recoge los 6 cristales dispuestos en el almacén y lleva todo a la meta.',
    hint: 'Barre la rejilla en zigzag con Mientras por fila; al acabar una fila cambia de fila con giros.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', 'I', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-4-10',
    title: '10. Desafío final',
    description: 'El reto definitivo: laberinto con muros, agujeros e ítems. Sé eficiente.',
    hint: 'Combina Mientras, Si/Si no anidados y usa sensores para decidir en cada celda.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', 'I', '#', '.', '.', '#'],
      ['#', '#', '#', '.', '#', '.', 'H', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', 'I', '.', '.', '.', 'H', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', 'I', '.', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3, noDeath: true },
    suggestedBlocks: 24,
  },
];

export const MISSIONS_BY_GRADE = {
  '1': grade1,
  '2': grade2,
  '3': grade3,
  '4': grade4,
};

export function getMissions(grade) {
  return MISSIONS_BY_GRADE[String(grade)] || grade1;
}

// ---------- Niveles tipo RETO (mucho más complejos) -----------------------
// Se cargan aleatoriamente desde un pool específico por curso.
// Los de 1º y 2º ESO usan únicamente los bloques disponibles para ese curso,
// pero las cuadrículas y los objetivos son más duros (más ítems, más muros,
// rutas más largas). Los de 3º y 4º ESO combinan Mientras + Si/Si no con
// agujeros, laberintos grandes y múltiples objetivos.

const reto1 = [
  {
    id: 'mr-reto-1-a',
    title: 'Reto · Patrulla múltiple',
    description: 'Recoge los 4 cristales del circuito y vuelve al punto de partida.',
    hint: 'Divide el problema en 4 tramos iguales y usa Repetir sobre cada tramo.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', 'T', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4 },
    suggestedBlocks: 12,
  },
  {
    id: 'mr-reto-1-b',
    title: 'Reto · Laberinto con doble giro',
    description: 'Encuentra la salida del laberinto tras dos curvas cerradas.',
    hint: 'Sigue el pasillo tramo a tramo. Usa Repetir en cada tramo recto.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '#', 'T', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 10,
  },
  {
    id: 'mr-reto-1-c',
    title: 'Reto · Barrido en zigzag',
    description: 'Recoge los 6 cristales barriendo la sala en zigzag.',
    hint: 'Patrón: avanza, gira, avanza, gira, avanza… combina varios Repetir.',
    grid: [
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['I', '.', 'I', '.', 'I', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-reto-1-d',
    title: 'Reto · Diamante',
    description: 'Recoge los 4 cristales dispuestos en rombo y llega a la meta.',
    hint: 'Haz una trayectoria en rombo: 4 tramos iguales con giros a la derecha.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', 'I', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'R', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', 'I', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', 'T', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 12,
  },
  {
    id: 'mr-reto-1-e',
    title: 'Reto · Circuito amurallado',
    description: 'Atraviesa el laberinto recogiendo los 3 cristales.',
    hint: 'Avanza tramo a tramo girando en cada esquina. Usa Repetir para los tramos largos.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', 'I', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', 'I', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', '.', '.', '.', '.', 'I', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '#', '#', '#', '#', '#', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 18,
  },
];

const reto2 = [
  {
    id: 'mr-reto-2-a',
    title: 'Reto · Recogida inteligente',
    description: 'Recorre la fila y recoge solo los cristales con condicional.',
    hint: 'Repetir 7 veces: avanza, si hay ítem recoge.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', 'I', '.', 'I', '.', 'I', 'I', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4 },
    suggestedBlocks: 4,
  },
  {
    id: 'mr-reto-2-b',
    title: 'Reto · Circuito con obstáculos',
    description: 'Recoge los 3 cristales esquivando muros con condicionales.',
    hint: 'Repetir: si hay obstáculo delante gira, si no avanza, si hay ítem recoge.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '#', '.', '.', 'I', '#'],
      ['#', '.', '.', '#', '.', '#', '.', '#'],
      ['#', '#', '.', '.', '.', '#', '.', '#'],
      ['#', 'I', '.', '#', '#', '#', '.', '#'],
      ['#', '#', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '.', 'I', '#', '#', '#'],
      ['#', '#', '#', '.', 'T', '#', '#', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 18,
  },
  {
    id: 'mr-reto-2-c',
    title: 'Reto · Cuadros dobles',
    description: 'Recoge 6 cristales dispuestos en dos cuadros con patrullas.',
    hint: 'Dos patrullas consecutivas con Repetir y Si hay ítem recoge.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', 'R', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', 'T', '.', '.', '.', '.'],
    ],
    startDir: 'N',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 16,
  },
  {
    id: 'mr-reto-2-d',
    title: 'Reto · Pasillo minado',
    description: 'Avanza por la fila esquivando los muros intercalados y recogiendo los 3 ítems.',
    hint: 'Repetir N veces (si obstáculo gira/rodea; si hay ítem recoge; si no avanza).',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['R', 'I', '#', '.', 'I', '#', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '#', '.', 'I', 'T'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3 },
    suggestedBlocks: 18,
  },
  {
    id: 'mr-reto-2-e',
    title: 'Reto · Barrido condicional',
    description: 'Barre toda la rejilla recogiendo solo los cristales con condicionales.',
    hint: 'Repetir 4 (repetir 7 avanza, si hay ítem recoge, gira derecha).',
    grid: [
      ['R', '.', 'I', '.', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['I', '.', '.', '.', 'I', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', '.', '.', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 18,
  },
];

const reto3 = [
  {
    id: 'mr-reto-3-a',
    title: 'Reto · Explorador automático',
    description: 'Recoge todos los cristales de la sala y llega a la meta.',
    hint: 'Usa Mientras puedas avanzar + Si hay ítem recoge en cada tramo.',
    grid: [
      ['.', '.', '.', '.', '.', '.', '.', '#'],
      ['R', 'I', '.', 'I', '.', 'I', '.', '#'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['#', 'I', '.', 'I', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-reto-3-b',
    title: 'Reto · Campo minado grande',
    description: 'Recoge 3 cristales sin caer en ninguno de los agujeros.',
    hint: 'Usa Si puedes avanzar/Si no para cambiar de fila antes de caer.',
    grid: [
      ['R', '.', 'I', '.', '.', '.', '.', '.'],
      ['.', 'H', '.', 'H', '.', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', 'I', '.', '.'],
      ['.', 'H', '.', 'H', '.', 'H', '.', '.'],
      ['.', '.', 'I', '.', '.', '.', '.', '.'],
      ['.', 'H', '.', 'H', '.', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 3, noDeath: true },
    suggestedBlocks: 16,
  },
  {
    id: 'mr-reto-3-c',
    title: 'Reto · Laberinto en espiral grande',
    description: 'Sal del laberinto en espiral. Requiere Mientras + Si/Si no.',
    hint: 'Mientras no llegues a la meta: si puedes avanzar avanza, si no gira derecha.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '#', 'T', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 0 },
    suggestedBlocks: 6,
  },
  {
    id: 'mr-reto-3-d',
    title: 'Reto · Sigue la línea con ítems',
    description: 'Sigue el pasillo recogiendo los cristales automáticamente.',
    hint: 'Mientras no estés en la meta: si hay ítem recoge, si puedes avanzar avanza, si no gira derecha.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', 'I', '.', '.', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', 'I', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '#', '#'],
      ['#', '.', '.', '.', '.', 'I', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', '.', 'I', '.', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4 },
    suggestedBlocks: 14,
  },
  {
    id: 'mr-reto-3-e',
    title: 'Reto · Campo de obstáculos',
    description: 'Recoge 4 cristales sin caer en ningún agujero.',
    hint: 'Usa Mientras con Si/Si no: si hay obstáculo o agujero delante, gira; si no, avanza.',
    grid: [
      ['R', '.', '.', 'I', '.', '.', '.', '.'],
      ['.', 'H', '.', '.', '.', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', '.', 'I', '.'],
      ['.', 'H', '.', 'I', '.', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'H', '.', '.', 'I', 'H', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4, noDeath: true },
    suggestedBlocks: 16,
  },
];

const reto4 = [
  {
    id: 'mr-reto-4-a',
    title: 'Reto · Almacén completo',
    description: 'Recoge los 10 cristales del almacén y llega a la meta.',
    hint: 'Barre la rejilla en zigzag con Mientras por fila y cambia de fila con 2 giros.',
    grid: [
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'I'],
      ['I', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', 'I', '.', 'I', '.', 'I', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 10 },
    suggestedBlocks: 16,
  },
  {
    id: 'mr-reto-4-b',
    title: 'Reto · Laberinto final',
    description: 'Recoge 5 cristales en un laberinto con muros y agujeros. Sin caer.',
    hint: 'Combina Mientras + Si/Si no anidados para decidir en cada celda.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', 'I', '#', '.', '.', '#'],
      ['#', '#', '#', '.', '#', '.', 'H', '#'],
      ['#', '.', '.', '.', '.', '.', '.', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', 'I', '.', '.', '.', 'H', '.', '#'],
      ['#', '#', '#', '#', '#', '#', '.', '#'],
      ['#', '.', 'I', '.', 'I', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 4, noDeath: true },
    suggestedBlocks: 22,
  },
  {
    id: 'mr-reto-4-c',
    title: 'Reto · Rejilla hostil',
    description: 'Recoge todos los cristales esquivando los agujeros del suelo.',
    hint: 'Divide la rejilla en filas seguras y usa condicionales anidados para navegar.',
    grid: [
      ['R', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', 'H', '.', 'H', '.', 'H', '.', 'I'],
      ['I', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', 'H', '.', 'H', '.', 'H', '.', '.'],
      ['.', '.', 'I', '.', 'I', '.', 'I', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', '.'],
      ['.', '.', '.', '.', '.', '.', '.', 'T'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 12, noDeath: true },
    suggestedBlocks: 24,
  },
  {
    id: 'mr-reto-4-d',
    title: 'Reto · Gran tour',
    description: 'Recoge 6 cristales repartidos por un laberinto grande y llega a la meta.',
    hint: 'Combina Mientras + Si/Si no anidados; recoge cada vez que pases por un ítem.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', '.', '.', 'I', '#'],
      ['#', '.', '#', '#', '#', '#', '.', '#'],
      ['#', '.', 'I', '.', '.', '#', '.', '#'],
      ['#', '.', '#', '#', '.', '#', '.', '#'],
      ['#', '.', '.', '#', '.', 'I', '.', '#'],
      ['#', '#', 'I', '#', '#', '#', '.', '#'],
      ['#', 'T', '.', 'I', '.', 'I', '.', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 6 },
    suggestedBlocks: 22,
  },
  {
    id: 'mr-reto-4-e',
    title: 'Reto · Supervivencia',
    description: 'Recoge 5 cristales esquivando muros y agujeros. Una caída y fin de reto.',
    hint: 'Usa Mientras + Si/Si no anidados. Comprueba obstáculos antes de cada paso.',
    grid: [
      ['#', '#', '#', '#', '#', '#', '#', '#'],
      ['#', 'R', '.', '.', 'H', '.', 'I', '#'],
      ['#', '.', '#', '.', '#', '.', '.', '#'],
      ['#', 'I', '.', '.', '.', 'H', '.', '#'],
      ['#', 'H', '#', '#', '#', '#', '.', '#'],
      ['#', '.', '.', 'I', '.', '.', '.', '#'],
      ['#', 'H', '#', '#', '#', '.', 'H', '#'],
      ['#', '.', 'I', '.', 'I', '.', 'T', '#'],
    ],
    startDir: 'E',
    objectives: { reachTarget: true, collectItems: 5, noDeath: true },
    suggestedBlocks: 24,
  },
];

export const RETO_MISSIONS_BY_GRADE = {
  '1': reto1,
  '2': reto2,
  '3': reto3,
  '4': reto4,
};

export function getRetoMissions(grade) {
  return RETO_MISSIONS_BY_GRADE[String(grade)] || reto1;
}

export function pickRandomReto(grade) {
  const pool = getRetoMissions(grade);
  return pool[Math.floor(Math.random() * pool.length)];
}

// Utilidades para preparar el mundo inicial a partir del grid textual
export function prepareWorld(mission) {
  const rows = mission.grid.length;
  const cols = mission.grid[0].length;
  const walls = new Set();
  const holes = new Set();
  const items = new Set();
  let target = null;
  let robot = { x: 0, y: 0, dir: mission.startDir || 'E' };

  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const cell = mission.grid[y][x];
      const key = `${x},${y}`;
      switch (cell) {
        case '#': walls.add(key); break;
        case 'H': holes.add(key); break;
        case 'I': items.add(key); break;
        case 'T': target = { x, y }; break;
        case 'R': robot = { x, y, dir: mission.startDir || 'E' }; break;
        default: break;
      }
    }
  }
  return { rows, cols, walls, holes, items, target, robot, initialItems: items.size };
}
