import React from 'react';
import { useOrdenaLaHistoriaGame } from '../../hooks/useOrdenaLaHistoriaGame';
import OrdenaLaHistoriaUI from '../_shared/OrdenaLaHistoriaUI';
import OrdenaLaHistoriaTestScreen from '../_shared/OrdenaLaHistoriaTestScreen';

const historias = [
    ["La civilización egipcia floreció a orillas del río Nilo.", "Construyeron impresionantes pirámides que servían como tumbas para sus faraones.", "Desarrollaron un sistema de escritura basado en jeroglíficos.", "Su sociedad estaba gobernada por un faraón considerado un dios viviente."],
    ["El ciclo del agua es un proceso fundamental para la vida en la Tierra.", "El sol calienta el agua de los océanos, que se evapora y sube a la atmósfera.", "Allí, el vapor de agua se enfría y se condensa para formar las nubes.", "Finalmente, el agua regresa a la superficie en forma de lluvia o nieve."],
    ["El corazón es el motor del sistema circulatorio.", "Bombea sangre rica en oxígeno a todas las células del cuerpo.", "La sangre viaja a través de las arterias y regresa por las venas.", "Este proceso es esencial para que nuestros órganos funcionen correctamente."],
    ["Durante la Edad Media, los caballeros vivían en castillos.", "Vestían pesadas armaduras para protegerse en las batallas.", "Juraban lealtad a un señor feudal a cambio de tierras.", "Participaban en torneos para demostrar su habilidad con la espada."],
    ["La fotosíntesis es el proceso mediante el cual las plantas fabrican su propio alimento.", "Utilizan la luz del sol, el dióxido de carbono del aire y el agua del suelo.", "Como resultado de este proceso, liberan el oxígeno que necesitamos para respirar.", "Por eso, los bosques son considerados los pulmones del planeta."],
    ["El sistema solar está formado por el Sol y los planetas que giran a su alrededor.", "Mercurio es el planeta más cercano al Sol y el más pequeño.", "Júpiter es el más grande, con una gran mancha roja que es una tormenta gigante.", "La Tierra es el único planeta donde sabemos que existe vida."],
    ["La Revolución Industrial comenzó en Gran Bretaña en el siglo XVIII.", "Se inventaron máquinas como la máquina de vapor, que cambiaron la producción.", "Mucha gente se mudó del campo a las ciudades para trabajar en las fábricas.", "Este período transformó por completo la sociedad y la economía."],
    ["Los ecosistemas están formados por seres vivos y el medio físico donde habitan.", "Los productores, como las plantas, crean su propio alimento.", "Los consumidores, como los herbívoros y carnívoros, se alimentan de otros seres vivos.", "Los descomponedores reciclan la materia muerta para que el ciclo continúe."],
    ["El esqueleto humano está compuesto por más de doscientos huesos.", "Nos proporciona soporte y protege órganos vitales como el cerebro y el corazón.", "Las articulaciones son las uniones entre los huesos y nos permiten movernos.", "El calcio es un mineral esencial para mantener los huesos fuertes."],
    ["Los antiguos griegos son famosos por su filosofía y su arte.", "Crearon la democracia, un sistema de gobierno donde los ciudadanos participaban.", "Construyeron templos impresionantes como el Partenón en Atenas.", "Sus mitos y leyendas sobre dioses y héroes todavía se cuentan hoy en día."],
    ["La cadena alimentaria muestra cómo fluye la energía en un ecosistema.", "Comienza con los productores, que son las plantas.", "Los herbívoros se comen a las plantas y los carnívoros a los herbívoros.", "Cada ser vivo es un eslabón importante en esta cadena."],
    ["El cerebro humano es el órgano más complejo del cuerpo.", "Controla nuestros pensamientos, movimientos y emociones.", "Está dividido en dos hemisferios, cada uno con funciones diferentes.", "Las neuronas son las células que transmiten la información a gran velocidad."],
    ["El Imperio Romano fue una de las civilizaciones más poderosas de la historia.", "Construyeron una vasta red de calzadas para conectar su imperio.", "Su idioma, el latín, es la base de muchas lenguas modernas como el español.", "Su caída marcó el final de la Antigüedad y el inicio de la Edad Media."],
    ["El reciclaje es un proceso clave para cuidar el medio ambiente.", "Consiste en separar los residuos como el papel, el vidrio y el plástico.", "Estos materiales se utilizan para fabricar nuevos productos, ahorrando recursos.", "Al reciclar, reducimos la contaminación y la cantidad de basura."],
    ["Los volcanes son aberturas en la corteza terrestre.", "Cuando entran en erupción, expulsan lava, cenizas y gases del interior de la Tierra.", "La lava, al enfriarse, se solidifica y forma nuevas rocas.", "Algunas islas, como las de Hawái, se formaron por erupciones volcánicas."],
    ["La digestión comienza en la boca cuando masticamos los alimentos.", "Luego, la comida baja por el esófago hasta el estómago.", "En el estómago, los jugos gástricos ayudan a descomponerla.", "Finalmente, en el intestino se absorben los nutrientes que nuestro cuerpo necesita."],
    ["Los cinco sentidos nos permiten percibir el mundo que nos rodea.", "Con la vista, vemos formas y colores; con el oído, escuchamos sonidos.", "El olfato nos permite oler, y el gusto, saborear la comida.", "A través del tacto, sentimos la temperatura y la textura de los objetos."],
    ["Cristóbal Colón buscaba una nueva ruta hacia las Indias.", "En 1492, partió con tres carabelas desde el puerto de Palos.", "Después de un largo viaje, llegó a un nuevo continente: América.", "Este acontecimiento cambió el curso de la historia para siempre."],
    ["Las placas tectónicas son enormes fragmentos de la corteza terrestre.", "Están en constante movimiento, aunque muy lentamente.", "Cuando dos placas chocan o se rozan, se producen los terremotos.", "El movimiento de las placas también es el responsable de la formación de montañas."],
    ["La democracia es un sistema donde el poder reside en el pueblo.", "Los ciudadanos eligen a sus representantes mediante el voto.", "Estos representantes toman decisiones en nombre de todos.", "La libertad de expresión y la igualdad son pilares fundamentales de la democracia."],
    ["La atmósfera es la capa de gases que rodea la Tierra.", "Nos protege de las radiaciones dañinas del Sol.", "Contiene el oxígeno que necesitamos para poder respirar.", "También ayuda a regular la temperatura del planeta."],
    ["La invención de la imprenta por Gutenberg fue revolucionaria.", "Antes, los libros se copiaban a mano, un proceso lento y costoso.", "La imprenta permitió producir libros de forma rápida y barata.", "Gracias a ello, el conocimiento y las ideas se difundieron por toda Europa."],
    ["Las abejas son insectos vitales para el ecosistema.", "Vuelan de flor en flor para recoger néctar y polen.", "Al hacerlo, polinizan las plantas, permitiendo que den frutos.", "Sin su trabajo, muchas de las frutas y verduras que comemos no existirían."],
    ["El Renacimiento fue un período de gran esplendor cultural en Europa.", "Artistas como Leonardo da Vinci y Miguel Ángel crearon obras maestras.", "Hubo grandes avances en la ciencia y la exploración.", "Se redescubrió el conocimiento de las antiguas civilizaciones de Grecia y Roma."],
    ["Los glaciares son inmensas masas de hielo que se mueven lentamente.", "Se forman en lugares muy fríos donde la nieve se acumula y compacta.", "El calentamiento global está provocando que se derritan a un ritmo alarmante.", "Esto causa la subida del nivel del mar en todo el mundo."],
    ["El sistema inmunológico es la defensa natural de nuestro cuerpo.", "Está formado por un ejército de células que combaten las infecciones.", "Cuando un virus o bacteria entra en el cuerpo, este sistema lo ataca.", "Las vacunas ayudan a entrenar a nuestro sistema inmunológico."],
    ["Los fósiles son restos de seres vivos que vivieron hace millones de años.", "Pueden ser huesos, conchas o incluso huellas que se han petrificado.", "Los paleontólogos los estudian para saber cómo era la vida en el pasado.", "Gracias a ellos conocemos a los dinosaurios."],
    ["La gravedad es una fuerza invisible que nos mantiene pegados al suelo.", "Fue descrita por el científico Isaac Newton.", "Es la misma fuerza que hace que los planetas giren alrededor del Sol.", "Sin ella, todo saldría flotando hacia el espacio."],
    ["Los derechos humanos son normas que protegen la dignidad de todas las personas.", "Incluyen el derecho a la vida, a la libertad y a la educación.", "Son universales, lo que significa que se aplican a todo el mundo.", "Es importante conocerlos y defenderlos para construir un mundo más justo."],
    ["El ADN contiene toda nuestra información genética.", "Es como un libro de instrucciones que dice cómo somos.", "Se encuentra en el núcleo de cada una de nuestras células.", "Heredamos la mitad de nuestro ADN de nuestro padre y la otra mitad de nuestra madre."],
    ["Los océanos cubren la mayor parte de la superficie de nuestro planeta.", "Son el hogar de una increíble variedad de seres vivos.", "Regulan el clima y producen gran parte del oxígeno que respiramos.", "Debemos protegerlos de la contaminación y la sobrepesca."],
    ["La comunicación es esencial para entendernos con los demás.", "Podemos comunicarnos hablando, escribiendo o mediante gestos.", "Saber escuchar es tan importante como saber hablar.", "Una buena comunicación ayuda a resolver los conflictos de forma pacífica."],
    ["La energía renovable proviene de fuentes naturales inagotables.", "El sol nos da energía solar y el viento, energía eólica.", "A diferencia de los combustibles fósiles, no contaminan el planeta.", "Son una alternativa clave para luchar contra el cambio climático."],
    ["La Vía Láctea es la galaxia en la que vivimos.", "Está formada por cientos de miles de millones de estrellas.", "Nuestro sistema solar es solo un pequeño punto en uno de sus brazos.", "Por la noche, podemos verla como una franja luminosa en el cielo."],
    ["El feudalismo fue el sistema social de la Edad Media.", "El rey repartía las tierras entre los nobles a cambio de su lealtad.", "Los campesinos trabajaban la tierra para los nobles.", "Vivían dentro de los feudos, que eran grandes extensiones de terreno."],
    ["Los anfibios, como las ranas, tienen una doble vida.", "Nacen en el agua como renacuajos y respiran por branquias.", "Cuando crecen, sufren una metamorfosis y desarrollan pulmones.", "De adultos, pueden vivir tanto en el agua como en la tierra."],
    ["La Constitución es la ley más importante de un país.", "Establece los derechos y deberes de todos los ciudadanos.", "También organiza cómo funciona el gobierno y los poderes del Estado.", "Ninguna otra ley puede contradecir lo que dice la Constitución."],
    ["El comercio justo busca ayudar a los productores de países pobres.", "Asegura que reciban un salario digno por su trabajo.", "Prohíbe la explotación infantil y promueve la igualdad.", "Al comprar productos de comercio justo, apoyamos un mundo más equitativo."],
    ["El telescopio espacial James Webb es el más potente jamás construido.", "Puede observar las primeras galaxias que se formaron en el universo.", "Sus espejos están recubiertos de una finísima capa de oro.", "Nos está enviando imágenes espectaculares del cosmos."],
    ["La erosión es el desgaste de las rocas y el suelo.", "Puede ser causada por el agua, el viento o el hielo.", "Este proceso modela lentamente el paisaje, creando valles y cañones.", "La falta de plantas acelera la erosión del suelo."]
];

const OrdenaLaHistoria5 = () => {
    // El 'true' indica que hay temporizador para este nivel
    const game = useOrdenaLaHistoriaGame(historias, true); 

    if (game.isTestMode) {
        return <OrdenaLaHistoriaTestScreen game={game} />;
    }
    return <OrdenaLaHistoriaUI {...game} />;
};

export default OrdenaLaHistoria5;