-- =====================================================================
-- Revisión Intruso Sets · 1 delete + 123 updates
-- Fixes: 18 cruces correct↔intruder, 102 deduplicaciones, 1 set duplicado.
-- =====================================================================

BEGIN;

-- Set duplicado: Números Primos
DELETE FROM intruso_sets WHERE id = 235;

-- Updates de cruces y deduplicaciones (123 sets)
UPDATE intruso_sets SET correct_items='["🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐨","🐯","🦁","🐮","🐷","🐸","🐵","🐘","🦓","🐢"]'::jsonb, intruder_items='["🚗","🚲","✈️","🏠","📱"]'::jsonb WHERE id=2;
UPDATE intruso_sets SET correct_items='["🌳","🌲","🌴","🌵","🌿","☘️","🍀","🪴","🌻","🌹","🌷","🌱","🍂","🍃","🌾"]'::jsonb, intruder_items='["🐶","🐱","🐭","🍕","🍔"]'::jsonb WHERE id=3;
UPDATE intruso_sets SET correct_items='["🍎","🍌","🍇","🍓","🍊","🍑","🍒","🍐","🥝","🫐","🥭","🍍","🥥"]'::jsonb, intruder_items='["🍟","🍔","🍕","🌭"]'::jsonb WHERE id=11;
UPDATE intruso_sets SET correct_items='["☀️","☁️","🌧️","❄️","🌩️","🌪️","🌈","🌤️","🌥️","🌬️","🌊"]'::jsonb, intruder_items='["🚗","🚌","🚲","🛒"]'::jsonb WHERE id=13;
UPDATE intruso_sets SET correct_items='["🐜","🐝","🐞","🦋","🦗","🦟","🐛","🪰","🪲","🪳","🕷️","🦂","🐌"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=18;
UPDATE intruso_sets SET correct_items='["☀️","☁️","🌧️","❄️","⛈️","🌈","🌪️","🌫️","🌬️","🌡️","🌤️","🌥️","🌦️","🌖","⚡","☔"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","👞","🎸","🍎","🚗"]'::jsonb WHERE id=19;
UPDATE intruso_sets SET correct_items='["🪐","🌍","🌕","⭐","☄️","🚀","🌌","🔭","🛰️","🛸","🌑","🌓","🌠","☀️","👽"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=27;
UPDATE intruso_sets SET correct_items='["✈️","🚁","🚀","🛫","🛬","🛸","🛰️","🛩️","🎈","🚠","🏗️","🌌","🪐","🌠"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=55;
UPDATE intruso_sets SET correct_items='["☀️","🌍","🌕","🪐","⭐","☄️","🌌","🔭","🌙","✨","🌑","🌘","👽","🚀"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=56;
UPDATE intruso_sets SET correct_items='["Coche","Autobús","Tren","Avión","Barco","Bicicleta","Metro","Tranvía","Helicóptero","Taxi","Moto","Camión","Ferry","Yate"]'::jsonb, intruder_items='["Pizza","Delfín","Martillo","Zapatilla","Teléfono","Silla","Nube","León","Cuchara"]'::jsonb WHERE id=59;
UPDATE intruso_sets SET correct_items='["🐶","🐱","🐭","🐰","🦊","🐻","🦁","🐯","🐵","🐬","🦅","🐘","🦒","🦓","🐺","🐷","🐸","🐹"]'::jsonb, intruder_items='["🍕","🚲","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=94;
UPDATE intruso_sets SET correct_items='["Voiture","Bus","Train","Avion","Bateau","Vélo","Tramway","Métro","Hélicoptère","Moto","Trottinette","Camion","Fusée"]'::jsonb, intruder_items='["Pizza","Dauphin","Marteau","Chaussure","Téléphone","Chaise","Nuage","Lion","Cuillère"]'::jsonb WHERE id=108;
UPDATE intruso_sets SET correct_items='["🦁","🐯","🐘","🦒","🦓","🐊","🦍","🐆","🐺","🐻","🦏","🦛","🐪","🐃","🐍","🦦"]'::jsonb, intruder_items='["☀️","☁️","🌧️","❄️","⛈️","🌬️","🌈"]'::jsonb WHERE id=131;
UPDATE intruso_sets SET correct_items='["🍎","🍌","🍇","🍊","🍓","🍍","🍉","🍒","🍑","🥝","🥭","🍋","🍈","🫐","🥥","🥑"]'::jsonb, intruder_items='["🦒","🦓","🐊","🦍","🐆","🐺","🐻","🦏","🦛"]'::jsonb WHERE id=132;
UPDATE intruso_sets SET correct_items='["Ball","Racket","Bat","Helmet","Net","Gloves","Goggles","Skis","Board","Boots","Club","Tee","Shuttlecock","Goal","Basket"]'::jsonb, intruder_items='["Pizza","Bicycle","Dolphin","Hammer","Shoe","Phone","Chair","Cloud","Lion","Spoon"]'::jsonb WHERE id=149;
UPDATE intruso_sets SET correct_items='["🍎","🍐","🍊","🍌","🍇","🍓","🥦","🥕","🌽","🍅","🥬","🍆","🍍","🥑","🍑","🍒","🥝","🍉"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🚗"]'::jsonb WHERE id=173;
UPDATE intruso_sets SET correct_items='["✈️","🚁","🚀","🛸","🛩️","🛰️","🎈","🪂","🛫","🛬","🚠","🏗️","🌌","🪐"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=174;
UPDATE intruso_sets SET correct_items='["Barco","Bueno","Blanco","Buscar","Abuelo","Nube","Bailar","Bajo","Boda","Botella","Burbuja","Biblia","Baldosa","Bicho","Bote","Bota"]'::jsonb, intruder_items='["Pizza","Delfín","Martillo","Zapatilla","Teléfono","Silla","León","Cuchara"]'::jsonb WHERE id=180;
UPDATE intruso_sets SET correct_items='["Árbol","Lápiz","Mesa","Silla","Casa","Coche","Difícil","Fútbol","Cárcel","Trébol","Ventana","Examen","Libreta","Cometa","Nube","Tarde"]'::jsonb, intruder_items='["Pizza","Bicicleta","Delfín","Martillo","Zapatilla","Teléfono","León","Cuchara"]'::jsonb WHERE id=181;
UPDATE intruso_sets SET correct_items='["Pájaro","Teléfono","Música","Lámpara","Plátano","Círculo","Brújula","Sábado","Página","África","Máquina","Sílaba","Médico","Relámpago","Túnica","Mágico"]'::jsonb, intruder_items='["Pizza","Bicicleta","Delfín","Martillo","Zapatilla","Silla","Nube","León","Cuchara"]'::jsonb WHERE id=182;
UPDATE intruso_sets SET correct_items='["Este","Esta","Ese","Esa","Aquel","Aquella","Estos","Estas","Esos","Esas","Aquellos","Aquellas","Mi","Tu","Su"]'::jsonb, intruder_items='["Pizza","Bicicleta","Delfín","Martillo","Zapatilla","Teléfono","Silla","Nube","León","Cuchara"]'::jsonb WHERE id=188;
UPDATE intruso_sets SET correct_items='["3+1","5-2","6x3","2+2","4+5","10-5","8-3","4x2","9+1","12-4","5x5","7+2","1+1","3+3","4+4","5+5","6+6","7+7","8+8","9+9","10+10"]'::jsonb, intruder_items='["ABC","Hola","Mundo","Casa","Perro","Cantar","Barco"]'::jsonb WHERE id=240;
UPDATE intruso_sets SET correct_items='["Página Web","Vídeo online","Juego en red","Correo electrónico","Base de datos","Buscador","Enlace","Aplicación","Nube","Contraseña","URL","Navegador","Streaming","Download","Upload"]'::jsonb, intruder_items='["Pizza","Bicicleta","Delfín","Martillo","Zapatilla","Teléfono","Silla","León","Cuchara"]'::jsonb WHERE id=243;
UPDATE intruso_sets SET correct_items='["😀","😉","😊","😇","🥰","😍","🤩","😘","😋","😛","😜","🤪","🥳","😎","🤓","🧐","😏","😻","😸"]'::jsonb, intruder_items='["😢","😡","😱","🤢","👿","💀","💩"]'::jsonb WHERE id=264;
UPDATE intruso_sets SET correct_items='["😀","😁","😂","🥰","😍","🙂","🥳","🤩","😊","😄","😆","😇","😌","😎","😻","🤗"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=272;
UPDATE intruso_sets SET correct_items='["🚿","🛁","🧼","🪥","🧴","🧻","🦷","🧖‍♀️","🍎","💧","🧺","💈","🪮"]'::jsonb, intruder_items='["🍕","🚲","🐬","🔨","☁️","👞","🌈","🎸","🚗"]'::jsonb WHERE id=273;
UPDATE intruso_sets SET correct_items='["🚴","🏊","🏃","🤸","🧗","⚽","🏀","🥗","🧘","🚶","🎾","🏐","🏸","🏌️","🛹"]'::jsonb, intruder_items='["🍕","🐬","🔨","☁️","👞","🌈","🎸","🍎"]'::jsonb WHERE id=280;
UPDATE intruso_sets SET correct_items='["Lealtad","Sinceridad","Amabilidad","Generosidad","Confianza","Respeto","Apoyo","Paciencia","Empatía","Comprensión","Ayuda","Compañerismo","Cariño"]'::jsonb, intruder_items='["Pizza","Bicicleta","Delfín","Martillo","Zapatilla","Teléfono","Silla","Nube","León","Cuchara"]'::jsonb WHERE id=281;
UPDATE intruso_sets SET correct_items='["🐶","🐱","🦁","🐯","🐬","🦅","🐘","🦒","🦓","🐋","🦜","🐢","🦀","🐝","🐺","🐮","🐷","🐸"]'::jsonb, intruder_items='["🍕","🚲","🔨","☁️","👞","🌈","🎸","🍎","🚗"]'::jsonb WHERE id=307;
UPDATE intruso_sets SET correct_items='["Lleó","Tigre","Elefant","Girafa","Zebra","Mico","Llop","Ós","Hipopòtam","Rinoceront","Dofí","Tauró","Goril·la","Lleopard","Pantera","Cabra"]'::jsonb, intruder_items='["Pizza","Bicicleta","Martell","Sabata","Telèfon","Cadira","Núvol","Cullerot"]'::jsonb WHERE id=318;
UPDATE intruso_sets SET correct_items='["Música","Pàgina","Telèfon","Màquina","Plàtan","Fàbrica","Síl·laba","Matemàtiques","Història","Càpsula","Dècada","Bèlgica","Àfrica","Lògica","Gràfica","Públic"]'::jsonb, intruder_items='["Pizza","Bicicleta","Dofí","Martell","Sabata","Cadira","Núvol","Lleó","Cullerot"]'::jsonb WHERE id=323;
UPDATE intruso_sets SET correct_items='["☀️","🌍","🌕","🪐","⭐","☄️","🌑","🌓","🌗","🛸","🚀","🛰️","🌠","🔭","🌌"]'::jsonb, intruder_items='["✈️","☁️","🦅","🪁","🚁","🎈"]'::jsonb WHERE id=329;
UPDATE intruso_sets SET correct_items='["🔬","🧪","🧫","🧬","🌡️","🩸","🥼","🧤","💉","💊","🧯","📊","🔍","📐"]'::jsonb, intruder_items='["🔨","🔧","🎤","🎧","🎮","🎸","🛹"]'::jsonb WHERE id=331;
UPDATE intruso_sets SET correct_items='["🦠","🧫","🧬","🩸","🔬","🧪","🥼","🧤","🌡️","💉","💊","🧯","📊","🔍","📐"]'::jsonb, intruder_items='["🪐","🚀","🌋","🏔️","🏗️","🛸","🚁","🦅"]'::jsonb WHERE id=337;
UPDATE intruso_sets SET correct_items='["🌋","🏔️","🪨","🏜️","💎","⛰️","🏗️","🛤️","🗺️","🌄","🌅","🏝️","🏕️","🛶"]'::jsonb, intruder_items='["🌊","🌳","🌻","☁️","🌧️","🦢","🦋","🍄"]'::jsonb WHERE id=340;
UPDATE intruso_sets SET correct_items='["💉","💊","🩺","🩹","🧬","🚑","🔬","🧫","🧪","🦠","🥼","🧤","🌡️","📊"]'::jsonb, intruder_items='["🔨","🔧","🎮","⚽","🔭","🎸","🎬","🎨"]'::jsonb WHERE id=348;
UPDATE intruso_sets SET correct_items='["🌋","🏔️","🏜️","🪨","🌊","⛏️","⛰️","🏗️","🏞️","🌅","🏖️","🏝️","🏕️","🛶","🌩️"]'::jsonb, intruder_items='["🌲","🌻","🐶","🏠","🚗","🧸","🍿","🍕"]'::jsonb WHERE id=349;
UPDATE intruso_sets SET correct_items='["🧬","🔬","🧫","🩸","🐁","🌱","🧪","💉","💊","🦠","📊","💻","🥼"]'::jsonb, intruder_items='[" telescope (Telescopi Telescopio)","🪐","🌋","🏗️","🚄","🛸","🛰️","🚀"]'::jsonb WHERE id=355;
UPDATE intruso_sets SET correct_items='["🦕","🦴","🐒","🚶","🐚","🐊","🐢","🦍","🌿","⛰️","🦖","🦣"]'::jsonb, intruder_items='["🤖","🚀","🏭","📱","🚗","🛰️","🕹️","💻"]'::jsonb WHERE id=356;
UPDATE intruso_sets SET correct_items='["⚽","🏀","🏐","🏉","⚾","🎾","🥎","🎱","🏓","🏸","🏏","🏒","🥅","⛳","🏟️"]'::jsonb, intruder_items='["🏊","🏃","🤸","🚴","🥊","🧘","🧗"]'::jsonb WHERE id=363;
UPDATE intruso_sets SET correct_items='["🧪","🔬","🌡️","⚖️","🔥","🥽","⚗️","🧫","🧬","📊","🥼","🧤","🔦","🔋","🔌"]'::jsonb, intruder_items='["🔨","🔧","🎸","⚽","🎮","🧸","🍦"]'::jsonb WHERE id=392;
UPDATE intruso_sets SET correct_items='["⚛️","🧬","🔬","⚗️","🧪","🧫","🦠","🩸","🔍","🔋","🔌"]'::jsonb, intruder_items='["🪐","🚀","🔭","🌍","🌙","🛸"]'::jsonb WHERE id=395;
UPDATE intruso_sets SET correct_items='["🧪","🔬","🌡️","⚖️","🔥","🥽","⚗️","🧫","📊","🔍","⏱️","📐","🥼","🧤"]'::jsonb, intruder_items='["🔨","🔧","🎸","⚽","🎮","🧸","🍿","🍕"]'::jsonb WHERE id=401;
UPDATE intruso_sets SET correct_items='["⚡","🔋","💡","☀️","🔥","🔌","🌡️","☢️","🏭","🏎️","🚠","🛰️"]'::jsonb, intruder_items='["💧","🌱","🦋","🐶","🐱","🌹","🍄","🐚"]'::jsonb WHERE id=403;
UPDATE intruso_sets SET correct_items='["⚛️","🧬","🔬","⚗️","🧪","🧫","🦠","🔍","🌡️"]'::jsonb, intruder_items='["🪐","🚀","🔭","🌍","🌙","🛸","🪁","🦅"]'::jsonb WHERE id=404;
UPDATE intruso_sets SET correct_items='["⚛️","🧪","⚗️","🔬","🧬","🧊","🧫","🌡️","⚖️","🔥","🥽","📋","📊","🔍","📐"]'::jsonb, intruder_items='["🪐","🔭","🌍","🚀","🛰️","🛸","🪁","🦅"]'::jsonb WHERE id=410;
UPDATE intruso_sets SET correct_items='["⚡","🔋","🔌","💡"," flashlight (Linterna Linterna)","🧲","⚙️","🔗","📶","📟","📡","🛰️"]'::jsonb, intruder_items='["💧","🌱","🔥","💨","🌊","🌹","🍄","🐚"]'::jsonb WHERE id=411;
UPDATE intruso_sets SET correct_items='["☢️","☣️","☠️","⚠️","🔥","🧊","💨","🧪","💧","⚡","🚫","🛑","🚱","🚭"]'::jsonb, intruder_items='["♻️","♿","🚹","🚺","🅿️","🚮","🚻","🚼"]'::jsonb WHERE id=413;
UPDATE intruso_sets SET correct_items='["🏋️","🏹","🧲","🍏","🚀","⚖️","⚙️","🔗","🎢","🏗️","🔩","📏","📉","📈","💹","🔋"]'::jsonb, intruder_items='["💡","🌡️","🦠","🧬","🧪","🔬","🧫"]'::jsonb WHERE id=419;
UPDATE intruso_sets SET correct_items='["🗼","🖼️","⛪","🥐","🥖","🍷","🧀","👒","🏛️","🎨","🎭","🏰","🚵","👟","🇫🇷"]'::jsonb, intruder_items='["🗽","🏯","⛩️","🕌","🕋","🌮","🍱"]'::jsonb WHERE id=441;
UPDATE intruso_sets SET correct_items='["🇫🇷","🇧🇪","🇨🇭","🇨🇦","🇸🇳","🥐","🥨","🥖","🧀","🍷","🗼","⛪","🎨","🏛️","🏰"]'::jsonb, intruder_items='["🇪🇸","🇮🇹","🇩🇪","🇬🇧","🇺🇸","🇯🇵","🇨🇳","🇧🇷"]'::jsonb WHERE id=448;
UPDATE intruso_sets SET correct_items='["🗼","⛪","🖼️","🚇","🚢","🥖","🛶","🏰","⛲","🏛️","👗","👠","👒","🍷","🧀"]'::jsonb, intruder_items='["🗽","🏯","🕌","🕋","⛩️","🎡","🎢","🏖️"]'::jsonb WHERE id=449;
UPDATE intruso_sets SET correct_items='["Qui","Que","Où","Dont","Lequel / Laquelle","Auquel / Auxquels","Duquel / Desquels","Ce qui","Ce que","Quiconque","Quoi","Ce dont","Quoi que ce soit"]'::jsonb, intruder_items='["Je suis","Tu vas","Il fait","Mon ami","Ton cahier","Leur maison","Notre école"]'::jsonb WHERE id=451;
UPDATE intruso_sets SET correct_items='["🔺","🐫","🏜️","🐈","👑","🛶","🏺","📜","🦅","🐍","🦁","💎","👳","🌞","📐"]'::jsonb, intruder_items='["🏟️","🏛️","🏰","🏯","⛩️","🗿","🗼","🌉"]'::jsonb WHERE id=456;
UPDATE intruso_sets SET correct_items='["🗺️","🌍","🧭","🌐","📍","🗾","🏔️","🏖️","🏞️","🌅","🌋","🏜️","🏝️","🏕️","🛶"]'::jsonb, intruder_items='["🕰️","🌡️","⚖️","🔭","🔬","🔋","💡","🎮"]'::jsonb WHERE id=457;
UPDATE intruso_sets SET correct_items='["🕌","🕋","☪️","⛲","🌴","🐎","👳","📜","💍","🍇","🍯","🌄","🏺","🐪"]'::jsonb, intruder_items='["⛪","✝️","🔔","🏛️","🏟️","⛩️","🏯","🍷"]'::jsonb WHERE id=465;
UPDATE intruso_sets SET correct_items='["👑","🤴","👸","🏰","⚔️","📜","🛡️","⚜️","🐎","🦁","🦅","🚩","🕍"]'::jsonb, intruder_items='["👔","💼","👨‍💼","🏭","🚆","🏢","🚗","🚲"]'::jsonb WHERE id=467;
UPDATE intruso_sets SET correct_items='["⛵","🗺️","🧭","🌍","⚓","📜","🪙","🏺","🔭","🏰","🌊","🌞","🌙","🦜","🪵"]'::jsonb, intruder_items='["🏭","🚂","💻","🚀","🏙️","💡","🔌","🔋"]'::jsonb WHERE id=473;
UPDATE intruso_sets SET correct_items='["👑","🤴","👸","🏰","⚜️","🗡️","⚔️","🛡️","📜","💍","🍷","⛲","🏛️","🚩","🐎"]'::jsonb, intruder_items='["🎩","👔","🗳️","⚖️","📢","📸","📹","📱"]'::jsonb WHERE id=474;
UPDATE intruso_sets SET correct_items='["🎨","🏛️","🖌️","🖼️","⛪","🗿","✍️","📖","📜","🎻","🎭","🏺","📐","✒️","📔","🔭"]'::jsonb, intruder_items='["🕌","🕋","⛺","🛖","🏭","🚜","🔩"]'::jsonb WHERE id=475;
UPDATE intruso_sets SET correct_items='["🏭","🪖","🚂","📻","✈️","🗳️","🗞️","📺","💻","🛰️","🚀","🏙️","🏎️","🚁","📸"]'::jsonb, intruder_items='["🏰","👑","🗡️","🛡️","🕯️","🛖","🏹","🏺"]'::jsonb WHERE id=482;
UPDATE intruso_sets SET correct_items='["🚀","🛰️","🧱","☢️","🕵️","🇺🇸","🇷🇺","🇩🇪","🗼","📡","🕵️‍♂️","🕵️‍♀️","🔒","📞","🚁"]'::jsonb, intruder_items='["⚔️","🏹","🏇","🏺","📜","🛡️","🔱","🏛️"]'::jsonb WHERE id=483;
UPDATE intruso_sets SET correct_items='["🗽","🗼","🌉","🎡","🏰","🏙️","🏛️","🏟️","🗺️","🧳","✈️","🚢","🚠","🚞","⛩️"]'::jsonb, intruder_items='["🛖","⛺","🏚️","🪵","🪨","🧺","🧹","🪣"]'::jsonb WHERE id=522;
UPDATE intruso_sets SET correct_items='["📖","📜","📨","📑","📓","📝","📔","📒","📘","📗","📂","🗂️","✍️","🪶"]'::jsonb, intruder_items='["🎥","💿","💾","🖱️","🔌","🔋","💡","🎮"]'::jsonb WHERE id=531;
UPDATE intruso_sets SET correct_items='["🎭","🎟️","🎬","👏","🔦","🎪","🎙️","🎤","🎹","🎺","🎻","🩰","🎨","📽️"]'::jsonb, intruder_items='["⚽","🏊","🚜","🏔️","🏥","🏢","🏗️","🚄"]'::jsonb WHERE id=538;
UPDATE intruso_sets SET correct_items='["📖","📚","🖊️","📝","📜","📓","📔","📒","📘","📗","✒️","✍️","🪶","📂","🗂️"]'::jsonb, intruder_items='["📺","📻","📱","💿","🔌","🔋","💡","🎮"]'::jsonb WHERE id=539;
UPDATE intruso_sets SET correct_items='["📧","💬","📱","💻","🌐","📶","🤳","📸","📹","🎬","🔔","📍","🔗","🔋","🔌"]'::jsonb, intruder_items='["📠","📼","📮","🕊️","🚬","💾","🎞️","🕯️"]'::jsonb WHERE id=540;
UPDATE intruso_sets SET correct_items='["📰","🗞️","📺","📻","💻","📡","🎙️","🎤","🎬","📱","🎞️","📽️","📷","📣","📢"]'::jsonb, intruder_items='["🚗","🍔","⚽","🎸","💊","🧸","🍦","🥪"]'::jsonb WHERE id=546;
UPDATE intruso_sets SET correct_items='["🎭","👑","🗡️","💀"," castles (Castells Castles)","📜","🕯️","💍","🏰","🎪","🤴","👸","🕵️","🏛️","🖋️"]'::jsonb, intruder_items='["🚀","📱","🚆","🎧","👟","🔌","🔋","💡"]'::jsonb WHERE id=547;
UPDATE intruso_sets SET correct_items='["✍️","🖊️","⌨️","📝","📖","✒️","📓","📔","📒","📘","📜","📂","🗂️","🪶","📄"]'::jsonb, intruder_items='["🔨"," Spoon (Cullera Spoon)","🧵","🔭","🔬","🔋","🔌","💡"]'::jsonb WHERE id=548;
UPDATE intruso_sets SET correct_items='["🎬","🎥","📺","📹","🎞️","🎙️","🎤","📷","📽️","📻","📱","💻"]'::jsonb, intruder_items='["📚","📰","🖌️","🗿","🏛️","🎨","🖋️","📜"]'::jsonb WHERE id=554;
UPDATE intruso_sets SET correct_items='["🍰","🍕","🌗","🧀","🍫","📊","🍩","🥧","🥯","🧇","🥞","🥘","🥪","🍳"]'::jsonb, intruder_items='["1️⃣","💯","🔟","🔢","#️⃣","🆗","🆒","🆕"]'::jsonb WHERE id=562;
UPDATE intruso_sets SET correct_items='["∟","⊿","📐","🔷","⚠️","🛤️","➰","↔️","↕️","↖️","↘️","↗️","↙️","➕","✖️"]'::jsonb, intruder_items='["🔴","〰️","⭕","🔗","🍩","🥯","🌕"]'::jsonb WHERE id=564;
UPDATE intruso_sets SET correct_items='["-5","+3","0","-10","15","-1","-100","+45","-22","+7","-99","+1000","1","-8","+12"]'::jsonb, intruder_items='["0.5","1/2","3.14","2/3","4,5","0.75","pi","sqrt(2)"]'::jsonb WHERE id=565;
UPDATE intruso_sets SET correct_items='["Equilátero","Isósceles","Escaleno","Acutángulo","Rectángulo","Obtusángulo","Triángulo","Hipotenusa","Cateto","Vértice","Ángulo recto","Ángulo agudo","Ángulo obtuso","Base"]'::jsonb, intruder_items='["Cuadrado","Rombo","Trapecio","Pentágono","Hexágono","Octógono"]'::jsonb WHERE id=568;
UPDATE intruso_sets SET correct_items='["📈","📉","📊","💹","⏲️","🕰️","📡","💻","🔭"]'::jsonb, intruder_items='["🥧","🔢","🎲","🎰","🧱","⚽","🏀","🎾"]'::jsonb WHERE id=572;
UPDATE intruso_sets SET correct_items='["🍕","🍰","🍫","🧀","🍪","🍩","🥧","🥯","🧇","🥞","🍳","🥪","📊","📉","📈"]'::jsonb, intruder_items='["🥤","🧃","🍎","🍐","1️⃣","🔋","🔌","💡"]'::jsonb WHERE id=574;
UPDATE intruso_sets SET correct_items='["📊","📉","📈","🥧","💹","⏲️","🕰️","📅","🔭","🔬","💻"]'::jsonb, intruder_items='["📐","📝","🎲","🧱","🎨","🎭","🎬","🎪"]'::jsonb WHERE id=580;
UPDATE intruso_sets SET correct_items='["🧊","📦","⚽","🥫","⛺","🏗️","🌍","🌕","🪐","🌑","🧱","🏘️","🛖","🏡","🏠"]'::jsonb, intruder_items='["🟦","🔴","🔺","📏","🗺️","〰️","🌀","🌊"]'::jsonb WHERE id=581;
UPDATE intruso_sets SET correct_items='["🎲","🃏","🎰","🪙","🎱","🎯","🕹️","🎮","🎳","🎟️","🎩","🗝️","🔮","🪄","🎴"]'::jsonb, intruder_items='["⏱️","🌡️","⚖️","🔢","➕","➖","✖️","➗"]'::jsonb WHERE id=582;
UPDATE intruso_sets SET correct_items='["🧮","💻","📱","📐","📏","✏️","📊","📉","📈","💹","📟","🖊️","✒️","📓"]'::jsonb, intruder_items='["🔨","🔧","🖌️","🧵","🍳","🧺","🧹","🪒"]'::jsonb WHERE id=583;
UPDATE intruso_sets SET correct_items='["📈","📉","📊","💹","🎢","🔄","📐","💻"]'::jsonb, intruder_items='["🎲","🧱","🎨","📝","🧩","🎭","🎬","🎪"]'::jsonb WHERE id=589;
UPDATE intruso_sets SET correct_items='["↗️","↘️","⬅️","⬆️","📐","📍","↔️","↕️","↖️","↙️","🗺️","🛑","📡","🛰️"]'::jsonb, intruder_items='["⏰","⚖️","💡","💰","🩺","🎸","🎨","🎬"]'::jsonb WHERE id=590;
UPDATE intruso_sets SET correct_items='["🎲","🃏","🎰","🪙","🎱"," bowling (Bitlles Bolos)","🎟️","🎩","🗝️","🔮","🪄","🎴","🎳","🎯"]'::jsonb, intruder_items='["📏","🔭","🔬","🖊️","🔨","🪚","🪓","⚒️"]'::jsonb WHERE id=591;
UPDATE intruso_sets SET correct_items='["🎸","🎹","🎺","🎻","🥁","🎷","🪗","🪕","🎼","🎙️","🎤"]'::jsonb, intruder_items='["🔨","🔧","🪚","🪓","⛏️","🗜️","🪛","🩹"]'::jsonb WHERE id=597;
UPDATE intruso_sets SET correct_items='["Do","Re","Mi","Fa","Sol","La","Si","Sostenido","Bemol","Becuadro","Clave de Sol","Clave de Fa","Líneas adicionales","Pentagrama","Escala mayor","Escala menor"]'::jsonb, intruder_items='["Clave","Compás","Tempo","Ritmo","Matiz","Dinámica"]'::jsonb WHERE id=603;
UPDATE intruso_sets SET correct_items='["🎻","🎺","🎷","🎸","🎹","🥁","🪗","🪕","🎼","🎙️","🎤"]'::jsonb, intruder_items='["🔨","🔧","🪚","🪓","⛏️","🗜️","🪛","🩹","🪒"]'::jsonb WHERE id=605;
UPDATE intruso_sets SET correct_items='["🎸","🎻","🎷","🎹","🎺","🥁","🪗","🪕","🎼","🎙️","🎤"]'::jsonb, intruder_items='["🔨","🔧","🪚","🪓","⛏️","🗜️","🪛","🩹","🧺"]'::jsonb WHERE id=612;
UPDATE intruso_sets SET correct_items='["🎼","🎶","🎵","🎹","𝄞","𝄢","🎙️","🎤","🎷","🎺","🎸","🎻","🥁","🪗","📻"]'::jsonb, intruder_items='["💯","💲","➕","➖","🔣","🅰️","🅱️","©️","®️"]'::jsonb WHERE id=620;
UPDATE intruso_sets SET correct_items='["🎨","🖌️","🖍️","✏️","📏","✂️","🖋️","✒️","🖼️","🎭","🎪","🗿","🏗️","📐","🖇️"]'::jsonb, intruder_items='["🔨","🔧","🥄","🍴","👓","🔋","🔌","💡"]'::jsonb WHERE id=626;
UPDATE intruso_sets SET correct_items='["🟥","🟧","🟨","🟩","🟦","🟪","⬛","⬜","🟫","🔺","🔻","💠","🔷","🔶","🛑"]'::jsonb, intruder_items='["🍎","🚗","🐶","🌳","🏠","🍕","🍔","🍦"]'::jsonb WHERE id=628;
UPDATE intruso_sets SET correct_items='["🔴","🔵","🟡","🟢","🟠","🟣","🟤","⚪","⚫","🟥","🟦","🟨","🟩","🟧","🟪","🟫"]'::jsonb, intruder_items='["🔳","🔲","🏁","🏳️","🏴","🏴‍☠️","💠","🌀"]'::jsonb WHERE id=634;
UPDATE intruso_sets SET correct_items='["🎨","🖌️","🖍️","✏️","📏","✂️","✒️","🖋️","🔍","📐","🖇️","🖼️","🎭","🗿"]'::jsonb, intruder_items='["🔨","🔧","🥄","🍴","👓","🪒","🩹","🪓","🧺"]'::jsonb WHERE id=635;
UPDATE intruso_sets SET correct_items='["🎨","🖌️","✏️","📏","📐","✂️","✒️","🖋️","🖼️","🗿","🏟️","🏗️","🖇️"]'::jsonb, intruder_items='["🔨","🔧","🥄","🍴","🕶️","🔋","🔌","💡"]'::jsonb WHERE id=641;
UPDATE intruso_sets SET correct_items='["🔴","🔵","🟡","🟢","🟠","🟣","🟤","⚪","⚫","🟥","🟦","🟨","🟩","🟧","🟪","🟫"]'::jsonb, intruder_items='["🏁","🏳️","🏴","🔳","🔲","💠","🌀"]'::jsonb WHERE id=642;
UPDATE intruso_sets SET correct_items='["🎨","🖌️","✏️","📏","📐","✂️","✒️","🖋️","📷","📽️","🎬","🎞️","🖇️"]'::jsonb, intruder_items='["🔨","🔧","🥄","🍴","🕶️","🔋","🔌","💡","🪒"]'::jsonb WHERE id=648;
UPDATE intruso_sets SET correct_items='["🔴","🔵","🟡","🟢","🟠","🟣","🟤","⚪","⚫","🟥","🟦","🟨","🟩","🟧","🟪","🟫"]'::jsonb, intruder_items='["🏁","🏳️","🏴","🔳","🔲","💠","🌀","🔘"]'::jsonb WHERE id=649;
UPDATE intruso_sets SET correct_items='["🤖","⚙️","🔋","🔌","💡","🛠️","🦾","🦿","🎛️","🌡️","⏲️","📡","🛰️","🏗️","🔩"]'::jsonb, intruder_items='["🌸","🍦","🐱","☁️","🎨","🦋","🌈","🌅"]'::jsonb WHERE id=656;
UPDATE intruso_sets SET correct_items='["Clic","Doble clic","Arrastrar","Soltar","Escribir","Borrar","Desplazar (Scroll)","Pulsar tecla","Zunm (Zoom)","Minimizar","Maximizar","Cerrar ventana","Restaurar"]'::jsonb, intruder_items='["Pintar óleo","Recortar","Pegar pegamento","Doblar ropa","Escribir a mano","Saltar","Correr"]'::jsonb WHERE id=662;
UPDATE intruso_sets SET correct_items='["🤖","⚙️","🔋","🔌","💡","🛠️","🌡️","⏲️","📡","🛰️","🦾","🦿","🔩","🧲","🚥"]'::jsonb, intruder_items='["🌸","🍦","🐱","☁️","🎨","🦋","🌈","🌅"]'::jsonb WHERE id=679;
UPDATE intruso_sets SET correct_items='["🌡️","⏲️","📡","🛰️","🎛️","📏","🧭","⚖️","🔋","🔌","💡"]'::jsonb, intruder_items='["🍔","🍕","🍦","🍩","🍪","🍰"]'::jsonb WHERE id=692;
UPDATE intruso_sets SET correct_items='["📡","📶","🌐","☁️","📱","💻","🛰️","🔌","🔋"]'::jsonb, intruder_items='["🪵","🕯️","📜","🖋️","🏺"]'::jsonb WHERE id=700;
UPDATE intruso_sets SET correct_items='["🔨","🔧","🪛","🔩","🗜️","📏","🪚","🪓","🛠️","⚒️","📐","🖇️","🧱","🏮"]'::jsonb, intruder_items='["✏️","🖊️","🧸","🍎","🥄","🧁","🍦","🥪"]'::jsonb WHERE id=704;
UPDATE intruso_sets SET correct_items='["🔋","🔌","💡","⚡","☀️","🌬️","🌊","🌡️","🔦","🕯️","⛽","☢️","🏭","🛰️"]'::jsonb, intruder_items='["💧","🌱","🦋","🐶","🐱","🌹","🍄","🐚"]'::jsonb WHERE id=707;
UPDATE intruso_sets SET correct_items='["🔨","🔧","🪛","🔩","🗜️","📏","🪚","🪓","🛠️","⚒️","📐","🖇️","🧱","🏮"]'::jsonb, intruder_items='["✏️","🖊️","🧸","🍎","🥄","🧁","🍦","🥪"]'::jsonb WHERE id=713;
UPDATE intruso_sets SET correct_items='["🔋","💡","🔌","⚡","🔦","🛑","📡","🛰️"]'::jsonb, intruder_items='["💧","🌱","🦋","🐶","🐱","🌹","🍄","🐚"]'::jsonb WHERE id=714;
UPDATE intruso_sets SET correct_items='["💻","🖱️","⌨️","🖥️","🖨️","💾","💿","🖲️","📼","📠","📟","🔋","🔌","📱"]'::jsonb, intruder_items='["🧱","🪵","🔨","🔧","🔩","🪚","🪓","⚒️"]'::jsonb WHERE id=715;
UPDATE intruso_sets SET correct_items='["⚡","🔋","💡","🔌","🔦","🛑","📟","📡","🛰️","📶"]'::jsonb, intruder_items='["💧","🔥","🌱","🐶","📚","🐚","🌹","🦋"]'::jsonb WHERE id=721;
UPDATE intruso_sets SET correct_items='["🔨","🔧","🪛","🔩","📏","✂️","🪚","🪓","🛠️","⚒️","📐","🖇️","🗜️","🏮"]'::jsonb, intruder_items='["✏️","🖊️","🥄","🍴","🧸","🍦","🥪","🧁"]'::jsonb WHERE id=722;
UPDATE intruso_sets SET correct_items='["💻","🖱️","⌨️","🖥️","🖨️","💾","💿","🖲️","📼","📠","📟","🔌","🔋"]'::jsonb, intruder_items='["📺","📻","📷","📹","🕰️","🧺","🕯️","🏺"]'::jsonb WHERE id=723;
UPDATE intruso_sets SET correct_items='["🔌","🔋","💡","📟","💾","📡","🛰️","📶"]'::jsonb, intruder_items='["🔨","🔧","🪚","🧱","🪵","🛠️","⛏️"]'::jsonb WHERE id=730;
UPDATE intruso_sets SET correct_items='["💻","⌨️","🖥️","🖱️","👾","🤖","🎮","🕹️","💾","💿","🔋","🔌","📱","📟","📶"]'::jsonb, intruder_items='["📚","🖊️","📝","🎨","🎭","🏺","📜","🧺"]'::jsonb WHERE id=731;
UPDATE intruso_sets SET correct_items='["🤝","👂","🗣️","🫂","👐","🙋","🕊️","🌍","🤲","🫶","✨","🌟","🎈","🎭","☀️"]'::jsonb, intruder_items='["🥊","🖕","😤","🤬","💣","🔫","🔥","🔪"]'::jsonb WHERE id=737;
UPDATE intruso_sets SET correct_items='["🤝","👂","🗣️","🫂","👐","🙋","👋","🤲","🫶","✨","🕊️","🌍"]'::jsonb, intruder_items='["🥊","🖕","😤","🤬","💣","🔫","🔥","🔪"]'::jsonb WHERE id=746;
UPDATE intruso_sets SET correct_items='["🤝","👂","🗣️","🫂","🛑","⚖️","👋","🤲","🫶","✨","🕊️","🌍"]'::jsonb, intruder_items='["🥊","🖕","😤","🤬","💣","🔫","🔥","🔪"]'::jsonb WHERE id=753;
UPDATE intruso_sets SET correct_items='["🎓","💼","🔬","🚀","⚖️","👨‍🎓","👩‍🎓","🏗️","🏥","🌍","💻","🎨","✍️","👷","📈","🌟"]'::jsonb, intruder_items='["🍼","🧸","🚼","🏰","🎠","🍭","👶"]'::jsonb WHERE id=759;
UPDATE intruso_sets SET correct_items='["🤝","☮️","⚖️","🌱","❤️","🫂","🕊️","🌍","🤲","✨","👐","🗳️","🕯️"]'::jsonb, intruder_items='["💣","🔫","💸","🦠","🥊","🚬","🤬","⚔️"]'::jsonb WHERE id=760;
UPDATE intruso_sets SET correct_items='["📚","✏️","🎒","🏫","📏","🖍️","📓","🖇️","🖋️","🔍","📐","✒️","🎨","💻","🪑","🧑‍🏫"]'::jsonb, intruder_items='["🛌","🛁","🍳","📺","🎮","🛋️","🚿"]'::jsonb WHERE id=766;
UPDATE intruso_sets SET correct_items='["🥘","🍊","🥖","🧀","🐟","🍇","🥚","🍤","🥗","🥩","🍗","🥛","🥣","🥨","🥞"]'::jsonb, intruder_items='["🍽️","🔪","🧂","🍷","🥤","🥢","🍴"]'::jsonb WHERE id=767;
UPDATE intruso_sets SET correct_items='["⛰️","🏖️","🌲","🌊","🦅","🌅","🌳","🌻","🌿","🦋","🌈","🌋","🏜️","🏝️","🏕️"]'::jsonb, intruder_items='["🏙️","🏭","🛣️","🚇","🏯","🏗️","🚄","🏢"]'::jsonb WHERE id=782;
UPDATE intruso_sets SET correct_items='["🔥","🥘","🎆","🏰","🦇","🍊","🎭","🎺","🥁","📜","🕯️","🏛️","🏟️","🏖️","⚽"]'::jsonb, intruder_items='["🗽","🗼","🏯","🌵","🥥","⛩️","🕌","🎿"]'::jsonb WHERE id=788;
UPDATE intruso_sets SET correct_items='["💶","💵","💷","💴","💳","🏧","💰","🪙","💹","🏦","💸","🧾","📓","💼","🏢"]'::jsonb, intruder_items='["🎫","🎟️","🏷️","🔖","📜","📂","🖊️","📝"]'::jsonb WHERE id=795;
UPDATE intruso_sets SET correct_items='["🏛️","🏟️","🏺","🍇","🦅","⚔️","🛡️","📜","🪙","⛲"]'::jsonb, intruder_items='["🕌","🏯","🏗️","💻","🚀","📱","🛰️","🏭"]'::jsonb WHERE id=802;

-- COMMIT;  -- descomenta tras revisar
ROLLBACK;
