// src/apps/ordena-la-historia/eso-4-tecnologia/OrdenaLaHistoriaEso4Tecnologia.jsx
import React from 'react';
import { useOrdenaLaHistoriaGame } from '@/hooks/useOrdenaLaHistoriaGame';
import OrdenaLaHistoriaUI from '@/apps/_shared/OrdenaLaHistoriaUI';
import OrdenaLaHistoriaTestScreen from '@/apps/_shared/OrdenaLaHistoriaTestScreen';

const historias = [
    ["La domótica busca automatizar y controlar de forma inteligente una vivienda.", "Permite gestionar la iluminación, la climatización o la seguridad de forma remota.", "Se utilizan sensores para recoger información del entorno, como la temperatura o la presencia.", "Un sistema central o controlador procesa esta información y da órdenes a los actuadores.", "Por ejemplo, puede bajar las persianas automáticamente si detecta demasiado sol.", "El objetivo es mejorar el confort, la seguridad y la eficiencia energética de la casa."],
    ["Un robot seguidor de líneas es un proyecto clásico de robótica educativa.", "Está equipado con sensores de infrarrojos en su parte inferior para detectar una línea negra.", "El microcontrolador, que es el cerebro del robot, lee la información de los sensores.", "Si un sensor detecta la línea, el programa ordena al motor de ese lado que gire más despacio o se pare.", "De esta forma, el robot va corrigiendo su trayectoria para mantenerse siempre sobre la línea.", "Este proyecto permite aprender conceptos básicos de sensores, actuadores y programación."],
    ["La comunicación entre dispositivos en internet se basa en el modelo cliente-servidor.", "Cuando escribimos una dirección en nuestro navegador, nuestro ordenador actúa como cliente.", "Realiza una petición a un ordenador remoto llamado servidor, donde se aloja la página web.", "El servidor recibe la petición, busca la información solicitada y la envía de vuelta.", "Nuestro navegador recibe la información y la muestra en la pantalla.", "Todo este proceso ocurre en apenas unos segundos."],
    ["La inteligencia artificial (IA) es una rama de la informática que busca imitar la inteligencia humana.", "Existen diferentes enfoques, como el aprendizaje automático o 'machine learning'.", "En este enfoque, el sistema aprende a partir de una gran cantidad de datos, sin ser programado explícitamente.", "Por ejemplo, una IA puede aprender a reconocer imágenes de gatos tras analizar miles de ellas.", "La IA ya está presente en muchas aplicaciones, como los asistentes de voz o los sistemas de recomendación."],
    ["La generación de electricidad en una central térmica convencional utiliza combustibles fósiles.", "Primero, se quema el combustible (carbón, gas o petróleo) en una caldera para calentar agua.", "El agua se convierte en vapor a alta presión.", "Este vapor se dirige hacia una turbina y la hace girar a gran velocidad.", "La turbina está conectada a un generador (alternador) que transforma la energía mecánica en energía eléctrica.", "Este proceso genera gases de efecto invernadero que contribuyen al cambio climático."],
    ["La hidráulica es la tecnología que utiliza un fluido, normalmente aceite, para transmitir potencia.", "Se basa en el principio de Pascal, que dice que la presión se transmite por igual en todo el fluido.", "Un sistema hidráulico utiliza una bomba para generar presión en el fluido.", "Esta presión se utiliza para mover cilindros o motores hidráulicos con una gran fuerza.", "Se emplea en maquinaria pesada como excavadoras, grúas o frenos de camión."],
    ["El lenguaje HTML es la base sobre la que se construyen todas las páginas web.", "Utiliza un sistema de etiquetas para marcar los diferentes elementos del contenido.", "Por ejemplo, la etiqueta `<p>` se usa para definir un párrafo y `<h1>` para un título principal.", "El navegador web es el encargado de interpretar estas etiquetas y mostrar la página con el formato correcto.", "HTML define la estructura, pero no el aspecto visual de la página."],
    ["Un programa informático es una secuencia de instrucciones que un ordenador puede ejecutar.", "Antes de escribir el código, es importante diseñar un algoritmo.", "Un algoritmo es un plan detallado de los pasos a seguir para resolver un problema.", "Una vez tenemos el algoritmo, lo traducimos a un lenguaje de programación como Python.", "Finalmente, el programa se compila o interpreta para que el ordenador pueda entenderlo y ejecutarlo."],
    ["La realidad virtual (VR) busca sumergir al usuario en un entorno digital completamente nuevo.", "El usuario utiliza unas gafas especiales que bloquean la visión del mundo real.", "Estas gafas muestran imágenes generadas por ordenador que crean una sensación de inmersión.", "Los sensores de movimiento en las gafas y los mandos permiten al usuario interactuar con este mundo virtual.", "Se utiliza en videojuegos, simuladores de entrenamiento o visitas virtuales a museos."],
    ["El reciclaje de aparatos electrónicos es de vital importancia para el medio ambiente.", "Estos dispositivos contienen materiales valiosos como el oro o el cobre, que se pueden recuperar.", "También contienen sustancias tóxicas, como el mercurio o el plomo, que no deben acabar en los vertederos.", "Al reciclarlos, se evita la contaminación del suelo y el agua.", "Además, se reduce la necesidad de extraer nuevas materias primas de la naturaleza.", "Deben ser depositados en puntos limpios o tiendas especializadas para su correcta gestión."]
];

const OrdenaLaHistoriaEso4Tecnologia = () => {
    const game = useOrdenaLaHistoriaGame(historias, true);
    if (game.isTestMode) {
        return <OrdenaLaHistoriaTestScreen game={game} />;
    }
    return <OrdenaLaHistoriaUI {...game} />;
};

export default OrdenaLaHistoriaEso4Tecnologia;
